### ISSUE TITLE
Question -- Client and Conn

### ISSUE THREAD

**Issue by a-dot** [segmentio/kafka-go#1004]
When should a Client be used, and when should a Conn be used?

If one was to implement a missing feature of the protocol, should it be implemented as a method on the Client or the Conn? Or both? When does one make more sense than the other? Thanks!

**Comment by achille-roussel** [comment]
Hello @a-dot, thanks for starting this conversation!

As much as possible, we would like all new additions to be made to the `kafka.Client` type rather than `kafka.Conn`.

Let us know what feature you are interested in adding and if you are running into any blockers!

**Comment by a-dot** [comment]
@achille-roussel thanks for your response! I would have one more question then...

You're saying we should prioritize `kafka.Client` over `kafka.Conn`. If I were to pick an example, say "Reading offsets", for `kafka.Conn` I have a few options, a few convenience methods:
- ReadOffset(time.Time)
- ReadFirstOffset()
- ReadLasttOffset()
- ReadOffsets()

However, if I look at what's there for `kafka.Client` all I have is `ListOffsets(context.Context, *ListOffsetsRequest)`.

Is the idea for `kafka.Client` implementations to not offer convenience methods and only allow users to call methods that expect a `<action>Request` for all protocol features? Thanks!

**Comment by achille-roussel** [comment]
You are correct. The intent is for `kafka.Client` to expose the Kafka APIs without adding an abstraction level. It is a bit more verbose but it helps support a broader set of application use cases, which is the right approach for a Kafka client library.

**Comment by a-dot** [comment]
Thanks! In that case, I'll post my PR for `offsetdelete` shortly.

If the direction the kafka.Client is taking is to only serve as a layer to expose the Kafka APIs, do you have another layer for convenience functions that would accept a kafka.Client or that's entirely left to the users to implement in their own libraries? 

If so, what's going to happen to the existing convenience functions? Or what about the commit logic currently implemented? (The commit loop, etc.) Is that going to be deprecated from kafka-go at some point and pushed down to the users to implement their own? Making kafka-go a simple Kafka APIs layer?

**Comment by achille-roussel** [comment]
> If so, what's going to happen to the existing convenience functions? Or what about the commit logic currently implemented? (The commit loop, etc.) Is that going to be deprecated from kafka-go at some point and pushed down to the users to implement their own? Making kafka-go a simple Kafka APIs layer?
>
> Are the kafka.Reader and kafka.Writer staying or being deprecated? What about kafka.ConsumerGroup? I'm assuming kafka.Conn will get deprecated at some point in favor of kafka.Client?

Currently we are not planning on deprecating the `kafka.Reader` or `kafka.Writer` APIs. `kafka.Client` is intended to become the core layer that other abstractions are built upon.

We value backwards compatibility in kafka-go, so none of the existing APIs will be removed for now but we are only investing in `kafka.Client` and other higher level APIs.

> Finally, for something like offsetdelete, where would you see convenience functions for this? kafka.Reader maybe?

Let's see how using `kafka.Client` works, and learn from it to see what a higher level API would look like.

**Comment by achille-roussel** [comment]
I'm going to close this issue since it seems the original question was answered already!
