### ISSUE TITLE
retries stat should be a counter

### ISSUE THREAD

**Issue by madshov** [segmentio/kafka-go#1005]
**Describe the solution you would like**

I have been going through the stats that you are exposing for the `reader` and `writer`. The `retries` stat on the `writer` doesn't make sense to me as it's a summary stat but it acts as a counter:
```
type writerStats struct {
        ...
	retries        summary
}
...
if attempt != 0 {
	stats.retries.observe(1)
        ...
}      
```
This means `min`,`max` and `avg` will always equal 1, which basically makes the stat useless. This should be changed to a `counter` instead or is there some other way of getting the actual number of retries out?

**Comment by achille-roussel** [comment]
Thanks reporting @madshov, I believe you are correct, this was mistakenly declared as a summary instead of a counter.
