### ISSUE TITLE
Conn.Close() should check if Conn.conn is set before performs any action on it

### ISSUE THREAD

**Issue by huszkacs** [segmentio/kafka-go#1012]
**Describe the bug**

> Conn.Close() can potentially close a nil connection, which leads to panicking. 
https://github.com/segmentio/kafka-go/blob/main/conn.go#L509

**Kafka Version**

> v0.4.33

**To Reproduce**

> close a connection that doesn't have conn set up.

**Expected behaviour**
> Conn.Close() checks if Conn.conn nil and pass or it checks if it fails, it returns with an error.

**Comment by rhansen2** [comment]
Hi @huszkacs,

Are you actively seeing this panic occur?

**Comment by huszkacs** [comment]
Hi @rhansen2,

Yes, when I have a failed Conn instance and I try to close it. I can't check if the Conn.conn is nil, since it is private to the lib.

**Comment by rhansen2** [comment]
Are you able to provide a reproduction where Conns are being created with a nil conn? It looks like the Conn type always assumes its underlying connection is not nil, seems like we shouldn't be constructing Conns with non-nil network connections.

**Comment by huszkacs** [comment]
Yes. I moved further with my application and I can't reproduce this issue. From now I always get nil to Conn if something goes wrong. I guess it was a wrong implementation on my side. I close this ticket.
