### ISSUE TITLE
Timeouts don'ts work when reader.FetchMessages

### ISSUE THREAD

**Issue by bruteforce1414** [segmentio/kafka-go#1016]
Timeouts don'ts work when reader.FetchMessages
```go
dialer := &kafka.Dialer{
			LocalAddr: kafka.TCP(params.Config.Queue.Kafka.Url),
			Timeout:   time.Duration(params.Config.Retry.Timeouts[i]) * time.Millisecond, //timeout = 2m0s
}

reader := kafka.NewReader(kafka.ReaderConfig{
                        Brokers: []string{params.Config.Queue.Kafka.Url},
			GroupID:        "",
			Topic:          topicConfig.Topic,
			MinBytes:       10e3, // 10KB
			MaxBytes:       10e6, // 10MB
			Dialer: dialer,
})
```		
**Expected Behavior**

timeout = 2m0s
**Observed Behavior**
timeout around 5-10s 

How to define timeout before message will fetch?

**Comment by rhansen2** [comment]
Hi @bruteforce1414,

The Timeout field of the Dialer is applied when connecting to brokers.

The timeout for [FetchMessage](https://pkg.go.dev/github.com/segmentio/kafka-go#Reader.FetchMessage) is controlled by the passed on context. 

The [ReaderConfig](https://pkg.go.dev/github.com/segmentio/kafka-go#ReaderConfig) also contains a few timeouts specific to the background fetching of message.

Hope that helps!
