### ISSUE TITLE
Bind custom parameter for Message to be called in Completion.

### ISSUE THREAD

**Issue by edoger** [segmentio/kafka-go#1019]
**Describe the solution you would like**

In many scenarios where Kafka produces messages asynchronously, we need to handle some other things after the message is sent successfully or fails, which are often associated with the message itself, but there is currently no way to map the event to the message itself, for example, for For log collection, we need to update the collection offset of the file after each message is successfully sent. For this reason, each message needs to be associated with the offset data of a file, but this data does not need to be sent to kafka.

```
// Message
type Message struct {
    Metadata interface{}
    // .... 
}

// Writer.Completion
func(messages []Message, err error) {
    for _, message := range messages {
        md := message.Metadata.(MyObject)
        // ....
    }
}
```

**Comment by dominicbarnes** [comment]
Starting with v0.4.39, we've added support for `Message.WriterData` which should work as described here.
