### ISSUE TITLE
Reader delay

### ISSUE THREAD

**Issue by maxim-ge** [segmentio/kafka-go#102]
`Reader` example gives ~5 seconds  delay until first output appears.  Can it be onfigured somehow? Sarama consumer prints  "immediately".

**Comment by maxim-ge** [comment]
Ok, got it. `MinBytes: 1` or `MaxWait:   1 * time.Second` do the job

**Comment by achille-roussel** [comment]
👍 

We chose the default to be values that we actually use in production where we want to maximize throughput. Longer wait time and batch size allow better throughput since less roundtrips need to be made to fetch data from kafka.

Glad you got it figured out!
