### ISSUE TITLE
readNewBytes function consumes lot of memory

### ISSUE THREAD

**Issue by gopi-bathala** [segmentio/kafka-go#1029]
**Describe the bug**

We are facing memory issues with kafka-go library. Majority of the memory has been allocated to readNewBytes function which takes around 1.6GB of memory.  Overall kafka-go library took 1.91 GB of memory.

Could you please advise on this? 

We are running the consumer with 2vcpu and 4GB ram instance. It would be great if you can provide the optimized consumer & producer hardware configuration?

**Kafka Version**

> AWS MSK kafka 3.2
>  kafka-go 0.4.36

**Expected Behavior**

> should not take more memory

**Observed Behavior**

> readNewBytes takes huge memory

pprof screen shot:

![image](https://user-images.githubusercontent.com/31345007/200733279-5e6c486d-6f08-4afa-aed8-73c288b3fdf3.png)

![image](https://user-images.githubusercontent.com/31345007/200732890-cc78cace-1e3b-4deb-abfd-49c6c15f1069.png)

![image](https://user-images.githubusercontent.com/31345007/200732764-c9fa6a54-bbe6-4382-923d-2ef4234e3cb2.png)

**Comment by gopi-bathala** [comment]
this issue is due to our application logic and nothing to do with kafka-go. Hence, closing the issue

**Comment by SimonFuu** [comment]
same issue, could u pls show any details?
