### ISSUE TITLE
go dep and kafka-go

### ISSUE THREAD

**Issue by maxim-ge** [segmentio/kafka-go#103]
For project which uses kafka-go `dep init` results into:

```
[[constraint]]
  branch = "master"
  name = "github.com/segmentio/kafka-go"
```

Whereas sarama:
```
[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.16.0"
```

Don't you have an intent to pin down first version somehow?

**Comment by f2prateek** [comment]
This is likely because we haven't cut a tag yet.

**Comment by maxim-ge** [comment]
Could someone add a tag like v1.0.0, please?

**Comment by f2prateek** [comment]
I don't think we're ready to cut a v1 yet https://github.com/segmentio/kafka-go/issues/96#issuecomment-385560506.

**Comment by maxim-ge** [comment]
Ok, 0.1.0 is also awesome.

**Comment by collinvandyck** [comment]
@maxim-ge in the meanwhile, `dep` allows you to specify a `revision` for a constraint.  at least this way you could pin it to a commit in the absence of a tag.

**Comment by maxim-ge** [comment]
@collinvandyck - you are right, missed this option, thx!
