### ISSUE TITLE
Consumers failed to subscribe to the topic and the partition intermittently. 

### ISSUE THREAD

**Issue by mohit-bureau** [segmentio/kafka-go#1034]
**Describe the bug**

> Consumer group is not starting to consume messages. However, I am able to consume messages from the kafka-console consumer cli. 

**Kafka Version**

> * What version(s) of Kafka are you testing against?
Apache Kafka 3.3.0

> * What version of kafka-go are you using?
v0.4.38

**To Reproduce**

> Resources to reproduce the behavior:

Code:
```go
func main() {

	topic_name := "dev-billing"
	signals := make(chan os.Signal, 1)
	signal.Notify(signals, syscall.SIGINT, syscall.SIGKILL)
	ctx, cancel := context.WithCancel(context.Background())

	go func() {
		sig := <-signals
		fmt.Println("Got signal: ", sig)
		cancel()
	}()

	r := kafka.NewReader(kafka.ReaderConfig{
		Brokers:                []string{"0.0.0.0:9092"},
		GroupID:                "consumer-group-biller",
		GroupTopics:            []string{},
		Topic:                  topic_name,
		QueueCapacity:          10,
		MinBytes:               10e3,
		MaxBytes:               10e6,
		MaxWait:                3 * time.Second,
		PartitionWatchInterval: 5 * time.Second,
		WatchPartitionChanges:  true,
		StartOffset:            kafka.LastOffset,
		ReadBackoffMax:         10 * time.Second,
		Logger:                 log.Default(),
		OffsetOutOfRangeError:  true,
	})

	i := 0

	// listening for the interrupts in a different channel.
	defer func() {
		err := r.Close()
		if err != nil {
			fmt.Println("Error closing consumer: ", err)
			return
		}
		fmt.Println("Consumer closed")
	}()

	for {
		m, err := r.FetchMessage(ctx)
		if err != nil {
			break
		}
		msg := m.Value
		content := Event{}
		json.Unmarshal([]byte(msg), &content)

		fmt.Printf("%+v\n", content)

		if content.StatusCode == 200 {
			i++
		}

		if err := r.CommitMessages(ctx, m); err != nil {
			log.Fatal("failed to commit messages:", err)
		}
		fmt.Println("Total:", i)
	}

	if err := r.Close(); err != nil {
		log.Fatal("failed to close reader:", err)
	}
}

```

**Expected Behavior**

Consumers should start consuming the messages in the topic partitions after the last offset as soon as it is started. 

**Observed Behavior**

The consumer is not able to subscribe to the topic when the producer is already producing. If the consumer is start before the producer it works. 

Error logs:
```
2022/11/17 14:25:34 entering loop for consumer group, consumer-group-biller
2022/11/17 14:25:37 joined group consumer-group-biller as member consumer@localhost.local (github.com/segmentio/kafka-go)-98bd8f69-bb6a-4130-a50b-16edf0c2cdff in generation 44
2022/11/17 14:25:37 joinGroup succeeded for response, consumer-group-biller.  generationID=44, memberID=consumer@localhost.local (github.com/segmentio/kafka-go)-98bd8f69-bb6a-4130-a50b-16edf0c2cdff
2022/11/17 14:25:37 Joined group consumer-group-biller as member consumer@localhost.local (github.com/segmentio/kafka-go)-98bd8f69-bb6a-4130-a50b-16edf0c2cdff in generation 44
2022/11/17 14:25:37 received empty assignments for group, consumer-group-biller as member consumer@localhost.local (github.com/segmentio/kafka-go)-98bd8f69-bb6a-4130-a50b-16edf0c2cdff for generation 44
2022/11/17 14:25:37 sync group finished for group, consumer-group-biller
2022/11/17 14:25:37 subscribed to topics and partitions: map[]
2022/11/17 14:25:37 started heartbeat for group, consumer-group-biller [3s]
2022/11/17 14:25:37 started partition watcher for group, consumer-group-biller, topic dev-billing [5s]
2022/11/17 14:25:37 started commit for group consumer-group-biller
```

When it worked:
```
2022/11/17 14:09:02 entering loop for consumer group, consumer-group-biller
2022/11/17 14:09:04 joined group consumer-group-biller as member consumer@localhost.local (github.com/segmentio/kafka-go)-fd0d8373-d966-4600-9cd6-d0dda31a7273 in generation 35
2022/11/17 14:09:04 joinGroup succeeded for response, consumer-group-biller.  generationID=35, memberID=consumer@localhost.local (github.com/segmentio/kafka-go)-fd0d8373-d966-4600-9cd6-d0dda31a7273
2022/11/17 14:09:04 Joined group consumer-group-biller as member consumer@localhost.local (github.com/segmentio/kafka-go)-fd0d8373-d966-4600-9cd6-d0dda31a7273 in generation 35
2022/11/17 14:09:04 sync group finished for group, consumer-group-biller
2022/11/17 14:09:04 subscribed to topics and partitions: map[{topic:dev-billing partition:0}:25]
2022/11/17 14:09:04 started heartbeat for group, consumer-group-biller [3s]
2022/11/17 14:09:04 started partition watcher for group, consumer-group-biller, topic dev-billing [5s]
2022/11/17 14:09:04 initializing kafka reader for partition 0 of dev-billing starting at offset 25
2022/11/17 14:09:04 started commit for group consumer-group-biller
2022/11/17 14:09:04 the kafka reader for partition 0 of dev-billing is seeking to offset 25
{RequestID:f9f1971f-3d5b-4ef5-b92b-880fe094887e EventID:0d52de85-8da4-435d-8d19-e267947670c3 Event:example MerchantID:id Status:OK StatusCode:200}
2022/11/17 14:09:04 committed offsets for group consumer-group-biller:
```

**Comment by dominicbarnes** [comment]
I did my best to reproduce what you're describing, but I think there are still some outstanding questions about your situation.

The code you supplied isn't complete, but I was able to get something running with the following changes:
- Adding a `package main` declaration
- Adding an `import` list of dependencies, including kafka-go
- Copying the `docker-compose.yml` from kafka-go (which includes topic auto-creation)
- Adding a `type Event struct { StatusCode int }` based on how you used it later
- Changing the `Brokers` config to `[ "localhost:9092" ]`

With this running, I was able to run the consumer and see no messages, as expected the topic was empty and the logs indicated that it wasn't yet available until auto-creation kicked in.

Next, I added a quick `kafka.Writer` to publish a single message before starting the consumer. I noticed that on each time I restarted the script, a new message was published and the reader would see the higher offset, but never consume the message. This sounds like what you described before, so I'll explain what is happening.

When using `LastOffset`, a new consumer will take the highest offset and begin consuming from there. For example, if the topic has 3 messages in it when the consumer starts, only the 4th message and beyond will be processed. However, if the consumer group never processes a new message, it will not commit an offset to the brokers, so this process will start all over again next time the consumer starts up.

My hunch here is that the message volume is quite low, in which case I may recommend using `FirstOffset` instead, as long as the topic has messages in it that have not expired, you'll at least be able to commit an offset for your consumer group. I fully acknowledge I had to make a lot of assumptions here, as I was operating on incomplete information, so please include more details if there is more to the situation that we can troubleshoot further.
