### ISSUE TITLE
Transaction support in producers

### ISSUE THREAD

**Issue by navaneeth** [segmentio/kafka-go#104]
Hi,

Any plans to support transaction support in producer?

**Comment by abraithwaite** [comment]
No plans, but happy to accept contributions.

**Comment by achille-roussel** [comment]
@navaneeth would you be available to submit a pull request that adds support for transactions? Or maybe start the discussion with some design ideas?

**Comment by navaneeth** [comment]
I'd be happy to do. But no guarantees on the timeline. Is that fine?

**Comment by achille-roussel** [comment]
Sure thing, just reach out if you have any questions or need guidance :+1:

**Comment by scarbo87** [comment]
I want to do this task. @achille-roussel, have any idea?

**Comment by achille-roussel** [comment]
Closing this issue in favor of #216

**Comment by abh** [comment]
Now in #755

**Comment by shiva0612** [comment]
Now in #897
