### ISSUE TITLE
Delay in Message read of order of ~10 seconds.

### ISSUE THREAD

**Issue by lazyboson** [segmentio/kafka-go#1041]
**Describe the bug**

I have couple of services exchanging data over Managed Kafka Service(MKS) of AWS. I am using  following configuration of writer 
```	
p.flowEventWriter = &kafka.Writer{
		Addr:        kafka.TCP(p.config.BrokerUrls...),
		Topic:       p.config.FlowKafkaTopic,
		Balancer:    &kafka.Hash{},
		MaxAttempts: 1,
		BatchSize:   1,
	}
```

and below is my reader configuration -
```
e.flowEventReader = kafka.NewReader(kafka.ReaderConfig{
		Brokers:  e.config.BrokerUrls,
		GroupID:  "flowExecutor",
		Topic:    e.config.KafkaTopic,
		MinBytes: 1,    // 1B
		MaxBytes: 10e6, // 10MB
	})
```
Both services are running in docker at network host.

when we give load ~ 10 events per seconds on above consumerGroup. We are encountering the delay of order of ~10 seconds. which can be seen in MKS Matrices.

<img width="733" alt="exec" src="https://user-images.githubusercontent.com/63603603/204001443-193fd5e0-8373-4abd-86a4-31ada89e95b4.png">

**Kafka Version**

>2.8.2
> 2.8.2

**Additional Context**

> Is there any problem in configuration for this delay or this can be issue on MKS.

**Comment by rhansen2** [comment]
Hi @lazyboson,
I don't see anything obviously wrong with your config. Are you seeing the delay in your consumer as well or just based on that metric?

Based on the AWS docs for MSK:
EstimatedTimeLag | After consumer group consumes from a topic. | Time estimate (in seconds) to drain the partition offset lag.

It's not clear to me if that metric is representing an actual delay or not.

If possible, hooking up a logger like https://github.com/segmentio/kafka-go#logging could provide more insights.

**Comment by akbariandev** [comment]
Same issue. 

> Hi @lazyboson, I don't see anything obviously wrong with your config. Are you seeing the delay in your consumer as well or just based on that metric?
> 
> Based on the AWS docs for MSK: EstimatedTimeLag | After consumer group consumes from a topic. | Time estimate (in seconds) to drain the partition offset lag.
> 
> It's not clear to me if that metric is representing an actual delay or not.
> 
> If possible, hooking up a logger like https://github.com/segmentio/kafka-go#logging could provide more insights.

Same issue. I see this delay on side of the consumer when setting group id. Between 10 to 20 seconds delay will occur but without group id, no delay happened.

**Comment by pmsdOliveira** [comment]
Setting MaxWait to a low interval like time.Second on kafka.ReaderConfig solved this for me

```golang
kafka.NewReader(kafka.ReaderConfig{
	Brokers:  brokers,
	GroupID:  groupId,
	Topic:    topic,
	MinBytes: 10e3, // 10KB
	MaxBytes: 10e6, // 10MB
	MaxWait:  time.Millisecond,
})
```

**Comment by rhansen2** [comment]
Closing this issue. Based on the description of the metric I'm not sure this represents any real lag especially seeing as changing maxwait affects the metric. Feel free to reopen with more information if the issue persists.
