### ISSUE TITLE
How to write message to desired partition ? 

### ISSUE THREAD

**Issue by emrecavunt** [segmentio/kafka-go#1047]
From my understanding, `kafka.WriterConfig` handles the partitioning.  And we can benefit from existing balancers e.g. `Hash{}`, `RoundRobin{},` e.g. which is cool to have it. 

But what we need to achieve is more like `confluent-kafka-go`,  and it has the ability to define the desired partition while declaring messages/producers. An example of usage like below; 

[producer.example.go](https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/producer_example/producer_example.go)

```
err = p.Produce(&kafka.Message{
			TopicPartition: kafka.TopicPartition{Topic: &topic, Partition: kafka.PartitionAny},
			Value:          []byte(value),
			Headers:        []kafka.Header{{Key: "myTestHeader", Value: []byte("header values are binary")}},
		}, nil)
		
```
**Q:**  it will be a massive effort for us to replace the existing behaviour of our legacy consumers. How can we send a message to desired `Partition` as confluent-kafka-go does?
```
w := &kafka.Writer{
		...
		Balancer:     &kafka.LeastBytes{}, //  or .Hash{}
		RequiredAcks: writerRequiredAcks,
		...
	}
```
and yet `kafka.Message` has a `Partition` variable but it is read-only as it is commented as: [message.go](https://github.com/segmentio/kafka-go/blob/main/message.go)

>  Partition is read-only and MUST NOT be set when writing messages 

Kafka Version
What version(s) of Kafka are you testing against?
Confluent Platform
What version of kafka-go are you using?
v0.4.36

**Observed Behavior**
it doesn't produce a message to the desired partition. We have played around with the balancer but didn't respond as we hoped. 

```
kafka.Message {
                 ...
		Partition: 2,
	}
```

**Comment by dominicbarnes** [comment]
If you need such strict control over which partition you write to, you could implement a custom Balancer with `BalancerFunc`:

```go
Balancer: kafka.BalancerFunc(func (msg kafka.Message, partitions ...int) int {
	return 2
})
```

This is a contrived example, I'm not 100% sure how you're choosing partitions, but I'm hoping this points to the configuration you need.

If this isn't enough, would you mind running through your use-case in more detail? Another option would be to create a `Conn` with the topic/partition configured directly, but I'm hoping the above is more of a direct solution.

**Comment by mrkagelui** [comment]
thank you very much for shedding light on this topic, you've helped me a great deal!

I don't have a concrete use case yet, but just checking. the example you gave us is essentially an option to decide the partitions based on something in the message. but is there an option to specify the partition at publishing, based on something else? a weird but quick example off the top of my head is, let's say my publisher saves some record into the database before publishing, and want to decide the partition based on the DB ID of the record (perhaps so that the same consumer always gets the message related to the same DB ID).

I'm a total kafka noob, let me know if something doesn't make sense to you!

**Comment by dominicbarnes** [comment]
You may be able to use `WriterData` (which was just recently added) to attach other arbitrary metadata to your `Message`. This is a new API, so there may be some kinks to work out, but I would try that first.

Beyond that, the `Balancer` is just an interface, you can attach most anything you want to it, so you'd have access to more than just the raw `Message`.

I'm going to close this particular issue, as I believe we've covered the original question. If you have a more concrete use-case and have questions about implementing a custom `Balancer`, feel free to open a new issue with those details.
