### ISSUE TITLE
SASL handshake failed: EOF when TLS InsecureSkipVerify: true is not set

### ISSUE THREAD

**Issue by lariskovski** [segmentio/kafka-go#1049]
**Describe the bug**

Connection to Kafka Cluster fails  when the dialer config `TLS: &tls.Config{InsecureSkipVerify: true}` is not set.

**Kafka Version**

- kafka-go v0.4.38
- 7.3.0 Confluent Platform (Apache Kafka® 3.3.0)

**To Reproduce**

> Resources to reproduce the behavior:

~~~~
func GetTopics(bootstrapServer string, username string, password string) []string {

	mechanism := plain.Mechanism{Username: username, Password: password}
	dialer := &kafka.Dialer{
		Timeout:       10 * time.Second,
		DualStack:     true,
		SASLMechanism: mechanism,
	}
	
	conn, err := dialer.DialContext(context.Background(), "tcp", bootstrapServer)
	if err != nil {
		panic(err.Error())
	}
	defer conn.Close()
	
	partitions, err := conn.ReadPartitions()
	if err != nil {
		panic(err.Error())
	}
	m := map[string]struct{}{}
	
	for _, p := range partitions {
		m[p.Topic] = struct{}{}
	}
	topics := []string{}
	for topic := range m {
		topics = append(topics, topic)
	}

	return topics
}
~~~~

**Expected Behavior**

> Return clsuter topics

**Observed Behavior**

`panic: could not successfully authenticate to xxxxx.confluent.cloud:9092 with SASL: SASL handshake failed: EOF`

> A clear and concise description of the behavior you observed.

When not setting `TLS: &tls.Config{InsecureSkipVerify: true}` on kafka.Dialer the error is present.

```
	dialer := &kafka.Dialer{
		Timeout:       10 * time.Second,
		DualStack:     true,
		SASLMechanism: mechanism,
	}

```

The code below works just fine:

```
	dialer := &kafka.Dialer{
		Timeout:       10 * time.Second,
		DualStack:     true,
		SASLMechanism: mechanism,
		TLS: &tls.Config{InsecureSkipVerify: true},
	}
```

**Comment by rhansen2** [comment]
Hi @lariskovski,

If you're using TLS I believe you still need to specify a config even if you don't want to set InsecureSkipVerify. 

Could you try the below snippet to see if that makes any difference?

```go
	dialer := &kafka.Dialer{
		Timeout:       10 * time.Second,
		DualStack:     true,
		SASLMechanism: mechanism,
                TLS: &tls.Config{}
	}

```

Thanks!
