### ISSUE TITLE
Message accounting does not include size of headers.

### ISSUE THREAD

**Issue by kung-foo** [segmentio/kafka-go#1050]
**Describe the bug**

Message accounting does not include size of headers. See:

https://github.com/segmentio/kafka-go/blob/v0.4.38/message.go#L43-L45

When messages get close to the bytes limit, they may end up going over due to headers. This results in a tcp rst from Azure Event Hub.

**Kafka Version**

Azure Event Hubs

**To Reproduce**

Send a batch messages with about 1MB of _payload_. Add headers. Boom.

**Expected Behavior**

Success.

**Observed Behavior**

**Additional Context**

**Comment by dominicbarnes** [comment]
This is interesting! At first, I thought simply we didn't factor in the header size at all, but that didn't seem likely as I'm sure we would have seen some sort of network errors related to this kind of mismatch. Once I dived into the code, I found the header size is calculated at the time the message is being written, which comes after the batch has been determined:

https://github.com/segmentio/kafka-go/blob/b7377546e0b02af5daaad25f739ccfa51dbc601e/write.go#L558-L562
https://github.com/segmentio/kafka-go/blob/b7377546e0b02af5daaad25f739ccfa51dbc601e/recordbatch.go#L104-L107

As you suggested, it seems the solution here is to ensure that headers are included when computing batches upstream of this code here.

I'll do my best to open a PR for this, but we will also gladly review one if you decide to submit. :)
