### ISSUE TITLE
Can I use kafka-go to get Topic's all value size? 

### ISSUE THREAD

**Issue by MasterYang7** [segmentio/kafka-go#1052]
Can I use kafka-go to get Topic's all value size? 

I want to get the topic 's all value size. I find this Java api doc  ↓  
But I not find this api in all go SDK 
https://kafka.apache.org/30/javadoc/org/apache/kafka/clients/admin/ReplicaInfo.html

**Comment by rhansen2** [comment]
Hi @MasterYang7,

I'm not familiar with a topics all value size and I don't see any mention of it on the documentation you linked.

Could you please provide a bit more description of what you're trying to do?

Thanks!
