### ISSUE TITLE
func (r *Reader) FetchMessages(ctx context.Context, maxSize int, timeout time.Interval) ([]Message, error)

### ISSUE THREAD

**Issue by dashie** [segmentio/kafka-go#1055]
I would like to fetch N messages (limited by max or timeout) using the Reader.
I need to read object that needs to be stored on DB, so the pattern is to read a batch of N messages, to transform them in DB objects, and to commit them on Kafka only if the DB transaction succeeds. But because I need to store them on DB it is better to have a batch of them, to limit the number of transactions.

**Comment by rhansen2** [comment]
Hi @dashie,

Though perhaps not ideal, you should be able accomplish this behavior by calling `FetchMessage` N times setting the expiration of the passed in context to your desired timeout.
