### ISSUE TITLE
Reader - ConsumerGroup Vs Partition

### ISSUE THREAD

**Issue by git-dhyaneshpoojary** [segmentio/kafka-go#1056]
I am writing a go lang service for data pipeline where speed matters. I am testing kafka reader and found following 

- 32 go routine in a single instance reading from 32 partition simultaneously. The speed is superb and no complains.

```
used the following code snippet
r := kafka.NewReader(kafka.ReaderConfig{
    Brokers:   []string{"localhost:9092","localhost:9093", "localhost:9094"},
    Topic:     "topic-A",
    Partition: 0,
    MinBytes:  10e3, // 10KB
    MaxBytes:  10e6, // 10MB
})
```

- But, 32 go routine in a single instance using same consumer group id, the speed drastically decreases. wondering why?

```
used the following code snippet
r := kafka.NewReader(kafka.ReaderConfig{
    Brokers:   []string{"localhost:9092", "localhost:9093", "localhost:9094"},
    GroupID:   "consumer-group-id",
    Topic:     "topic-A",
    MinBytes:  10e3, // 10KB
    MaxBytes:  10e6, // 10MB
})
```

**Comment by git-dhyaneshpoojary** [comment]
I found out why consumer group id is slow. In the example code snippet shared in this repo for ConsumerGroup does not have commit interval specified. By default commit interval is zero which means fetch and commit immediately which cause the reader to slow down. When using consumer group please use commit interval in reader config to see effect. Why the partition reader was faster was because it only fetches the message and then it needs manual commit.

**Comment by rhansen2** [comment]
Closing this issue as it sounds like you've found a solution.
