### ISSUE TITLE
controller broker port whit Reslover

### ISSUE THREAD

**Issue by AlgerDu** [segmentio/kafka-go#1057]
**Describe the solution you would like**

I have a msk cluster. it looks like this:
* a.myhost:9098
* b.myhost:9098

now, I need to connect them by nginx, like this:
* myNginxHost:9098 -> a.myhost:9098
* myNginxHost:9099 -> b.myhost:9098

I whish the port is always active from `Reslover.LookupHost()` .
Is there a better way ?

**Comment by rhansen2** [comment]
Hi @AlgerDu,

Though I've never attempted this set up before, it might be able to be accomplished by manipulating the advertised listeners in your cluster. https://www.confluent.io/blog/kafka-listeners-explained/ describes a bit about how it might be done.

Hopefully that helps!
