### ISSUE TITLE
Add a method in *Writer that can return the delivery partiton and offset

### ISSUE THREAD

**Issue by chazex** [segmentio/kafka-go#1064]
**Describe the solution you would like**
Our business needs to record the partition and offset of message delivery, but there is no such method in *Writer, WriteMessages() just returns whether there is an error. kafka.*Conn.WriteCompressedMessagesAt() can get the delivered offset and partiton, but it is not as convenient to use as kafka.Writer. For example, various Partition Balancer solutions can be implemented through configuration, and self-reconnection.

> A clear and concise description of what you want to happen.

After the message is delivered, the delivered partition and offset can be returned

thanks!

**Comment by 3AceShowHand** [comment]
I think you can take a look at the writer's `Completion` method, it returns a slice of messages, each message's  partition and offset fields is what you desired.

**Comment by dominicbarnes** [comment]
@chazex as mentioned by @3AceShowHand you can use the `Completion` configuration function to receive these types of details after writing. At first, I thought this may only be called upon for Async writes, but internally it looks like it is always called. While it will end up being called on a separate goroutine, it is still an option based on what you've described.

Most of the time, writers don't need to be aware of message offsets, as they're really just implementation details for consumers, so I'm curious what your use-case is.

**Comment by dominicbarnes** [comment]
I'm going to close this issue due to a lack of response, feel free to re-open if you need further assistance.
