### ISSUE TITLE
How to WriteMessage Via a Non-leader Connection

### ISSUE THREAD

**Issue by davidzhongsydney** [segmentio/kafka-go#1065]
**Describe the bug**

May I ask if the connLeader is connected  via an existing non-leader connection, how use the connLeader to write message to a topic?

The code below is from the README file.
```
To Connect To Leader Via a Non-leader Connection
// to connect to the kafka leader via an existing non-leader connection rather than using DialLeader
conn, err := kafka.Dial("tcp", "localhost:9092")
if err != nil {
    panic(err.Error())
}
defer conn.Close()
controller, err := conn.Controller()
if err != nil {
    panic(err.Error())
}
var connLeader *kafka.Conn
connLeader, err = kafka.Dial("tcp", net.JoinHostPort(controller.Host, strconv.Itoa(controller.Port)))
if err != nil {
    panic(err.Error())
}
defer connLeader.Close()
```

Is it possible to have some code like below
```
connLeader.Set(topic, partition)
_, err = connLeader.WriteMessages(
		kafka.Message{Value: []byte("one!")},
		kafka.Message{Value: []byte("two!")},
		kafka.Message{Value: []byte("three!")},
	)
```

**Kafka Version**

> * What version of kafka-go are you using?
v0.4.38

**Comment by dominicbarnes** [comment]
As far as I understand, the broker must also be the leader for the topic/partition you are attempting to write to, which won't be guaranteed when connecting like this. You should probably consider using the `Writer`, as this sort of book-keeping will be handled automatically for you.

Perhaps I am misunderstanding your use-case though, could you elaborate more on what you're trying to accomplish?

**Comment by dominicbarnes** [comment]
Closing this issue due to a lack of response, feel free to re-open if you need further assistance.
