### ISSUE TITLE
Establishing connection latency problem when TLS and SCRAM Enabled

### ISSUE THREAD

**Issue by Abdulsametileri** [segmentio/kafka-go#1066]
Hello, first of all, thank you very much for this great library.

***Bug | Misimplementation***
We are using `secureDialer` to connect our Kafka brokers. It means we are using tls & scram when establishing connections our Kafka brokers.

We are facing latency when establishing this type of connection in our individual development and stage environments.
This latency is approximately ~20min; therefore, we have a hard time developing. At first glance, it seems establishing the first connection is really time-consuming 🤔 

Note: For our java spring projects, we are connecting the same Kafka clusters as soon as we run the project. No latency at all 🤔 

I don't know if this is a bug or mis-implementation; I wanted to show our implementation. 

***Our implementation***

We are initializing our kafka consumer as follows;

```go
func NewKafkaConsumer(kafkaConfig config.KafkaConfig, consumerConfig config.Consumer) KafkaConsumer {
	readerConfig := kafka.ReaderConfig{
		Brokers:        strings.Split(kafkaConfig.Servers, ","),
		GroupID:        consumerConfig.ConsumerGroup,
		GroupTopics:    consumerConfig.Topics,
		MinBytes:       10e3, 
		MaxBytes:       10e6,
		MaxWait:        2 * time.Second,
		CommitInterval: time.Second,
	}

	if consumerConfig.SecureCluster {
		tlsConfig := CreateTLSConfig(&kafkaConfig)
		secureDialer := CreateSecureKafkaDialer(&kafkaConfig, tlsConfig)

		readerConfig.Brokers = strings.Split(kafkaConfig.SecureServers, ",")
		readerConfig.Dialer = secureDialer
		readerConfig.GroupBalancers = []kafka.GroupBalancer{kafka.RackAffinityGroupBalancer{Rack: kafkaConfig.Rack}}
	}

	newConsumer := kafka.NewReader(readerConfig)
	return &kafkaConsumer{consumer: newConsumer}
}
```

Creating TLS Config following
```go
func CreateTLSConfig(kafkaConfig *config.KafkaConfig) *tls.Config {
	rootCA, err := os.ReadFile(kafkaConfig.RootCAPath)
	if err != nil {
		panic("Error while reading Root CA file: " + kafkaConfig.RootCAPath + " error: " + err.Error())
	}

	interCA, err := os.ReadFile(kafkaConfig.IntermediateCAPath)
	if err != nil {
		panic("Error while reading Intermediate CA file: " + kafkaConfig.IntermediateCAPath + " error: " + err.Error())
	}

	caCertPool := x509.NewCertPool()
	caCertPool.AppendCertsFromPEM(rootCA)
	caCertPool.AppendCertsFromPEM(interCA)

	return &tls.Config{
		RootCAs: caCertPool,
	}
}
```

Setting SCRAM Mechanism following
```go
func CreateSecureKafkaDialer(kafkaConfig *config.KafkaConfig, tlsConfig *tls.Config) *kafka.Dialer {
	mechanism, err := scram.Mechanism(scram.SHA512, kafkaConfig.ScramUsername, kafkaConfig.ScramPassword)
	if err != nil {
		panic("Error while creating SCRAM configuration, error: " + err.Error())
	}

	return &kafka.Dialer{
		TLS:           tlsConfig,
		SASLMechanism: mechanism,
	}
}
```

we listen to new messages as `msg, err := k.kafkaConsumer.ReadMessage()` 

Segment IO version: `v0.4.35`
Go version: `1.17`

**Is it possible to point us to the right direction? Any idea 🤔 ?**

**Comment by rhansen2** [comment]
Hi @Abdulsametileri,

Nothing immediately stands out as wrong in your code. 

Are your java spring applications using the same MinBytes as your go application? 

Besides that, enabling logging may help show what's happening in more detail.

https://pkg.go.dev/github.com/segmentio/kafka-go#readme-logging

**Comment by Abdulsametileri** [comment]
Thank you very much, yea it seems the connection latency problem is because of minBytes value. I will enable logging and paste it here on Monday

**Comment by Abdulsametileri** [comment]
As soon as I leave minBytes as its default value, our project connects immediately. Thank you for your support :)
