### ISSUE TITLE
SyncProducer blocked until BatchTimeout

### ISSUE THREAD

**Issue by jseparator** [segmentio/kafka-go#1067]
**Describe the bug**

When set `Async = false`, kafka.Writer.WriteMessages() blocked until BatchTimeout

**Kafka Version**

Kafka 3.1.0
kafka-go v0.4.38

**To Reproduce**

Here is my test code

```go
func TestSync(t *testing.T) {
	p := &kafka.Writer{
		Addr:         kafka.TCP("kfk-dev01:9092", "kfk-dev02:9092"),
		BatchSize:    1000,
		BatchTimeout: time.Minute,
		Compression:  compress.Snappy,
		RequiredAcks: kafka.RequireOne,
		Async:        false,
		ErrorLogger:  kafka.LoggerFunc(log.Errorf),
	}

	msgs := make([]kafka.Message, 10)
	for i := 0; i < 10; i++ {
		msgs[i] = kafka.Message{
			Topic: "errlog",
			Value: []byte("Test"),
		}
	}

	//ctx, cancel := context.WithCancel(context.Background())
	go func() {
		time.Sleep(time.Second * 10)
		log.Info("after 10 second")
	}()

	log.Info("Start")
	err := p.WriteMessages(context.Background(), msgs...)
	if err != nil {
		log.Errorf("WriteMessagesErr: %v", err)
	}
	log.Info("Finished")
}
```

```log
=== RUN   TestSync
INFO[2023-01-30T12:16:30.036] sync_test.go:53 Start                                        
INFO[2023-01-30T12:16:40.036] sync_test.go:50 after 10 second                              
INFO[2023-01-30T12:17:33.546] sync_test.go:58 Finished                                     
--- PASS: TestSync (63.51s)
PASS
```

**Expected Behavior**

In sync mode, WriteMessages() should flush and send to kafka brokers immediately
I think the reason why does this happen is this code `case <-batch.done`,
batch.done channel closed  when timeout or batch is full, but in this siution batch is not full.

IF I set `Async = true`, I will face another issue  https://github.com/segmentio/kafka-go/issues/819

```go
	batches := w.batchMessages(msgs, assignments)
	if w.Async {
		return nil
	}

	done := ctx.Done()
	hasErrors := false
	for batch := range batches {
		select {
		case <-done:
			return ctx.Err()
		case <-batch.done:
			if batch.err != nil {
				hasErrors = true
			}
		}
	}
```

**Comment by dominicbarnes** [comment]
This is by design, kafka-go will always batch messages to optimize round-trips to the brokers. If you want your messages delivered at a different cadence, then you will need to adjust the batch config (eg: `BatchTimeout`, `BatchSize`, `MinBytes`, `MaxBytes`) to fit your application needs.

The default `BatchTimeout` is 1s, and you've explicitly set it to 1m, which is the primary reason the extra delay in this case. You may want to experiment with the defaults and then adjust from there.
