### ISSUE TITLE
Question: how to close a `Client` instance ?

### ISSUE THREAD

**Issue by 3AceShowHand** [segmentio/kafka-go#1068]
`Client` does not provide a method to close it, such as releasing all resources, like network connections, or anything else.

* Is it necessary to close the client to prevent the potential resource leak?
* Is there any way to achieve the goal?

**Comment by rhansen2** [comment]
Hi @3AceShowHand,

The client itself does not create any resources that need to be cleaned up. The Transport associated with it maintains the connections which can be cleaned up via https://pkg.go.dev/github.com/segmentio/kafka-go#Transport.CloseIdleConnections
