### ISSUE TITLE
The consumer continues, even if the Topic is deleted 

### ISSUE THREAD

**Issue by kanhaiyaratsky** [segmentio/kafka-go#1071]
**Describe the solution you would like**
As the `UnknownTopicOrPartition` is a retriable error, the library considers it temporary
And if we delete the topic,  the consumers run in an infinite loop while looking up for this topic, and throws this temporary error and does not send the error out to the caller

> A clear and concise description of what you want to happen.
We should be having the temporary definition configurable for the errors so that if we don't consider `UnknownTopicOrPartition` to be temporary and want to close of consumer, we can do that.

**Supporting documentation**

> Please provides links to relevant Kafka protocol docs and/or KIPs.
<img width="284" alt="temporary" src="https://user-images.githubusercontent.com/103108987/216022179-98afee40-a767-4d32-9d96-2dbd72fe6406.png">
<img width="719" alt="Screenshot 2023-02-01 at 4 18 04 PM" src="https://user-images.githubusercontent.com/103108987/216022374-79ae906e-fe44-4fbe-879e-f8c5c6bfa5a1.png">

**Comment by kanhaiyaratsky** [comment]
@dominicbarnes any comments or workaround for this ?

**Comment by dominicbarnes** [comment]
I'm going to close this ticket due to a lack of activity. We will still consider a PR to adjust the internal handling of `UnknownTopicOrPartition` errors if one is submitted.
