### ISSUE TITLE
Dialer.DualStack ignored when set to false (and huge number of connections)

### ISSUE THREAD

**Issue by lbergesio** [segmentio/kafka-go#1072]
**Describe the bug**

I am creating the dealer I later use for the readers and writers the following way:

```
api.dialer = &kgo.Dialer{                                       
        Timeout:   timeout,                                     
        DualStack: dualStack,                                   
        TLS: &tls.Config{                                       
                RootCAs:    rootCA,                             
                MinVersion: 0x0303, // TLS 1.2 from https://pkg.go.dev/crypto/tls#VersionTLS12
        },                                                      
        SASLMechanism: plain.Mechanism{                         
                Username: api.opts.Username,                    
                Password: api.opts.Password,                    
        },                                                      
}                  

newReader := kgo.NewReader(kgo.ReaderConfig{
        Brokers:     hosts,                 
        Topic:       t,                     
        GroupID:     api.opts.ConsumerId,   
        MaxAttempts: MaxAttempts,           
        MaxWait:     maxWait,               
        Dialer:      api.dialer,            
})                                          
     
newWriter := kgo.NewWriter(kgo.WriterConfig{
        Brokers:      hosts,                
        Topic:        t,                    
        Balancer:     &kgo.LeastBytes{},    
        MaxAttempts:  MaxAttempts,          
        WriteTimeout: WriteTimeout,         
        Dialer:       api.dialer,           
})                                          
                                             
```

where `dualStack`is set to `false`

I still see that for (almost) any tcp4 connection there is one tcp6 connection (reduced and edited output):

```
leo:~$ netstat -an | grep 9092 
tcp        0      0 0.0.0.0:9092            0.0.0.0:*               LISTEN     
tcp        0      0 1.0.0.1:56064           1.0.0.3:9092            TIME_WAIT  
tcp        0      0 1.0.0.1:56034           1.0.0.3:9092            TIME_WAIT  
tcp        0      0 1.0.0.1:55984           1.0.0.3:9092            TIME_WAIT  
tcp        0      0 1.0.0.1:35094           1.0.0.3:9092            TIME_WAIT  
tcp6       0      0 :::9092                 :::*                    LISTEN     
tcp6       0      0 ::1:48362               ::1:9092                TIME_WAIT  
tcp6       0      0 ::1:48354               ::1:9092                TIME_WAIT  
tcp6       0      0 ::1:55156               ::1:9092                TIME_WAIT  
tcp6       0      0 ::1:48366               ::1:9092                TIME_WAIT  
 
```
**Kafka Version**

Kafka: confluentinc/cp-zookeeper-7.3.1-1-ubi8
Kafka-go: v0.4.38

**To Reproduce**

I have a two apps communicating via this kafka setup. One sends a message and reads the answer that is sent by the other after receiving the original message. After that the applications close everything and end.

**Expected Behavior**

Only see tcp4 connections.

**Observed Behavior**

I see a huge and random number of connections when sending only this one message that is sent by one app, read by the other, answered and read back by the original app:

```
while true; do netstat -an | grep 9092 | wc -l; sleep 1; done
0
2
50
59
66
```

They remain in `TIME_WAIT` state and eventually dissapear. Approx half of them are tcp4 and half tcp6 even I have configured the Dialer NOT to use dual stack.

Also why that many connections, 66? When doing the same experiment with the apache kafka scripts (https://dlcdn.apache.org/kafka/3.2.3/) the number of connections is ~10. Is this expected? Is it documented how many connection is expected kafka-go to open when a reader/writer does a read/write?

**Comment by rhansen2** [comment]
HI @lbergesio,

The DualStack value of the kafka-go Dialer looks to be a straight pass through to a net.Dialer which as deprecated the DualStack field in favor of setting FallbackDelay to < 0; Could you try setting the FallbackDelay of the kakfa-go Dialer to < 0 and see if that stops the ipv6 connections?

As far as connection counts go, the number of connections that are opened and closed depends on what operations are being performed and the number of brokers that need to be connected too.

It's worth noting that the TIME_WAIT state occurs when a connection is closed and lasts for a fixed amount of time by OS. (30s on linux I believe and upwards of 2m on windows by default). You may see more connections in that state while using kafka-go as the underlying transport will close open and close connections as needed.

**Comment by lbergesio** [comment]
> HI @lbergesio,
> 
> The DualStack value of the kafka-go Dialer looks to be a straight pass through to a net.Dialer which as deprecated the DualStack field in favor of setting FallbackDelay to < 0; Could you try setting the FallbackDelay of the kakfa-go Dialer to < 0 and see if that stops the ipv6 connections?
> 
> As far as connection counts go, the number of connections that are opened and closed depends on what operations are being performed and the number of brokers that need to be connected too.
> 
> It's worth noting that the TIME_WAIT state occurs when a connection is closed and lasts for a fixed amount of time by OS. (60s on linux I believe and upwards of 2m on windows by default). You may see more connections in that state while using kafka-go as the underlying transport will close open and close connections as needed.

I have changed my Dialer conf to:

```
                api.dialer = &kgo.Dialer{
-                       Timeout:   timeout,
-                       DualStack: dualStack,
+                       Timeout:       timeout,
+                       FallbackDelay: -1, // Do not use TCP/IP v6
                }
```


And I still see tcp6 connections:

```
leo:gateway$ netstat -an | grep 9092
tcp        0      0 0.0.0.0:9092            0.0.0.0:*               LISTEN     
tcp        0      0 1.0.0.1:56972           1.0.0.3:9092            TIME_WAIT  
tcp        0      0 1.0.0.1:57006           1.0.0.3:9092            TIME_WAIT  
tcp        0      0 1.0.0.1:57082           1.0.0.3:9092            TIME_WAIT  
tcp        0      0 1.0.0.1:57400           1.0.0.3:9092            TIME_WAIT  
tcp        0      0 1.0.0.1:56648           1.0.0.3:9092            TIME_WAIT  
tcp        0      0 1.0.0.1:57034           1.0.0.3:9092            TIME_WAIT  
tcp        0      0 1.0.0.1:53958           1.0.0.3:9092            TIME_WAIT  
tcp        0      0 1.0.0.1:56740           1.0.0.3:9092            TIME_WAIT  
tcp        0      0 1.0.0.1:56878           1.0.0.3:9092            TIME_WAIT  
tcp6       0      0 :::9092                 :::*                    LISTEN     
tcp6       0      0 ::1:39138               ::1:9092                TIME_WAIT  
tcp6       0      0 ::1:38974               ::1:9092                TIME_WAIT  
tcp6       0      0 ::1:9092                ::1:39622               ESTABLISHED
tcp6       0      0 ::1:38834               ::1:9092                TIME_WAIT  
tcp6       0      0 ::1:38766               ::1:9092                TIME_WAIT  
tcp6       0      0 ::1:38972               ::1:9092                TIME_WAIT  
tcp6       0      0 ::1:50736               ::1:9092                TIME_WAIT  
tcp6       0      0 ::1:39512               ::1:9092                TIME_WAIT  
tcp6       0      0 ::1:9092                ::1:39712               ESTABLISHED
```

**Comment by lbergesio** [comment]
> @lbergesio, Based on [golang/go#14760 (comment)](https://github.com/golang/go/issues/14760#issuecomment-195348080) it looks like my understanding of those settings is incorrect and DualStack and FallbackDelay don't serve to disable ipv6.
> 
> Perhaps supplying a DialFunc which converts the network from tcp to tcp4 may solve your issue?

Well, I am providing a domain name so it is resolved in both ip4 and ipv6 if they exist. I won't be implementing this atm, I just though that DualStack was doing exactly that. If this is not considered a bug or request for a feature please feel free to close the issue.

Thanks

**Comment by rhansen2** [comment]
When I configured a reader and writer as below I only saw ipv4 connections perhaps this will work for you as well?

```go
w := kafka.Writer{

	Transport: &kafka.Transport{
		Dial: func(ctx context.Context, network string, addr string) (net.Conn, error) {
			var d net.Dialer
			return d.DialContext(ctx, "tcp4", addr)
		},
	},
}
reader := kafka.NewReader(kafka.ReaderConfig{
	Dialer: &kafka.Dialer{
		DialFunc: func(ctx context.Context, network string, address string) (net.Conn, error) {
			var d net.Dialer
			return d.DialContext(ctx, "tcp4", address)
		},
	},
})
```

**Comment by lbergesio** [comment]
Not sure that will work with my code. I am passing a previously created dialer to the reader/writer (the same dialer to both) `api.dialer` in my original description. So I guess I will need to change `api.dialer.DialFunc` to use "tcp4" and for the writer set do somethink like this?

```
w := kafka.Writer{
        Dialer: api.dialer,
	Transport: &kafka.Transport{
		Dial: func(ctx context.Context, network string, addr string) (net.Conn, error) {
			return api.dialer.DialContext(ctx, "tcp4", addr)
		},
	},
}
```
Why do you set the Writer.Dialer then? Is not possible to define the Proto ("tcp4") for the Reader/Writer instead?

**Comment by rhansen2** [comment]
I'm sorry I missed your last reply on this issue. I'm not sure about your example, I don't see a Dialer on the Writer type. I don't believe it's possible to directly set the protocol for network connections directly on the Reader/Writer as it can be configured via the techniques in the examples above.
