### ISSUE TITLE
How to fetch uncommitted messages without triggering rebalance?

### ISSUE THREAD

**Issue by mahditakrim** [segmentio/kafka-go#1089]
I'm facing issues to fetch uncommitted messages without closing consumer and triggering partition rebalance, so is there any way to fetch uncommitted messages in kafka-go ?

**Comment by rhansen2** [comment]
Hi @mahditakrim ,

I'm not entirely sure if I'm understanding the question. Are you trying to fetch messages the Reader has previously fetched? If so the reader doesn't currently support that usage pattern when using a consumer group.

**Comment by mahditakrim** [comment]
> Hi @mahditakrim ,
> 
> I'm not entirely sure if I'm understanding the question. Are you trying to fetch messages the Reader has previously fetched? If so the reader doesn't currently support that usage pattern when using a consumer group.

Dear @rhansen2, thank you for your response.
So considering what being said, manual-commit strategy is kind of useless specially for messages that has short retention time !

**Comment by rhansen2** [comment]
@mahditakrim, 

I'm not sure I understand why manual commits are useless. Perhaps you could provide an example of what you're trying to do?

Thanks!

**Comment by mahditakrim** [comment]
> @mahditakrim,
> 
> I'm not sure I understand why manual commits are useless. Perhaps you could provide an example of what you're trying to do?
> 
> Thanks!

Imagine you have messages with short retention (relative to rebalance lag) and you're consuming messages in concurrent mode or something, in some step of process something goes wrong and you don't want to commit message so you can consume and process it later, but to fetch uncommitted messages we should trigger partition rebalance and by what I have been researched rebalance only occurs in three cases: consumer-removed, consumer-added and partition-changed.
So in this scenario uncommitted messages (failed to process) with short retention will never process and we have data-loss.

I'm thinking that Kafka says: you want exactly-once, set auto-commit and mind your business :)

**Comment by rhansen2** [comment]
Thanks for the additional details! I'm going to close this issue for now as I believe the original question is answered. Please feel free to create another issue if that's not the case, thanks!
