### ISSUE TITLE
Support Authentication 

### ISSUE THREAD

**Issue by abraithwaite** [segmentio/kafka-go#109]
Kafka supports this.  It would be nice to support it in our client as well.

https://kafka.apache.org/documentation/#security_overview

**Comment by achille-roussel** [comment]
We already support TLS encryption, but we haven’t implemented anything regarding authentication.

**Comment by mxk1235** [comment]
SASL/Kerberos would be great.  you'll likely need to take gokrb5 dependency.

**Comment by achille-roussel** [comment]
@mxk1235 regarding the external dependency, we've tried to isolate those in sub-packages of kafka-go to keep the top-level package dependency-free. I'd assume we'd want to do the same in this case by abstracting the authentication mechanism behind an interface and having the kerebros implementation in a sub-package.

**Comment by stevevls** [comment]
Just merged in #223 which adds general support for SASL as well as implementations for PLAIN and SCRAM mechanisms.

Also opened #237 and #238 as follow-ups to add additional SASL mechanisms.
