### ISSUE TITLE
How to configure kafka parameters

### ISSUE THREAD

**Issue by zhendliu** [segmentio/kafka-go#1091]
I am using our latest version, I would like to ask, how to set the following parameters "max.poll.records", "auto.offset.reset", "batch.size"

**Comment by rhansen2** [comment]
Hi @zhendliu,

kafka-go doesn't really have the equivalent of "max.poll.records". I believe that setting is specific to the behavior of the poll method of the Java consumer. 

I believe StartOffset on the ReaderConfig works the same as "auto.offset.reset".

I think BatchBytes is the equivalent of "batch.size"

Hope that helps, thanks!
