### ISSUE TITLE
DescribeGroups hangs for inactive groups

### ISSUE THREAD

**Issue by petedannemann** [segmentio/kafka-go#1109]
**Describe the bug**

Issuing a DescribeGroup request for a consumer group without active members hangs until the context deadline times out

**Kafka Version**

> * What version(s) of Kafka are you testing against?
2.4.1
> * What version of kafka-go are you using?
v0.4.39

**To Reproduce**

> Resources to reproduce the behavior:

I am testing against the kafka version 2.4.1 provided in this repo in the docker-compose-241.yml
```bash
docker-compose -f docker-compose-241.yml up -d
```

Adding `r.Close()` to the existing `TestClientDescribeGroups` in `describegroups_test.yaml` makes the consumer group inactive

```diff
modified: describegroups_test.go
@ describegroups_test.go:62 @ func TestClientDescribeGroups(t *testing.T) {
                t.Fatal(err)
        }

+        r.Close()

        resp, err := client.DescribeGroups(
                ctx,
                &DescribeGroupsRequest{
```

Running the test with an inactive consumer group leads to the DescribeGroups request timing out

```bash
go test -run TestClientDescribeGroups\$ .
context deadline exceeded
--- FAIL: TestClientDescribeGroups (10.21s)
    describegroups_test.go:28: createTopic(kafka-go-6b912294e55cdcfd, 2)
    describegroups_test.go:28: waitForTopic: found topic "kafka-go-6b912294e55cdcfd" with 2 partitions
    describegroups_test.go:71: context deadline exceeded
FAIL
FAIL    github.com/segmentio/kafka-go   10.884s
FAIL
```

**Expected Behavior**

> DescribeGroups should complete successfully for inactive consumer groups and return DescribeGroupResponse without hanging and timing out due to context deadline exceeded. 

**Observed Behavior**

> DescribeGroups does not complete successfully for inactive consumer groups and times out due to context deadline exceeded. 

**Additional Context**
We would like to be able to describe consumer groups in various states other than active in order to build a new kafka consumer lag tool that works against consumer groups in many states

**Comment by rhansen2** [comment]
I believe this is caused because the Close() call waits for ongoing background fetch requests to finish which can be up to MaxWait which isn't set in the test so it defaults to 10s. Once Close() returns, the context has already timed out. 

If you increase the context timeout to be over 10s or change the MaxWait to be under 5s you should see the expected behavior.

**Comment by petedannemann** [comment]
Thanks @rhansen2, I changed the timeout in the test to be 15 seconds and this worked
