### ISSUE TITLE
did not retry create topic when maxAttempt=10 and AllowAutoTopicCreation=true

### ISSUE THREAD

**Issue by carlclone** [segmentio/kafka-go#1113]
**Describe the bug**

when setting AllowAutoTopicCreation to true , the maxAttempts param only affect the message write , but the topic creation did not retry when temporary error occurred , should we add retry in this partition method too ?

writer.go:740
```
func (w *Writer) partitions(ctx context.Context, topic string) (int, error) {
	client := w.client(w.readTimeout())
	// Here we use the transport directly as an optimization to avoid the
	// construction of temporary request and response objects made by the
	// (*Client).Metadata API.
	//
	// It is expected that the transport will optimize this request by
	// caching recent results (the kafka.Transport types does).
	r, err := client.transport().RoundTrip(ctx, client.Addr, &metadataAPI.Request{
		TopicNames:             []string{topic},
		AllowAutoTopicCreation: w.AllowAutoTopicCreation,
	})
	if err != nil {
		return 0, err
	}
	for _, t := range r.(*metadataAPI.Response).Topics {
		if t.Name == topic {
			// This should always hit, unless kafka has a bug.
			if t.ErrorCode != 0 {
				return 0, Error(t.ErrorCode)
			}
			return len(t.Partitions), nil
		}
	}
	return 0, UnknownTopicOrPartition
}
```

**Kafka Version**

> * What version(s) of Kafka are you testing against?
> * What version of kafka-go are you using?

**To Reproduce**

> Resources to reproduce the behavior:

```yaml
---
# docker-compose.yaml
#
# Adding a docker-compose file will help the maintainers setup the environment
# to reproduce the issue.
#
# If one the docker-compose files available in the repository may be used,
# mentioning it is also a useful alternative.
...
```

```go
package main

import (
    "github.com/segmentio/kafka-go"
)

func main() {
    // Adding a fully reproducible example will help maintainers provide
    // assistance to debug the issues.
    ...
}
```

**Expected Behavior**

> A clear and concise description of what you expected to happen.

**Observed Behavior**

> A clear and concise description of the behavior you observed.

```
Often times, pasting the logging output from a kafka.Reader or kafka.Writer will
provide useful details to help maintainers investigate the issue and provide a
fix. If possible, providing stack traces or CPU/memory profiles may also contain
valuable information to understand the conditions that triggered the issue.
```

**Additional Context**

> Add any other context about the problem here.

**Comment by rhansen2** [comment]
HI @carlclone,

As document, MaxAttempts controls the number of times the Writer will attempt to deliver messages to Kafka. https://pkg.go.dev/github.com/segmentio/kafka-go#Writer

Are you seeing an error returned from WriteMessages when topic creation fails? If so could you just retry your WriteMessages calls?

Thanks!

**Comment by zydovech** [comment]
when kafka server enable auto  create topic, fetch metadata will trigger async create topic, but metadata req maybe return LeaderNotAvailable ErrorCode , should we add retry in this partition method too ?
