### ISSUE TITLE
Set BatchTimeout to 10 seconds in NewWriter will block after call Writer.Close()

### ISSUE THREAD

**Issue by bigpigeon** [segmentio/kafka-go#1121]
**Describe the bug**

> A clear and concise description of what the bug is.

here is my unittest, the function will block at writer.Close() step
```
func TestKafkaWriter(t *testing.T) {
	writer := kafka.NewWriter(kafka.WriterConfig{
		Brokers:      []string{"localhost:9092"},
		Topic:        "batch_timeout_test",
		WriteTimeout: time.Second * 10,
		ReadTimeout:  time.Second * 5,
		BatchTimeout: time.Second * 10,
		BatchSize:    100,
		Balancer:     &kafka.LeastBytes{},
		Async:        false,
	})
	msg := `{"ip": "1.2.3.4", "env":{"user": "sth"}}`
	for i := 0; i < 100000; i++ {
		err := writer.WriteMessages(context.Background(), kafka.Message{
			Key:   []byte("key"),
			Value: []byte(msg),
		})
		if err != nil {
			panic(err)
		}
	}
	writer.Close()
}
```

**Kafka Version**

> * What version(s) of Kafka are you testing against?

I use docker images confluentinc/cp-kafka:7.3.0

> * What version of kafka-go are you using?

github.com/segmentio/kafka-go v0.4.39

**Comment by rhansen2** [comment]
Is it the Close() call that's hanging here? This code looks to write in synchronous mode. Since you're writing one message at a time with BatchSize 100 you have to wait the full batch timeout between writes.
