### ISSUE TITLE
Synchronous `CommitMessages` is not always synchronous

### ISSUE THREAD

**Issue by iffyio** [segmentio/kafka-go#1126]
**Describe the bug**

Hi! Noticed a consumer receiving duplicate messages when it shouldn't have, and after debugging, found a surprising behavior by the reader.
It essentially boils down to the reader first `Commit`ting an offset, but after it goes to start fetching messages, receives messages that should have been resolved by the aforementioned commit.

I'm attaching a minimal example and the log output from the library which I think should clarify the behavior, happy to add more context and info as needed.

```go
	r := kafka.NewReader(kafka.ReaderConfig{
		Brokers: brokers,
		GroupID: groupid,
		Topic:  topic,
		StartOffset: kafka.FirstOffset,
	})


	r.CommitMessages(kafka.Message{Topic: topic, Partition: 0, Offset: 1})

	for {
		msg, err := r.FetchMessage()
		// first message has Offset 0
		assert msg.Offset >= 2 // Expected behavior
	}
```

Logs from the library suggest that the commit does not in fact happen after `CommitMessages` returns, even though that method is supposed to be synchronous - but rather when `FetchMessage` is called

In the last few lines, notice that the reader goes to commit the offset as requested, but right after it `Seek`s to 0 which is likely the source of this undesirable behavior since it doesn't follow Kafka's definition of committing an offset.

Additionally, by replacing with a confluent-kafka-go reader, things work as expected.

```

// Actual commit invocation by the application happens at this point in time as the very first thing.

joined group validio-src-bd21e1d5-94e9-489a-a8df-a55dce439d5a as member [redacted] in generation 3 selected as leader for group, src-bd21e1d5-94e9-489a-a8df-a55dce439d5a

using 'range' balancer to assign group, src-bd21e1d5-94e9-489a-a8df-a55dce439d5a
found member: [redacted]
found topic/partition: TEST-3518333a-0c5b-43ef-9bca-c49c6d3a6007/0
assigned member/topic/partitions [redacted]/TEST-3518333a-0c5b-43ef-9bca-c49c6d3a6007/[0]
...
Syncing 1 assignments for generation 3 as member [redacted] 
sync group finished for group, src-bd21e1d5-94e9-489a-a8df-a55dce439d5a
subscribed to topics and partitions: map[{topic:TEST-3518333a-0c5b-43ef-9bca-c49c6d3a6007 partition:0}:0]
started heartbeat for group, src-bd21e1d5-94e9-489a-a8df-a55dce439d5a [3s]
started commit for group src-bd21e1d5-94e9-489a-a8df-a55dce439d5a

initializing kafka reader for partition 0 of TEST-3518333a-0c5b-43ef-9bca-c49c6d3a6007 starting at offset 0
committed offsets for group src-bd21e1d5-94e9-489a-a8df-a55dce439d5a: 
	topic: TEST-3518333a-0c5b-43ef-9bca-c49c6d3a6007
		partition 0: 2
the kafka reader for partition 0 of TEST-3518333a-0c5b-43ef-9bca-c49c6d3a6007 is seeking to offset 0
```

**Kafka Version**

> * What version(s) of Kafka are you testing against? 

Kafka 3.4.0

> * What version of kafka-go are you using?

0.4.40

**Expected Behavior**

Reader should not receive previously committed messages

**Observed Behavior**

Please see illustration - the reader received a message with an offset that was synchronously committed right before the call to FetchMessage

**Comment by rhansen2** [comment]
I think what you're seeing is due to the Reader type starting the consumer group once NewReader is called. At that point the Reader is already fetching messages from any previously committed offsets. You can see in the logs you posted the reader has fetched the offsets just before your commit happens. While the call to CommitMessages is synchronous w.r.t. the calling code, the creation and initialization of the consumer group is not.
