### ISSUE TITLE
According to actual test results, kafka-go is slower than sarama.

### ISSUE THREAD

**Issue by SoThisMint** [segmentio/kafka-go#1135]
r := kafka.NewReader(kafka.ReaderConfig{
		Brokers: []string{"192.168.202.154:9092"},
		Topic:   "my-topic",
		//Partition: 0,
		MinBytes: 10e3, // 10KB
		MaxBytes: 10e6, // 10MB
	})
	r.SetOffset(0)

	for {
		m, err := r.ReadMessage(context.Background())
		if err != nil {
			break
		}
		fmt.Printf("message at offset %d: %s = %s\n", m.Offset, string(m.Key), string(m.Value))
	}

	if err := r.Close(); err != nil {
		fmt.Errorf("failed to close reader:", err)
	}

**Comment by petedannemann** [comment]
Hi @SoThisMint, what is desired in this issue? Benchmarking is very application specific and reading a single message at a time is unlikely to be used in production.
