### ISSUE TITLE
Writing to a specified partition

### ISSUE THREAD

**Issue by perceptronnn** [segmentio/kafka-go#1143]
I've a topic which is contains multiple partitions. The producer instances are running across various AWS regions, one instance per AWS region. I want to have partitioning logic such that all the data produced by a producer instance running in a given region must always go into the same partition. E.g. all the data produced by producer running in `us-west-2` should go to `us-west-2` partition and so on... How do I implement this in kafka-go? 
One way to do this is via the `Partition` field in the `Message` struct:
```
// Message is a data structure representing kafka messages.
type Message struct {
	// Topic indicates which topic this message was consumed from via Reader.
	//
	// When being used with Writer, this can be used to configure the topic if
	// not already specified on the writer itself.
	Topic string

	// Partition is read-only and MUST NOT be set when writing messages
	Partition     int
	Offset        int64
	HighWaterMark int64
	Key           []byte
	Value         []byte
	Headers       []Header

	// This field is used to hold arbitrary data you wish to include, so it
	// will be available when handle it on the Writer's `Completion` method,
	// this support the application can do any post operation on each message.
	WriterData interface{}

	// If not set at the creation, Time will be automatically set when
	// writing the message.
	Time time.Time
}
```
But because of the comment `// Partition is read-only and MUST NOT be set when writing messages`, it does not seem the right way to do it. Could someone please explain why we should not set Partition ID in the Message?
Another way is to achieve this is by defining a customer Balancer function which will return the partition ID.
Any other ideas on if there are any better ways to do this?

**Comment by sansmoraxz** [comment]
Perhaps create a `kafka.Client` and use `Produce` method

Refer: https://pkg.go.dev/github.com/segmentio/kafka-go#Client.Produce

**Comment by petedannemann** [comment]
Hi @perceptronnn, @sansmoraxz looks like they had a good pointer for you and you can specify the Partition in the [ProduceRequest](https://pkg.go.dev/github.com/segmentio/kafka-go#ProduceRequest). Have you tried that out?
