### ISSUE TITLE
Feature request: reader.FetchMessage should return another error instead of context.DeadlineExceeded

### ISSUE THREAD

**Issue by ducquangkstn** [segmentio/kafka-go#1151]
**Describe the solution you would like**

We are using this library as a reader. 
```go
ctx, cancel := context.WithTimeout(parentCtx, readerTimeout)
defer cancel()

msg, err := reader.FetchMessage(ctx)
switch {
  case errors.Is(err, context.DeadlineExceeded):
    logrus.Info("kafka timed out when retrieving a message, queue may be empty")
  case err != nil:
     return fmt.Errorf("fetch kafka message: %w", err)
  default:
    // handle message here
}
```

If the returned error is context.DeadlineExceeded, does it mean the queue is empty or it could be returned by this [line](https://github.com/segmentio/kafka-go/blob/8492075557ac8bda295a24a64866ce82eb786629/reader.go#L830C1-L831C1) or this [line](https://github.com/segmentio/kafka-go/blob/8492075557ac8bda295a24a64866ce82eb786629/reader.go#L858)

If the latter is true, then we should return another error different from  context.DeadlineExceeded

**Comment by petedannemann** [comment]
Hi @ducquangkstn,

context.DeadlineExceeded will only be returned by [this line](https://github.com/segmentio/kafka-go/blob/8492075557ac8bda295a24a64866ce82eb786629/reader.go#L827). [This signifies the reader has not found any messages within the timeout specified](https://github.com/segmentio/kafka-go/blob/8492075557ac8bda295a24a64866ce82eb786629/reader.go#L806).
