### ISSUE TITLE
Is writer.WriteMessages atomic?

### ISSUE THREAD

**Issue by Amogh-Bharadwaj** [segmentio/kafka-go#1152]
For instance in this example, will the writes to topic-A and topic-B be rolled back if the write to topic-C fails?
```Go
err := w.WriteMessages(context.Background(),
    // NOTE: Each Message has Topic defined, otherwise an error is returned.
	kafka.Message{
        Topic: "topic-A",
		Key:   []byte("Key-A"),
		Value: []byte("Hello World!"),
	},
	kafka.Message{
        Topic: "topic-B",
		Key:   []byte("Key-B"),
		Value: []byte("One!"),
	},
	kafka.Message{
        Topic: "topic-C",
		Key:   []byte("Key-C"),
		Value: []byte("Two!"),
	},
)
```

**Comment by petedannemann** [comment]
`Writer.WriteMessages` is not atomic. You can track support for exactly once semantics in this issue https://github.com/segmentio/kafka-go/issues/233

Another option is to [look at the errors returned](https://github.com/segmentio/kafka-go/blob/8492075557ac8bda295a24a64866ce82eb786629/writer.go#L598) and only retry messages that failed
