### ISSUE TITLE
Will AdminAPI be supported in the future？

### ISSUE THREAD

**Issue by zouyaowen** [segmentio/kafka-go#1161]
**Describe the solution you would like**
I want to use admin API to monitor message produce and consume
 
> A clear and concise description of what you want to happen.

**Supporting documentation**
https://kafka.apache.org/documentation/#api
> Please provides links to relevant Kafka protocol docs and/or KIPs.
<img width="1079" alt="image" src="https://github.com/segmentio/kafka-go/assets/20028367/64366589-2aeb-4493-97c7-5e83b34f107d">

**Comment by petedannemann** [comment]
> The Admin API supports managing and inspecting topics, brokers, acls, and other Kafka objects. 

kafka-go supports managing and inspecting topics, brokers, acls and more. kafka-go doesn't currently have 100% feature coverage for all Admin API endpoints, but the library has most of the common ones.

You can see many of these by [viewing the methods available to the Client type](https://pkg.go.dev/github.com/segmentio/kafka-go?utm_source=godoc#readme-connection). For example, here are two APIs for [creating topics](https://pkg.go.dev/github.com/segmentio/kafka-go?utm_source=godoc#Client.CreateTopics), and [fetching metadata about topics and partitions](https://pkg.go.dev/github.com/segmentio/kafka-go?utm_source=godoc#Client.Metadata), respectively.

**Comment by zouyaowen** [comment]
Your email is received and will be handled  as soon as possible,and this is an automatic reply,I will respond to your message  immediately when I see it.Thank you.

**Comment by zouyaowen** [comment]
I get what I want---------> OffsetFetch,thanks a lot
