### ISSUE TITLE
Kafka Lag and Offset with GroupID

### ISSUE THREAD

**Issue by gmikhaile** [segmentio/kafka-go#1163]
Hello! 

From the documentation it is clearly stated if `group id` is set for consumer `Lag` and `Offset` will allways be `-1`. [link](https://pkg.go.dev/github.com/segmentio/kafka-go#section-readme:~:text=(*Reader).Lag%20will%20always%20return%20%2D1%20when%20GroupID%20is%20set)

But if I call [Reader.Stats().Lag](https://pkg.go.dev/github.com/segmentio/kafka-go#Reader.Stats) on the same consumer with `group id` the lag will be retrieved.

Is there a reason for such behavior?

**Comment by hhahn-tw** [comment]
Hello - I believe the discrepancy is that `reader.Lag` and `reader.Stats().Lag` behave and are documented differently. 

You've linked the description for `reader.Lag` which does behave as described - it returns `-1` when GroupID is set

`reader.Stats()`, on the other hand, returns a ReaderStats struct with `Lag` not necessarily set to `-1` (though `Partition` is set to `-1`, as documented)
