### ISSUE TITLE
Connect Kafka failed when using Resolver

### ISSUE THREAD

**Issue by wilson-song** [segmentio/kafka-go#1175]
**Describe the bug**

I have set kafka.Dialer.Resolver to get the address of Kafka from Consul. For example, the Kafka address obtained from Consul is 127.0.0.1:31000, but the actual connected Kafka address after running is 127.0.0.1:9092, which causes the connection to fail.

Got the following error:
```
failed to open connection to 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused
```

**Kafka Version**

> * What version(s) of Kafka are you testing against?
> * What version of kafka-go are you using?
v0.4.42

**Expected Behavior**
Connect Kafka successfully.

**Comment by wilson-song** [comment]
Hi @petedannemann,  I got 3 addresses (including port) from resolver at line 471, but could not set the `resolvePort` to `port` as `port` had a value `9092` at line 487.

![image](https://github.com/segmentio/kafka-go/assets/6452040/e4f4dcc8-f4e0-4161-b15d-94dbceba4c98)

**Comment by petedannemann** [comment]
Hi @wilson-song, please provide a code snippet for how you are setting up your Dialer and Resolver.

**Comment by wilson-song** [comment]
Hi @petedannemann , this is how I set up Dialer and Resolver.

```go
var (
	cacheResolved = cache.New(time.Second*30, time.Second*10)
	lock          sync.Mutex
)

type consulKafkaResolver struct {
	serviceName string
}

func (r *consulKafkaResolver) LookupHost(ctx context.Context, addr string) (addrs []string, err error) {
	lock.Lock()
	defer lock.Unlock()

	if ret, exists := cacheResolved.Get(addr); exists {
		return ret.([]string), nil
	}
	defer func() {
		if err == nil {
			cacheResolved.SetDefault(addr, addrs)
		}
	}()
	if addr == r.serviceName {
		// Initial lookup. Directly return broker addresses.
		addrs := consul.GetConsulClient().GetAllAddress(r.serviceName, "")
		if len(addrs) == 0 {
			return nil, errors.New("Failed to lookup address")
		}
		sort.Strings(addrs)
		return addrs, nil
	}

	_, _, err = net.SplitHostPort(addr)
	if err != nil {
		addr = addr + ":9092"
	}

	mapAddr, err := consul.GetConsulClient().GetMappedAddress(addr)
	if err != nil {
		return []string{addr}, nil
	}
	return []string{mapAddr}, nil
}

func newKafkaDialer(serviceName string) *kafka.Dialer {
	return &kafka.Dialer{
		Resolver:  &consulKafkaResolver{serviceName},
		Timeout:   10 * time.Second,
		DualStack: true,
	}
}

newKafkaDialer("kafka").DialContext(ctx, "tcp", "kafka")
```

**Comment by petedannemann** [comment]
I think the issue is that `splitHostPort` is providing a default port of 9092 since you are not specifying a port to DialContext. Can you try this? I think that will make the port null instead of 9092

```go
newKafkaDialer("kafka").DialContext(ctx, "tcp", "kafka:")
```

**Comment by wilson-song** [comment]
It works. Thank you. @petedannemann
