### ISSUE TITLE
Write kafka message to Server,  and got   kafka.(*Client).Produce: write tcp xxx:xxx->xxx:xxx i/o timeout"  error

### ISSUE THREAD

**Issue by Metatronxl** [segmentio/kafka-go#1176]
**Describe the bug**

> A clear and concise description of what the bug is.

"I am using kafka-go to send data to a Kafka server. I have 2 client servers, each with 20 workers to concurrently send data to the server. The Kafka server has one topic and 60 partitions. I am experiencing the 'kafka.(*Client).Produce: write tcp xxx ->xxx: i/o timeout' issue, which I suspect is due to too many connections. Is there a way to manage the number of connections on each client, similar to the kafka.NewConnPool() method?"

**Kafka Version**

> * What version(s) of Kafka are you testing against?
> * What version of kafka-go are you using?
v0.4.12

**Comment by hhahn-tw** [comment]
Hello - do you have visibility into the `kafka.network:type=RequestChannel,name=RequestQueueSize` metric? This might confirm that kafka is unable to keep up with the incoming requests. When the queue is at max size (`queued.max.requests=500` by default), this can result in client timeouts.

**Comment by Metatronxl** [comment]
> Hello - do you have visibility into the `kafka.network:type=RequestChannel,name=RequestQueueSize` metric? This might confirm that kafka is unable to keep up with the incoming requests. When the queue is at max size (`queued.max.requests=500` by default), this can result in client timeouts.

Thank you for your advice~ i have resolved  my problem. In my project, i create 20 clients to  send messages to server which leading to the quota of the server's connection pool.  After reading the source code detaily, i found that client is thread-safe which means i just need to create one client and reues it to send multi-messages.

**Comment by hhahn-tw** [comment]
Great - glad you find a correction for your issue. I'll go ahead and close this out.
