### ISSUE TITLE
Data loss when using consumer groups + commit offsets sync

### ISSUE THREAD

**Issue by richardartoul** [segmentio/kafka-go#1179]
**Describe the bug**
The following method in the library has a bug:

```golang
// ReadMessage reads and return the next message from the r. The method call
// blocks until a message becomes available, or an error occurs. The program
// may also specify a context to asynchronously cancel the blocking operation.
//
// The method returns io.EOF to indicate that the reader has been closed.
//
// If consumer groups are used, ReadMessage will automatically commit the
// offset when called. Note that this could result in an offset being committed
// before the message is fully processed.
//
// If more fine-grained control of when offsets are committed is required, it
// is recommended to use FetchMessage with CommitMessages instead.
func (r *Reader) ReadMessage(ctx context.Context) (Message, error) {
	m, err := r.FetchMessage(ctx)
	if err != nil {
		return Message{}, err
	}

	if r.useConsumerGroup() {
		if err := r.CommitMessages(ctx, m); err != nil {
			return Message{}, err
		}
	}

	return m, nil
}
```

Specifically, when using consumer groups and commit offsets sync is enabled (which I believe is the default if `commitInterval` is left at the default value of 0). Here's how the bug / data loss happens:

`r.FetchMessage(ctx)` returns a valid message. `r.useConsumerGroup()` returns true since consumer groups are enabled. `r.CommitMessages` returns an error because sync commits are enabled. `r.commitMessages` can return an error for many different reasons (connection closed, network problem, broker failures, etc). 

If `r.CommitMessages` returns an error, we're in bad shape. The valid message that was returned previously is lost and the caller just sees the commit error. The next call to `ReadMessage()` will return the *next* message in the in the partition, not the one that was dropped on the floor.

From a consumers perspective, this bug manifests as complete loss of some messages.

I'm not sure what the correct solution here is considering how this interface mixes reading and commiting synchronously.

Also the method description *hints* at this problem: 

```
// If consumer groups are used, ReadMessage will automatically commit the
// offset when called. Note that this could result in an offset being committed
// before the message is fully processed.
//
// If more fine-grained control of when offsets are committed is required, it
// is recommended to use FetchMessage with CommitMessages instead.
```

However the description implies that the caller will at least receive every message even if messages may be committed before the caller is done processing them. However, I don't think callers/users would expect to miss message entirely even though their application never crashed (in which case they would expect to maybe lose some messages since this method commits offsets without waiting for the caller to ack them).

The issue can be worked around by configuring `commitInterval` to be > 0.

**Kafka Version**
Kafka version doesn't matter for this bug, its a bug in the client implementation. I have no way to "force" this bug to trigger in any deterministic way, we only caught it because we're running chaos + property testing.

> * What version of kafka-go are you using?
github.com/segmentio/kafka-go v0.4.42

**To Reproduce**
I don't have an easy way to reproduce the behavior. We have a custom chaos + property testing setup that can reproduce the issue after a period of time, but it's not something I can provide in this issue description. That said, I think its "obvious" reading the code that its buggy, and I've added additional assert on my end that prove that repeated calls to `ReadMessage` under chaos injection will return messages with gaps in offsets (messages are missing)

**Expected Behavior**

I'm not sure. This interface is kind of weird. I guess the most reasonable thing would be that if committing offsets is going to return an error due to failure to commit offsets, subsequent calls to ReadMessage should return the message that was "dropped" to the previous commit error. That would still cause callers to experience data loss if their application crashes after receiving a commit error (if the commit secretly succeeded), but that feels like it would at least be much closer to honoring the describe method description,

**Observed Behavior**
Commit failures cause messages to be silently dropped without the caller being aware unless they're manually comparing the offset of every message against the last one they received.

**Additional Context**
Sorry I wish I could provide a better reproducer, but our fault injection and property testing setup is not open source so there is no reasonable way for me to do that.

**Comment by petedannemann** [comment]
I don't think this is a bug, this is just the design of `ReadMessage`. It sounds like the behavior you want is `FetchMessage` with manual commits via `CommitMessages`.

**Comment by petedannemann** [comment]
Furthermore, changing the behavior of `ReadMessage` would be a very disruptive change so I don't think that is an option.

**Comment by richardartoul** [comment]
@petedannemann I do think its a bit weird that it skips a message entirely even though the client application never crashed, but I'm inclined to agree this method gives so few guarantees I'm not sure there is much to fix.

**Comment by petedannemann** [comment]
I agree the behavior can be a gotcha, but I think any implementation of automatic offset commits will have the potential for data loss. If you can't tolerate data loss, commits need to be managed manually. If the verbiage around this method isn't clear enough, feel free to submit a PR helping clear that up!

**Comment by richardartoul** [comment]
Cool I'll close it then. Thanks for replying.
