### ISSUE TITLE
Support for max.request.size producer config

### ISSUE THREAD

**Issue by mts57017** [segmentio/kafka-go#1186]
### Discussed in https://github.com/segmentio/kafka-go/discussions/1160

<div type='discussions-op-text'>

<sup>Originally posted by **gagangoku** July  8, 2023</sup>
I want to send large messages through Kafka (>10 MB). 

[tutorial 1](https://www.baeldung.com/java-kafka-send-large-message) and [tutorial 2](https://www.conduktor.io/kafka/how-to-send-large-messages-in-apache-kafka/) suggest that the 1st step is to set the `max.request.size` property in producer config. But i'm not finding the option in the Writer config.

Is this supported ?
</div>

**Comment by petedannemann** [comment]
You can use [Writer's BatchBytes](https://github.com/segmentio/kafka-go/blob/f4ca0b48296538eb5639027cd83f40a3828caf7d/writer.go#L121)
