### ISSUE TITLE
Reader spams error logs because of timeout. Move logging to trace

### ISSUE THREAD

**Issue by gavinmcnair** [segmentio/kafka-go#1191]
**Describe the solution you would like**
In this issue its highlighted that excessive log output can be annoying (https://github.com/segmentio/kafka-go/issues/170)

I would like it to be less noisy.

> A clear and concise description of what you want to happen.

If my application utilising the library has its own DEBUG log output it get swamped in noise. Can we move this specific output to the TRACE log level so that its still available but doesn't obstruct app logging.

**Supporting documentation**

```
time="2019-01-03T21:32:05Z" level=info msg="no messages received from kafka within the allocated time for partition 12 of apps-logging-logfmt at offset 826264824" package=kafka
time="2019-01-03T21:32:05Z" level=info msg="no messages received from kafka within the allocated time for partition 4 of apps-logging-logfmt at offset 826259286" package=kafka
time="2019-01-03T21:32:05Z" level=info msg="no messages received from kafka within the allocated time for partition 8 of apps-logging-logfmt at offset 826274463" package=kafka
time="2019-01-03T21:32:05Z" level=info msg="no messages received from kafka within the allocated time for partition 7 of apps-logging-logfmt at offset 826252985" package=kafka
time="2019-01-03T21:32:05Z" level=info msg="no messages received from kafka within the allocated time for partition 6 of apps-logging-logfmt at offset 826265614" package=kafka
time="2019-01-03T21:32:05Z" level=info msg="no messages received from kafka within the allocated time for partition 13 of apps-logging-logfmt at offset 826307337" package=kafka
time="2019-01-03T21:32:05Z" level=info msg="no messages received from kafka within the allocated time for partition 0 of apps-logging-logfmt at offset 826260565" package=kafka
time="2019-01-03T21:32:05Z" level=info msg="no messages received from kafka within the allocated time for partition 1 of apps-logging-logfmt at offset 826288380" package=kafka
time="2019-01-03T21:32:05Z" level=info msg="no messages received from kafka within the allocated time for partition 10 of apps-logging-logfmt at offset 826294189" package=kafka
time="2019-01-03T21:32:05Z" level=info msg="no messages received from kafka within the allocated time for partition 5 of apps-logging-logfmt at offset 826271150" package=kafka
time="2019-01-03T21:32:05Z" level=info msg="no messages received from kafka within the allocated time for partition 2 of apps-logging-logfmt at offset 826296142" package=kafka
```

This is particularly serious in GO since most loggers only have global log levels and wont allow log level per library.

**Comment by hhahn-tw** [comment]
Hello - the volume of these messages under certain circumstances is certainly less than ideal but INFO does seem like the correct level for this type of error. Dropping it to TRACE or even DEBUG risks losing visibility where this error could be significant and expected to be INFO (or higher).

Have a richer set of configuration for Go logging would be ideal but lacking that, I think you're left with filtering via external tool, whether it's `grep -v` at the terminal or excluding it in logging platform queries, as options.
