### ISSUE TITLE
Cannot create acl

### ISSUE THREAD

**Issue by LiDaiyan** [segmentio/kafka-go#1198]
Kafka version: 3.5.1

Can not create acl and there is no useful error info.

`
	var prefix = "proj1"

	res, err := client.CreateACLs(context.Background(), &kafka.CreateACLsRequest{

		ACLs: []kafka.ACLEntry{
			{
				ResourceType:        2,
				ResourceName:        prefix,
				ResourcePatternType: 1,
				Principal:           "u1",
				Host:                "*",
				Operation:           5,
				PermissionType:      2,
			},
		},
	})

	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(res.Errors)`

and i get the info below

`&{0s [{u1 <nil>}]}
[[-1] Unknown: an unexpected server error occurred]`

i have checked the client is the superuser having enough right to create the acl using kafka command.

I guess maybe this is caused by kafka version?

**Comment by LiDaiyan** [comment]
I have solved the problem, the Principal should be "User:u1"

**Comment by petedannemann** [comment]
I think in this scenario the easiest way to debug things would be to look at the Kafka broker's logs. I don't think we'll realistically be able to capture every single thing that could go wrong here in terms of validating the data

**Comment by LiDaiyan** [comment]
yeah, thanks for your teaching, i get it!
