### ISSUE TITLE
Round Robin Balancer not working as expected, always send message to the partition 0

### ISSUE THREAD

**Issue by slouma2000** [segmentio/kafka-go#1207]
Round Robin Balancer not working, always send message to partition 0, there is 8 partitions in the topic

kafkaWriter := &kafka.Writer{
		Addr:     kafka.TCP(config.BootstrapServers),
		Topic:    topic,
		// Balancer: &kafka.RoundRobin{},
}
defer kafkaWriter.Close()
var messages []kafka.Message
for _, x := range annonces {
    payload, _ := json.Marshal(x)
    msg := kafka.Message{
        Value: payload,
    }
    messages = append(messages, msg)
}

err = kafkaWriter.WriteMessages(context.Background(), messages...)

**Comment by sizovilya** [comment]
@slouma2000 
In my case code was creating a new `kafka.Writer` each time it had to send a new message to Kafka. As a result each message was threat as first message, and of course, each message was sent to partition 0. 
So, my suggestion is - check whether you are creating **new** `kafka.Writer` connection each time you want to sent a message to Kafka. If so, change your code, you need to create the connection once and then reuse it.

**Comment by petedannemann** [comment]
Thanks for the help @sizovilya !
