### ISSUE TITLE
WriteMessages return Leader Not Available ErrorCode

### ISSUE THREAD

**Issue by zydovech** [segmentio/kafka-go#1208]
**Describe the bug**

>  
1.  kafka server enable auto create topic when topic not exist. 
2. WriteMessages return Leader Not Available error.
3. this Leader Not Available error code retern by partitions. because when topic not exist , fetch metadata will trigger create topic ,but medata response with  Leader Not Available error code.
https://github.com/segmentio/kafka-go/blob/9ecb9d2f7da50f4e23e4ef40270751820e154c81/writer.go#L744
**Kafka Version**

> * What version(s) of Kafka are you testing against?
   * 2.6
> * What version of kafka-go are you using?
   * v0.4.43

**To Reproduce**

> Resources to reproduce the behavior:

```go
package main

import (
    "github.com/segmentio/kafka-go"
)

func main() {
   w := &kafka.Writer{
		Async:                  true,
		AllowAutoTopicCreation: true,
		Addr:                   kafka.TCP("localhost:9092", "localhost:9093", "localhost:9094"),
		Balancer:               &kafka.LeastBytes{},
	}

	err := w.WriteMessages(context.Background(),
		kafka.Message{
			Topic: "TESTTTT-123_123",
			Key:   []byte("Key-A"),
			Value: []byte("Hello World!"),
		},
	)
}
```

**Expected Behavior**

>  can retry max attempt times ,not directy return error without retry.

**Observed Behavior**

> when https://github.com/segmentio/kafka-go/blob/9ecb9d2f7da50f4e23e4ef40270751820e154c81/writer.go#L744 fail , directy return error code

**Additional Context**

> As can be seen from the packet capture file below, it is the metadata request that returned the error.

![image](https://github.com/segmentio/kafka-go/assets/8581262/e1cd1484-b03c-4e75-a61b-697b9da584f3)

**Comment by petedannemann** [comment]
Did you try the steps noted in our [README here](https://github.com/segmentio/kafka-go#missing-topic-creation-before-publication)? It will be up to the caller to handle the LeaderNotAvailable error
