### ISSUE TITLE
Need to upgrade to Kafka Client version 3.6.0

### ISSUE THREAD

**Issue by devd120698** [segmentio/kafka-go#1223]
We are using kafka-go v0.4.42

As per the Readme file for this repository, this has been tested till Kafka versions 0.10.1.0 to 2.7.1 . Although, we want to upgrade the Kafka version to 3.6.0

Are there any issues identified in using this library post Kafka versions 2.7 or is it compatible with the later ones as well?

**Comment by hhahn-tw** [comment]
We are not aware of any specific issues, however as you've noted our current testing does not apply to versions higher than 2.7 so it is unknown.

We are looking to expand that testing to 2.8 and 3.6 soon and will have a clearer picture of issues then.
