### ISSUE TITLE
Kafka Compatibility for the Client versions

### ISSUE THREAD

**Issue by hariever** [segmentio/kafka-go#1229]
Hi, 
We have various micro services and we are using below kafka client versions in production. We are planning to upgrade our **Kafka versions to 3.3.x**. As per the current readme page it says, only tested for versions 0.10.1.0 to 2.7.1. It would be great if someone can let us know the compatibility matrix for client versions and Kafka versions.

Our current client versions in production are 
v0.4.30
v0.4.31
v0.4.38
v0.4.39
v0.4.42

**Comment by hariever** [comment]
Can someone please shed some light here

**Comment by hhahn-tw** [comment]
We're looking to expand our test matrix to newer versions (2.8.x and 3.6.x) soon. We'll discuss including 3.3 as well.
