### ISSUE TITLE
The default value of fetch.max.wait.ms

### ISSUE THREAD

**Issue by qinjin** [segmentio/kafka-go#1246]
**Describe the solution you would like**

The default value of `fetch.max.wait.ms` is set to [10 seconds](https://github.com/segmentio/kafka-go/blob/v0.4.46/reader.go#L654), which is quite large compare to Kafka default and other Golang Kafka libraries. 

All of the followings have `500ms` as the default.
- Kafka [default](https://kafka.apache.org/documentation.html#consumerconfigs_fetch.max.wait.ms)
- [confluent-kafka-go/librdkafka](https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md)
- [sarama](https://github.com/IBM/sarama/blob/main/config.go#L391)

I can understand that having a larger value of `fetch.max.wait.ms` could increase the throughput, but it could also lead to higher latency, which might not be idea for applications demand low latency.

If `kakfa-go` lib's choice is on throughput, I think a minor increase on the default value (e.g 1s) sounds reasonable. 10s is 20 times compare to Kafka default and other libs.

That being said, how does it sound to change the default of `fetch.max.wait.ms` to 1s?

**Comment by petedannemann** [comment]
Changing the default value will be a breaking change that we don't believe will be well received. I agree the default is less than ideal but I think we need to stick with it for now
