### ISSUE TITLE
Go1.16 cannot run tests

### ISSUE THREAD

**Issue by loktarjugg** [segmentio/kafka-go#1280]
I am using go1.16. When running tests, I encountered an error "unix/syscall.go:83:16: undefined: unsafe.Slice". 
Upon further investigation, I found that the kafka-go package references testify v1.8.0, which requires at least go1.17. 
This prevents me from executing the tests.

Is it possible to downgrade testify to v1.7.0?

![image](https://github.com/segmentio/kafka-go/assets/3970144/af82c697-0184-4420-aa6d-63a43e94e283)

**Comment by erikdw** [comment]
I don't work much in this project, but it seems really unlikely this would be a good idea.

**Comment by isaacd9** [comment]
Go 1.16 was released in February of 2021 and is 3 years out of date. I think probably the right solution here is to bump the required Go version to something more modern? https://github.com/segmentio/kafka-go/blob/main/go.mod#L3
