### ISSUE TITLE
Support for Streams and Connectors

### ISSUE THREAD

**Issue by palsivertsen** [segmentio/kafka-go#130]
Does this library support / plan to support Kafka Streams and Kafka Connectors?

I guess combining producers / consumers could achieve the same thing, but a utilizing the API sounds like the proper way to do it. I'm fairly new to Kafka and it's concepts, so sorry if I'm missing something.

**Comment by Pryz** [comment]
We haven't looked at those yet so no plan to support Streams or Connectors. If you feel strong about it you can still submit a PR or a proposal :)
