### ISSUE TITLE
Multiple topics and topic pattern

### ISSUE THREAD

**Issue by palsivertsen** [segmentio/kafka-go#131]
I've been trying to get `Reader` to work with topic regex's. Kafka documentation is very unclear on how to do this and most search results points to Java specific implementations.

# Case
I have three topics:
* `topic.a`
* `topic.b`
* `topic.c`

To subscribe to the first two topics (`topic.a` and `topic.b`) I've tried setting the `Topic` field in `ReaderConfig` to:
* `topic\.[ab]`
* `^topic\.[ab]`
* `topic.a|topic.b`
* `/^topic.*/`

Some cases does nothing (I'm assuming it's subscribed to a non existing topic) and others crashes other consumers in the same group (`unable to commit offsets for group, test: [25] Unknown Member ID: the member id is not in the current generation`).

**Comment by pawanrawal** [comment]
I am interested in helping with this feature. For starters, can we have a way by which to read from multiple topics @achille-roussel? Right now ReaderConfig only accepts one topic from what I understand.

**Comment by achille-roussel** [comment]
That’s true. 

The problem with adding support for multiple topics is it would likely be a breaking change this we would need to change the type of the Topic configuration option to be a slice of strings (or introduce some new configuration option which would make things confusing). If you have other ideas on how to add this feel free to share them :)

I think a very first step would be to add a method to list existing topics on the kafka.Conn type, this seems like the missing building block to get this working.

**Comment by pawanrawal** [comment]
This could be done in a backward compatible way by accepting a comma separated list of topics as part of the config. Does that sound OK? I can work on adding a method to list existing topics, should be an easy one I guess.

**Comment by achille-roussel** [comment]
I think if we support regexp it would still work, `topic-A|topic-B|topic-C` would work the same as a comma-separated list, wouldn't it?

**Comment by pawanrawal** [comment]
Any ideas about which API can I use to implement the ListTopics? I couldn't find an API while looking at http://kafka.apache.org/protocol.html.

**Comment by stevevls** [comment]
Hi @pawanrawal.  Have you looked at the [Metadata API](http://kafka.apache.org/protocol.html#The_Messages_Metadata)?  If you leave the topics empty, then you'll get back metadata for all known topics.

**Comment by achille-roussel** [comment]
Yep I was just looking into that https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-TopicMetadataRequest

Seems like calling `conn.ReadPartitions()`on a connection that has no topic configured would return all partitions for all topics... seems like it could be a lot of data but I don't know if kafka has a better way of doing this.

**Comment by magicdvd** [comment]
@pawanrawal how about the PR of support mulit topics? regexp is not a good way for topics with different name. I think extend the config option "Topics" string slice or a comma separated list is better.

**Comment by achille-roussel** [comment]
@magicdvd a configuration option to list topics that the reader should consume from sounds like a good plan 👍 

Would you be able to contribute a patch for this?

**Comment by elfar** [comment]
As a workaround for this, would there happen to be any way to consume from multiple topics without needing multiple readers? Or is the overhead per reader not that great or what would be the recommended solution? Thanks for making this great code public btw! :)

**Comment by xmaster484** [comment]
> Yep I was just looking into that https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-TopicMetadataRequest
> 
> Seems like calling `conn.ReadPartitions()`on a connection that has no topic configured would return all partitions for all topics... seems like it could be a lot of data but I don't know if kafka has a better way of doing this.

Have you tried this? I keep receiving empty responses for the topic info, unsure if its a setup or library issue.

**Comment by achille-roussel** [comment]
https://github.com/segmentio/kafka-go/pull/388

**Comment by oarriet** [comment]
@achille-roussel Looking forward to this improvement.

**Comment by alok87** [comment]
Thanks for making the wonderful code public. 

This is a blocker for us. Please release this ❤️

**Comment by hsawhney09** [comment]
Blocking us as well. Can this be released please

**Comment by gonejack** [comment]
Any update about multiple topic support?

**Comment by achille-roussel** [comment]
We missed the opportunity to follow up on this discussion earlier on. A couple months back we added new APIs to facilitate topic discovery, which can then be used to configure the list of topics that `kafka.Reader` consumes from https://github.com/segmentio/kafka-go/pull/663

Let us know if this is useful, or if you would prefer to see other improvements be added to kafka-go!

**Comment by achille-roussel** [comment]
I'm going to close this assuming the last response addressed the original issue. Feel free to reopen if it needs further discussion!
