### ISSUE TITLE
If we cant delete message or update message how can we know that this message has been consumed and we wont need to consume it again

### ISSUE THREAD

**Issue by Megatenogoukui** [segmentio/kafka-go#1357]
If we cant delete message or update message how can we know that this message has been consumed and we wont need to consume it again

_Originally posted by @Megatenogoukui in https://github.com/segmentio/kafka-go/issues/418#issuecomment-2550057658_

**Comment by erushing** [comment]
This is a Kafka fundamental question.  Kafka is not a message queue.  It is an append only log.
Once a consumer has read a message, it can automatically or manually commit that messages' offset.  Then it will not read this message again.

Here's an example blog.  Confluent or Redpanda or many other sources will explain this concept.
https://eryilmaz0.medium.com/designing-event-consumers-everything-about-commit-offsets-in-kafka-23d3f88472bd
