### ISSUE TITLE
Large reader lag (in consumer group)

### ISSUE THREAD

**Issue by grglcs** [segmentio/kafka-go#136]
Hello!

Thanks for a great library, it's a real pleasure to use it.

Unfortunately, I can't figure out how to tune the reader lag — for now it remains real big and it's hard to say that program reacts to events as fast as we expect.

I'm using high-level Reader like this (it's only one consumer in group):
```
	r := kafka.NewReader(kafka.ReaderConfig{
		Brokers:          c.getBrokers(),
		GroupID:          "group-1",
		Topic:            topic,
		QueueCapacity:    1024,
		SessionTimeout:   10 * time.Second,
		RebalanceTimeout: 5 * time.Second,
		MaxWait:          1 * time.Second,
		MinBytes: 1,    // 1B
		MaxBytes: 10e6, // 10MB
	})
```

This is the best config after a lot of experiments but it gives lag about 20-30 messages with producer frequency about 3-5 messages per second.

When program starts it waits for 5-10 seconds and then receives near all unread messages in group. Then it begins to receive messages as chunks accumulated for 10-second window (approx), sometimes it freezes for a longer time. Freeze happens on `r.ReadMessage(context.Background())`

Comparing to `kafkacat` tool it gives lag 0-1 messages rarely up to 10.

Is it something special about Kafka overall config, topic config, consumer group config, etc?
System: MacOS, Kafka & Zookeeper in Docker (confluentinc bundle), `go version go1.11.1 darwin/amd64 vgo:devel +b0a1c5df98`

Thanks for any updates!

**Comment by achille-roussel** [comment]
@grglcs I wonder if this is a manifestation of a bug we fixed in #143 

Can you try with a more recent version of the package and let us know if you still notice the issue?

**Comment by gimpf** [comment]
@achille-roussel We experience the same issue, and I just deployed our software with master of the library -- still experiencing the same thing. Well, it's better now, typical lag of (eyeballing) 5 instead of 10 to 15 we had earlier. Could it be that there are some related issues still open?

**Comment by gimpf** [comment]
@achille-roussel Please ignore the previous remark. There was one place where explicitly setting MaxWait was missing. Once reduced, the problem was gone.

**Comment by achille-roussel** [comment]
@grglcs any updates on this issue?

**Comment by bullsi** [comment]
I have a fresh version and I am facing the exact same issue. Most of the time, the consumer gets stuck at the beginning and then consumes a bunch at a time. Sometimes, it gets stuck only certain topics apparently waiting for a batch. And if I run the same consumer code (with different group Id), one system reads everything while the other one gets stuck consuming from the same Kafka server. The other moment, they both read everything.

**Comment by grglcs** [comment]
@achille-roussel sorry for the long response, yep, recent update fixed it, thanks!
