### ISSUE TITLE
Supply an rdkafka-compatible hash function too

### ISSUE THREAD

**Issue by samv** [segmentio/kafka-go#138]
This is relatively trivial, but for folk who are also using eg confluent_kafka or other librdkafka-based libraries in other places, they might appreciate a quick way to select this.

This code uses the test cases from `github.com/edenhill/librdkafka/tests/0048-partitioner.c` to confirm that this library/polynomial pair produces the same CRC32's.

The Java world uses a different partitioning function again, [murmur](https://en.wikipedia.org/wiki/MurmurHash).  Fun.  And none of are [consistent hashes](https://en.wikipedia.org/wiki/Consistent_hashing). 

```go
package main

import (
	"hash/crc32"
	"log"
)

var hashTable = crc32.MakeTable(0xEDB88320)

func main() {
	cases := []string{
		"this is another string with more length to it perhaps",
		"hejsan",
		"23456",
	}
	expected := []uint32{
		0xb0150df7,
		0xd077037e,
		0xb1b451d7,
	}

	for testCaseIdx := range cases {
		hasher := crc32.New(hashTable)
		hasher.Write([]byte(cases[testCaseIdx]))
		if hasher.Sum32() != expected[testCaseIdx] {
			log.Printf("mismatch on %s!  %x != %x", cases[testCaseIdx], hasher.Sum32(), expected[testCaseIdx])
		} else {
			
			log.Printf("%#v hashes to %x, good", cases[testCaseIdx], hasher.Sum32())
		}
	}
}
```

**Comment by stevevls** [comment]
Fixed by #334
