### ISSUE TITLE
Balancer API cannot be used to provide compatible balancers

### ISSUE THREAD

**Issue by samv** [segmentio/kafka-go#139]
Hi, I was just integrating some code I was writing against this, and I noticed that the API provided for writing balancers does not provide the number of partitions in the topic metadata, just the available partitions.  This means that if a partition goes offline, the Hash partitioner will use a different modulus, and messages will be sent in all directions.  Saramer's Partitioner API solves this by requiring a method, "RequiresConsistency", whereby partitioners can say whether they want to distribute over all or just available partitions.

**Comment by achille-roussel** [comment]
Good catch.

Would you be available to submit a pull request to address this issue?

**Comment by achille-roussel** [comment]
@stevevls @Pryz @rakeshnair @erikdw do you know if offline partitions are returned in the metadata responses?

**Comment by erikdw** [comment]
@achille-roussel & @samv : I just researched this a bit, and [according to Jun Rao, the metadata response includes "all" partitions whether the leaders are available or not](https://mail-archives.apache.org/mod_mbox/kafka-users/201503.mbox/%3CCAFc58G8+AtVMaJaRtdNTROjGdXhoo3bO8ywnsDg6kykKmeR3zg@mail.gmail.com%3E).

An earlier (apparently erroneous) conclusion on that email thread was that the metadata did *not* include the offline partitions.  That led to the filing of [KAFKA-1998](https://issues.apache.org/jira/browse/KAFKA-1998), but then the ticket was closed, citing Jun's response that I linked above.

**Comment by achille-roussel** [comment]
Nice :) thanks for the thorough research Erik!

**Comment by achille-roussel** [comment]
It seems like the original concern has been addressed, I'll close but feel free to re-open if this needs further discussion!
