### ISSUE TITLE
Optimising the reader

### ISSUE THREAD

**Issue by palsivertsen** [segmentio/kafka-go#144]
Are there recommendations on how to optimize the Reader? When I'm comparing the example in readme to the test script that comes with Kafka, the Reader is extremely slow (up to 1 minute vs Kafka test < 1 second for processing 10 000 messages).
I've played around with the ReaderConfig without any luck.

**Comment by achille-roussel** [comment]
Usually MinBytes/MaxBytes/MaxWait are the main parameters to tune to optimize throughput, the larger the batches that the reader can fetch the higher the throughput.

Do you have more details to provide on the test setup that you use (hardware, kafka configuration, reader configuration, etc...)?

If you also have CPU profiles of the reader consuming from Kafka, those could help identify any bottleneck in the implementation.

**Comment by palsivertsen** [comment]
I'm running everything locally on the same machine. Kafka is set up with default settings and I've put in 10 000 messages for testing.

First I measure the test script Kafka provides:
```
$ time bin/kafka-console-consumer.sh --bootstrap-server 192.168.10.231:9092 --topic events --from-beginning --max-messages 10000
...
<messages are printed here>
...
Processed a total of 10000 messages

real	0m1.859s
user	0m2.962s
sys	0m0.274s
```
As you can see the execution time is in the seconds range.

Kafka-go code:
```
package main

import (
  "context"
  "flag"
  "fmt"
  "log"
  "time"
  
  "github.com/pkg/profile"
  "github.com/segmentio/kafka-go"
)

func main() {
  defer profile.Start().Stop()
  
  var num = flag.Int("num", 10000, "Messages to read")
  flag.Parse()
  
  r := kafka.NewReader(kafka.ReaderConfig{
    Brokers: []string{
      "localhost:9090",
      "localhost:9091",
      "localhost:9092",
      "localhost:9093",
    },
    Topic:    "events",
  })    
  
  ctx := context.Background()
  
  for i := 0; i < *num; i++ {
    _, err := r.ReadMessage(ctx)
    if err != nil {
      log.Fatal(err)
    }
    fmt.Println(i)
  } 
}
```

And run it:
```
$ time go run main.go
...
<messages are printed here>
...
real	1m4.609s
user	0m0.598s
sys	0m0.124s
```
Over one minute.

Execution pauses at the following message counts:
* 5601
* 8066
* 9186
* 9690
* 9914

When tweaking MinBytes/MaxBytes/MaxWait like so I get better results:
```
     MaxWait:  time.Second,
     MinBytes: 10e3, // 10KB
     MaxBytes: 10e6, // 10MB
```
And run:
```
$ time go run main.go
...
real	0m12.397s
user	0m0.566s
sys	0m0.145s
```
Much better, but still not good.

Execution pauses at the following message counts:
* 9690
* 9914

Tweaking helps, but still not comparable to Kafka test script. Pauses are longer than `MaxWait`.

In both my test cases execution pauses at the exact same messages over different runs. I'm guessing this is a buffer filling up somewhere.

I'm also including CPU profile for the run with default settings:
![profile001](https://user-images.githubusercontent.com/11890143/48613352-c46cf100-e98b-11e8-8e55-4285f4d77ee7.png)

**Comment by palsivertsen** [comment]
```
$ go version
go version go1.10.2 linux/amd64
```

**Comment by palsivertsen** [comment]
Upgrading form `v0.2.0` to `master` (185fcae6c0959e2368bd0f9fc8b86f0746d8c826) gives MUCH better results!

Any chance on a new release?

**Comment by achille-roussel** [comment]
I just tagged v0.2.1 👍 

We did release a fix for a bug where sometimes the reader would hang because it was waiting for more data than the server would send, which could have looked like poor performance because it would just hang.

Let us know if you still have trouble with the latest release.

**Comment by palsivertsen** [comment]
> sometimes the reader would hang because it was waiting for more data than the server would send

Sounds like what I was seeing. v0.2.1 does not have these issues.
