### ISSUE TITLE
Support for Zstd compression.

### ISSUE THREAD

**Issue by yctn** [segmentio/kafka-go#154]
Kafka already support zstd compression. please consider to add it.

https://cwiki.apache.org/confluence/display/KAFKA/KIP-110%3A+Add+Codec+for+ZStandard+Compression

**Comment by achille-roussel** [comment]
This would be a great addition to the project. We already support a couple of formats so there should be enough code examples to get started, would you be able to contribute a patch for this?

**Comment by vrischmann** [comment]
As far as I can tell zstd is only available via wrappers to the C library (for example https://github.com/datadog/zstd).

This means it would require cgo, I don't know how much of a problem that is for the maintainers.

**Comment by achille-roussel** [comment]
As long as it's optional (like being in a sub-package) this is totally acceptable. We don't want to enforce CGO dependency on a program that doesn't need zstd compression tho.

**Comment by Pryz** [comment]
Implemented in https://github.com/segmentio/kafka-go/pull/253.
