### ISSUE TITLE
The example consumer code is not working with the error "unexpected EOF"

### ISSUE THREAD

**Issue by uynap** [segmentio/kafka-go#155]
The producer code on the front page of https://github.com/segmentio/kafka-go works. But the kafka-go's consumer code throw out "unexpected EOF" at `_, err := batch.Read(b)`.

I'm pretty sure the messages have been in Kafka. I use the Kafka command to check it. I can also use `github.com/bsm/sarama-cluster` to read the message without issues. 

Our Kafka version is 0.9.0.1. Any advice on what the issue might be ?

**Comment by achille-roussel** [comment]
Hello, thanks for reporting the issue. 

This library doesn’t support Kafka 0.9, we offer compatibility with Kafka 0.10 and upward, I would assume this is the reason why you’re getting this error.
