### ISSUE TITLE
error write msg to kafka

### ISSUE THREAD

**Issue by chainarong-Trainapakul** [segmentio/kafka-go#167]
conn, err := kafka.DialLeader(context.Background(), "tcp", "x.x.x.x:9092", "myTopic", 0)
if err != nil {
   fmt.Println(err)
}

that got error = "not enough bytes available to load the response"
how to fix it ?

**Comment by chainarong-Trainapakul** [comment]
version : kafka_2.10-0.9.0.1 
I'm try on kafka_2.10-0.10.2.2 and i got same error

**Comment by achille-roussel** [comment]
This project has only been tested against Kafka 0.10+ and Kafka 1. Confluent introduced breaking changes in Kafka 2 so I would expect things not to work.

We'd welcome fixes tho if you're available to look into the issue.

**Comment by achille-roussel** [comment]
We're adding tests to validate that kafka-go works against Kafka 2.x and haven't been able to reproduce the issue.

Do you mind sharing a little more about your setup? Maybe a docker-compose file that we can use to reproduce the issue?

**Comment by chainarong-Trainapakul** [comment]
when i'm try on kafka 2.11-2.1.0 . I have no issue. 
thank you
