### ISSUE TITLE
Using `0` as required acks returns an `InvalidRequiredAcks`

### ISSUE THREAD

**Issue by ppatierno** [segmentio/kafka-go#174]
The current `conn.SetRequiredAcks()` method doesn't take into account the `0` value (which means no ack from the broker) as a valid one.
If `0` is used, the above method returns an `InvalidRequiredAcks` which is not right.

**Comment by dominicbarnes** [comment]
The documentation has been updated to indicate that v0.3 will not support this particular feature, but if you need this you can upgrade to v0.4.
