### ISSUE TITLE
An `InvalidRequiredAcks` error is just ignored

### ISSUE THREAD

**Issue by ppatierno** [segmentio/kafka-go#175]
The `writer.dial()` method just ignores a possible error due to an invalid required acks.
As reported in #174, even using `0` returns an `InvalidRequiredAcks` but it's ignored here so all it's working fine (but it should not). 
This is also the reason why using a `RequiredAcks` different from -1, 0 and 1 in the `WriterConfig` doesn't raise any error.

**Comment by achille-roussel** [comment]
Thanks for reporting, it seems like the best thing to do would be to validate the RequiredAcks value in WriterConfig when creating a Writer, what do you think?

Would you be able to submit a patch for this?

**Comment by dominicbarnes** [comment]
The documentation has been updated to indicate that v0.3 will not support this particular feature, but if you need this you can upgrade to v0.4.
