### ISSUE TITLE
Fast reading for testing without log spam

### ISSUE THREAD

**Issue by abuchanan-nr** [segmentio/kafka-go#178]
I'm writing some simple tests and I want to configure the reader to read messages immediately. These are low traffic, only a few messages.

I used `ReaderConfig.MaxTime` to achieve this. Unfortunately, this makes both the Logger and ErrorLogger extremely spammy. I'd prefer to have logging always on, so that logs are useful for testing/debugging without going in to modify the test code.

Do you have any recommendations to achieve this?

This might be related to #162. I can't tell exactly.

**Comment by achille-roussel** [comment]
We merged https://github.com/segmentio/kafka-go/pull/172 recently, which may be related to the problem you describe.

Do you mind sharing which version of the package you're working with?

**Comment by abuchanan-nr** [comment]
We're on a28af3c7f143 which is just a couple days older than #172, which I think will fix the problem. Thanks!
