### ISSUE TITLE
[Help want]example about  multiple  process/concurrency in same consumer group?

### ISSUE THREAD

**Issue by likun123687** [segmentio/kafka-go#180]
There is already a consumer groups example:
r := kafka.NewReader(kafka.ReaderConfig{
    Brokers:   []string{"localhost:9092"},
    GroupID:   "consumer-group-id",
    Topic:     "topic-A",
    MinBytes:  10e3, // 10KB
    MaxBytes:  10e6, // 10MB
})

for {
    m, err := r.ReadMessage(context.Background())
    if err != nil {
        break
    }
    fmt.Printf("message at topic/partition/offset %v/%v/%v: %s = %s\n", m.Topic, m.Partition, m.Offset, string(m.Key), string(m.Value))
}

r.Close()
That seems too basic. Now i want to make multiple consumer using multiple  process/concurrency , is there any example? Or do i miss any other document.
Thanks.

**Comment by achille-roussel** [comment]
Hello @likun123687 

You could call `ReadMessage` concurrently from multiple goroutines, or each goroutine could have its own reader.

When he reader is part of a consumer group it may already fetch messages from multiple partitions, depending on the rebalance logic.

Let me know if that helps, or maybe tell us a little more about your use-case!

**Comment by achille-roussel** [comment]
Closing in favor of #201
