### ISSUE TITLE
MaxMessageBytes for Producer

### ISSUE THREAD

**Issue by ShaneSaww** [segmentio/kafka-go#188]
It looks like it's not possible to set MaxMessageBytes for a Producer.
This is quite important as you can get errors trying to send to kafka if the producer batch size is too large, as you can't produce a  message you send  larger then the broker configured MaxMessageBytes.

**Comment by abuchanan-nr** [comment]
This was closed by https://github.com/segmentio/kafka-go/pull/208 right?

**Comment by stevevls** [comment]
Yup.  Thanks for pointing it out. 😄
