### ISSUE TITLE
How to investigate write failures?

### ISSUE THREAD

**Issue by grglcs** [segmentio/kafka-go#192]
As far as I'm using such cool library as kafka-go I faced sometimes unpredictable write failures.
I'm using high-level Writer and write messages asynchronously.
Currently it's about 8 concurrent writers to different topics. And write to some of topics that used rarely than others fails as I can see by reading from topic.

How I can investigate the reason of such behaviour?

Also, high-level Reader, what should automatically reconnect, doesn't do it — tested by restarting kafka.

kafka:
kafka_2.12-2.1.0
java.version=1.8.0_191
zookeeper.version=3.4.13

**Comment by grglcs** [comment]
Let me explain in other words.

As I noticed, disabling "async" on writer makes things better as there are several re-tries to send message — never failed to send messages to kafka.
But it causes freeze on caller to amount at least of `writer.BatchTimeout` what looks like big lag on sending like 100 messages one-by-one even if `BatchTimeout` set to `200ms`

So what to do? Decrease `BatchTimeout` to compromisable `10-20ms` in words of caller's freeze (maybe it will increase consuming CPU) or I just don't know the obvious solution?

Thanks!

**Comment by grglcs** [comment]
One more update: the error while writing is `error writing messages to <topic> (partition 0): EOF`

**Comment by ShaneSaww** [comment]
Working with Kafka-go I've seen the same problem. 
I'm wondering if adding retries into the async producer makes sense. From my understanding that would match the java and librd kafka clients.

for example: https://github.com/edenhill/librdkafka/wiki/Producer-message-reliability#temporary-server-side-errors

**Comment by achille-roussel** [comment]
@grglcs do you have a way to reproduce this in an isolated environment?

EOF seems like the connection got closed by the server and because you're using the async writer the messages are not guaranteed to be delivered if the brokers suffer unavailability.

**Comment by grglcs** [comment]
@achille-roussel yep, you're right — it's the problem with closed idle connection from server side. So I had to build a custom bicycle to allow async write with rewrite-on-failure.

**Comment by loveczp** [comment]
@grglcs I think maybe you could define your own Dialer and set a very long keepalive time. Maybe this could prevent the server close the idle connection. This is my guess.

**Comment by sansna** [comment]
I'm suffering from write failure at tag v0.2.5
Is this problem fixed?
