### ISSUE TITLE
consumer-group going into rebalancing state whenever services are scaled up and they try to join a particular consumer group

### ISSUE THREAD

**Issue by TheGUNNER13** [segmentio/kafka-go#199]
we are running our services in AWS EC2. When we start with one service instance, the consumer group --describe properly displays the details of the reader (service) that joined the group. Now when we scale this service, the consumer group --describe tell that its in rebalancing state, and it stays there and no messages flow.

this is the init of the reader that i use in code.

`
reader = kafka.NewReader(kafka.ReaderConfig{
			Brokers:  []string{conf.Broker},
			Topic:    conf.Topic,
			GroupID:  conf.GroupID,
})
`

**Comment by stevevls** [comment]
Hi @TheGUNNER13.  Can you verify which commit you're using?  We recently fixed issue #164, which I believe would cause this behavior.

**Comment by TheGUNNER13** [comment]
i feel this is fixed, did not face this after a pull of this lib.

**Comment by stevevls** [comment]
Awesome...glad to hear it.  I'm going to close this issue then, but please re-open if you see it happen again.  Thanks!
