### ISSUE TITLE
Clarify Reader concurrency safety

### ISSUE THREAD

**Issue by eliaslevy** [segmentio/kafka-go#201]
Related to #180, the documentation is silent on whether `Reader` is safe to use concurrently from multiple goroutines.

**Comment by smmcneill** [comment]
Please advise.  Referring to [#180](https://github.com/segmentio/kafka-go/issues/180).  Achille's response _suggested_ that `Reader` is safe for concurrent use, but getting a definitive _yes/no_ is appreciated.

**Comment by achille-roussel** [comment]
Yes, the `kafka.Reader` and `kafka.Writer` types are safe for concurrent use, apologies if the documentation wasn't clear about it.

Happy to merge an update if you want to contribute a fix for that 👍
