### ISSUE TITLE
Create multiple example for kafka-go

### ISSUE THREAD

**Issue by tarekbadrshalaan** [segmentio/kafka-go#210]
I was wondering if i can contribute with you by creating `example` directory include multiple example about how to use **kafka-go**.

thanks for your advice.

**Comment by achille-roussel** [comment]
This sounds like a great idea, what would you need from us to make this happen?

**Comment by tarekbadrshalaan** [comment]
as you can find in my repo https://github.com/tarekbadrshalaan/GoKafka
I was working to find Golang package able to communicate with Kafka, and found **kafka-go** is the best.
I create sample example with docker file.
what I need to create example for 

1. **simple consumer**
2. **simple producer**
3. **docker-compose example with end point, data storage, consumer and producer**

if those examples are good for the project, I will start work on, and it will be great if you advice me about others.

**Comment by dominicbarnes** [comment]
Looks like we've merged a PR that added some examples, so I will close this ticket. Feel free to open a new ticket if we want more examples or need to correct something in an existing example.
