### ISSUE TITLE
Consumed message returned stanger offset and it seems lost some messages

### ISSUE THREAD

**Issue by yaoguais** [segmentio/kafka-go#220]
**Describe the bug**

reader returned a message that

offset is 65535 or 4294967295 and
value and key is nil but
partition has the correct value.

such as:
```
   Topic: test
   Partition: 5
   Offset: 65535,
   Key: nil
   Vaue: nil,
```

but the previous mesage offset is 4799.

**Kafka Version**
What version(s) of Kafka are you testing against?

Apache Kafka: 2.11-2.1.1

**To Reproduce**
Steps to reproduce the behavior.  Bonus points for a code sample.

```
package main

import (
	"context"
	"flag"
	"fmt"
	"strings"
	"time"

	kafka "github.com/segmentio/kafka-go"
)

var (
	brokers   string
	topic     string
	partition int
)

func init() {
	flag.StringVar(&brokers, "brokers", "", "broker addresses")
	flag.IntVar(&partition, "partition", 0, "partition number")
	flag.StringVar(&topic, "topic", "", "topic name")
	flag.Parse()
}

func main() {
	r := kafka.NewReader(kafka.ReaderConfig{
		Brokers:   strings.Split(brokers, ","),
		Topic:     topic,
		Partition: partition,
		//MinBytes:      1e6,
		//MaxBytes:      1e6,
		//MaxWait:       1000 * time.Millisecond,
		//QueueCapacity: 100,
	})
	r.SetOffset(kafka.FirstOffset)

	defer r.Close()

	timer := time.NewTimer(30 * time.Second)

	var offset int64
	for {
		select {
		case <-timer.C:
			return
		default:
		}

		m, err := r.ReadMessage(context.Background())
		if err != nil {
			break
		}

		if offset == 0 {
			offset = m.Offset
		} else {
			offset++
		}
		fmt.Printf("offset %d %s\n", m.Offset, string(m.Value))

		if offset != m.Offset {
			// fmt.Printf("offset compare kafka %d vs memory %d\n", m.Offset, offset)
		}

		//fmt.Printf("message at offset %d: %s = %s\n", m.Offset, string(m.Key), string(m.Value))
	}
}
```

 $ go run main.go -brokers "192.168.1.78:9092" -partition 5 -topic internal.http.request.v1 > out.log

 $ grep 'offset 4799 ' -A 2 -B 1 out.log

```
offset 4798 {"time":"2019-02-13T19:13:18+00:00"}
offset 4799 {"time":"2019-02-13T19:13:18+00:00"}
offset 65535 
offset 65536 {"time":"2019-02-14T00:02:44+00:00"}
```

**Expected behavior**

offset should be continuous.

when I use sarama and the offset is continuous.

code:

```
package main

import (
	"fmt"
	"log"
	"os"
	"os/signal"

	"github.com/Shopify/sarama"
)

func main() {
	consume()
}

func consume() {
	consumer, err := sarama.NewConsumer([]string{"192.168.1.78:9092"}, nil)
	if err != nil {
		panic(err)
	}

	defer func() {
		if err := consumer.Close(); err != nil {
			log.Fatalln(err)
		}
	}()

	partitionConsumer, err := consumer.ConsumePartition("internal.http.request.v1", 5, sarama.OffsetOldest)
	if err != nil {
		panic(err)
	}

	defer func() {
		if err := partitionConsumer.Close(); err != nil {
			log.Fatalln(err)
		}
	}()

	// Trap SIGINT to trigger a shutdown.
	signals := make(chan os.Signal, 1)
	signal.Notify(signals, os.Interrupt)

	consumed := 0
ConsumerLoop:
	for {
		select {
		case msg := <-partitionConsumer.Messages():
			fmt.Printf("offset %d %s\n", msg.Offset, string(msg.Value))
			consumed++
		case <-signals:
			break ConsumerLoop
		}
	}

	fmt.Printf("Consumed: %d\n", consumed)
}
```

$ go run consumer.go > out.log

$ grep 'offset 4799 ' -A 2 -B 1 out.log

```
offset 4798 {"time":"2019-02-13T19:13:18+00:00"}
offset 4799 {"time":"2019-02-13T19:13:18+00:00"}
offset 4800 {"time":"2019-02-13T19:13:18+00:00"}
offset 4801 {"time":"2019-02-13T19:13:35+00:00"}
```

**Additional context**

kafka-go version:

```
  digest = "1:29fd25ca11a0d508c31ba1c3224d85b14ee73781bc82e46cb955322bc3783fc7"
  name = "github.com/segmentio/kafka-go"
  packages = ["."]
  pruneopts = "NT"
  revision = "0b3aacc527812d4040e51211146a43545e82d670"
  version = "v0.2.2"
```

**Comment by yaoguais** [comment]
Apache Kafka 2.11-2.1.1 is not compatible with kafka-go v0.2.2.

**Comment by salomatu** [comment]
Sorry for posting to a closed issue, but I just wanted to report some findings if someone else stumbles here.

At my job, we ended up having to ingest several gigabytes wort of data through a piece of software that uses, now likely outdated version, of the kafka-go library.

We were quite stumped by a problem where it would sometimes randomly decide to commit 4294967296 as the current offset of the consumer group it was using on the single and only partition of the topic. The maximum offset at this point for that partition was in the order of 190M, so obviously it just stop any activities on the software. We had to stop the software and guess the proper offset and manually commit it to the consumer group before continuing.

After some attempts of data capture and protocol analysis, it seems (with a low sample size) that the occurrence of these incidents (every 15m to 1h+) was co-morbid with a batch from Kafka that had trailing null messages at the end of the batch. These "null" messages would not have any data and per protocol would have -1 as the offset (int64), so it left me wondering if that somehow gets mangled or truncated and ends up interpreted as 4294967295 instead, although I could not find any logical route for that to happen in the code.

I'm not sure if the null-messages are an expected feature of the protocol or if they are artifacts created by the software that was used to send the data in to the topic in the first place (maybe a failed commit?).
The version of the Kafka server was 2.11-2.0.0. The kafka-go library is checked out from 6e83c96052e818332e743abb3c06d6148d3951bb so it is relatively old at this point.

As this was quite a puzzling exercise, I would be delighted to arrive to a proper explanation so to know if this problem still exists in later versions, but in the meantime I'll leave this here in case it provides any clues.

**Comment by stevevls** [comment]
It's strange that the value is that 4294967295...that's the max value for a `uint32`.  For clarification, were you consuming messages in this scenario when receiving these "null" messages?  If so, was there any chance that you had idempotent producers upstream?  kafka-go currently doesn't support consuming from topics with idempotent producers, but there is active work to add that functionality. one PR which may be relevant is #261.

**Comment by salomatu** [comment]
> It's strange that the value is that 4294967295...that's the max value for a `uint32`.

Exactly. That's why I tried to see if I could find any hints of weird casting along the line or a bug in the protocol parser. 

> For clarification, were you consuming messages in this scenario when receiving these "null" messages? If so, was there any chance that you had idempotent producers upstream? kafka-go currently doesn't support consuming from topics with idempotent producers, but there is active work to add that functionality. one PR which may be relevant is #261.

The topic was pre-populated with data and was not added upon during the time it was being consumed. That means we would be receiving close to the maximum requested batch size from the server almost all the time. The topic was populated using kafkacat 1.3.1 (librdkafka 0.11.5) which isn't the newest one either. From what I gather, these versions don't yet have support for idempotency or transactions.

**Comment by stevevls** [comment]
Out of curiosity, did you try upgrading kafka-go?  We've put a lot of work into it since the release you linked, which doesn't have proper support for Kafka 2.  For example, that release won't properly decode a RecordBatch.  I remember from when I was working on compression support (also not yet present in the code you linked) that under certain circumstances, Kafka 0.11+ would switch between MessageSet and RecordBatch for transferring messages to a consumer.  You may be running into that.  

My suggestion would be to try with the latest release of kafka-go and then open up a new bug if that doesn't fix the issue.  Thanks!

**Comment by sneko** [comment]
Hi,

@stevevls you say `kafka-go currently doesn't support consuming from topics with idempotent producers, but there is active work to add that functionality. one PR which may be relevant is #261.` but while looking at this PR it seems no one from the core team has reacted to last updates in May '19.

That's clearly a differentiator if `kafka-go` could implement that, contrarily to other Go libraries.

Thank you,
