### ISSUE TITLE
Partition reassignment causes reader to fail with arbitrary errors

### ISSUE THREAD

**Issue by VictorDenisov** [segmentio/kafka-go#225]
**Describe the bug**
I have a reader that consumes messages from a topic. This topic has only one partition and only one replica in a three node kafka cluster. Reassigning partition to another broker causes reader to close with different errors that are not only unhandled, but also can vary from version to version of kafka.

Error on kafka 1.1.1: `Not Leader For Partition: the client attempted to send messages
to a replica that is not the leader for some partition, the client's metadata are likely out of date`

Error on kafka 2.1.1: `Unsupported Compression Type: the requesting client does not support the compression type of given partition.`

**Kafka Version**
What version(s) of Kafka are you testing against? 2.1.1 and 1.1.1

**To Reproduce**
Run kafka cluster locally as described here: https://hub.docker.com/r/wurstmeister/kafka/
Use HOSTNAME_COMMAND to setup advertised hostname. It's the only way to set it up properly for clusters with several brokers.
```
HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
```
Scale the cluster to three brokers:
```
> docker-compose scale kafka=3
```
Create test topic on one of the brokers:
```
> docker-compose exec kafka /bin/bash
> cd /opt/kafka/bin
> ./kafka-topics.sh --zookeeper zookeeper:2181 --create --topic test-topic --partitions 1 --replication-factor 1
```
Start reader:

```
	r := k.NewReader(k.ReaderConfig{
		Brokers:   []string{"172.21.0.3:9092"},
		Topic:     topic,
		Partition: 0,
		MinBytes: 1,
		MaxBytes: 1000,
	})
	defer r.Close()

	for {
		m, err := r.ReadMessage(context.Background())
		if err != nil {
			log.Fatal(err)
		}
		log.Printf("Message: %v", string(m.Value))
		log.Printf("Offset: %v", m.Offset)
		for _, h := range m.Headers {
			log.Printf("%v - %v", h.Key, string(h.Value))
		}
		log.Printf("================")
	}
```
Then reassign partitions from inside the container:
```
docker-compose exec kafka
```
Create reassignment json file:
```
> cat reassign_file.json
{"version":1,"partitions":[{"topic":"test-topic","partition":0,"replicas":[1002]}]}
```
Reassign partitions: 
```
> ./kafka-reassign-partitions.sh --zookeeper zookeeper:2181 --reassignment-json-file reassign_file.json --execute
```

The consumer will exit with an error:
```
[76] Unsupported Compression Type: the requesting client does not support the compression type of given partition
```

**Expected behavior**
It should reestablish connection to the new broker instead of exiting with an irrelevant error.

**Additional context**

**Comment by luish000** [comment]
any update of this ?
