### ISSUE TITLE
Respect the port from Resolver in Dialer.

### ISSUE THREAD

**Issue by hoveychen** [segmentio/kafka-go#231]
We'd like to implement the `Resolver` interface to adapt our name discovery system.
Our name resolving sys returns not only host but also port. However, the current `Dialer` implementation abandons the resolved port. Would we add an option to opt in port resolving?

**Comment by achille-roussel** [comment]
@hoveychen this is a good idea that could help integrate with more advanced service discovery mechanisms.

Would you be able to submit a patch for this?

**Comment by dominicbarnes** [comment]
With #545 you should be able to use this functionality in v0.4
