### ISSUE TITLE
kafka-go client not retrieving all the message

### ISSUE THREAD

**Issue by Albinzr** [segmentio/kafka-go#236]
**Describe the bug**
I have sent in more than 10k message in kafka producer, but in kafka client is only receiving 882 messages when I run client again

**Kafka Version**
What version(s) of Kafka are you testing against?
2.1.0
**To Reproduce**
Steps to reproduce the behavior.  Bonus points for a code sample.
**Client code**
`		
                package main

		import (
			"context"
			"fmt"
			"time"

			"github.com/segmentio/kafka-go"
		)

		func main() {
			topic := "albin8"
			partition := 0

			conn, _ := kafka.DialLeader(context.Background(), "tcp", "localhost:9092", topic, partition)

			conn.SetReadDeadline(time.Now().Add(10 * time.Second))

			batch := conn.ReadBatch(10e3, 1e6) // fetch 10KB min, 1MB max

			b := make([]byte, 10e3) // 10KB max per message
			for {
				_, err := batch.Read(b)
				if err != nil {
					break
				}
				fmt.Println(string(b))
			}

			batch.Close()
			conn.Close()
		}

`

**producer**

`
					package main

				import (
					"context"
					"time"

					"github.com/segmentio/kafka-go"
				)

				var a = `Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32. The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.`

				func main() {
					topic := "albin8"
					partition := 0

					conn, _ := kafka.DialLeader(context.Background(), "tcp", "localhost:9092", topic, partition)

					conn.SetWriteDeadline(time.Now().Add(10 * time.Second))
					conn.WriteMessages(
						kafka.Message{Value: []byte(a)},
					)

					conn.Close()
				}

`
**Expected behavior**
Should retrive all message insted of only 882 message

**Comment by VictorDenisov** [comment]
Looking into it.

**Comment by achille-roussel** [comment]
@Albinzr the size and number of messages in a batch are mostly controlled by Kafka. A typical program would call `conn.ReadBatch` in a loop as the client doesn't have control over the range of messages that the fetch response will contain, it can only give Kafka hints about how many bytes it wants to read, and how long it wants to wait.

**Comment by Albinzr** [comment]
@achille-roussel Can you give me an example for how to user kafka.Reader?

**Comment by VictorDenisov** [comment]
```go
	r := k.NewReader(k.ReaderConfig{
		Brokers:   []string{"localhost:9092"},
		Topic:     topic,
		Partition: 0,
		MinBytes: 1,
		MaxBytes: 1000,
	})
	defer r.Close()

	for {
		m, err := r.ReadMessage(context.Background())
		if err != nil {
			log.Fatal(err)
		}
		log.Printf("Message: %v", string(m.Value))
		log.Printf("Offset: %v", m.Offset)
		for _, h := range m.Headers {
			log.Printf("%v - %v", h.Key, string(h.Value))
		}
		log.Printf("================")
	}
```

**Comment by Albinzr** [comment]
@VictorDenisov I tried your code and its working fine but it very slow in reading the message, It took 5 min to read around 6000 messages.

**Comment by VictorDenisov** [comment]
Do you print the messages? Usually it takes longer to print the messages than consume them. Remove printf statements and measure the time again.

**Comment by Albinzr** [comment]
`r := k.NewReader(k.ReaderConfig{
		Brokers:   []string{"localhost:9092"},
		Topic:     topic,
		Partition: 0,
		MinBytes: 1,
		MaxBytes: 1000,
	})`

@VictorDenisov Dose MaxBytes means only if it reaches max it will start sending the message?

**Comment by VictorDenisov** [comment]
MaxBytes means that if the unread messages  on the broker are worth more than MaxBytes then your reader will consume those messages in several batches.

**Comment by Albinzr** [comment]
@VictorDenisov got it, is there a way to configure client just to receive new messages only(avoid already read message)?.

**Comment by VictorDenisov** [comment]
I'm not sure what you mean, but you probably need consumer groups. Kafka will be remembering what messages you've already consumed and next time you connect to the brokers it will only be sending you the messages you haven't consumed yet. Look at the configuration options of reader: https://github.com/segmentio/kafka-go/blob/master/reader.go#L889

**Comment by stevevls** [comment]
This doesn't seem to be an issue with the library itself.  Closing for now, but feel free to re-open if needed.  Thanks!

**Comment by contrerasarf03** [comment]
> ```go
> 	r := k.NewReader(k.ReaderConfig{
> 		Brokers:   []string{"localhost:9092"},
> 		Topic:     topic,
> 		Partition: 0,
> 		MinBytes: 1,
> 		MaxBytes: 1000,
> 	})
> 	defer r.Close()
> 
> 	for {
> 		m, err := r.ReadMessage(context.Background())
> 		if err != nil {
> 			log.Fatal(err)
> 		}
> 		log.Printf("Message: %v", string(m.Value))
> 		log.Printf("Offset: %v", m.Offset)
> 		for _, h := range m.Headers {
> 			log.Printf("%v - %v", h.Key, string(h.Value))
> 		}
> 		log.Printf("================")
> 	}
> ```

Hi, I'm having a problem when I use ReadMessage .. it won't read all the messages sent to kafka ..

**Comment by joachimbulow** [comment]
Still seeing this, may 2023
