### ISSUE TITLE
Reading from offset does not work?

### ISSUE THREAD

**Issue by kidphys** [segmentio/kafka-go#257]
**Describe the bug**
I try to start reading from a offset which is not zero, here is the code:
```
	host := "localhost"
	topic := "test"
	r := kafka.NewReader(kafka.ReaderConfig{
		Brokers:   []string{host + ":9092"},
		Topic:     topic,
		Partition: 0,
		MinBytes:  1,
		MaxBytes:  1e3,
	})

	// err := r.SetOffset(kafka.LastOffset)
	err := r.SetOffset(4)
	if err != nil {
		fmt.Println("Error setting offset", err.Error())
	}

	for {
		m, err := r.ReadMessage(context.Background())
		if err != nil {
			fmt.Println("error reading message", err.Error())
			break
		}
		fmt.Printf("message at offset %d: %s = %s\n", m.Offset, string(m.Key), string(m.Value))
	}

	r.Close()
```
The `SetOffset()` method doesn't seem to work, the reader always read from offset 0.

Also, is reading from the latest offset possible with `Reader`?

**Kafka Version**
2.1.1

**Comment by luzhuqun** [comment]
@kidphys  I have the same problem, how to solve this ?

**Comment by VictorDenisov** [comment]
There is a possibility that your offsets were compacted and offset 4 is before any available offset. Checkout the offset of the earliest message that you have in the topic.
