### ISSUE TITLE
Batch.Read blocks in some cases

### ISSUE THREAD

**Issue by vrischmann** [segmentio/kafka-go#265]
**Describe the bug**

`Batch.Read` seems to block in some cases, specifically in this call to [io.ReadFull](https://github.com/segmentio/kafka-go/blob/master/batch.go#L129).

I made a [small reproduction program](https://gist.github.com/vrischmann/3c2e67e0cd18c8b8039982a3d9837a96) which triggers this. Here's a sample output on a partition with 10 messages of 400 bytes each:

    $ ./benchmark
    INFO[0000] read batch 0xc0000ee080 with offset: 0
    INFO[0000] message: 400
    INFO[0000] message: 400
    INFO[0000] message: 400
    INFO[0000] message: 400
    INFO[0000] message: 400
    INFO[0000] closing batch, total read: 2000
    INFO[0000] read batch 0xc0000ee100 with offset: 5
    INFO[0000] message: 400
    INFO[0000] message: 400
    INFO[0000] message: 400
    INFO[0000] message: 400
    INFO[0000] short read ! size: 163 nbytes: 400
    FATA[0002] unable to read batch message: read tcp 127.0.0.1:42042->127.0.0.1:9092: i/o timeout

The "short read" is this code:

			if size < nbytes {
				logrus.Printf("short read ! size: %d nbytes: %d", size, nbytes)
			}

which I added just before the call to `io.ReadFull`.

I also have this strack trace:

    1 @ 0x431919 0x42c78a 0x42bd55 0x4d00bb 0x4d0ed2 0x4d0eb4 0x59717f 0x5aa6d8 0x550acb 0x48f447 0x821c7b 0x821c39 0x81926d 0x81783b 0x80c978 0x80c418 0x835dbe 0x836d1f 0x835bb7 0x45f291
    #	0x42bd54	internal/poll.runtime_pollWait+0x54					/home/vincent/sdk/gotip/src/runtime/netpoll.go:184
    #	0x4d00ba	internal/poll.(*pollDesc).wait+0x10a					/home/vincent/sdk/gotip/src/internal/poll/fd_poll_runtime.go:87
    #	0x4d0ed1	internal/poll.(*pollDesc).waitRead+0x191				/home/vincent/sdk/gotip/src/internal/poll/fd_poll_runtime.go:92
    #	0x4d0eb3	internal/poll.(*FD).Read+0x173						/home/vincent/sdk/gotip/src/internal/poll/fd_unix.go:169
    #	0x59717e	net.(*netFD).Read+0x4e							/home/vincent/sdk/gotip/src/net/fd_unix.go:202
    #	0x5aa6d7	net.(*conn).Read+0x67							/home/vincent/sdk/gotip/src/net/net.go:177
    #	0x550aca	bufio.(*Reader).Read+0x23a						/home/vincent/sdk/gotip/src/bufio/bufio.go:223
    #	0x48f446	io.ReadAtLeast+0x86							/home/vincent/sdk/gotip/src/io/io.go:310
    #	0x821c7a	io.ReadFull+0x9a							/home/vincent/sdk/gotip/src/io/io.go:329
    #	0x821c38	github.com/segmentio/kafka-go.(*Batch).Read.func2+0x58			/home/vincent/dev/go/src/github.com/segmentio/kafka-go/batch.go:129
    #	0x81926c	github.com/segmentio/kafka-go.(*messageSetReaderV2).readMessage+0x2fc	/home/vincent/dev/go/src/github.com/segmentio/kafka-go/message.go:514
    #	0x81783a	github.com/segmentio/kafka-go.(*messageSetReader).readMessage+0x6a	/home/vincent/dev/go/src/github.com/segmentio/kafka-go/message.go:124
    #	0x80c977	github.com/segmentio/kafka-go.(*Batch).readMessage+0x77			/home/vincent/dev/go/src/github.com/segmentio/kafka-go/batch.go:204
    #	0x80c417	github.com/segmentio/kafka-go.(*Batch).Read+0xb7			/home/vincent/dev/go/src/github.com/segmentio/kafka-go/batch.go:111
    #	0x835dbd	main.readPartition+0x17d						/home/vincent/dev/perso/kafkago-benchmark/main.go:69

It's trying to read from the network (because as shown before, the number of bytes buffered isn't enough to satisfy the read request). I may be wrong but I thought that a Batch worked on data already fetched ?

Also, I took a look at how `ReadMessage` works and it calls [readNewBytes](https://github.com/segmentio/kafka-go/blob/master/read.go#L113:6) which does handle this case by issuing a `errShortRead`.

**Kafka Version**

Kafka 2.1.0

**To Reproduce**

See above.

**Expected behavior**

I expect `Batch.Read` to not block or fail.

**Additional context**

It's possible that I'm not using the Batch correctly but looking at [the sample here](https://github.com/segmentio/kafka-go#connection-) I don't see what I'm doing wrong.

If I did do something wrong I think it would be good to clarify the documentation.

**Comment by stevevls** [comment]
Thanks for the great write-up.  We have seen variants of this bug a couple of times.  You are right that the request should not be going out to the network.  What's happening is that we're not accounting for the remaining bytes when we call `io.ReadAll`, so it's trying to go to the network to receive the bytes beyond what we have available.  However, the message has been truncated by the broker (this is an optimization on the broker) and no more bytes are coming.  Keep an eye on #267 as it should fix this issue.

**Comment by stevevls** [comment]
This should be fixed now on master.
