### ISSUE TITLE
Configure retry.backoff.ms in Reader

### ISSUE THREAD

**Issue by ostenbom** [segmentio/kafka-go#269]
I have a need to configure the `backoffDelayMin` (and potentially `backoffDelayMax`) property that decides how tight the Readers read loop runs. This property is currently defaulted to [100 ms in the reader](https://github.com/segmentio/kafka-go/blob/master/reader.go#L1705-L1706), and backs off up to one second. Waiting even 30ms on my project would be too slow!

Issue #243 is similar but refers to the `reconnect.backoff.ms` property - I believe this issue is more similar to the [`retry.backoff.ms`](https://kafka.apache.org/documentation/#consumerapi) property.

I understand that the importance in the documentation is "low". But given that I will be altering my own fork anyway, I would be happy to PR it in here too if appropriate.

If so, should both `backoffDelayMin` and `backoffDelayMax` be configurable? Or just `delayMin`

**Comment by stevevls** [comment]
Hi @ostenbom.  I think it makes sense to have those two values be configurable, and if you have the code ready, a PR would be great.  Thanks!
