### ISSUE TITLE
Question: Is multiple writes atomic?

### ISSUE THREAD

**Issue by zhangchiqing** [segmentio/kafka-go#271]
I'd like to write multiple messages into the same topic, which contains only 1 partition. If I use the `Write` as [the example shows](https://github.com/segmentio/kafka-go#writer-), is the multiple writes atomic? Is it possible that some messages were saved and some weren't saved?

**Comment by achille-roussel** [comment]
The `kafka.Writer` API does not give atomicity garantees, and depending on the partitioning mechanism employed by the writer the messages may be delivered to different partitions.

You can look at using `kafk.Conn` instead, which gives you a lower-level API. When using a connection directly, each call to `WriteMessages` submits a single Produce request. In this case the operation is atomic.

**Comment by zhangchiqing** [comment]
Thanks @achille-roussel .
