### ISSUE TITLE
Partition Rebalancing

### ISSUE THREAD

**Issue by danijeldjuric** [segmentio/kafka-go#274]
**ConsumerRebalance Listener methods implementations in kafka-go**

Is there a way to track two main rebalancing methods onPartitionsRevoked and onPartitionsAssigned. Are those methods or equivalents available in kafka-go

**Comment by danijeldjuric** [comment]
Also can i ask a question. 

So when using kafka-go package and specifying GroupID, how can i track new partitions added. 

Currently my go app, reads messages nicely, but if i add a partition to a topic that i'm allready listening, is there any way for me to detect it in my consumer app. At this moment those messages stay in kafka, but are not consumed by my consumers, 
aldo i'm not changing consumers in any way. 
Is there any ways to do this? 

I can't find any examples for this use case so i'm not having any luck with guessing it atm

Contact me if i wasn't clear

Tnx in advance

**Comment by danijeldjuric** [comment]
Here is the code that i'm using to create the reader
`streamReader := kafka.NewReader(kafka.ReaderConfig{
		Brokers:               []string{connectionString},
		Topic:                   topic,
		GroupID:              group,
		GroupBalancers: []kafka.GroupBalancer{kafka.RangeGroupBalancer{}, kafka.RoundRobinGroupBalancer{}},
		MinBytes:             MinBytes,
		MaxBytes:            MaxBytes,
})`

**Comment by stevevls** [comment]
Greetings!  I believe that we have what you're looking for.  There's a flag on the `ReaderConfig` called `WatchPartitionChanges` (https://github.com/segmentio/kafka-go/blob/d7d75c372d532b74b5447337396aa451d378f487/reader.go#L963-L965).  It's off by default, but it can be turned on to trigger consumer group rebalances when the number of partitions changes.  Does that solve your issue?

**Comment by danijeldjuric** [comment]
Yes thank you

I managed to find it. Can you help me with one more thing if you don't mind
Can you tell me how can i commit offsets before rebalancing so i can track all messages when rebalancing happens

Thank you

**Comment by stevevls** [comment]
You have a couple of options for committing offsets.  By default, commits are handled synchronously, but you can also have them committed at an interval with this option https://github.com/segmentio/kafka-go/blob/d7d75c372d532b74b5447337396aa451d378f487/reader.go#L946-L952

Also, look to see whether you're using `ReadMessage` or `FetchMessage` to get messages from the reader.  `ReadMessage` will update the consumer offset but `FetchMessage` will not.  If using the latter, you'll also need to call `CommitMessages` in order to update the offset.

**Comment by danijeldjuric** [comment]
I'm using ReadMessage for getting the messages

Ok let me explain the situation and problem that i have so you can understand me better. Maybe i'm missing something obvious

I'm building a group consumer workers that read all the messages and track the offset our end in case of failure. All is fine, except in case of rebalancing. So as an example we have a topic called **sample-topic** with 3 partitions

When i start the consumer and messages come in all is fine it tracks the offset and messages get processed. Because we have very enormous traffic, let's say we need to increase the partition count to 4. We increase the partition, offsets are preserved for 3 partitions, and 4th partition starts with 0.

Because producer is partition aware it will start publishing to partition 4.
At this point i need to create a new worker that will fetch messages from that partition, because we're creating worker per partition count, so it's properly consuming messages without one worker processing messages from multiple partitions. And i need to get offsets right so i don't lose any messages from the existing 3 partitions and the new 4th partition

So any suggestions is welcome

Thank you very much.

**Comment by stevevls** [comment]
I see.  I think you may want to keep an eye on #263 because it sounds like it would help you manage your worker pool if you could access each partition as a single stream.  Does that sound right?  I can't think of a good way to implement what you're describing with the current `Reader`, unfortunately, because  It hides too much of what's going on underneath the hood.

**Comment by stevevls** [comment]
We just merged #277, and the new API makes it possible to implement the solution you described above by managing the consumer group more directly.

**Comment by Max-Cheng** [comment]
Let me explain the question, Kafka topic `A` include 3 Partition A[0,1,2]

**Comment by Max-Cheng** [comment]
I got same problem. Let me explain the main Question:did `Kafka-go` can handle consumer group rebalancing event or sent a signal to user?

situation:
  Program A using groupid:`test` to subscribe topic `test` and topic test got 3 petition`[0,1,2]`

```go
package main

import (
	"context"
	"fmt"
	"github.com/segmentio/kafka-go"
	"io"
	"log"
	"time"
)

func main() {
	client := kafka.NewReader(kafka.ReaderConfig{
		Brokers:       []string{"localhost:9092"},
		GroupID:       "test",
		Topic:         "test",
		MaxBytes:      10e6, // 10MB
		QueueCapacity: 1000,
	})
	rec := make(chan *kafka.Message)

	go func() {
		for {
			select {
			case v := <-rec:
				if err := client.CommitMessages(context.Background(), *v); err != nil {
					panic(err)
				}
			}
		}
	}()

	for {
		r, err := client.FetchMessage(context.Background())
		if err != nil && err != io.EOF {
			log.Println(err)
			time.Sleep(time.Second * 5)
			continue
		}
		fmt.Println(string(r.Value), time.Now().String())
        // Send message into cache queue
        // waiting for receive a batch message && send HTTP request
        // and waiting for remote server ack and commit those index of message
		rec <- &r
	}

}
```

First:
  Program `A` running success, subscribe whole topic of partition. But now, new consumer `B` join in the group, Kafka send rebalance request to `A`,
In this time, did kafka-go can using some call back function or using a signal to **block rebalance process**. Cause Program `A` need processing local queue to keep Kafka will not consume twice
