### ISSUE TITLE
Can the order of messages in a partition be lost due to batch retries?

### ISSUE THREAD

**Issue by marselester** [segmentio/kafka-go#278]
Hello, I want to clarify the ordering guarantees of `WriteMessages()`.

Let's say I need to write 100 messages with batch size of 5 messages.
The messages are balanced among 2 partitions.
Can the order of messages in a partition be lost due to batch retries?
For example, the first batch is failed, the second succeeded, then first batch is retried successfully.

```go
w := kafka.NewWriter(kafka.WriteConfig{
	Brokers: []string{"localhost:9092"},
	Topic:   "my-topic",
	BatchSize: 5,
	// Balancer uses hash function to route messages with the same key to the same partition.
	Balancer: &kafka.Hash{},
})
w.WriteMessages(ctx, msgs) // msgs contains 100 messages.
```

**Comment by VictorDenisov** [comment]
Each partition has a separate writer. Each partition writer forms it's own batch and will be trying to send the same batch again and again until it succeeds.

**Comment by marselester** [comment]
Thank you for the explanation! Just to reiterate, If `msgs` contains 100 messages which are batched by 5
```
msg 0: should be in partition 0
msg 1: should be in partition 0
msg 2: should be in partition 1
msg 3: should be in partition 0
msg 4: should be in partition 1
msg 5: should be in partition 0
msg 6: should be in partition 0
msg 7: should be in partition 0
...
msg 99: should be in partition 0
```
The first batch of 5 messages (0, 1, 3, 5, 6) will be processed by a single goroutine (dedicated to partition 0) that will sequentially try to write the first batch until `MaxAttempts`. The second batch to the same partition (7, ...) is not going to be written until the first one succeeds.

**Comment by VictorDenisov** [comment]
Correct.
