### ISSUE TITLE
consume message wrong 

### ISSUE THREAD

**Issue by wypsmall** [segmentio/kafka-go#281]
**Describe the bug**
when run demo, result is like this
i write message twice 
------
conn.WriteMessages(
        kafka.Message{Value: []byte("one!")},
        kafka.Message{Value: []byte("two!")},
        kafka.Message{Value: []byte("three!")},
    )

------
but read 

one!
two!
three!

one!e!
two!e!
three!

use this code
-------------------
topic := "my-topic"
    partition := 0

    conn, _ := kafka.DialLeader(context.Background(), "tcp", "localhost:9092", topic, partition)

    conn.SetReadDeadline(time.Now().Add(10 * time.Second))
    batch := conn.ReadBatch(10e3, 1e6) // fetch 10KB min, 1MB max

    b := make([]byte, 10e3) // 10KB max per message
    for {
        _, err := batch.Read(b)
        if err != nil {
            break
        }
        fmt.Println(string(b))
    }

    batch.Close()
    conn.Close()

-------------------

**Kafka Version**
What version(s) of Kafka are you testing against?
kafka_2.11-0.10.1.0

**To Reproduce**
Steps to reproduce the behavior.  Bonus points for a code sample.

**Expected behavior**

**Additional context**

**Comment by stevevls** [comment]
Hello!  The issue you're running into is that you're re-using the byte slice, but you're not capturing the return value for the number of bytes read.  With two minor modifications to the code, your problem will be fixed: 

```
conn, _ := kafka.DialLeader(context.Background(), "tcp", "localhost:9092", topic, partition)

conn.SetReadDeadline(time.Now().Add(10 * time.Second))
batch := conn.ReadBatch(10e3, 1e6) // fetch 10KB min, 1MB max

b := make([]byte, 10e3) // 10KB max per message
for {
    n, err := batch.Read(b)  // modification 1 : capture the number of bytes read
    if err != nil {
        break
    }
    fmt.Println(string(b[:n]))  // modification 2 : re-slice the bytes
}

batch.Close()
conn.Close()
```
