### ISSUE TITLE
question about go language

### ISSUE THREAD

**Issue by bemyth** [segmentio/kafka-go#282]
hello , I have some doubts about the following description in your readme.md.
>It also passes all values as pointers which causes large numbers of dynamic memory allocations, more frequent garbage collections, and higher memory usage.

i want to know why pointer can cause those issue? thank you.

**Comment by stevevls** [comment]
Greetings!  I'd recommend this article from the Segment blog: https://segment.com/blog/allocation-efficiency-in-high-performance-go-services/.
