### ISSUE TITLE
Question: wildcard subscriptions

### ISSUE THREAD

**Issue by procyclinsur** [segmentio/kafka-go#283]
Are wildcard subscriptions possible? I tried setting the `topic` to `my-topic*`, and the client didn't fail.. but it made kafka repeatedly boot and re-register the client every 3 seconds.

**Comment by procyclinsur** [comment]
also do you have a slack or help channel for issues that are not feature requests or bugs, or is it expected to be asked as I have?

**Comment by stevevls** [comment]
Greetings.  We don't currently support wildcards, but we are tracking this feature request #131.  PRs are welcome, though! 😄 

We are in the #kafka-go channel in the [Gophers slack](https://invite.slack.golangbridge.org/) if you want to get in touch with us there.  Issues on GH are also good.
