### ISSUE TITLE
Could not dial broker: dial tcp: lookup kafka-1.kafka.kafka-ca1.svc.cluster.local: device or resource busy

### ISSUE THREAD

**Issue by malonaz** [segmentio/kafka-go#285]
Hey all,
I'm not sure if this qualifies for an issue, but I've been trying to setup a kafka on my micro-service project and I keep hitting the 'resource busy', when deploying on minikube.
I believe that my zookeeper/kafka setup is correct because I can run a node.js application that publishes and consumes from a topic successfully.
Is there some driver, library I must install on my docker image before I spin my golang binary?
Any help would be much appreciated, thank you.

**Comment by malonaz** [comment]
FIX: I was creating a statically linked go binary, which caused some issue for DNS look ups

**Comment by kabaluyot** [comment]
what does this mean? @malonaz

**Comment by pmahoney** [comment]
We've run into a similar issue where, given a static go binary, seemingly anything ending in `.local` fails DNS resolution. I've run tcpdump and observed no DNS packets when trying to resolve such an address (while other addresses resolve fine and are observed through tcpdump).

Reading through [Name Resolution](https://golang.org/pkg/net/#hdr-Name_Resolution) and [.local](https://en.wikipedia.org/wiki/.local) suggests that golang may correctly be treating `.local` differently.  But also that when dynamically linked to the c library, will use that routine for `.local`, which explains the difference between static binary and dynamic.

Not sure I've got the details 100% yet, but wanted to post this here.

**Comment by prashant-shahi** [comment]
was facing the same issue.

Adding runtime environment `GODEBUG` to `netdns=go` resolved the issue.
