### ISSUE TITLE
auto_offset_reset

### ISSUE THREAD

**Issue by kwame998** [segmentio/kafka-go#297]
auto_offset_reset FirstOffset is the default value of, how to modify LastOffset

**Comment by stevevls** [comment]
Greetings...  are you referring to in the case of consumer groups?  We have a fix coming soon as part of #277 if that's the case.

**Comment by cretz** [comment]
I believe this is in that case. In most (all?) other Kafka clients there is a setting ([`auto.offset.reset`](https://docs.confluent.io/current/installation/configuration/consumer-configs.html#cp-config-consumer) in the JVM consumer) that is basically "what is the offset if we've never seen this group ID before?". When using a simple `ReaderConfig`, this cannot be set that I can see (not to be confused with SetOffset everytime, there is no way to know if this is first load). Is there any workaround for this?

**Comment by stevevls** [comment]
We just merged #277, which adds a `StartOffset` field to the configuration that will tell the consumer group where to start in case there's no committed offset.  This can be set to either `FirstOffset` (default) or `LastOffset`.

**Comment by mikawudi** [comment]
> We just merged #277, which adds a `StartOffset` field to the configuration that will tell the consumer group where to start in case there's no committed offset. This can be set to either `FirstOffset` (default) or `LastOffset`.

why not update readme Reader demo, auto_offset_reset(StartOffset) is a very common property
