### ISSUE TITLE
consuming: "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by tolitius** [segmentio/kafka-go#30]
I am able to read messages from one broker, but not another (same Kafka version `0.10.2`). I am able to consume messages from all using Clojure/Java.

Here is what I am getting with `segmentio/kafka-go`:

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13788d2]

goroutine 85 [running]:
github.com/segmentio/kafka-go.(*Conn).SetReadDeadline(0x0, 0xbe7644d72f0448ba, 0x26204df38, 0x16aef00, 0xbe7644d72f0448ba, 0x26204df38)
	/../go/src/github.com/segmentio/kafka-go/conn.go:168 +0x22
github.com/segmentio/kafka-go.(*reader).read(0xc4204e8000, 0x16793e0, 0xc420064300, 0x0, 0x0, 0x0, 0x1675460, 0x14c3c60)
	/../go/src/github.com/segmentio/kafka-go/reader.go:692 +0xcc
github.com/segmentio/kafka-go.(*reader).run(0xc4204e8000, 0x16793e0, 0xc420064300, 0x0, 0xc4204e4440)
	/../go/src/github.com/segmentio/kafka-go/reader.go:585 +0x311
created by github.com/segmentio/kafka-go.(*Reader).start
	/../go/src/github.com/segmentio/kafka-go/reader.go:476 +0x219
```

how do I go about debugging this? Again, same consuming code with `segmentio/kafka-go` does work with one broker, but not with another. The only difference in config is a hostname.

**Comment by achille-roussel** [comment]
Would it be possible for you to share the code sample thy triggered the panic?

**Comment by tolitius** [comment]
it is spread over several functions, but comes down to something like this:

```go
func createConsumer(config map[string]string, partition int) *kafka.Reader {

	maxBytes, err := strconv.Atoi(config[max_partition_fetch_bytes])
	brokerList := strings.Split(config[brokers], ",")

	if err != nil {
		log.Fatalf("\ncould not parse a number for 'max_partition_fetch_bytes' from config %+v due to:%+v\n", err)
	}

	consumer := kafka.NewReader(kafka.ReaderConfig{
		Brokers:   brokerList,
		Topic:     config[topic],
		Partition: partition,
		MaxBytes:  maxBytes,
	})

	fmt.Printf("created consumer: %+v\n", *consumer)

	return consumer
}
```

and in another `consume` go routine:

```go
	for ctx.Err() == nil {
		m, err := consumer.ReadMessage(ctx)      ;;  <<<<<<< (!) PANICS FROM HERE
		if err != nil {
			//TODO: fatal for now to fail fast (and learn the reasons) until recover / retry logic is in
			log.Fatalf("\ncould not consume from partition: %+v, %+v \ndue to:%+v\n", consumer.Stats(), consumer.Config(), err)
		} else {
			...
		}
	}
```

**Comment by tolitius** [comment]
caused by `OffsetOutOfRange`. It seems that even when this error occurs, the flow continues into the `readLoop:` and fails here: https://github.com/segmentio/kafka-go/blob/1e83cf5b64391047336130bb080ea81ac399db9b/reader.go#L585

because the connection is `nil` (i.e. was not created due to the `OffsetOutOfRange`).

the real panic due to the `nil` connection is here: https://github.com/segmentio/kafka-go/blob/1e83cf5b64391047336130bb080ea81ac399db9b/reader.go#L690

_minor: https://github.com/segmentio/kafka-go/blob/a8872edfa036c637c20984630e42083f5c905796/error.go#L97 error message spelling_

**Comment by achille-roussel** [comment]
Thanks for the report, I'll send a PR with a test to reproduce the issue and a fix.

**Comment by achille-roussel** [comment]
I'm having trouble reproducing the issue, it seems like this code should be taking care of not having offsets out of range issues. Could it be a race between the reader reading from the first offset and kafka expiring those data?

Would you happen to know what's the range of valid offsets on your partition, and which offset the reader was trying to consume from? (looking at your code snippet it seems like it's reading from the oldest offset).

**Comment by tolitius** [comment]
> Could it be a race between the reader reading from the first offset and kafka expiring those messages?

I don't think this is the case due to the next answer

> Would you happen to know what's the range of valid offsets on your partition, and which offset the reader was trying to consume from?

I did point it to a different Kafka broker that did not yet have messages for a partition. But I read offsets from Consul, which remembered offsets from a previous broker. i.e. so any offset set to greater than zero for a brand new partition results in this panic

> looking at your code snippet it seems like it's reading from the first offset

I do manual offset management: recording them in a `sync.Map`, and periodically persisting them to Consul. When the app starts it reads Consul along with all the partition offsets

**Comment by achille-roussel** [comment]
Hm... I tried writing a test that would do `r.SetOffset(42)` on an empty topic but it didn't trigger the issue, I'll dig more.

**Comment by achille-roussel** [comment]
Ah! Never mind I got it, in the test the topic didn't exist until messages were produced to it. See the PR for the test and fix.

Thanks for your help making this project better!

**Comment by tolitius** [comment]
just in case: Kafka version `kafka_2.12-0.10.2.0`

if I put `continue` after `OffsetOutOfRange` case, as in your pull request, it does _not_ panic on a wrong offset.

At this point this is not a blocker for me, since theoretically "it's a user error", but it would be nice to avoid a panic of course.

**Comment by tolitius** [comment]
great, sure always welcome, thanks for a quick fix :)
