### ISSUE TITLE
Use Zstd compression not requiring CGO

### ISSUE THREAD

**Issue by dwin** [segmentio/kafka-go#303]
**Describe the solution you'd like**
There are Go packages available that provide `zstd` compression without requiring CGO which is not preferred. 

Working on this, will submit PR.

**Supporting documentation**

https://github.com/klauspost/compress/tree/master/zstd
https://godoc.org/github.com/klauspost/compress/zstd

**Comment by Pryz** [comment]
hi @dwin, thanks for working on this. Do we have a timeline for the PR ?

**Comment by dwin** [comment]
> hi @dwin, thanks for working on this. Do we have a timeline for the PR ?

Should have one over today.
