### ISSUE TITLE
How to disable autocommit with GroupID used

### ISSUE THREAD

**Issue by hookover** [segmentio/kafka-go#309]
I want to commit manually, or there is a way to roll back to the target offset
I need to keep the current message uncommitted when an error occurs in the program. 
However, when the program receives the exit signal, the offset is still submitted

**Comment by m4ng0** [comment]
Have you tried this:
https://github.com/segmentio/kafka-go#explicit-commits
?

**Comment by hookover** [comment]
> https://github.com/segmentio/kafka-go#explicit-commits

Yes, that's what I did.
Pseudo code：
```
ctx,cancel := context.WithCancel()

go func{
    for {
       select {
        case msg, err := reader.FetchMessage(ctx)
              do(msg)
        case <-ctx.Done():
            return
        }
    }
 }

func (msg Message) {
      err := process(msg)
      if err != nil {
         cancel() // context cancel
        fmt.Print("caught an error，app is about to exit")
     } else {
         reader. CommitMessages(ctx,msg)   // if has err ,can't commit this.
         fmt.Print("commit by hand",msg.Id)
     }
}
func process(msg Message)  error{
    if msg.Id == 5 {
       return errors.New("test")
    }
    fmt.Print("process msg id:" , msg.Id)
   return nil
}
```

Log
```
process msg id: 1
commit by hand 1
process msg id: 2
commit by hand 2
process msg id: 3
commit by hand 3
process msg id: 4
commit by hand 4
process msg id: 5
caught an error，app is about to exit
committed offsets: map[rupiah_loan_user_info:map[0:5]]  // kafka-go auto committed,But I don't want it to be submitted.
app exit
```

**Comment by hookover** [comment]
I'm sorry. This is probably my program error.

**Comment by stevevls** [comment]
Great.  If you're looking to do more advanced offset management, you can also keep an eye on #277.  We're getting pretty close to merging that in.

**Comment by SkipUFO** [comment]
Good day. 

I cannot understand how to work with Fetch and Commit
I have code 
`go func(brokers []string, wg *sync.WaitGroup) {
		defer wg.Done()

		reader := kafka.NewReader(kafka.ReaderConfig{
			Brokers:  brokers,
			Topic:    "topic"
			GroupID:  "group",
			MinBytes: 10e3, // 10KB
			MaxBytes: 10e6, // 10MB
			Dialer:   dialer,
		})
		defer reader.Close()

		u := uuid.New()
		ctx := context.Background()
		ctx = context.WithValue(ctx, logger.SessionIDContextKey, u.String())

		for {
			m, err := reader.FetchMessage(ctx)
			if err != nil {
				msu.Warn(ctx, err)
			}
			if err = process(ctx, m.Key, m.Value); err != nil {
				msu.Warn(ctx, err)
			} else {
				if err = reader.CommitMessages(ctx, m); err != nil {
					msu.Warn(ctx, err)
				}
			}
		}
	}(brokers, &wg)`

Function process work with postgres and can return err; when it returns I expect that on reader.FetchMessage I will fetch message with error without reconnect. In code I see that offset changed when called FetchMessage. 

Is it true, that I need to re-initialize reader to get started with errored message?
