### ISSUE TITLE
No function for modifying topic config

### ISSUE THREAD

**Issue by navneetyps** [segmentio/kafka-go#310]
trying to find function for modifying topic properties like its number of partitions/retention.ms and other config properties of a topic but cannot find any. Only solution right now is create new topic with required properties , copy data to it from previous topic and then delete previous topic.

**Comment by Pryz** [comment]
Hi @navneetyps, you're right we don't have any function to do that right now. Feel free to send a PR if you want to implement it :)

**Comment by stevevls** [comment]
Here's the KIP for adding API calls for describing and modifying topics:
https://cwiki.apache.org/confluence/display/KAFKA/KIP-133%3A+Describe+and+Alter+Configs+Admin+APIs

The API calls are documented here:
https://kafka.apache.org/protocol#The_Messages_DescribeConfigs
https://kafka.apache.org/protocol#The_Messages_AlterConfigs

**Comment by stevevls** [comment]
@ankitm123 No one on our end is working on this feature...go for it!

**Comment by SchwarzWeiss** [comment]
Is there any new information?

**Comment by Luffy110** [comment]
Hi All, I have implemented these APIs, and have a pull request [470](https://github.com/segmentio/kafka-go/pull/470)  . anybody can help review it ?

**Comment by nlsun** [comment]
AlterConfig was implemented in https://github.com/segmentio/kafka-go/pull/544
