### ISSUE TITLE
Clients metadata is most likely out of date

### ISSUE THREAD

**Issue by danncoba** [segmentio/kafka-go#311]
**Describe the bug**
I'm not sure this is a bug, so please excuse me if i'm not right. However i haven't been able to find a solution in kafka-go. This problem is when i'm using reader to read messages from kafka cluster. The problem is that when a broker is restarted or shutdown for update/upgrade we have a massive consumer that is reading the messages and it gets this messages multiple ones

> Kafka stream error: dial tcp :0: connect: can't assign requested address

After these i get the following error

> Kafka stream error: [6] Not Leader For Partition: the client attempted to send messages to a replica that is not the leader for some partition, the client's metadata are likely out of date

**Kafka Version**
2.3.0

**To Reproduce**
Normal Reader object that has 3 brokers inside it.

**Expected behavior**
Should just pick up that the broker has turned of and read from another and not throw that error

**Additional context**
I haven't found a solution on the web or ridding the docs, or maybe i've missed it. Is there an existing solution for this issue that i can work with. I'm guessing there is

Thanks for your help

**Comment by Pryz** [comment]
@danncoba I think the way we have been dealing with this behavior is by catching the error and refresh the metadata using `ReadPartitions`.

**Comment by danncoba** [comment]
@Pryz thanks for quick reply. I'll try it out now

**Comment by danncoba** [comment]
@Pryz i want to just say i use consumer groups not partitions directly to read from

Regards i let you know when i test it properly

**Comment by danncoba** [comment]
Hi all.

I haven't been able to create this as i use Reader with consumer groups. The problem happens when zookeeper in cluster fails. I have a zookeeper ensemble and kafka cluster, and when zookeeper fails, which we're testing for the consumer just looses that those partitions and doesn't refresh the metadata for at least 30 mins in my case.

Any suggestions

**Comment by Pryz** [comment]
Looks more like a Kafka problem than a client one right ? If your ZK fails and you don't have any controller in your cluster then you can't do much.

But maybe I don't understand what you are trying to achieve :)

**Comment by Pryz** [comment]
@danncoba I am going to close this issue since it looks to be an operational problem. Feel free to re-open if that's not the case.
