### ISSUE TITLE
Change offset for consumer Group

### ISSUE THREAD

**Issue by vgvineet4** [segmentio/kafka-go#312]
**Describe the bug**
Not able to change offset for a consumer group.I checked the reader API setOffset() and it doesn't allowed to change the offset if groupID is specified.
No details are present why this is not allowed.

**Kafka Version**
What version(s) of Kafka are you testing against?

**To Reproduce**
Steps to reproduce the behavior.  Bonus points for a code sample.

**Expected behavior**

**Additional context**

**Comment by stevevls** [comment]
We just merged #277, which adds a `StartOffset` field to the configuration that will tell the consumer group where to start in case there's no committed offset.  This can be set to either `FirstOffset` (default) or `LastOffset`.
