### ISSUE TITLE
undefined string writer on master

### ISSUE THREAD

**Issue by ldrrp** [segmentio/kafka-go#321]
**Describe the bug**
..\github.com\segmentio\kafka-go\crc32.go:60:4: undefined: io.StringWriter

**Additional context**
Not exactly sure what happened, just cant build anymore. Using go version 1.11 
I see the docs for io.StringWriter but im not sure what version it was released for. Many of the docs say 1.10

**Comment by achille-roussel** [comment]
@ldrrp what do you think the fix should be here? We could update the docs saying we support Go 1.12+, or do you need support for 1.11?

**Comment by ldrrp** [comment]
Im not sure, im dealing with slow bureaucracy here getting IT to update my go version to 1.12 to see if thats it. I should have it by the end of today. If thats it maybe i can update the docs to reflect 1.12+

**Comment by GrimTheReaper** [comment]
We're running into similar issues, with our build at 1.10. We're rebuilding with 1.12 as well to see what happens.

**Comment by GrimTheReaper** [comment]
Upgrading straight to 1.12 seemed to resolve the issues, Btw the 1.10 we we're using was the one [here](https://storage.googleapis.com/golang/go1.10.windows-amd64.zip). I'm not entirely sure what the minor version is, but when looking through the source I don't see StringWriter.

**Comment by achille-roussel** [comment]
Yeah, `io.StringWriter` was introduced with Go 1.12, we made a few _breaking_ changes recently which is why we moved from 0.2.x to 0.3.x.

Happy to reconsider some of these decisions if it's getting in your way.

**Comment by ldrrp** [comment]
@GrimTheReaper im glad to hear that fixed it, Im stick waiting for red tape office politics for 1.12. I asked for admin rights a long while ago and got a slap on the wrist lol

**Comment by GrimTheReaper** [comment]
@ldrrp glhf. I don't envy your red tape.

**Comment by ldrrp** [comment]
Tested it works then got fired :P Guess ill be asking my next interview about system admin rights.
