### ISSUE TITLE
Performance degradation with MaxMessageBytes

### ISSUE THREAD

**Issue by sagarkrkv** [segmentio/kafka-go#328]
**Describe the bug**
Our application produces a lot of messages in Async mode. Since we are in control of the creation of these messages, we don't need the ability to set MaxMessageBytes. But we are paying the performance penalty for this feature.

**v0.2.4** 
<img width="1537" alt="Screen Shot 2019-07-31 at 9 44 38 PM" src="https://user-images.githubusercontent.com/7545781/62262010-d6d57080-b3dc-11e9-918f-0a0cd66004d8.png">

I noticed we don't need to create a channel when producing messages in async mode, so I created a PR to fix that https://github.com/segmentio/kafka-go/pull/290.

So I expected v0.2.5 to perform better than the previous version, as this unnecessary allocation was removed. But I was surprised to see a new expensive function running, especially since we didn't change any config to enable this feature.

**v0.2.5**
<img width="1537" alt="Screen Shot 2019-07-31 at 9 44 18 PM" src="https://user-images.githubusercontent.com/7545781/62262011-d76e0700-b3dc-11e9-98d8-4a74355b0320.png">

**Kafka Version**
- N.A -

**To Reproduce**
This was found during benchmark testing of our application. If needed I can probably write a simple benchmark to show this.

**Expected behavior**
Users who don't set `MaxMessageBytes` shouldn't pay the cost for it.

**Additional context**
Maybe we can look into reducing the cost of calculating the message size.

cc @ShaneSaww @achille-roussel @stevevls

**Comment by achille-roussel** [comment]
@sagarkrkv thanks for reporting! I'll look into this shortly.

Other changes have landed between 0.2.4 and 0.2.5, and since we've also released 0.3. Having some simple example to highlight the problem would be very helpful to track down which commit introduced the regression.

**Comment by sagarkrkv** [comment]
@achille-roussel I believe this was caused by https://github.com/segmentio/kafka-go/pull/208. I created a PR to fix this issue, PTAL.

**Comment by sagarkrkv** [comment]
I think https://github.com/segmentio/kafka-go/pull/318 has reduced this problem to a large extent. I created #329 based on what I've observed in 0.2.5, there's still some slight performance benefit with my new PR. 

I'm totally willing to abandon the PR if you think a small performance benefit is not enough to justify the new function.

Cheers.

**Comment by achille-roussel** [comment]
Improvements are always welcome!

**Comment by ShaneSaww** [comment]
imo you should always be setting some sort of `MaxMessageBytes` aka `max.request.size` 
As without it you could end up sending messages to Kafka that don't fit and will be dropped. 
FWIW I don't think you can disable the`max.request.size`  in the java client and I think we should follow that pattern. 

>Maybe we can look into reducing the cost of calculating the message size. 

I think this is the best route and looking at #329  it should help.

**Comment by sagarkrkv** [comment]
Fixed by #329
