### ISSUE TITLE
reader: exposing first and last offset constants

### ISSUE THREAD

**Issue by tolitius** [segmentio/kafka-go#33]
Our apps read `auto-offset-reset` from config (i.e. Consul) which comes in as `latest` or `earliest`: i.e. to mimic an official Kafka config.

I could create a connection object and do `ReadFirstOffset()` / `ReadLastOffset()` on it to later set this offset on a `Reader`, but it is simpler just to pass `-2` or `-1` to `Reader.SetOffset()` to communicate startWithLast / startWithFirst offset.

`-1` and `-2` are of course leaky and "bad magic" from the Kafka protocol, and it'd be great to use the same constants that `Reader` uses: https://github.com/segmentio/kafka-go/blob/d5ac6b5abc400441878b92d9721d22b94764bf99/reader.go#L15-L18

Hence I thought it'd be useful to open them for external visibility. What do you think?

**Comment by achille-roussel** [comment]
This sounds fine to me, feel free to send a PR for this 👍

**Comment by achille-roussel** [comment]
This was added in https://github.com/segmentio/kafka-go/commit/f2ddea9b0584b523b0ef4828d4903e856c5c6a5c
