### ISSUE TITLE
Reader is initialized with FirstOffset when using Group ID but reader.Offset() returns LastOffset

### ISSUE THREAD

**Issue by harshvladha** [segmentio/kafka-go#333]
**Describe the bug**
- When `Reader` is initialized with `ReaderConfig`  (from `NewReader(readerConfig)` ) then Offset is Set to `FirstOffset` https://github.com/segmentio/kafka-go/blob/46aa607838f84ad3512d7d2729bd59617b322688/reader.go#L1258
- When `ReadMessage` or `FetchMessage` is called it uses `reader.offset` to start consuming message, so it is using `FirstOffset` instead of `LastOffset` https://github.com/segmentio/kafka-go/blob/46aa607838f84ad3512d7d2729bd59617b322688/reader.go#L1345
- but `reader.Offset()`  returns `LastOffset` see below code extract from library:

```go

const (
	LastOffset  int64 = -1 // The most recent offset available for a partition.
	FirstOffset       = -2 // The least recent offset available for a partition.
)

func (r *Reader) Offset() int64 {
	if r.useConsumerGroup() {
		return -1
	}

	r.mutex.Lock()
	offset := r.offset
	r.mutex.Unlock()
	r.withLogger(func(log *log.Logger) {
		log.Printf("looking up offset of kafka reader for partition %d of %s: %d", r.config.Partition, r.config.Topic, offset)
	})
	return offset
}
```

**Kafka Version**
1.1.1

**To Reproduce**
Because of this whenever I am starting new consumer group (with new consumer group id) I can see that it is reading message from `FirstOffset` available in kafka for that given topic. 

**Expected behavior**
New kafka consumer (with new group id) should be consuming messages from last offset  (as `r.Offset()` returns) and when committed first time and app crashes it should use `FirstOffset` after restart (i.e., Offset available after last commit) 

**Additional context**
- I might be confused a bit about `FirstOffset` and `LastOffset` name
- I think https://github.com/segmentio/kafka-go/pull/121/files has introduced this bug

**Comment by harshvladha** [comment]
Version of `kafka-go`
github.com/segmentio/kafka-go v0.3.0

**Comment by stevevls** [comment]
Greetings, and thank you for the report.  Fortunately, everything looks to be working as expected.  On the docs for the `Offset` func, you'll find that it returns `-1` when consumer groups are in use:

```
// Offset returns the current absolute offset of the reader, or -1
// if r is backed by a consumer group.
func (r *Reader) Offset() int64 {
```

This `-1` is a sentinel value and is not intended to have meaning.  The fact that it is equal to `FirstOffset` is just coincidence.

Which leaves the question of why we don't return an offset when using consumer groups...  When using a `Reader` _without_ consumer groups, the `ReaderConfig` specifies a single partition.  As the `Reader` advances, it tracks the offset within that partition and makes it available via the `Offset()` func.  In the consumer groups case, though, the `Reader` is probably reading from _many_ partitions, so there is no single offset it could report.

Hope that helps!

**Comment by harshvladha** [comment]
Thanks. 
It was quite confusing, I knew that reporting Offset is not possible because of Partition that's why I thought `-1` (`LastOffset`) is returned.
