### ISSUE TITLE
how do guarantees messages were written to kafka?

### ISSUE THREAD

**Issue by boer0924** [segmentio/kafka-go#342]
### Reference
https://godoc.org/github.com/segmentio/kafka-go#Writer.WriteMessages
https://github.com/segmentio/kafka-go#explicit-commits

*Note that in this case there are no guarantees made on whether messages were written to kafka.*

### Q
how do guarantees messages were written to kafka?
&
explicit commits `r.CommitMessages(ctx, m)` can guarantees offsets commited?

**Comment by achille-roussel** [comment]
Hello @boer0924.

`CommitMessages` is a reader method, it is not involved in the write path.

The `WriteMessages` method states
> Unless the writer was configured to write messages asynchronously, the method blocks until all messages have been written, or until the maximum number of attempts was reached.
Another way to phrase it is, unless you are configuring the writer to work asynchronously, messages are guaranteed to be written to Kafka if the method call returns no errors.

Let me know if you need anything else to be clarified.
