### ISSUE TITLE
How can I decouple consumption from processing?

### ISSUE THREAD

**Issue by nitin302** [segmentio/kafka-go#344]
The Kafka Consumer Java Doc suggests a way to de-couple consumers from the actual processing. 

https://kafka.apache.org/23/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html

> 2. Decouple Consumption and Processing
> Another alternative is to have one or more consumer threads that do all data consumption and hands off ConsumerRecords instances to a blocking queue consumed by a pool of processor threads that actually handle the record processing. This option likewise has pros and cons:
> PRO: This option allows independently scaling the number of consumers and processors. This makes it possible to have a single consumer that feeds many processor threads, avoiding any limitation on partitions.
> CON: Guaranteeing order across the processors requires particular care as the threads will execute independently an earlier chunk of data may actually be processed after a later chunk of data just due to the luck of thread execution timing. For processing that has no ordering requirements this is not a problem.
> CON: Manually committing the position becomes harder as it requires that all threads co-ordinate to ensure that processing is complete for that partition.
> There are many possible variations on this approach. For example each processor thread can have its own queue, and the consumer threads can hash into these queues using the TopicPartition to ensure in-order consumption and simplify commit.

I'm trying to implement a similar approach, where-in, I can manually define the number consumers I want to spawn per application process (since, we are always limited by number of partitions, i think its a good to have a static value per process), then async hand off messages to a processing pool. Offset commits are also then async processed using a queue per partition.

for example : https://gist.github.com/RichardHightower/041c2c546e513a3481289ca16fe11cd4

What is a way I can do this with kafka-go?

**Comment by achille-roussel** [comment]
Hello @nitin302, thanks for reaching out!

If you're using Consumer Groups (which I'd assume you are since you mentioned committing offsets), then most of the consumer logic you describe is managed by the [`kafka.Reader`](https://godoc.org/github.com/segmentio/kafka-go#Reader) type in kafka-go. You would read new messages with [`kafka.(*Reader).FetchMessage`](https://godoc.org/github.com/segmentio/kafka-go#Reader.FetchMessage) and commit them asynchronously after processing with [`kafka.(*Reader).CommitMessages`](https://godoc.org/github.com/segmentio/kafka-go#Reader.CommitMessages).

If you need more granular control over the consumer, you may look at the API exposed by the [`kafka.ConsumerGroup`](https://godoc.org/github.com/segmentio/kafka-go#ConsumerGroup) type, which exposes lower-level semantics of consumer groups.

**Comment by nitin302** [comment]
Looking at the example here : https://github.com/segmentio/kafka-go/blob/master/example_consumergroup_test.go, i see no go routine spawned per topic-parition? Does it needed to be done manually?

**Comment by nitin302** [comment]
I found this for every generation.Start https://github.com/segmentio/kafka-go/blob/11670d5e1801c6e535ce810e57b04dfbd0245e49/consumergroup.go#L320 but does this also mean per topic-partition?

**Comment by nitin302** [comment]
Also, when committing, we need to commit current offset which is processed + 1. So, on failure it will start processing from an unprocessed offset.
https://github.com/segmentio/kafka-go/blob/master/example_consumergroup_test.go#L49

From Kafka Documentation:

> Note: The committed offset should always be the offset of the next message that your application will read. Thus, when calling commitSync(offsets) you should add one to the offset of the last message processed.

**Comment by nitin302** [comment]
@achille-roussel Below is my test-code to consume multiple topics simultaneously, But I see only the last topic being consumed, and that too, there are duplicate processing. Not sure what the issue is. Do I have to manually spawn a go-routine for every new topic?


`package main

import (
	"context"
	"fmt"
	"os"
	"time"

	"github.com/segmentio/kafka-go"
)

func ExampleConsumerGroupParallelReaders() {

	topics := []string{"my-topic", "my-topic2", "my-topic3", "my-topic4"}
	clientId := "my-consumer"

	group, err := kafka.NewConsumerGroup(kafka.ConsumerGroupConfig{
		ID:      "my-group",
		Brokers: []string{"localhost:9092"},
		Topics:  topics,
		Dialer: &kafka.Dialer{
			Timeout:   10 * time.Second,
			DualStack: true,
			ClientID:  clientId,
		},
	})
	if err != nil {
		fmt.Printf("error creating consumer group: %+v\n", err)
		os.Exit(1)
	}
	defer group.Close()

	for {
		gen, err := group.Next(context.TODO())
		if err != nil {
			break
		}

		for i, _ := range topics {

			assignments := gen.Assignments[topics[i]]
			for _, assignment := range assignments {
				partition, offset := assignment.ID, assignment.Offset
				gen.Start(func(ctx context.Context) {
					// create reader for this partition.
					reader := kafka.NewReader(kafka.ReaderConfig{
						Brokers:   []string{"127.0.0.1:9092"},
						Topic:     topics[i],
						Partition: partition,
						MaxWait:   1 * time.Second,
					})
					defer reader.Close()

					// seek to the last committed offset for this partition.
					err = reader.SetOffset(offset)
					if err != nil {
						fmt.Print(err)
					}
					for {

						msg, err := reader.ReadMessage(ctx)
						switch err {
						case kafka.ErrGenerationEnded:
							fmt.Printf("gen ended")
							return
						case nil:
							fmt.Printf("received message %s/%d/%d : %s\n", msg.Topic, msg.Partition, msg.Offset, string(msg.Value))
							err = gen.CommitOffsets(map[string]map[int]int64{msg.Topic: {msg.Partition: msg.Offset + 1}})
							if err != nil {
								fmt.Print(err)
							}
						default:
							fmt.Printf("error reading message: %+v\n", err)
						}
					}
				})
			}
		}
	}
}

func main() {
	ExampleConsumerGroupParallelReaders()
}
`

**Comment by nitin302** [comment]
Turns out to be a bug with how Go uses local variables Vs global variables usable within go-routines. After that is fixed it is working as expected.

**Comment by stevevls** [comment]
Ah yes...every Go programmer has been bitten by that one countless times.  Glad to hear that everything is working as expected now!
