### ISSUE TITLE
broken pipe connections using WriteMessages

### ISSUE THREAD

**Issue by joaoferrao** [segmentio/kafka-go#345]
**Describe the bug**
Sporadic (several times a day) producer related `broken pipe` errors. There are multiple topics, all of them with 9 partitions each. 3x brokers are also running in the cluster.
When the microservice is spun up, a Writer is instantiated and is reused for the lifecycle of that pod for each message that needs to be sent to kafka. Each microservice is typically only producing to one or two topics. 

Example error is the one that follows. 

```
error writing messages to <some-topic> (partition 3): write tcp 123.123.123.123:55555->123.123.123.123:9092: write: broken pipe
```

The errors seem to originate from the the below method on `write.go`.

```go
	t0 := time.Now()
	conn.SetWriteDeadline(time.Now().Add(w.writeTimeout))
	if _, err = conn.WriteCompressedMessages(w.codec, batch...); err != nil {
		w.stats.errors.observe(1)
		w.withErrorLogger(func(logger *log.Logger) {
			logger.Printf("error writing messages to %s (partition %d): %s", w.topic, w.partition, err)
		})
		for i, res := range resch {
			res <- &writerError{msg: batch[i], err: err}
		}
	} else {
		for _, m := range batch {
			w.stats.messages.observe(1)
			w.stats.bytes.observe(int64(len(m.Key) + len(m.Value)))
		}
		for _, res := range resch {
			res <- nil
		}
	}
```

**Kafka Version**
2.2.1 running on kubernetes (bitnami's Helm Chart if it helps)

**To Reproduce**
The code simply uses your kafka.WriteMessages method while looping through a channel:

```go
for record := someChan {
  if err := writer.WriteMessages(ctx, record); err != nil {
   log.Info(err)
}
}
```

Configuration of `dialer` and `writer` are:

	dialer := &kafka.Dialer{
		Timeout:   time.Second * 5,
		DualStack: true,
	}

	config := kafka.WriterConfig{
		Brokers:          "<some-broker-list>",
		Topic:            "<some-topic>",
		Dialer:           dialer,
		Balancer:         &kafka.Hash{},
		QueueCapacity:    100,
		BatchSize: 1,
		MaxAttempts: 20,
		RequiredAcks: -1,
		Async:        false,
	}

**Expected behavior**
Can you propose a way to deal with this error? 
Shouldn't the producer retry to redial and resend the message?

**Additional context**
I have set MaxAttempts at 20, but the stats printed right after the broken pipe are as follow. It's weird for showing 2 writes but 1 message as well as 1 Error.
The error happens even if not using any auth for connection or encryption.

```
Writer stats: {Dials:1 Writes:2 Messages:1 Bytes:722 Rebalances:4 Errors:1 DialTime:{Avg:8.771171ms Min:8.771171ms Max:8.771171ms} WriteTime:{Avg:111.469004ms Min:111.469004ms Max:111.469004ms} WaitTime:{Avg:1.22381ms Min:362.503µs Max:2.085117ms} Retries:{Avg:1 Min:1 Max:1} BatchSize:{Avg:1 Min:1 Max:1} BatchBytes:{Avg:744 Min:744 Max:744} MaxAttempts:20 MaxBatchSize:1 BatchTimeout:1s ReadTimeout:10s WriteTimeout:10s RebalanceInterval:15s RequiredAcks:1 Async:false QueueLength:0 QueueCapacity:100 ClientID: Topic:<some-topic>}
```

**Comment by achille-roussel** [comment]
Thanks for reporting.

Would you be able to share what the throughput of your producers are? (rate of messages sent, size of messages)

**Comment by joaoferrao** [comment]
@achille-roussel the messages are relatively small (less than 10k) and this happens even when sending messages just as the one on the stats I shared.

Have idea on how I would be able to handle this error? Or force a resend?

**Comment by joaoferrao** [comment]
As an update, I'm starting to think that after all the producer does eventually deliver the message.

This line of code from the library prints the error AND reschedules it. As far as I saw, the WriteMessages doesn't effectively return an error, it just prints it.

```
w.withErrorLogger(func(logger *log.Logger) {
			logger.Printf("error writing messages to %s (partition %d): %s", w.topic, w.partition, err)
		})
```
However, this increments an Error in the stats, correct? Maybe the most insightful State would be to know how many messages were NOT delivered after the amount of tries established.

**Comment by sagarkrkv** [comment]
@achille-roussel We saw a similar issue on our production boxes, we have a metrics topic where we observed weird behavior, messages are successfully published for 25 mins, then we see broken pipe errors for the next 25 mins, and then the cycle continues.

Upon further investigation we found that, 

We publish one message per 5 mins, and there are 5 partitions, so the Kafka writer sends 1 message to each partition every 25mins. Under the default settings, the Kafka broker closes a connection if it doesn't receive any new message in the last 10 mins. But the Kafka writer doesn’t know that the connection has been closed, so when it tries to a second message on the same connection, it sees broken pipe errors.

So for the next 25 mins as the writer cycles through the partitions it sends messages on connections which have been closed, and on next cycle new connections are created and the messages sent on these new connections succeed, and cycle repeats.

When I looked through [Kafka documentation](https://kafka.apache.org/documentation/#producerconfigs), I found that there is a config that can solve this issue, please note that the default value is set to 9mins, which is 1 min less than broker timeout. 

`connections.max.idle.ms | Close idle connections after the number of milliseconds specified by this config. | long | 540000 |  `

I'll create a PR to add and enforce this config, I believe this'll solve the issue.

**Comment by joaoferrao** [comment]
@achille-roussel would it be possible to know when you estimate making a release that includes this fix? Highly appreciated!

**Comment by stevevls** [comment]
We just tagged a `v0.3.4` release.  Let us know if that doesn't fix the issue!
