### ISSUE TITLE
ReadMessage will not commit messages when using ConsumerGroup

### ISSUE THREAD

**Issue by chenhengqi** [segmentio/kafka-go#349]
I tried to use the feature introduced in #277 

<details><summary>code: CLICK ME</summary>
<p>

```go
package main

import (
	"context"
	"io"
	"log"

	"github.com/segmentio/kafka-go"
)

const (
	groupID = "consumer-group-test"
	topic   = "consumer-group-test"
)

var brokers = []string{
	"9.1.0.28:9092",
}

func consume(index int, reader *kafka.Reader) func(ctx context.Context) {
	return func(ctx context.Context) {
		defer reader.Close()
		for {
			select {
			case <-ctx.Done():
				log.Println(ctx.Err())
				return
			default:
				msg, err := reader.ReadMessage(ctx)
				switch err {
				case nil:
					log.Printf("index: %04d, partition: %04d, offset: %04d\n", index, msg.Partition, msg.Offset)
				case io.EOF:
					log.Println("reader has been closed")
					return
				default:
					log.Printf("error reading message: %+v\n", err)
				}
			}
		}
	}
}

func main() {
	group, err := kafka.NewConsumerGroup(kafka.ConsumerGroupConfig{
		ID:                    groupID,
		Brokers:               brokers,
		Topics:                []string{topic},
		WatchPartitionChanges: true,
	})
	if err != nil {
		panic(err)
	}
	defer group.Close()

	for {
		gen, err := group.Next(context.TODO())
		switch err {
		case nil:
			log.Println("new generation started")
		case kafka.ErrGroupClosed:
			log.Panic(err)
		default:
			log.Printf("error getting next generation failed: %+v\n", err)
			continue
		}

		assignments := gen.Assignments[topic]
		readers := make([]*kafka.Reader, len(assignments))
		for i, assignment := range assignments {
			readers[i] = kafka.NewReader(kafka.ReaderConfig{
				Brokers:   brokers,
				Topic:     topic,
				Partition: assignment.ID,
				MinBytes:  1,
				MaxBytes:  1024 * 1024,
			})
			readers[i].SetOffset(assignment.Offset)
			gen.Start(consume(i, readers[i]))
		}
	}
}
```

</p>
</details>

In the code above, if I add a `GroupID` field to the `ReaderConfig`, `NewReader` will initiate a new `ConsumerGroup` which will cause Kafka to rebalance infinitely.

If I omit the `GroupID` field, `ReadMessage` won't commit offset automatically. And there is no way to commit offset since the `CommitMessages`  not work either.

**Comment by chenhengqi** [comment]
ping @achille-roussel  @stevevls

**Comment by achille-roussel** [comment]
Hello @chenhengqi, I believe this is the expected behavior. If you use the `*kafka.ConsumerGroup` API directly you're expected to call [CommitOffsets](https://godoc.org/github.com/segmentio/kafka-go#Generation.CommitOffsets) on the `Generation` objects that you receive.

If you're looking at a more managed model, you can configure the `GroupID` on a reader in order to have the partition assignment and generations managed internally, you'll still need to call [CommitMessages](https://godoc.org/github.com/segmentio/kafka-go#Reader.CommitMessages) on the reader.

**Comment by chenhengqi** [comment]
Thanks.

> If you're looking at a more managed model, you can configure the GroupID on a reader in order to have the partition assignment and generations managed internally, you'll still need to call CommitMessages on the reader.

This works well, but I believe that the `*kafka.ConsumerGroup` API is more scalable since it can create as many goroutine as needed in every generation to handle messages.

> If you're looking at a more managed model, you can configure the GroupID on a reader in order to have the partition assignment and generations managed internally, you'll still need to call CommitMessages on the reader.

`CommitMessages` are not required if I use [ReadMessage](https://godoc.org/github.com/segmentio/kafka-go#Reader.ReadMessage), right ?

**Comment by achille-roussel** [comment]
> CommitMessages are not required if I use ReadMessage, right ?

Correct! Sorry for the confusion, either you use ReadMessage and there's no need to Commit (although you're prone to data loss if the message processing fails but the commit succeeds, it depends on the use case whether that's OK or not), otherwise you use FetchMessage/CommitMessages 👍
