### ISSUE TITLE
the compression code is invalid or its codec has not been imported

### ISSUE THREAD

**Issue by zhs077** [segmentio/kafka-go#352]
**Describe the bug**
the compression code is invalid or its codec has not been imported

**Kafka Version**
0.11

**To Reproduce**
```golang
package main

import (
        "fmt"
        "context"
        "github.com/segmentio/kafka-go"
        _ "github.com/segmentio/kafka-go/snappy"
        "log"
        "strings"
)

func getKafkaReader(kafkaURL, topic, groupID string) *kafka.Reader {
        brokers := strings.Split(kafkaURL, ",")
        return kafka.NewReader(kafka.ReaderConfig{
                Brokers:  brokers,
                GroupID:  groupID,
                Topic:    topic,
                MinBytes: 10e3, // 10KB
                MaxBytes: 10e6, // 10MB
        })
}

func main() {
        kafkaURL := "10.17.135.100:58080,10.17.135.101:58080,10.17.135.102:58080,10.17.135.103:58080,10.17.135.104:58080,10.17.135.105:58080"
        topic := "qlog.dmp"
        groupID := "mygroup"

        reader := getKafkaReader(kafkaURL, topic, groupID)
        defer reader.Close()
        fmt.Println("start consuming ... !!")
        for {
                m, err := reader.ReadMessage(context.Background())
                if err != nil {
                        log.Fatalln(err)
                }
                fmt.Printf("message at topic:%v partition:%v offset:%v  %s = %s\n", m.Topic, m.Partition, m.Offset, string(m.Key), string(m.Value))
        }
}
```

**Comment by stevevls** [comment]
Hi @zhs077.  Sounds to like you have messages in that topic that have been compressed with another codec.  Have you tried importing the other compression codecs?

See https://github.com/segmentio/kafka-go#compression

**Comment by zhs077** [comment]
> Hi @zhs077. Sounds to like you have messages in that topic that have been compressed with another codec. Have you tried importing the other compression codecs?
> 
> See https://github.com/segmentio/kafka-go#compression

the kafka comperssion is snappy,other compression codecs cannot used

**Comment by VertexC** [comment]
Got the same issue here. Have you solved it? @zhs077

**Comment by VertexC** [comment]
> Got the same issue here. Have you solved it? @zhs077

My issue might be the incompatible version between kafka and kafka-go

**Comment by dominicbarnes** [comment]
I'm closing this ticket because of a lack of response here. It seems pretty likely this can be resolved by importing the compression package that corresponds to the strategy used to encode the messages.

If they should all be using snappy, then it would be really helpful to include the raw message that causes this error to occur, otherwise we cannot troubleshoot further.
