### ISSUE TITLE
How  many connections (with same topic name)can be created and write concurrently 

### ISSUE THREAD

**Issue by arjunvofficial** [segmentio/kafka-go#356]
is there any issue if multiple writers created with same topic name(individual goroutines for each writers) and writing to kafka using them concurrently ?

**Comment by dominicbarnes** [comment]
As far as I know, there shouldn't be any trouble doing this, as the Kafka broker(s) should maintain a consistent state in regards to topic metadata. That being said, you can configure topics to be created automatically by the brokers as well, and also I have no reason to believe the `Writer` would not be able to handle that.

If you run into any specific issues, feel free to create an issue with a way to reproduce so we can address it.
