### ISSUE TITLE
Question: Do you support avro?

### ISSUE THREAD

**Issue by manidlou** [segmentio/kafka-go#366]
Do you guys support avro key and value serialization/deserialization?

**Comment by achille-roussel** [comment]
Hello @manidlou,

kafka-go only provides APIs to build Kafka clients, but the library makes no assumption on the format that message keys and values are serialized in, these are simply treated as opaque byte sequences.

So "Yes" this package supports avro and any other serialization format that the client wishes to use, but it doesn't provide any mechanism for automatically encoding or decoding the content of message keys and values.

Let me know if that helps!

**Comment by manidlou** [comment]
Cool thank you for your response!
