### ISSUE TITLE
Processing pre compressed (deflated or gzip) messages 

### ISSUE THREAD

**Issue by mpiivonen** [segmentio/kafka-go#370]
**Describe the bug**
Consumer is unable to notice or handle messages which has been deflated or gzipped before sending to kafka

**Kafka Version**
2.1.0

**To Reproduce**
compress message by using zlib deflate or gzip, send message.
As a producer I have used nodejs with https://github.com/Blizzard/node-rdkafka and there hasn't been any compatibility issues if the messages has been plain text before buffering and sending to kafka.

**Expected behavior**
Consumer would recognize a new message and would at least fetch the message but this is not the case. Producer does not recognize new message. 

**Additional context**
If I use kafka's consumer from bash the compressed message will go to the desired topic and I've managed to retrieve and process the compressed message by using https://github.com/confluentinc/confluent-kafka-go on the go side but I would rather not refactor many microservices to use the other library if that can be avoided.

**Comment by tetafro** [comment]
Maybe you just missed import?
```go
import _ "github.com/segmentio/kafka-go/gzip"
```

**Comment by achille-roussel** [comment]
Hello @mpiivonen! Was @tetafro's answer helpful to solve your issue?
