### ISSUE TITLE
Offset vs highWaterMark missmatch for kafka enabled Azure Eventhubs

### ISSUE THREAD

**Issue by jonnylangefeld** [segmentio/kafka-go#384]
Thanks for a great library!

**Describe the bug**
We are using kafka enabled Azure Eventhubs. We can consume messages with the following `Reader` configuration:
```go
    reader := kafka.NewReader(kafka.ReaderConfig{
		Brokers: []string{fmt.Sprintf("%s:9093", host)},
		Dialer: &kafka.Dialer{
			SASLMechanism: plain.Mechanism{
				Username: "$ConnectionString",
				Password: connectionString,
			},
			TLS: &tls.Config{},
		},
		GroupID:        consumerGroup,
		Topic:          topic,
		CommitInterval: time.Second * time.Duration(commitInterval),
		Logger:         log.Logger{},
		ErrorLogger:    log.ErrorLogger{},
	})
```

In general we can read messages and especially with high loads there are no issues. However on queues with less messages, the error logger becomes quite verbose and logs `unexpected EOF` errors as well as `multiple Read calls return no data or error` errors.

On debugging with an empty Eventhub, with only one partition, I found out that if the partition is all caught up (no new messages on the Eventhub) we always get the `unexpected EOF` error. Then if another message is sent to the queue, we evolve to the `multiple Read calls return no data or error` error. Then on the second message, both of the messages are consumed and handled and then we're back to an all caught up queue.

I found, that the following line dosen't eval to `true` if the queue is all caught up (or on a new empty queue).

https://github.com/segmentio/kafka-go/blob/3b34bbf9eff0c49b524e115eed40452014e9c2da/conn.go#L859-L863

`highWaterMark` is always one behind `offset` while the queue is all caught up:
![Screen Shot 2019-12-04 at 5 01 56 PM](https://user-images.githubusercontent.com/18717376/70195330-3b217d00-16ba-11ea-9da2-e7b6390dd74d.png)

hence we enter the `else`, expecting a new message, however there is none, so we run into the unexpected EOF error.

Does anyone else experience this? Are we configuring something wrong?

**Kafka Version**
> 1.0.0

**To Reproduce**
Create an Azure Eventhubs, consume it with the reader and send messages one by one, for instance with 
```
curl -X POST \
  https://[Namespace].servicebus.windows.net/[Eventhubs name]/messages \
  -H 'authorization: [your shared access signature]' \
  -d '{"test":"test"}'
```

Reader + loop:
```go
reader := kafka.NewReader(kafka.ReaderConfig{
	Brokers: []string{fmt.Sprintf("%s:9093", host)},
	Dialer: &kafka.Dialer{
		SASLMechanism: plain.Mechanism{
			Username: "$ConnectionString",
			Password: connectionString,
		},
		TLS: &tls.Config{},
	},
	GroupID:        consumerGroup,
	Topic:          topic,
	CommitInterval: time.Second * time.Duration(commitInterval),
	Logger:         log.Logger{},
	ErrorLogger:    log.ErrorLogger{},
})

for {
    msg, err := reader.ReadMessage(context.Background())
    fmt.Printf("%s\n", string(msg.Value))
}
```

**Expected behavior**
Message should be read as soon as it's there and no errors should be there.

**Additional context**

**Comment by o1egl** [comment]
We get the same error

**Comment by achille-roussel** [comment]
Thanks for reporting!

Have you observed this behavior outside of Azure Eventhubs?

**Comment by lmtyler** [comment]
Getting the same error

**Comment by lmtyler** [comment]
We have proved this is a bug in MS EventHub Kafka exposed endpoint.

MS is currently rolling out a fix for this...

This is from an email with MS Customer Engineer
`We’ve made a change of addressing the difference in watermark property between Kafka Broker and Event Hubs and we’re verifying the change. The change is with the Event Hub Broker.`

`The Event Hub team deployed the change in production regarding the issue you were observing. Please let us know if you are still seeing this behavior.`

**Comment by stevevls** [comment]
Thanks for following up @lmtyler !  Glad to know we can close this one out. 😄
