### ISSUE TITLE
How to check the connection status to ensure it's alive?

### ISSUE THREAD

**Issue by icamys** [segmentio/kafka-go#389]
First of all I would like to thank you for sharing this library. 

I'm writing a service that uses this library to connect to kafka. Now I want to expose a url to check the readiness and liveness of the service. In order to check the liveness I have to check the status of the connections to the infrastructure services used by the service instance.

The question is: how to check the connection status to ensure it's alive?

**Comment by achille-roussel** [comment]
The Kafka protocol has no ping  or health check mechanism, so there's no _native_ way to do this.

I you're using a [`kafka.Conn`](https://godoc.org/github.com/segmentio/kafka-go#Conn) you could call a method that reads metadata from the Kafka server periodically to test if it's still connected (for example calling [`kafka.(*Conn).Brokers`](https://godoc.org/github.com/segmentio/kafka-go#Conn.Brokers)).

Let me know if that helps.

**Comment by icamys** [comment]
@achille-roussel Thanks for this tip. I'll try this after 8th January and leave some feedback.

**Comment by achille-roussel** [comment]
This issue has been stale for a while. I'll go ahead and close it but feel free to reopen if this is still a problem.
