### ISSUE TITLE
SSL Encryption 

### ISSUE THREAD

**Issue by dlsgusrn7577** [segmentio/kafka-go#399]
Where can I specify sslOptoins for SSL Encryption such as 
1. ssl.truststore.location, 2. ssl.truststore.password, and 3. ssl.endpoint.identification.algorithm

**Comment by kernle32dll** [comment]
kafka-go does not implement trust- or keystores. These are java constructs to bundle certificates and keys. As such, both 1) and 2) are not applicable here.

That being said, for enabling SSL encryption (not authentication afaik), you must set the `Dialer` property of your `kafka.WriterConfig` or `kafka.ReaderConfig` respectively. Depending on your setup, `&tls.Config{}` might suffice, if your OS certificates (especially the CA, if using self-signed certificates) are properly set. If not, you need to fill the tls config appropriately yourself (i.e. give it the correct x509 certificates).

**Comment by Pryz** [comment]
Hi there,

As @kernle32dll  said, if you need your connection to be encrypted you can use the TLS configuration from the Dialer. See https://pkg.go.dev/github.com/segmentio/kafka-go@v0.3.5?tab=doc#Dialer.

We also do support authentication via SASL (PLAIN or SCRAM). See: https://pkg.go.dev/github.com/segmentio/kafka-go/sasl?tab=doc. 

Note that we also have two opened issues to add GSSAPI (https://github.com/segmentio/kafka-go/issues/237) and OAUTHBEARER (https://github.com/segmentio/kafka-go/issues/238) :)

I will go ahead and close this issue. Please feel free to reopen if you need more information.
