### ISSUE TITLE
Default batch size is confusing

### ISSUE THREAD

**Issue by dtsellos03** [segmentio/kafka-go#400]
**Describe the solution you'd like**
A default batch size of 100 for the Writer means nothing will be sent in the example given in the README.md
```
// make a writer that produces to topic-A, using the least-bytes distribution
w := kafka.NewWriter(kafka.WriterConfig{
	Brokers: []string{"localhost:9092"},
	Topic:   "topic-A",
	Balancer: &kafka.LeastBytes{},
})

w.WriteMessages(context.Background(),
	kafka.Message{
		Key:   []byte("Key-A"),
		Value: []byte("Hello World!"),
	},
	kafka.Message{
		Key:   []byte("Key-B"),
		Value: []byte("One!"),
	},
	kafka.Message{
		Key:   []byte("Key-C"),
		Value: []byte("Two!"),
	},
)

w.Close()
```
This is confusing/unintuitive when using the library for the first time, or when troubleshooting broker addresses (no error until the Writer actually attempts to send a message)

My suggestion would be to update the example Writer to explicitly pass in a BatchSize of 100 and a comment clarifying that the Writer won't write until 100 messages are reached. People usually often copy from the example code and may not change it later, so I don't think having a Batchsize of 1 would be good to have in the README.md

Happy to submit a PR for this.

**Comment by dzeban** [comment]
> A default batch size of 100 for the Writer means nothing will be sent

No, it will be sent because batch is flushed every [`WriterConfig.BatchTimeout` interval](https://godoc.org/github.com/segmentio/kafka-go#WriterConfig):

```
...
    // Time limit on how often incomplete message batches will be flushed to
    // kafka.
    //
    // The default is to flush at least every second.
    BatchTimeout time.Duration
...
```

**Comment by dtsellos03** [comment]
Thanks for clarifying. I'll close this issue.
