### ISSUE TITLE
Error = [41] Not Controller when creating topic

### ISSUE THREAD

**Issue by vikusku** [segmentio/kafka-go#402]
**Describe the bug**
CreateTopics randomly fails returning an error=41. 
`error = [41] Not Controller: this is not the correct controller for this cluster`

To be honest, I'm not sure if this is a bug or I'm doing something stupid. It usually fails on first attempt and succeeds on second, but sometimes it requires several retries before topic is created.

**Kafka Version**
2.4 deployed in confluent platform version 5.4.0

**To Reproduce**
Calling this CreateTopics func

```
func CreateTopics(ctx context.Context, topics ...string) (err error) {
	dialer := &kafka.Dialer{
		SASLMechanism: mech,
		DualStack:     true,
		TLS: &tls.Config{
			InsecureSkipVerify: false,
		},
	}

	conn, err := dialer.DialContext(ctx, "tcp", "confluent-bootstrap-server")
	if err != nil {
		return
	}

	var topicConfigs []kafka.TopicConfig

	for _, t := range topics {
		config := kafka.TopicConfig{
			Topic:             t,
			NumPartitions:     6,
			ReplicationFactor: 3,
		}

		topicConfigs = append(topicConfigs, config)
	}

	return conn.CreateTopics(topicConfigs...)
}
```

**Expected behavior**
Topic created, err = nil

**Comment by Pryz** [comment]
Hi @vikusku,

Your dialer address looks fancy to me. Kafka is using it's own protocol and not http. Usually we connect to kafka using something like `kafka-addr:9092`. 

I've no experience with the Confluent Platform however. If this is your issue, we may need to improve the error message or check for potential malformed URI to connect to.

**Comment by vikusku** [comment]
Hi @Pryz 

Thanks for fast reply. I'm able to send messages for existing topic using both writer and conn and confluent bootstrap server url, so at least with sending messages url is not a problem.

**Comment by vikusku** [comment]
Actually sorry, confluent doesn't use http in their endpoint. I edited original message. Confluent's bootstrap server url looks something like this
`blah-blah-blah.confluent.cloud:9092`

**Comment by Pryz** [comment]
Sounds good :)

So when you open the connection that way, you are randomly picking one of the broker in the cluster. At this point you may or may not end up on the actual Kafka controller. You will need to lookup for the controller and open a new connection to it.

See the `Controller` method : https://pkg.go.dev/github.com/segmentio/kafka-go?tab=doc#Conn.Controller.

**Comment by vikusku** [comment]
It worked. Thanks :)

**Comment by MohamedShaj** [comment]
> Sounds good :)
> 
> So when you open the connection that way, you are randomly picking one of the broker in the cluster. At this point you may or may not end up on the actual Kafka controller. You will need to lookup for the controller and open a new connection to it.
> 
> See the `Controller` method : https://pkg.go.dev/github.com/segmentio/kafka-go?tab=doc#Conn.Controller.

How to do this in Python3 any reference ?
