### ISSUE TITLE
Best practices with worker pool and consumer group

### ISSUE THREAD

**Issue by vtolstov** [segmentio/kafka-go#404]
I have app that uses worker pool with 50 workers. For this workers I'm pull messages from kafka using sarama client with consumer group.
My issue now - when I'm not ack some message in worker, kafka it not redelivery.
As i understand this because autocommit. But after reading docs they sad that if I'm commit message that goes after not commited, kafka thinks that both messages acked 
Does this right?
What you recommend to worker pool and consumer group? Preferable to use one connection to kafka from app, and not for each worker. Does it possible?

**Comment by jpelletier-dad** [comment]
Did you see this example? [example_consumergroup_test.go] 
I based my implementations off this and commits don't occur unless I call 
```
topic := "my-topic"
partition := 1
offset := 52131
Generation.CommitOffsets(map[string]map[int]int64{topic: {partition: offset}})
```

**Comment by vtolstov** [comment]
thanks, if i have 3 partitions and use highlevel reader from topic with group.
does messages from 3 partitions goes to buffered channel with len equal to partition count?
as messages from each consumer independent of each others.

**Comment by jpelletier-dad** [comment]
I create a reader per topic-partition. `gen.Start(func(ctx context.Context) {...` runs the handler function in a go-routine. Each reader consumes synchronously (`ReadMessage()` is blocking)

**Comment by vtolstov** [comment]
I saw this, but i'm interested in highlevel interface, does it possible with it?
As i saw in my tests, partition count does not change active database connection count, so i'm always work with single worker (messages goes to unbuffered channel)

**Comment by echotrue** [comment]
mark

**Comment by vtolstov** [comment]
thanks
