### ISSUE TITLE
Static Membership of consumer group

### ISSUE THREAD

**Issue by paritadhandha** [segmentio/kafka-go#411]
**Describe the solution you'd like**
Is there any plan or timeline to support apache kafka version 2.3 or higher? 
Specifically the static membership feature to reduce rebalancing of consumer group.

**Supporting documentation**
Reference: https://cwiki.apache.org/confluence/display/KAFKA/KIP-345%3A+Introduce+static+membership+protocol+to+reduce+consumer+rebalances

**Comment by achille-roussel** [comment]
Hello @paritadhandha, thanks for asking!

We are going to track this feature request in https://github.com/segmentio/kafka-go/issues/493, feel free to chime in there if you wish to 👍
