### ISSUE TITLE
Support for KIP-392: Allow consumers to fetch from closest replica

### ISSUE THREAD

**Issue by Sk8rMarc** [segmentio/kafka-go#415]
We're looking to reduce data transfer costs in AWS, especially when using Kafka HA clusters.  AWS MSK solves part of the problem, not charging for replication data transfer, but there's still a lot of juggling that has to be done to avoid cross-az data transfer costs between consumers and the cluster.  AWS MSK currently supports Kafka version 2.3.1.  Hopefully soon, AWS MSK will support Kafka version 2.4.0 which adds the ability for consumers to fetch from their closest replica.  If you're feeding Kafka high volumes of data, this feature results in a huge cost savings, not to mention the simplification of consumer deployment.

Kafka release 2.4.0 added support for KIP-392 in Task KAFKA-8443
- [Release Notes - Kafka - Version 2.4.0](https://downloads.apache.org/kafka/2.4.0/RELEASE_NOTES.html)
- [KAFKA-8443 - Allow broker to select a preferred read replica for consumer](https://issues.apache.org/jira/browse/KAFKA-8443)
- [KIP-392: Allow consumers to fetch from closest replica](https://cwiki.apache.org/confluence/display/KAFKA/KIP-392%3A+Allow+consumers+to+fetch+from+closest+replica)

**Comment by Sk8rMarc** [comment]
So now this will be a problem for us as we are active in AWS with MSK, and they've announced support for Kafka 2.4.1
https://aws.amazon.com/about-aws/whats-new/2020/04/amazon-msk-adds-support-for-apache-kafka-version-2-4-1/

**Comment by stevevls** [comment]
Hi @Sk8rMarc.  We currently don't have the bandwidth internally to work on that feature, but PRs are always welcome. 😄 

In the meantime, if you're using consumer groups, you may want to have a look at our `RackAffinityGroupBalancer`: https://github.com/segmentio/kafka-go/blob/e0af1cfbb8dd463571748e350262e2c81754bb73/groupbalancer.go#L153

We've been using it in production for the last year and a half and generally keep 90%+ of traffic between consumer and broker in-zone.  We have some [example code](https://github.com/segmentio/kafka-go/blob/e0af1cfbb8dd463571748e350262e2c81754bb73/example_groupbalancer_test.go#L37) for how one might use this in AWS.

**Comment by Sk8rMarc** [comment]
Hi @stevevls!  Thank you for pointing this out.  Our use-case is not your normal Kafka use-case.  For lack of a better solution, already built, Kafka provides us with two features we need: retention, and multiple consumers.  We are moving edge compute into a central location in the cloud.  We are(/will be) processing transcoded single program transport streams (SPTS);  several thousands of such feeds.  Each feed will have several consumers, each having their own processing chain.  We therefore will have single partition topics for each feed, and the ability to read from an insync replica in our own rack(AZ) becomes paramount to save the X hit in cross-az traffic.

**Comment by kd7lxl** [comment]
Work continues on KIP-392 in #984.
