### ISSUE TITLE
remove message

### ISSUE THREAD

**Issue by aminNazarii** [segmentio/kafka-go#418]
How can i remove a specefic message after read??

**Comment by baconalot** [comment]
No, that is not the way kafka works. It ingests messages, that you then can consume. No updates or deletes are allowed. So you need to architecture your way around that or use another tool than kafka.

**Comment by Pryz** [comment]
Like @baconalot said, you can't delete messages in Kafka topics.

**Comment by Megatenogoukui** [comment]
If we cant delete message or update message how can we know that this message has been consumed and we wont need to consume it again
