### ISSUE TITLE
Using a consumer group and resetting offsets on errors.

### ISSUE THREAD

**Issue by jskelcy** [segmentio/kafka-go#427]
**Describe the bug**
I am filing a bug, but it reality this is more of a question that I am looking for some guidance on. I am considering using a consumer group to consume messages because the ability to commit messages back the broker seems handy across consumer restarts. My application is simple where it reads messages from a topic and then writes them to a downstream DB, however, due to the nature of my deployment it is likely that there will be regular network partitions between my consumer application and the downstream DB will be unavailable. When this happens I would like to not advance the offset of the consumer group for this partition and retry to process the message after some backoff.
I initially tried to do this by using `FetchMessage` on a `Reader` configured with the group id, and when I encountered an error from the downstream DB I would just not call `CommitMessages`, and then attempt to read again after the backoff period. However, when I did this it appeared as though the offset was still advancing, I tried to use `SetOffset` on the read, but I do not think that is compatible with consumer groups. Based on #277 it would appear that we can use `CommitOffsets` on the generation object to perhaps accomplish the goal? But it also seems like perhaps we are landing on a Kafka anti-pattern. Maybe the recommended thing to do here is to bake the retry logic into my consumer application, and if the consumer crashes during the backoff interval and a new one comes to take its place that is ok. Because the previous consumer never committed the message so the new consumer will pick up where the previous consumer left off.
In any event, looking for some guidance.

Thanks a ton and I am really enjoying this project.

**Kafka Version**
Currently 2.4.0, but I don't think that is relevant to the ticket.  If a different version is preferred I would be happy to use it.

**To Reproduce**
Not Applicable.

**Expected behavior**
Not Applicable.

**Additional context**
Not Applicable.

**Comment by jskelcy** [comment]
I would like to add the `question` label to this ticket but it appears I can not do that.

**Comment by jskelcy** [comment]
I am going to close this for now because I feel like I kind of answered my own question. I should not be leveraging the Kafka client to manage my application retries within the lifetime of a single consumer instance.

**Comment by achille-roussel** [comment]
@jskelcy thanks for following up on the issue! I'm sure it'll help someone who runs into a similar problem at some point.
