### ISSUE TITLE
Support Kafka record headers

### ISSUE THREAD

**Issue by Pryz** [segmentio/kafka-go#43]
Since 0.11.x, Kafka support record headers. See : https://issues.apache.org/jira/browse/KAFKA-4208 / https://cwiki.apache.org/confluence/display/KAFKA/A+Case+for+Kafka+Headers.

There is a lot of use cases where headers could be useful !

**Comment by Pryz** [comment]
I will try to take a look to it the coming week :)

**Comment by townsendbt** [comment]
Hi,
I'm wondering if there is any progress on this issue? I need to use Message Headers. I'll use the confluent go client if this isn't on the radar for release.

Thanks,
Brian.

**Comment by Pryz** [comment]
Unfortunately no progress since we don't have the need for it anymore. Feel free to send a PR if you have time to work on this :)

**Comment by scarbo87** [comment]
I tried to implement #185 , but failed.
Messages are sent to Kafka, but there are no headers.
Have any ideas?

**Comment by achille-roussel** [comment]
Making progress on this front with https://github.com/segmentio/kafka-go/pull/163
