### ISSUE TITLE
workflow with consumer group and auto reconnecting

### ISSUE THREAD

**Issue by vtolstov** [segmentio/kafka-go#431]
I have framework (go-micro) and i'm write broker plugin for it that uses kafka-go for pub/sub.
when working with consumer groups we have 3 kind of errors:
1) kafka.ErrGroupClosed - does it possible that this error returned when kafka doing rebalance?
2) kafka.ErrGenerationEnded - why it happens? and what need to do client app if user don't call  unsubscribe?
3) other error when doing group.Next(ctx) - what logic here?

**Comment by achille-roussel** [comment]
@stevevls you're probably the best person to answer the question here ☝️

**Comment by vtolstov** [comment]
i'm crate question because as i saw my app sometimes stuck , all three topics contains messages but my app dont fetch them.
most of the logic here: https://github.com/micro/go-plugins/blob/master/broker/segmentio/segmentio.go#L213

**Comment by vtolstov** [comment]
@stevevls gentle ping

**Comment by achille-roussel** [comment]
Thanks for following up @kazhuravlev !
