### ISSUE TITLE
on consumer start generation contains last already ack messages

### ISSUE THREAD

**Issue by vtolstov** [segmentio/kafka-go#432]
**Describe the bug**
I have consumer that get generation Assignments and process messages. Always after consumer start generation Assignments contains LAST ALREADY ACKED messages. So consumer always reprocess last message

**Kafka Version**
master

**To Reproduce**
https://github.com/micro/go-plugins/blob/master/broker/segmentio/segmentio.go#L205

**Expected behavior**
message that already acked not reprocessed twice

**Additional context**
i'm write segmentio kafka plugin for go-micro framework

**Comment by vtolstov** [comment]
@achille-roussel can you help with such case? Mostly i have service that send push notifications based on kafka messages and when service restarted it get from all partitions last already ack-ed messages, so i have duplicate push notifications

**Comment by vtolstov** [comment]
@achille-roussel any progress?

**Comment by vtolstov** [comment]
gentle ping..

**Comment by vtolstov** [comment]
@achille-roussel any chance to fix this? Issue present in current master and in 0.4.x branch. And reproduced when consumer group is used

**Comment by vtolstov** [comment]
link the #566 as it contains more examples

**Comment by vtolstov** [comment]
@achille-roussel this is very important for us

**Comment by vtolstov** [comment]
also if you looks at kafka partitions after consumer commit message lag is always lower then expected

**Comment by vtolstov** [comment]
i'm dig into code (for 0.3.x branch, but for 0.4.x this is the same) may be we need to add in examples and in docs that then you commit offset you must use offset from generation + 1 
for example in commig.go makeCommit already have such stuff (msg.Offset + 1)

**Comment by dmarkhas** [comment]
@vtolstov per Kafka spec, the committed offset should be of the *next* message you want to process, not of the one you just processed.

https://kafka.apache.org/22/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html#:~:text=Note%3A%20The%20committed%20offset%20should,of%20the%20last%20message%20processed.

**Comment by vtolstov** [comment]
yeah, but examples on consumer group not contains such stuff, and docs does not says about this thing in kafka-go repo.
so i think the best to clarify such stuff in docs in this package

**Comment by dmarkhas** [comment]
It is demonstrated in this example:
https://github.com/segmentio/kafka-go/blob/master/example_consumergroup_test.go#L49

I know it is there because I submitted this change myself after spending a considerable amount of time on the same issue a few months ago :)

**Comment by vtolstov** [comment]
Nice! But may be add this info to godoc too?

пн, 21 дек. 2020 г., 8:47 Dan Markhasin <notifications@github.com>:

**Comment by vtolstov** [comment]
solved
