### ISSUE TITLE
wrong default value for ReaderConfig.MinBytes?

### ISSUE THREAD

**Issue by eaglexiang** [segmentio/kafka-go#434]
**Describe the solution you'd like**

Argument `ReaderConfig.MinBytes` was set with `ReaderConfig.MaxBytes` by default. 

see [reader.go](https://github.com/segmentio/kafka-go/blob/e0af1cfbb8dd463571748e350262e2c81754bb73/reader.go#L557)

In my opinion, that should be set with const value `1` by default following apache document said.

see [replica.fetch.min.bytes](https://kafka.apache.org/documentation/#replica.fetch.min.bytes)

**Supporting documentation**

* [replica.fetch.min.bytes](https://kafka.apache.org/documentation/#replica.fetch.min.bytes)

**Comment by achille-roussel** [comment]
Hello @eaglexiang!

I may be mistaking, but I believe that `replicat.fetch.min.bytes` applies to partition replication between kafka brokers, and not to kafka clients.

I'm open to making the change, we should probably accompany it with a documentation update in kafka-go to explain why we're changing the default value.

Would you be available to submit a fix for this?

**Comment by eaglexiang** [comment]
I'm so sorry about that wrong href I provided, it's a misoperation.

the correct href about supporting document is:

* [fetch.min.bytes](https://kafka.apache.org/documentation/#fetch.min.bytes)

>  The default setting of 1 byte means that fetch requests are answered as soon as a single byte of data is available or the fetch request times out waiting for data to arrive. Setting this to something greater than 1 will cause the server to wait for larger amounts of data to accumulate which can improve server throughput a bit at the cost of some additional latency.

I'm glad to submit a fix :)

**Comment by eaglexiang** [comment]
[pr](https://github.com/segmentio/kafka-go/pull/565) is ready yet :)
