### ISSUE TITLE
How to create topic for Kafka Cluster

### ISSUE THREAD

**Issue by nitiprabhu** [segmentio/kafka-go#440]
Can I get an example of creating a topic programmatically? 

 I tried creating a topic as below: 

c, _ := kafka.Dial("tcp", "host:port")
kt := kafka.TopicConfig{Topic: "sometopic", NumPartitions: 1, ReplicationFactor: 1}
e := c.CreateTopics(kt)

But this will work only if the given **host:port** is Kafka Leader. If the **host:port** is not Leader, then I will be getting this error: _**Not Controller: this is not the correct controller for this cluster**_

What is the right way of passing clusters address and creating a topic?

**Comment by z2665** [comment]
you may try this code
```golang
        conn, err := kafka.Dial("tcp", "localhost:9092")
	if err != nil {
		panic(err.Error())
	}
	controller, _ := conn.Controller()
	fmt.Printf("%s %d ", controller.Host, controller.Port)
	conncontroller, err := kafka.Dial("tcp", net.JoinHostPort(controller.Host, strconv.Itoa(controller.Port)))
	if err != nil {
		panic(err.Error())
	}
	err = conncontroller.CreateTopics(topic)
	if err != nil {
		panic(err.Error())
	}
```

**Comment by aultimus** [comment]
I added documentation to the readme which should help answer your question. I'm going to close this issue now, please let me know if your issue is not solved
