### ISSUE TITLE
How to consume messages in batches using Reader?

### ISSUE THREAD

**Issue by R-Romanov** [segmentio/kafka-go#443]
Hi and thanks for your work and the cool library!

I need to consume 10 000 messages in one iteration/request, but I can't find any instruction on how can I do what using Reader. Also, I can't do this using conn.ReadBatch, because I need to specify the consumer group for my tasks.

Please tell me how to solve the problem.

**Comment by abhigyank** [comment]
@achille-roussel Any idea about how to go about doing this?

**Comment by R-Romanov** [comment]
Completely moved on https://github.com/confluentinc/confluent-kafka-go
Huge difference between speed and functionality.

**Comment by vtolstov** [comment]
Do you have benchmarks to see the difference?
