### ISSUE TITLE
KeepAlive and reuse connection in Kafka Reader

### ISSUE THREAD

**Issue by WideLee** [segmentio/kafka-go#444]
How kafka reader reuse connection? I have found that it set connection deadline to 0 after each batch read operation (around line 1394 in reader.go )

```
func (r *reader) read(ctx context.Context, offset int64, conn *Conn) (int64, error) {
   	.....
		offset = msg.Offset + 1
		r.stats.offset.observe(offset)
		r.stats.lag.observe(highWaterMark - offset)

		size++
		bytes += n
	}

	**conn.SetReadDeadline(time.Time{})**

	t2 := time.Now()
	r.stats.readTime.observeDuration(t2.Sub(t1))
	r.stats.fetchSize.observe(size)
	r.stats.fetchBytes.observe(bytes)
	return offset, err
}
```

Actually, It seems to start a new tcp connection at each batch read, and cause lots of TIME_WAIT sockets in system. 

Here is my configuration

```
r := kafka.NewReader(kafka.ReaderConfig{
    Brokers: ["localhost:9092"],
    GroupID: ["kafka-input-1"],
    Topic:   ["test-topic"],
    Dialer: &kafka.Dialer{
        Timeout:   10 * time.Second,
        DualStack: true,
        KeepAlive: 7200000 * time.Millisecond,
    },
})
```

Thank you very much~

**Comment by WideLee** [comment]
![image](https://user-images.githubusercontent.com/2196814/81466082-447eba80-9201-11ea-8770-49fbe4619bb7.png)

It sent FIN and close connection every 10 secs.

**Comment by stevevls** [comment]
Hi @WideLee .  Can you confirm which version of kafka-go you are using?  The latest release (`v0.3.6`) fixes a bug where reader connections were closed after each batch.  The issue was fixed in #409.  If you are on an earlier release of kafka-go, please update and let us know if the problem persists.  Thanks!

**Comment by WideLee** [comment]
The version I used is the latest release version `v0.3.6` and still have this problem. 

I wonder why it set the connection deadline to time.Time{}  (`reader.go:1394`, `conn.SetReadDeadline(time.Time{})`) after each read operation? Seems that it will close the connection after each read.

**Comment by achille-roussel** [comment]
Hello @WideLee, thanks for reporting the issue.

We made a couple of improvements to connection management in the latest 0.3.x versions, have you noticed the issue after upgrading kafka-go?

**Comment by WideLee** [comment]
@achille-roussel Thank you very much ^_^  I'll using v0.4.5 and cannot reproduce this issue, may be fixed in the latest release.

**Comment by fessmage** [comment]
I get this same problem with v0.3.10 of library - keepalive seems like not working at all. I'm tested keepalive setting in dialer with 0, 1 min and 10 min, but monitoring of tcp connections count on kafka brokers dont show any difference. Also tcpdump on consumer host traces tcp fin packets around every 10 seconds.
