### ISSUE TITLE
Writing to topic preceded by deletion of topic throws error 

### ISSUE THREAD

**Issue by abhigyank** [segmentio/kafka-go#456]
**Describe the bug**
First delete a topic
```go
conn, _ := kafka.Dial("tcp", "localhost:9092")
conn.DeleteTopics(topicString)
```

Then write a message to the same topic using kafkaWriter
```go
message := kafka.Message{
		Key:   key,
		Value: value,
		Time:  time.Now(),
	}
	kafkaWriter.WriteMessages(context.Background(), message)
}
```
This throws an error - 
```
[5] Leader Not Available: the cluster is in the middle of a leadership election and there is currently no leader for this partition and hence it is unavailable for writes
```
Shouldn't writing create a topic and that should get elected as the leader?

**Kafka Version**
kafka_2.12-2.5.0

**Additional context**
I tried creating the topic as an intermediate step after deletion, 
```go
topic := kafka.TopicConfig{
		Topic:        topicString,
		NumPartitions: 5,
		ReplicationFactor: 1,
	}
	err := conn.CreateTopics(topic)
``` 
But this doesn't have any impact. I check topics list using kafka-topics.sh and it doesn't show the topic after running CreateTopics.

**Comment by achille-roussel** [comment]
Hello @abhigyank!

Topic creation and deletion in kafka is asynchronous, have you tried waiting a bit between steps?

The writer also maintains a cache of the cluster layout (which broker host which partition and where the leaders are), so it is expected that the state will eventually converge, but may be outdated for a short period of time after topics were added or removed.

**Comment by abhigyank** [comment]
> Hello @abhigyank!
> 
> Topic creation and deletion in kafka is asynchronous, have you tried waiting a bit between steps?

Thanks! This helped. Waiting after deletion for some time and then creating the topic worked.

> The writer also maintains a cache of the cluster layout (which broker host which partition and where the leaders are), so it is expected that the state will eventually converge, but may be outdated for a short period of time after topics were added or removed.

Yes, I did think about that. For this I added a wait for 10-15 secs after deletion (no addition), yet still it threw the same error. So I suppose creation of topic is necessary after deletion for writer to get information about new leaders i.e. it is unable to recreate a deleted topic probably.

Closing, as found fix :)
