### ISSUE TITLE
Closing a Writer is "deadlocked" on `func (w *writer) close() {`

### ISSUE THREAD

**Issue by JordyMoos** [segmentio/kafka-go#459]
**Describe the bug**
If I create a basic Writer (as in the readme) and write messages to it and make sure all works fine (kafka up and running). Now if I kill kafka then I will get a `EOF` error when writing to kafka. So far as expected.

But now if I want to close that writer. Then it will hang in a dead lock

**Kafka Version**
wurstmeister/kafka:2.12-2.4.0

**To Reproduce**
Steps to reproduce the behavior.  Bonus points for a code sample.

**Expected behavior**
I expect that Kafka will be successfully closed within a minute.

**Additional context**
I think the problem lies here:
This will be called and adds 1 to the waitgroup
https://github.com/segmentio/kafka-go/blob/v0.3.6/writer.go#L502
```go
func (w *Writer) close(writer partitionWriter) {
	w.join.Add(1)
	go func() {
		writer.close()
		w.join.Done()
	}()
}
```

Which in turn will execute this piece of code:
https://github.com/segmentio/kafka-go/blob/v0.3.6/writer.go#L568
```go
func (w *writer) close() {
	close(w.msgs)
	w.join.Wait()
}
```

Which will then Wait for the waitgroup. Although that will never succeed because of the addition on line 502.

What will happen is something like this
```go
func (w *Writer) close(writer partitionWriter) {
	w.join.Add(1)
	go func() {
		close(w.msgs)
                // This will wait forever because the Done is the line below
	        w.join.Wait()
		w.join.Done()
	}()
}
```

Removing the wait on line 570 will solve the neverending wait.

**Comment by stevevls** [comment]
Thanks for submitting this bug report and for including code samples!  Could you also share the `WriterConfig` that you are using minus the hostnames?

One clarification I'd like to make is that the there are two types in play.  There's the exported `Writer` and the unexported `writer`, each of which have a `close` function and a wait group named `join`.  In the first code block above, the `Writer` (capital W) calls `close` on the `writer` (lower w).  With that in mind, the inlined code would look like this instead:

```
func (w *Writer) close(writer partitionWriter) {
	w.join.Add(1)
	go func() {
		close(writer.msgs)
	        writer.join.Wait()
		w.join.Done()
	}()
}
```

Thanks!

**Comment by JordyMoos** [comment]
Thanks for answering the report @stevevls 

You are indeed right, I overlooked that piece and that looks fine. Thanks for clarifying, that makes way more sense now!

I made a demo, which also includes the config, to denote the problem that I have.
The demo can be found here:
https://github.com/JordyMoos/kafka-disconnect-test

Briefly what the code does is:
- It creates a new Kafka writer.
- It sends two messages to Kafka (to show that everything works fine)
- Then it prints a requests to kill Kafka and will sleep a little
- Then you have to stop Kafka in a terminal
- After 30 seconds the script continues to write another batch of 2 messages.
- This will fail (as expected)
- Then Kafka will be closed but that will hang forever (did not try to wait longer then 30 minutes, but it should close earlier)

The readme shows how to start the environment which is handled by docker compose.

Hopefully this demo proves useful to you. If there is anything I can do to help resolve this issue then please ask.

Have a good day

**Comment by stevevls** [comment]
Thanks @JordyMoos.  We recently got another bug report internally about similar behavior, and it may be a bug introduced by #382.  We currently are looking to merge #462 to revert that change and also have a longer term fix in the form of #461.  If you get a moment, could you try #462 to see if it solves your issue?

**Comment by JordyMoos** [comment]
Tested this with the new kafka-go v0.3.7 and now Kafka closes properly. Thanks for the quick fix!

**Comment by stevevls** [comment]
Glad to hear it worked!
