### ISSUE TITLE
Change config Logger type to interface or func

### ISSUE THREAD

**Issue by Sora233** [segmentio/kafka-go#463]
**Describe the solution you'd like**
For now, ReaderConfig contains two `log.Logger`, which is heavy and not compatible with much log framework.

Changing it to interface or just a func(format string, args ...interface{}) {} will be nice.

**Comment by vtolstov** [comment]
i'm fine with current stuff, 
```
 Logger:          kafka.LoggerFunc(logger.Debugf),       
 ErrorLogger:     kafka.LoggerFunc(logger.Errorf),       
```

**Comment by vtolstov** [comment]
hint: use LoggerFunc

**Comment by achille-roussel** [comment]
@Sora233 thanks for opening the issue.

The solution that @vtolstov suggests is the right one. `kafka-go` provides a the helper type `kafka.LoggerFunc` to bridge functions or methods to the `kafka.Logger` interface.

This is common model in Go, take as example `http.Handler` and `http.HandlerFunc`, so I don't think there is anything to fix here, the use case is already addressed.
