### ISSUE TITLE
Possibility to get Generation information when using Reader

### ISSUE THREAD

**Issue by vadzappa** [segmentio/kafka-go#466]
**Describe the solution you'd like**
There are cases when it's convenient to use Reader with consumer group ID, and at the same time to be notified when next generation happened. (mainly for some side effects when some action is needed when rebalance happened and no new messages yet arrived).
So, close to observing rebalance, some trigger (channel based or callback based) with Generation, like:

somewhere in Reader.run method
```golang
gen, err := cg.Next(r.stctx)
// .... error handling
// existing observer for rebalance
r.stats.rebalances.observe(1)
// new rebalance notification
if r.config.OnRebalance != nil {
  go r.config.OnRebalance(gen)
}
```

Was trying to find solution using existing functionality, but wasn't able to, so came up with this idea

**Comment by achille-roussel** [comment]
Hello @vadzappa!

This information is not currently exposed by the`kafka.Reader` type, but it can be accessed if you use the consumer group API directly (see for example [kafka.Generation](https://pkg.go.dev/github.com/segmentio/kafka-go#Generation)).

**Comment by psykhi** [comment]
@achille-roussel Something you'd be fine with if there was a PR for it? Would there be any workaround at the moment? Using the consumer group API would basically mean re-implementing the whole `Reader` just to be able to be notified when there's a rebalance. 
Some context about our use case: We've written our own function to read the lag for a given consumer group, but that becomes inaccurate when there's a rebalance and we keep tracking some offsets for partitions we're not subscribed to anymore.

**Comment by achille-roussel** [comment]
I realized we forgot to follow up on this issue.

We always welcome pull requests, especially if the change is small, it can be simpler to drive discussions with a code change to look at 👍 

The problem of getting lag information from `kafka.Reader` when using a consumer group is common. Generally we recommend monitoring out-of-bands with a system like burrow, but having APIs to better serve the use case in kafka-go could be helpful as well.

**Comment by achille-roussel** [comment]
I'm going to close this issue due to inactivity, feel free to reopen if this needs further discussion.
