### ISSUE TITLE
How can i use StartOffset when using ConsumerGroup.

### ISSUE THREAD

**Issue by pyama86** [segmentio/kafka-go#467]
**Describe the bug**
Hi!
I have written above code.

```go
	return kafka.NewReader(kafka.ReaderConfig{
		Brokers:     "example:9092",
		GroupID:    "example",
		Topic:       "example",
		StartOffset: 170710263,
		MinBytes:    10e3, // 10KB
		MaxBytes:    10e6, // 10MB
	}), nil

```

And, I was got this error message.

```
panic: StartOffset is not valid 170710263
```

I think that this message happen from [this](https://github.com/segmentio/kafka-go/blob/master/consumergroup.go#L230)
However, `FirstOffset` and `LastOffset` is [cont value](https://github.com/segmentio/kafka-go/blob/master/reader.go#L17), therefore  I can't set any number to `StartOffset`?

Please let me know your opinion on the implementation of this part.

thanks!

**Kafka Version**
What version(s) of Kafka are you testing against?

**To Reproduce**
Steps to reproduce the behavior.  Bonus points for a code sample.

**Expected behavior**

**Additional context**

**Comment by pyama86** [comment]
I have solved this trouble myself.
We can overwrite offset by [ConsumerGroup](https://github.com/segmentio/kafka-go/blob/master/example_consumergroup_test.go#L63).

Please close the issue if this is the intended way!

**Comment by stevevls** [comment]
Nice...that's a perfect solution!
