### ISSUE TITLE
how to dynamically update topic partition number 

### ISSUE THREAD

**Issue by Luffy110** [segmentio/kafka-go#469]
Actually , i don't know this is a bug or feature.  Now i have a requirement that to dynamically update topic partition number in runtime(such as i want topic partition scales to 3 when producer or consumer from 2 scaled to 3). but i don't found any this interface or function can be invoked. 

**Kafka Version**
version 0.3.4

**Comment by gonejack** [comment]
Kafka support adding partitions only, removing partition is not allowed.

Kafka topic 分区数只支持扩容，不支持缩容。

**Comment by Luffy110** [comment]
Yes, you are right. but actually, kafka support admin API to update partitions. even though it don't support reduce its amount. but you still can use this API to dynamic scale out partitions amount.

**Comment by achille-roussel** [comment]
Hello @Luffy110, thanks for starting the discussion on admin APIs in kafka-go!

The kafka admin API is currently not supported in this Go client, but you can leverage other tools in the kafka ecosystem to increase the partition count of a topic. The [kafka documentation](https://kafka.apache.org/081/documentation.html) gives some details on how to use the `kafka-topics.sh` program for this purpose.
