### ISSUE TITLE
how to use the same consumer group over different machines?

### ISSUE THREAD

**Issue by chy373** [segmentio/kafka-go#473]
when I start one consumer group on one machine, this consumer group can't process message in time, so how can I use the consumer group over different machines?

**Comment by gonejack** [comment]
Consumer group was designed to be use on multiple machines.

消费组直接起就可以了，不同机器可以配相同消费组，会平分消息。

**Comment by chy373** [comment]
> Consumer group was designed to be use on multiple machines.
> 
> 消费组直接起就可以了，不同机器可以配相同消费组，会平分消息。
嗯，我自己实际做了测试，的确可以。
