### ISSUE TITLE
Reading the most recent message off a partition

### ISSUE THREAD

**Issue by gargath** [segmentio/kafka-go#476]
I'm new to Kafka, so I may be doing something daft here. If so, I'd greatly appreciate some guidance.

I am working on a tool that consumes data from an upstream system and publishes it to a Kafka topic.
On startup, I would like to read back the most recently published message on that topic because it contains information I can use to seamlessly resume the upstream subscription.

Right now, I am trying to `ReadLastOffset()` and then create `Reader`, call `SetOffset()` to that number and attempt to `ReadMessage()`
This call times out.

I have also tried `kafka.LatestOffest` with the same result. Using `FirstOffset` works, so the client can read, but of course that will not provide me with the most recently published message - quite the opposite in fact.

Can someone enlighten me what I'm doing wrong?

Here is the code I am currently using (error handling removed for brevity).
I understand that eventually there will be more than one partition. In my local testing, there is only one: `[0]`

```
func (f *Publisher) GetResumeID() string {
	co1, cancel1 := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel1()

	c, _ := kafka.DialLeader(co1, "tcp", f.destination.Brokers[0], f.destination.Topic, 0)

	last, _ := c.ReadLastOffset()

	cl := &crudLogger{}
	r := kafka.NewReader(kafka.ReaderConfig{
		Brokers:     f.destination.Brokers,
		Topic:       f.destination.Topic,
		Logger:      cl,
	})

	r.SetOffset(last)
//	r.SetOffset(last - 1)

	co, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	msg, _ := r.ReadMessage(co)               // This hangs
	key := string(msg.Key)
	return key
```

**Comment by achille-roussel** [comment]
Hello @gargath!

The last offset in kafka is the offset **after** the last message. If you which to read the last message that was produced to a partition you need to lookup the value of the last offset, then read the message at _lastOffset - 1_.

You can use [kafka.(*Conn).ReadLastOffset](https://pkg.go.dev/github.com/segmentio/kafka-go#Conn.ReadLastOffset) to lookup the value of the last offset.

Let me know if you have more questions.

**Comment by gargath** [comment]
Thanks for getting back to this and my apologies for not closing it sooner.
I did figure it out in the end.

As you can see from my sample, I did try using _lastOffset -1_ and it didn't work. But I must have made a mistake somewhere else.
It works now exactly as you suggest it should.

**Comment by achille-roussel** [comment]
I'm glad you got it working!
