### ISSUE TITLE
Unable to catch EOF

### ISSUE THREAD

**Issue by susonsapkota** [segmentio/kafka-go#480]
I am trying to close the reader after all the messages have been read but program just waits for new messages. Am I doing something wrong?
```go
package main

import (
	"context"
	"crypto/tls"
	"fmt"
	"github.com/segmentio/kafka-go"
	"github.com/segmentio/kafka-go/sasl/plain"
	"io"
	"log"
	"time"
)

func main() {

	tlsConfig := tls.Config{
		InsecureSkipVerify: true,
	}
	saslFunc := plain.Mechanism{
		Username: "user",
		Password: "pass",
	}
	dailKafka := &kafka.Dialer{
		ClientID:      "my-Client",
		SASLMechanism: saslFunc,
		TLS:           &tlsConfig,
		Timeout:       5 * time.Second,
		KeepAlive:     10 * time.Second,
	}
	kafkaConfig := kafka.ReaderConfig{
		Brokers: []string{"mykafka:9092"},
		Dialer:  dailKafka,
		GroupID: "group-ID",
		Topic:   "my-topic",
	}
	
	kafkaReader := kafka.NewReader(kafkaConfig)

	defer func() {
		err := kafkaReader.Close()
		if err != nil {
			log.Println("Error occurred while trying to close reader type", err)
			return
		}
	}()

	for {
		m, err := kafkaReader.ReadMessage(context.Background())

		if err != nil {
			switch err {
			case io.EOF:
				// trying to catch this but programs waits for new messages
				log.Println("End of the file reached")
				break
			default:
				log.Println("Error while fetching messages:", err)
				continue
			}
		}
		fmt.Printf("message at offset %d: %s = %s\n", m.Offset, string(m.Key), string(m.Value))
	}
     fmt.Println("Finished Reading messages now doing rest of my work here...")
}

```

**Comment by achille-roussel** [comment]
Hello @susonsapkota, thanks for opening the issue!

Kafka consumers are usually designed to block waiting for new data on a topic or partition, `kafka.Reader` follows this model and will block once it reaches the end of the partition(s) that it reads from.

This is usually the desired behavior as the producers and consumers are often running as separate processes, so the consumer has no way to know whether more messages will arrive or whether the producer has stopped.

If you know that no more messages will be produced to the partition, you may first read the first and last offsets, configure the reader to start reading from the first offset, and break out of the loop when a message with `.Offset == lastOffset` is seen.

Let me know if this was useful.

**Comment by susonsapkota** [comment]
Thanks @achille-roussel,
