### ISSUE TITLE
Balancer not passed in backwards compatible `newWriter`

### ISSUE THREAD

**Issue by pandaadb** [segmentio/kafka-go#488]
Recently we attempted upgrading and found that the function https://github.com/segmentio/kafka-go/blob/v0.4.2/writer.go#L390 
fails to set the configured `Balancer` on the new writer.

Since the function is documented as backwards compatible I think this is important. 

When upgrading, this switched our message writer from a `CRC32Balancer` to a `RoundRobin` one. 

**Kafka Version**
- unrelated 

**To Reproduce**
- configure a new writer with a balancer 
- call `newWriter`
- check the balancer 

**Expected behavior**
The balancer is set correctly on the writer object 

**Additional context**

**Comment by pandaadb** [comment]
This is true for (at least) the versions: 0.4.1 and 0.4.2

**Comment by achille-roussel** [comment]
Hello @pandaadb! And thanks a lot for reporting the issue.

0.4+ is still under development, go modules made it hard in some cases to reference both 0.3.x and the untagged 0.4 branch (which it assumed was still a 0.3.x release), so we had to enter this unfortunate temporary state where we are still finalizing the 0.4 release but have tagged commits. I'm hoping the finish the 0.4 release in the coming weeks, and will look into this issue before merging it.

If you need stability, I would recommend that you stick to the latest 0.3.x, and if you have cycles to help on this project I would happily review a pull request for a fix.

**Comment by pandaadb** [comment]
Hi @achille-roussel 

0.3.6. suffers from a more complex bug (i haven't reported it because I wasn't sure that this is being worked on, and 4.* fixes the bug). 

In 0.3.6. the retry logic on the writer causes the error channel to fill up, so the writer hangs forever :/ 

If you think this is worth a different issue, let me know and i'll create a new one and sum up all I found out. 

The above writer fix seems like a very easy PR, i'll give that a go :)

**Comment by achille-roussel** [comment]
Have you tried a more recent 0.3.x version? I believe 0.3.7 included [a fix](https://github.com/segmentio/kafka-go/pull/462) for the problem you describe.

**Comment by pandaadb** [comment]
Hi

just ran on 0.3.7. and it fixes both the retry errors and the balancer setting. Thanks! 

As for a fix, this might be a silly question, but which branch/tag do I fork? I forked master but the code in question I think doesn't exist on master. Should I fork v0.4.2?

**Comment by achille-roussel** [comment]
Good to hear!

https://github.com/segmentio/kafka-go/pull/461 is the current head of 0.4.x

**Comment by pandaadb** [comment]
Hi - thanks! 

I Hope I did that right :) If not, please let me know. I've added the code + 1 test here: 

https://github.com/segmentio/kafka-go/pull/489
