### ISSUE TITLE
Use plain.Mechanism and get the Error: unexpected EOF

### ISSUE THREAD

**Issue by windyear** [segmentio/kafka-go#490]
```
saslMech := plain.Mechanism{
	Username: username,
	Password: password,
}

dialer := &kafka.Dialer{
	// DualStack:     true,
	SASLMechanism: saslMech,
	ClientID: "zhang",
}

kafkaWriter := kafka.NewWriter(kafka.WriterConfig{
	Brokers: []string{brokers},
	Topic: topic,
	Balancer: &kafka.LeastBytes{},
	BatchTimeout: 100*time.Millisecond,
	BatchSize: 100,
	//Async: true,
	Dialer: dialer,
	})

err = kafkaWriter.WriteMessages(ctx, msg)
```

use the code to produce message to kafka，but get the unexpected EOF, Could someone give some advise to solve this problem? Or give the example to use sasl in kafka-go?

**Comment by windyear** [comment]
Hi~ I use the v0.4.2 will get that error. But use the v0.3.7 is ok. I think this is becasue the 0.4.x is no stable. Thanks!

**Comment by YangAidi** [comment]
> ```
> saslMech := plain.Mechanism{
> 	Username: username,
> 	Password: password,
> }
> 
> dialer := &kafka.Dialer{
> 	// DualStack:     true,
> 	SASLMechanism: saslMech,
> 	ClientID: "zhang",
> }
> 
> kafkaWriter := kafka.NewWriter(kafka.WriterConfig{
> 	Brokers: []string{brokers},
> 	Topic: topic,
> 	Balancer: &kafka.LeastBytes{},
> 	BatchTimeout: 100*time.Millisecond,
> 	BatchSize: 100,
> 	//Async: true,
> 	Dialer: dialer,
> 	})
> 
> err = kafkaWriter.WriteMessages(ctx, msg)
> ```
> 
> use the code to produce message to kafka，but get the unexpected EOF, Could someone give some advise to solve this problem? Or give the example to use sasl in kafka-go?

Thanks, your code tells me how use mechanism!
