### ISSUE TITLE
Why StartOffset only used when GroupId specified?

### ISSUE THREAD

**Issue by chanchancl** [segmentio/kafka-go#494]
**Describe the solution you'd like**
If I have code like this:
```
func main() {
  reader := kafka.NewReader(kafka.ReaderConfig{
    Brokers: []{"..."},
    Topic: "TopicA",
    StartOffset: kafka.LastOffset,
  })
  // But this StartOffset does nothing.
  // So I have to call SetOffset
  reader.SetOffset(kafka.LastOffset)
}
```
Is there any advantages to do like this?

**Comment by achille-roussel** [comment]
Hello @chanchancl, when using a consumer group, the offsets are stored in kafka, the positions that consumers must start reading from is managed by the consumer group, and it is not possible for a single reader to declare where it wants to start consuming from.

Kafka provides tools to edit the consumer groups, so you can reset the position of each topic partition of the a group if needed, but this is an out-of-band operation, it is not performed automatically by the reader.

Let me know if this answer is useful.

**Comment by chanchancl** [comment]
Thanks for your response.

But my question is why StartOffset only used when GroupID is set.

For these readers without GroupID, it have to call SetOffset.
