### ISSUE TITLE
how to use writer.Close() ?

### ISSUE THREAD

**Issue by Min-Feng** [segmentio/kafka-go#497]
Is it's life span long or short?

like sql.DB have a long lifecycle ?

or

like sql.Tx have a short lifecycle

**Comment by stevevls** [comment]
It has a long lifecycle (more like `sql.DB`).  Typically, you'd create a `kafka.Writer` at the start of your application and then call `Close` when your application is exiting.

**Comment by Pryz** [comment]
Closing as you got the answer. Feel free to open a new issue if it doesn't work.
