### ISSUE TITLE
The connection sometimes hangs when it is retried multiple times

### ISSUE THREAD

**Issue by chen-ABC** [segmentio/kafka-go#507]
**Describe the bug**
When K8S restarts the Kafka container
The connection sometimes hangs when it is retried multiple times
![image](https://user-images.githubusercontent.com/30097790/92907056-95c0e400-f457-11ea-811a-734dc36575cc.png)

example code:
```
var conn *kafka.Conn
	var err error
	var retry int
	retry = 0
	for true {
		retry++
		if retry > 30 {
			return
		}
		logs.Info("begin")
		conn, err = kafka.Dial("tcp", nodeHost)
		if err != nil {
			logs.Warn("error: %s \n  retry", err)
			time.Sleep(1 * time.Second)
		} else {
			break
		}
	}
	defer conn.Close()
```
use debug
There seems to be an endless cycle going on
![image](https://user-images.githubusercontent.com/30097790/92908867-349a1000-f459-11ea-827f-086fbf4d6986.png)

**Kafka Version**
What version(s) of Kafka are you testing against?
kafka 2.1  kafka-go 0.3.8

**Comment by achille-roussel** [comment]
Hello @chen-ABC, thanks for reporting!

The piece of logs that you added appears to indicate that the kafka client had trouble connecting to the broker, then it retried. This would appear to match the for loop that you have in your example program.

Could you describe the behavior you were expecting instead?
