### ISSUE TITLE
WriteMessages should allow Kafka broker to route Messages to partitions

### ISSUE THREAD

**Issue by savaki** [segmentio/kafka-go#51]
Currently, it appears that both Conn and Writer use client side routing of messages to specific partitions.  Can I suggest that either Writer or Conn have the option to allow the broker to do the routing.  

Many users of Kafka (including us) use the key to ensure messages with the same key arrive on the same partition.  This is critical for many data replication cases where ordering matters.  While we could attempt to mirror the default kafka consistent hashing strategy, there are edge cases where the number of partitions is being changed where the client may route incorrectly because of lack of information.

My proposal is to add a special case ```Balancer``` type to indicate messages should be routed by the broker.

**Comment by savaki** [comment]
Gonna close this.  On further inspection, I think I've just misunderstood how the partitioning works.

**Comment by mhamrah** [comment]
Can you elaborate how you've solved this? It seems you must specify the partition on the connection?
