### ISSUE TITLE
Where can I find detailed use documents of this project？

### ISSUE THREAD

**Issue by NewHongjayGitHub** [segmentio/kafka-go#511]
Hi,im a new golang developer also to kafka,   i need to find good kafka client component recently so i got segmentio/kafka-go ，This component looks good so far.
But i think the getting started documentation is not detailed enough or  Where can I find detailed use documents of this project which let me  get started quickly（for example，set up the sasl auth authentication config）？

Thank you for the component！

**Comment by nlsun** [comment]
Hello!

Here's a sample usage of SASL in the tests https://github.com/segmentio/kafka-go/blob/fe9465884ef6ae2eb2df445e2a6c0e9486de8e50/sasl/sasl_test.go#L94

You can find information about the `Dialer` here https://godoc.org/github.com/segmentio/kafka-go#Dialer

Any other parts you find needs clarification?

**Comment by achille-roussel** [comment]
@NewHongjayGitHub was the answer useful?

**Comment by aultimus** [comment]
@nlsun seems like issue is dormant and we should close

**Comment by NewHongjayGitHub** [comment]
> Hello!
> 
> Here's a sample usage of SASL in the tests (see how it's used and configured in the rest of the test around this code block)
> 
> https://github.com/segmentio/kafka-go/blob/fe9465884ef6ae2eb2df445e2a6c0e9486de8e50/sasl/sasl_test.go#L93-L95
> 
> You can find information about the `Dialer` here https://godoc.org/github.com/segmentio/kafka-go#Dialer
> 
> We have the following 2 `sasl.Mechanism` implementations in the repo:
> 
> Plain: https://godoc.org/github.com/segmentio/kafka-go/sasl/plain#Mechanism
> 
> SCRAM: https://godoc.org/github.com/segmentio/kafka-go/sasl/scram#Mechanism
> 
> Any other parts you find needs clarification?

Sorry to reply you now，thanks for ur answer,  i will practice with your suggestions.Hope the docof this project is more friendly to novices.
