### ISSUE TITLE
Balancer isn't copied with NewWriter constructor

### ISSUE THREAD

**Issue by fvosberg** [segmentio/kafka-go#524]
**Describe the bug**
We are using v0.4.2 and messages with the same key are produced into multiple partitions. (Although we have configured the Hash balancer)

**Kafka Version**
2.4.0 (in confluentinc/cp-kafka:5.4.0 docker image)

**To Reproduce**
```
w := kafka.NewWriter(kafka.WriterConfig{
	Brokers: kafkaURLs,
	Dialer: &kafka.Dialer{
		Timeout:   3 * time.Second,
		DualStack: true, // IPv4 and IPv6
	},
	Topic:        "foo",
	Balancer:     &kafka.Hash{},
})

w.WriteMessages(context.Background(), kafka.Message{
    Key: []byte(""30142322.022108_2000""),
})
```

**Expected behavior**
The Topic "foo" has 32 partitions, we expect it to be produced in partition 28, but it gets distributed randomly.

**Additional context**
I've found out, that in kafka-go the writer v0.4.2 doesn't use the internal config field anymore, but the Balancer value isn't copied to the writer.Balancer field. So RoundRobin is used. When I look into the master it looks more like the older version v0.3.5. How does that come?

And do you have any migration scripts to clean up the current mess? The messages aren't ordered correctly, but have the timestamp, which might be used for ordering. Is there any migration tool, I guess we aren't the first with that problem.

Cheers and happy coding

**Comment by achille-roussel** [comment]
Hello @fvosberg, thanks for reporting.

I believe the bug you describe has been fixed in https://github.com/segmentio/kafka-go/pull/489/files, would you b able to confirm if pulling a more recent version fixes the issue?

**Comment by fvosberg** [comment]
Hi Achille, 
thanks for helping me. This is a pull request from 20th August and I've used the v0.4.2 release, which was the latest yesterday, wasn't it? I'm quite confused, that gihub says, that it is 24 days old. I'm pretty sure, that I've fetched all tags yesterday.

So if I used v0.4.3 it should be fixed, right? I'll give it a try and try to migrate. Maybe this fix should be added to other releases aswell?

**Comment by achille-roussel** [comment]
v0.4.3 should have the fix indeed.

Back-porting the fix will likely cause a lot of troubles with go modules, as it would require changing tags which would invalidate the hashes recorded in the `go.sum` files. If that's not too much of a burden, I'd recommend getting the newer version. Let me know if you're still running into the issue after upgrading.

**Comment by fvosberg** [comment]
v0.4.3 fixed the bug, thanks.

If you're interested, we've developed a tool for rebalancing kafka messages, as we had this bug in one of our production systems and needed to balance the messages on the partitions. This tool might be handy for changing the amount of partitions, too: https://github.com/tarent/kafka-rebalancer.

Thanks for your help

**Comment by achille-roussel** [comment]
I'm glad it's working now.

Thanks for sharing your tool, it looks great! We'll probably use it if we run into this use case 👍
