### ISSUE TITLE
create go mod error producer

### ISSUE THREAD

**Issue by sawungalin** [segmentio/kafka-go#532]
Hi,

I 'm create go mod init and run producer  error unexpected EOF

if I'm delete file go.mod in project, producer runing well

can you help me?

**Comment by aultimus** [comment]
Hi @sawungalin can you post an example program to help reproduce this issue and a copy of your go.mod?

**Comment by htlhenry** [comment]
I'm new to use kafka-go, May be i got the same question like this, my go.mod is this 
```
module kafka

go 1.15

require github.com/segmentio/kafka-go v0.4.8 // indirect

```

> Hi @sawungalin can you post an example program to help reproduce this issue and a copy of your go.mod?

**Comment by achille-roussel** [comment]
I'm going to close due to inactivity, but feel free to re-open if you still need assistance @sawungalin 👍
