### ISSUE TITLE
administrative client?

### ISSUE THREAD

**Issue by yuzhichang** [segmentio/kafka-go#534]
sarama [ClusterAdmin](https://github.com/Shopify/sarama/blob/master/admin.go) is the administrative client for Kafka, which supports managing and inspecting topics, brokers, configurations and ACLs.
I wish kafka-go provide this feature.

**Comment by nlsun** [comment]
Hi @yuzhichang , we've been adding support for more admin APIs to the [0.4 branch](https://github.com/segmentio/kafka-go/tree/0.4) as they are requested or as people contribute them.

If you have a need for specific APIs feel free to create a request!

**Comment by nlsun** [comment]
@yuzhichang I'm closing this for now but feel free to open a new request with the specific management functions you're interested in!
