### ISSUE TITLE
keepalive setting seems like not working (v0.3.10)

### ISSUE THREAD

**Issue by fessmage** [segmentio/kafka-go#536]
**Describe the bug**
Setting of keepalive in dialer dont get expected effect with v0.3.10 of library

**Kafka Version**
2.5.0

**To Reproduce**
Monitor count of tcp current connections on kafka host. Run `tcpdump (tcp[tcpflags] & (tcp-fin) = 1) and (host <kafka_ip> )` on consumer host with kafka ip

**Expected behavior**
After change dialer keepalive from default zero to something like 60 seconds at least - there must be almost same number of tcp connections over that time period, because of connections reusing. Also there must be almost zero fin packets from/to kafka host over that time period.

**Additional context**
This looks exactly like issue #444 , but topic starter closed it because can't reproduce it in v.0.4+ of library.

**Comment by achille-roussel** [comment]
We are not maintaining the v0.3.x series, programs should migrate to v0.4.

Since it appears that the latest versions do not exhibit the issue, I am going to close this issue, but feel free to reopen if needed.

**Comment by NitroCao** [comment]
It seems that the latest version also doesn't work.
I'm using `0.4.17` with Kafka Docker `bitnami/kafka:2` image.  
My code is like the following:
```
    go func(kafkaAddr string, fileQueue chan string) {
        dialer := &kafka.Dialer{
            KeepAlive: 8 * time.Second,
        }
        conn, err := dialer.DialLeader(context.Background(), "tcp", kafkaAddr, "file-queue", 0)
        if err != nil {
            log.Fatalf("failed to connect to kafka server %s: %s", kafkaAddr, err)
        }

        for {
            select {
            case filename := <-fileQueue:
                if _, err = conn.Write([]byte(filename)); err != nil {
                    log.Printf("failed to write message to kafka: %s", err)
                }
            }
        }
    }(c.String("kafka"), fileQueue)
```
When I send messages to this topic after a while, my code would output:
```
2021/07/26 18:26:30 main.go:133: failed to write message to kafka: write tcp 127.0.0.1:47628->127.0.0.1:9092: use of closed network connection
```
