### ISSUE TITLE
[question]How do I set  ReadPartitions  timeout

### ISSUE THREAD

**Issue by chen-ABC** [segmentio/kafka-go#538]
ReadPartitions sometimes waits until it returns,I hope to return after the deadline
SetDeadline is invalid
```
kafkaConn.SetDeadline(time.Now().Add(1*time.Second))
time.Sleep(5 * time.Second)
partitions, _ := kafkaConn.ReadPartitions(topics...)  //There is no timeout, but i hope  is timeout
```

**Comment by dominicbarnes** [comment]
When I run something similar locally, I get an "i/o timeout" error returned. I only ran my test using v0.4, if you're using v0.3 I can check into that as well.

It looks like you're ignoring the returned `err` value in your sample code, but if you check the `err` value, do you see the same thing?
