### ISSUE TITLE
Topic Created as side effect of DialLeader

### ISSUE THREAD

**Issue by tlinford** [segmentio/kafka-go#540]
**Describe the bug**
Following the example in [README](https://github.com/segmentio/kafka-go#to-create-topics), the topic gets created with the call to DialLeader. This seems to rely on `auto.create.topics.enable` being on by default in kafka config.

Running the example with the option set to false causes DialLeader to never return.

Creating a connection to leader explicitly works as expected, so possibly the documentation is just a bit misleading.
I think this could also be related to #436.

**Kafka Version**
2.6.0

**To Reproduce**
set `auto.create.topics.enable=false` in `server.properties`
run example code from [README](https://github.com/segmentio/kafka-go#to-create-topics)

**Expected behavior**
the topic gets created with the call to CreateTopics, and not as a side effect of DialLeader.

**Comment by aultimus** [comment]
Thank you for your bug report @tlinford. I was able to reproduce this behaviour using this example program:

```
package main
import (
	"context"
	"fmt"
	"math/rand"
	"time"
	"github.com/segmentio/kafka-go"
)
func listTopics(conn *kafka.Conn) {
	partitions, err := conn.ReadPartitions()
	if err != nil {
		panic(err.Error())
	}
	m := map[string]struct{}{}
	for _, p := range partitions {
		m[p.Topic] = struct{}{}
	}
	fmt.Println("topics that exist:")
	for k := range m {
		fmt.Println(k)
	}
}
func main() {
	rand.Seed(time.Now().UTC().UnixNano())
	topic := fmt.Sprintf("topic-%d", rand.Intn(1000000))
	fmt.Printf("creating topic %s\n", topic)
	partition := 0
	conn, err := kafka.DialLeader(context.Background(), "tcp", "localhost:9092", topic, partition)
	if err != nil {
		panic(err.Error())
	}
	defer conn.Close()
	listTopics(conn)
}
```

example output:
```
12:24:28 matthew.ault@aulty-mac:runkafka$ go run create-topics/main.go 
creating topic topic-149182
topics that exist:
topic-149182
```

As a result, I have updated the documentation here https://github.com/segmentio/kafka-go/pull/546. I hope that this satisfies your request.

**Comment by aultimus** [comment]
@tlinford does this satisfy your request?

**Comment by tlinford** [comment]
totally, thanks a lot for the clarification!

**Comment by aultimus** [comment]
thanks for your contribution :)
