### ISSUE TITLE
High memory usage of kafka-go

### ISSUE THREAD

**Issue by xiaokgs** [segmentio/kafka-go#548]
kafka-go version: 0.4.6

My service has a part of code utilizing the kafka-go library to send event to kafka.

But I noticed that the memory usage of the pod increased a lot after sending one event, and here is part of the pprof result:

```
13834.57kB 35.38% 35.38% 13834.57kB 35.38%  github.com/segmentio/kafka-go.makePartitions
 4968.10kB 12.70% 48.08%  4968.10kB 12.70%  reflect.unsafe_NewArray
 2560.13kB  6.55% 54.63%  2560.13kB  6.55%  github.com/segmentio/kafka-go/protocol.bytesToString (inline)
 2078.67kB  5.32% 59.95%  2078.67kB  5.32%  google.golang.org/protobuf/internal/strs.(*Builder).AppendFullName
 1566.25kB  4.01% 63.95% 15400.83kB 39.38%  github.com/segmentio/kafka-go.makeLayout
...
...
...
         0     0%   100%  7528.23kB 19.25%  github.com/segmentio/kafka-go.(*conn).roundTrip
         0     0%   100%  7528.23kB 19.25%  github.com/segmentio/kafka-go.(*conn).run
         0     0%   100% 15400.83kB 39.38%  github.com/segmentio/kafka-go.(*connPool).discover
         0     0%   100% 15400.83kB 39.38%  github.com/segmentio/kafka-go.(*connPool).update
         0     0%   100%  7528.23kB 19.25%  github.com/segmentio/kafka-go/protocol.(*Conn).RoundTrip
         0     0%   100%  7528.23kB 19.25%  github.com/segmentio/kafka-go/protocol.(*decoder).decodeArray
         0     0%   100%  2560.13kB  6.55%  github.com/segmentio/kafka-go/protocol.(*decoder).decodeString
         0     0%   100%  2560.13kB  6.55%  github.com/segmentio/kafka-go/protocol.(*decoder).readString
         0     0%   100%  7528.23kB 19.25%  github.com/segmentio/kafka-go/protocol.ReadResponse
         0     0%   100%  7528.23kB 19.25%  github.com/segmentio/kafka-go/protocol.RoundTrip
         0     0%   100%  7528.23kB 19.25%  github.com/segmentio/kafka-go/protocol.arrayDecodeFuncOf.func1
         0     0%   100%  4968.10kB 12.70%  github.com/segmentio/kafka-go/protocol.makeArray
         0     0%   100%  7528.23kB 19.25%  github.com/segmentio/kafka-go/protocol.structDecodeFuncOf.func2
```

are we supposed to consume more memory by leveraging kafka-go?

**Comment by achille-roussel** [comment]
Hello @xiaokgs, thanks for reporting!

Do you have more details on your configuration? For example, how many brokers and partitions are in your cluster? Or what is the [metadata TTL](https://github.com/segmentio/kafka-go/blob/0.4/transport.go#L82)?

**Comment by achille-roussel** [comment]
We also just merged https://github.com/segmentio/kafka-go/pull/547 and release v0.4.8, this should shrink by half the memory used by `kafka-go.makePartitions`, let me know if you're able to test it out.

I'm still interested in hearing more about your setup, it's very likely that we can optimize memory usage here.

**Comment by xiaokgs** [comment]
Thanks for the quick reply! Will try out the v0.4.8 later.

We have 3 brokers in total, 12 partitions per topic, totally around 228 partitions. The MetadataTTL should be the default value.

**Comment by schandra157** [comment]
I am also running with a similar issue, but with a **0.4.8** version of **Kafka-go**

     flat  flat%   sum%        cum   cum%
   **108.59MB** 45.79% 45.79%   108.59MB 45.79%  github.com/segmentio/kafka-go.makePartitions
   66.84MB 28.18% 73.97%    66.84MB 28.18%  reflect.unsafe_NewArray
   17.16MB  7.23% 81.20%    17.16MB  7.23%  github.com/segmentio/kafka-go.(*writeBatch).add
   6.01MB  2.53% 88.20%     6.01MB  2.53%  github.com/segmentio/kafka-go.readNewBytes
   5MB  2.11% 90.30%        5MB  2.11%  github.com/segmentio/kafka-go/protocol.bytesToString


We have a setup up of 3 brokers with 100 Topics, with each topic has 4 partitions

**Comment by achille-roussel** [comment]
@schandra157 @xiaokgs can you tell us more about your setup? For example:

* Are you seeing high memory usage on programs that consume or produce with kafka-go?
* Are you creating one `kafka.Reader` or one `kafka.Writer` per topic?

**Comment by schandra157** [comment]
we are using high memory usage on the producer side of Kafka-go.

We are creating **Kafka.Writer** per topic(in my case 100), to write msgs to respective topics.

**Comment by achille-roussel** [comment]
Are you creating the writer with [`kafka.NewWriter`](https://godoc.segment.build/github.com/segmentio/kafka-go?tab=doc#NewWriter) by any chance?

If that's the case, there's a possibility of memory amplification because `kafka.NewWriter` will create a `kafka.Transport` underneath (for backward-compatibility reasons), see https://github.com/segmentio/kafka-go/blob/v0.4.9/writer.go#L464-L471

**Comment by schandra157** [comment]
@achille-roussel   

nope, I am creating a writer as below, hope this helps

```
writer := &kafka.Writer{
		Addr:         kafka.TCP(brokerAdd),
		Topic:        topicName,
		BatchSize:    batchSize,
		RequiredAcks: kafka.RequireOne,     // Ack from replicas are not Required
		BatchTimeout: 10 * time.Nanosecond // keep this value in min closer to 0, we are seding data already in bulk 
	}
```

Please let me know if any further info is required

**Comment by xiaokgs** [comment]
A followup question to this:
Now the memory usage of kafka-go sometimes burst to 200MB whenever we send messages to kafka.
```
96MB 74.23% 74.23%       96MB 74.23%  github.com/pierrec/lz4.newBufferPool.func1
   11.57MB  8.94% 83.17%    11.57MB  8.94%  github.com/go-pg/pg/v10/internal/pool.NewBufReader (inline)
    8.76MB  6.77% 89.94%     8.76MB  6.77%  github.com/pierrec/lz4.NewWriter (inline)
    2.50MB  1.93% 91.88%     2.50MB  1.93%  github.com/segmentio/kafka-go.makePartitions
    2.41MB  1.86% 93.74%     2.41MB  1.86%  google.golang.org/protobuf/internal/strs.(*Builder).AppendFullName
    1.64MB  1.26% 95.01%     1.64MB  1.26%  reflect.unsafe_NewArray
    1.61MB  1.24% 96.25%     1.61MB  1.24%  github.com/go-pg/pg/v10/internal/pool.NewWriteBuffer (inline)
    0.74MB  0.57% 96.82%     3.24MB  2.51%  github.com/segmentio/kafka-go.makeLayout
      ..
     0     0% 97.21%       96MB 74.23%  github.com/pierrec/lz4.(*Writer).Write
         0     0% 97.21%       96MB 74.23%  github.com/pierrec/lz4.(*Writer).newBuffers (inline)
         0     0% 97.21%       96MB 74.23%  github.com/pierrec/lz4.(*Writer).writeHeader
         0     0% 97.21%       96MB 74.23%  github.com/pierrec/lz4.getBuffer
         0     0% 97.21%   106.43MB 82.29%  github.com/segmentio/kafka-go.(*conn).roundTrip
         0     0% 97.21%   106.43MB 82.29%  github.com/segmentio/kafka-go.(*conn).run
         0     0% 97.21%     3.24MB  2.51%  github.com/segmentio/kafka-go.(*connPool).discover
         0     0% 97.21%     3.24MB  2.51%  github.com/segmentio/kafka-go.(*connPool).update
         0     0% 97.21%     8.76MB  6.77%  github.com/segmentio/kafka-go/compress/lz4.(*Codec).NewWriter
         0     0% 97.21%   106.43MB 82.29%  github.com/segmentio/kafka-go/protocol.(*Conn).RoundTrip
         0     0% 97.21%   104.76MB 81.00%  github.com/segmentio/kafka-go/protocol.(*RecordSet).WriteTo
         0     0% 97.21%   104.76MB 81.00%  github.com/segmentio/kafka-go/protocol.(*RecordSet).writeToVersion2
         0     0% 97.21%       96MB 74.23%  github.com/segmentio/kafka-go/protocol.(*RecordSet).writeToVersion2.func1
         0     0% 97.21%     1.14MB  0.88%  github.com/segmentio/kafka-go/protocol.(*decoder).decodeArray
         0     0% 97.21%    96.53MB 74.64%  github.com/segmentio/kafka-go/protocol.(*encoder).Write
         0     0% 97.21%   104.76MB 81.00%  github.com/segmentio/kafka-go/protocol.(*encoder).encodeArray
         0     0% 97.21%       96MB 74.23%  github.com/segmentio/kafka-go/protocol.(*encoder).writeVarInt
         0     0% 97.21%     1.14MB  0.88%  github.com/segmentio/kafka-go/protocol.ReadResponse
         0     0% 97.21%   106.43MB 82.29%  github.com/segmentio/kafka-go/protocol.RoundTrip
         0     0% 97.21%   105.29MB 81.41%  github.com/segmentio/kafka-go/protocol.WriteRequest
         0     0% 97.21%     1.14MB  0.88%  github.com/segmentio/kafka-go/protocol.arrayDecodeFuncOf.func1
         0     0% 97.21%   104.76MB 81.00%  github.com/segmentio/kafka-go/protocol.arrayEncodeFuncOf.func2
         0     0% 97.21%       96MB 74.23%  github.com/segmentio/kafka-go/protocol.forEachRecord
         0     0% 97.21%       96MB 74.23%  github.com/segmentio/kafka-go/protocol.handleRecord
         0     0% 97.21%     1.14MB  0.88%  github.com/segmentio/kafka-go/protocol.makeArray
         0     0% 97.21%     1.14MB  0.88%  github.com/segmentio/kafka-go/protocol.structDecodeFuncOf.func2
         0     0% 97.21%   104.76MB 81.00%  github.com/segmentio/kafka-go/protocol.structEncodeFuncOf.func2
         0     0% 97.21%   104.76MB 81.00%  github.com/segmentio/kafka-go/protocol.writerEncodeFuncOf.func1

```

looks like RoundTrip is calling kafka topic and open a newBufferPool with huge size.. any idea on that?

**Comment by xiaokgs** [comment]
<img width="1531" alt="Screen Shot 2021-03-05 at 11 39 27 AM" src="https://user-images.githubusercontent.com/25518694/110165308-9d7a9900-7da7-11eb-8133-68a0851627bd.png">
Flame graph here more clear... @achille-roussel  any idea why it creates that big buffer?. by sending several events.

**Comment by xiaokgs** [comment]
Update: We accidentally set the `batchSize` to 1. The memory usage dropped after we reset it to 100.

**Comment by achille-roussel** [comment]
Good to hear! 

It's still unclear to be what the relationship is between batch size and holding metadata in memory here, but generally the kafka-go client is designed to prefer batching reads and writes (because this is what kafka is optimized for).

I'll close the issue, feel free to re-open if you're still running into this problem.

**Comment by ChandraAltGaming** [comment]
Im still facing this issue after making all suggested changes.
