### ISSUE TITLE
How to poll a batch messages and then explicit commit offset when using consumer group?

### ISSUE THREAD

**Issue by RifeWang** [segmentio/kafka-go#550]
If consumer groups are used, `ReadMessage` will automatically commit the offset when called. Note that this could result in an offset being committed before the message is fully processed.

If more fine grained control of when offsets are  committed is required, it is recommended to use `FetchMessage` with `CommitMessages` instead.

But the `FetchMessage` return only one message ( this meaning that the function poll only one message from kafka every fetch and commit loop ? ) , how to poll a batch messages ( example 100 messages )，so I can handle all 100 messages , and then commit offset .

**Comment by godwhoa** [comment]
`Reader` already [reads from Kafka in batches](https://github.com/segmentio/kafka-go/blob/master/reader.go#L1382), based on the configured Min and Max bytes. 
`FetchMessage` simply [reads from a channel](https://github.com/segmentio/kafka-go/blob/master/reader.go#L763) of messages [being filled by the `read` method](https://github.com/segmentio/kafka-go/blob/master/reader.go#L1416).
I'm not a maintainer but that is what I understood from reading the source code.

**Comment by RifeWang** [comment]
@godwhoa Thanks for your reply,  it help me.  As you said `FetchMessage` reads from a channel of messages, what about `CommitMessages`,  how to batch  `CommitMessages` after message fully processed ?

**Comment by godwhoa** [comment]
`CommitMessages` takes multiple messages so, over-all code can look something like this.
```go
batchSize := 100
var messages []kafka.Message
for i := 0; i < batchSize; i++ {
	message, err := reader.FetchMessage(ctx)
	if err != nil {
		log.Error(err)
		continue
	}
	messages = append(messages, message)
}
if err := processBatch(messages); err == nil {
	reader.CommitMessages(ctx, messages...)
}
```
`CommitMessages` again simply sends those commits to `commits` channel which get processed by either [`commitLoopInterval`](https://github.com/segmentio/kafka-go/blob/c66d8ca149e7f1a7905b47a60962745ceb08a6a9/reader.go#L197) or [`commitLoopImmediate`](https://github.com/segmentio/kafka-go/blob/c66d8ca149e7f1a7905b47a60962745ceb08a6a9/reader.go#L179)[ based on the configuration of commit interval](https://github.com/segmentio/kafka-go/blob/master/reader.go#L246).
If you _**don't**_ need **_immediate_** commits then set a [commit interval](https://github.com/segmentio/kafka-go/blob/c66d8ca149e7f1a7905b47a60962745ceb08a6a9/reader.go#L376), with that you don't have to buffer the kafka messages in a slice yourself for committing.

```go
# No need to buffer if you set a commit interval
# Just fetch -> process -> commit, in a loop
# Reader will take care of reading in batches
message, err := reader.FetchMessage(ctx)
...
# Reader will take care of committing the buffered commits on each interval.
reader.CommitMessages(ctx, message)
```
One last thing, [`commitLoopInterval`](https://github.com/segmentio/kafka-go/blob/c66d8ca149e7f1a7905b47a60962745ceb08a6a9/reader.go#L215) sends out any remaining commits when `context` is cancelled. So, you won't be losing any commits on a graceful shutdown.

**Comment by lakshay2k** [comment]
Correct if i am wrong here in understanding.
When we wish to achieve a situation of reading batch of messages and process them and commit the batch after processing. Can this be done by setting the commit interval and simpling using the FetchMessage -> CommitMessage. in a loop?
Will those commits be buffered till commit interval gets over and then will the whole batch will be commited at once via CommitMessage func?
