### ISSUE TITLE
reader: write broken pipe

### ISSUE THREAD

**Issue by brzyangg** [segmentio/kafka-go#552]
kafka-go version:  v0.3.10

My application ReadMessage in one consumer, and three partitions.

When message is not write will return a error

`the kafka reader got an unknown error reading partition 0 of topic_name at offset 1234: write tcp instance_ip:9999->broker_ip:9092: write: broken pipe`

**Comment by aultimus** [comment]
@brzyangg can you provide an example program and steps to help reproduce the issue?

**Comment by brzyangg** [comment]
@aultimus Hi, i solve the problem. 
The reason is that the processing of the message is too slow. 
The tcp connection was actively disconnected by the server.
thank you
