### ISSUE TITLE
Is is possible to write to different topics with a single writer?

### ISSUE THREAD

**Issue by Nossiac** [segmentio/kafka-go#553]
The `Writer` example implies that it is bond to a single topic, but i have to dynamically route my messages to different topics based on message content. 
So, is there any way to specifing message topic dynamically with a single writer?

**Comment by salakhovilia** [comment]
when creating a writer via NewWriter (), panic is called with the message "cannot create a kafka writer with an empty topic" same message when trying to create a writer directly and sending messages via WriteMessages

**Comment by dominicbarnes** [comment]
@salakhovilia have you updated to the latest version of the v0.4 branch? #561 was recently merged and added support for this feature. If you have any trouble with that, please open a new issue so we can track it.
