### ISSUE TITLE
Seek return error at second time

### ISSUE THREAD

**Issue by sunshine69** [segmentio/kafka-go#558]
**Describe the bug**
I can not seek 

**Kafka Version**
What version(s) of Kafka are you testing against? 2.3.1

**To Reproduce**

```
func main() {
	flag.StringVar(&kafkaBrokerUrl, "b", "localhost:19092,localhost:29092,localhost:39092", "Kafka brokers in comma separated value")
	flag.BoolVar(&kafkaVerbose, "v", true, "Kafka verbose logging")
	flag.StringVar(&kafkaTopic, "t", "foo", "Kafka topic. Only one topic per worker.")
	flag.StringVar(&kafkaConsumerGroup, "cgroup", "consumer-group", "Kafka consumer group")
	flag.StringVar(&kafkaClientId, "client-id", "my-client-id", "Kafka client id")
	flag.IntVar(&kafkaPartition, "p", 0, "Partition number. Default 0")
	flag.Parse()
	ctx := context.Background()
	brokers := strings.Split(kafkaBrokerUrl, ",")

	conn, err := kafka.DialLeader(ctx, "tcp", brokers[0], kafkaTopic, kafkaPartition)
	if err != nil {
		log.Fatalf("failed to dial %v", err)
	}
	defer conn.Close()
	conn.SetWriteDeadline(time.Now().Add(120 * time.Second))

	firstOffset, lastOffset, _ := conn.ReadOffsets()
	log.Printf("First offset: %d\n", firstOffset)
	log.Printf("Last offset: %d\n", lastOffset)
	batchSize := int(10e6)
	offset, err := conn.Seek(firstOffset, kafka.SeekAbsolute)
	if err != nil {
		log.Printf("Can not seek %v\n", err)
	} else {
		println(offset)
	}

	m, err := conn.ReadMessage(batchSize)
	if err != nil {
		log.Printf("Can not read %v\n", err)
	}
	log.Printf("Start Message: %v - Key: %s => Val: %s\n", m.Time, m.Key, m.Value)

	offset, err = conn.Seek(lastOffset - 1, kafka.SeekAbsolute)
	if err != nil {
		log.Printf("Can not seek last - %v\n", err)
	} else {
		println(offset)
	}

	m, err = conn.ReadMessage(batchSize)
	if err != nil {
		log.Printf("Can not read %v\n", err)
	}
	log.Printf("Last Message: %v - Key: %s => Val: %s\n", m.Time, m.Key, m.Value)
}
```

**Expected behavior**
I should be able to seek and set the offset on the con object and read the message at last offset - 1. However I got error

```
2020/11/17 16:03:48 Can not seek last - multiple Read calls return no data or error
2020/11/17 16:03:48 Can not read multiple Read calls return no data or error
2020/11/17 16:03:48 Last Message: 0001-01-01 00:00:00 +0000 UTC - Key:  => Val:
```

The first seek always pass though. No matter how I select the `whence` still the same errors.

**Additional context**

**Comment by sunshine69** [comment]
Just for more information - If I use the `kafka.NewReader` and set the offset there I am able to read message within that offset on ward fine. I did a look at the code in seek function does the call `conn.ReadOffsets()` and somehow it return error.

**Comment by sunshine69** [comment]
Also if for the first seek I replace the `firstOffset` with a number within the rage example 50, it works as well. So it seems it is always a success at the first seek operations and then the subsequent seek failed.

**Comment by sunshine69** [comment]
More information. I tested with a small topics with different kafka version run at my laptop and it works fine. Thus I think there might be something in the deadline context and timeout but too quick. Or even the kafka version 2.3.1 has some issues with this.

**Comment by sunshine69** [comment]
All right even with kafka version 2.3.1 If I tested with small topics then it works as expected. Thus it would be the timeout but I don't know where in the code cause it. Probably seeking too afar from the start, the server wait for long time to return and this library just abort it somehow.

**Comment by nlsun** [comment]
How long does it take to reach the code
```
offset, err = conn.Seek(lastOffset - 1, kafka.SeekAbsolute)
```

Is it possible that setting the write deadline
```
conn.SetWriteDeadline(time.Now().Add(120 * time.Second))
```
is causing the client to receive no data and return the `io.ErrNoProgress` (`multiple Read calls return no data or error`) you are seeing?

**Comment by sunshine69** [comment]
Yes you are right! Removing the set deadline it seems to pass.

Thanks
