### ISSUE TITLE
race condition writing to closing (*reader).msgs

### ISSUE THREAD

**Issue by savaki** [segmentio/kafka-go#56]
Managed to hit a scenario where reader attempted to write to its internal msgs channel after it was closed.  It seems like the simplest way to remove this race is to not close msgs.  closing a channel doesn't free up its resources any sooner or cause a leak.    From examining the code, it doesn't appear that anyway it waiting for a close signal.

**Comment by achille-roussel** [comment]
So the channel is supposed to be closed after waiting for all internal goroutines to complete (see https://github.com/segmentio/kafka-go/blob/master/reader.go#L227).

Is it possible that with the consumer group changes we don't properly manage the sync group counter which results in some goroutines attempting to publish to the channel after it was closed?

**Comment by savaki** [comment]
Yep, I think that was it.  I believe there's an edge case where rebalance could be called during (*Reader).Close which would in turn spawn new readers that would close, but not until after a race condition.

Solution was to include a check at the beginning of start to make it clear that readers cannot be started if Reader.close
