### ISSUE TITLE
README states "suitable for Go 1.12+", code says "1.13+"

### ISSUE THREAD

**Issue by ingvarm-gr** [segmentio/kafka-go#560]
**Describe the bug**
In a few places, the code uses errors.Is, which was introduced in Go 1.13. Looks like this code was introduced in the v0.4.0 release (but, I have not tested this extensively).

**Kafka Version**
N/A

**To Reproduce**
Build a v0.4.0+ version of the libraru with a Go 1.12 compiler

**Expected behavior**
I expected a successful compilation, as the README clearly states 1.12+

**Additional context**
Not sure if the correct solution is "update the README to say Go 1.13+" or "work around the lack of `errors.Is`". I actually lean towards the former as being the most correct thing.

**Comment by achille-roussel** [comment]
Hello @ingvarm-gr, thanks for reporting the issue!

I'm tempted to change the documentation to raise the requirement to Go 1.13+, is upgrading Go an option for you or would it cause you issues if you had to use a more recent version?
