### ISSUE TITLE
Last message in partition always not commit

### ISSUE THREAD

**Issue by siller174** [segmentio/kafka-go#566]
**Describe the bug**
Last message in partition always not commit.

**Kafka Version**
v2.1.0

**Lib version**
0.4.8 and 0.3.y

**To Reproduce**
1) Create topic
2) Send 2 msg to topic
3) Execute 

 `kafka-consumer-groups --bootstrap-server localhost:39092 --group my.group —describe
`
**Lug = 2**

4) Execute code

https://gist.github.com/siller174/924a72f0a0cada11bd4acceede46b14f

5) Execute 

`kafka-consumer-groups --bootstrap-server localhost:39092 --group my.group —describe`

**Lug = 1**

Last message was not commit. If you send more message, last message always will not commit in each partitions.
Send 3 message, will commit 2 messages
Send 10 message, will commit 9 messages

**Expected behavior**
All messages commit

**Additional context**
Reproduce only with consumer group

**Comment by vtolstov** [comment]
@achille-roussel please, close this issue, as it solved

**Comment by siller174** [comment]
It was not correct my implementation

Correct commit: https://github.com/segmentio/kafka-go/blob/master/example_consumergroup_test.go#L49

solved
