### ISSUE TITLE
How to set topic - partition offset for a consumer group

### ISSUE THREAD

**Issue by sunshine69** [segmentio/kafka-go#580]
**Describe the solution you'd like**
I want to port the equivalent of the kafka tools command 
```
kafka-run-class.sh kafka.admin.ConsumerGroupCommand --bootstrap-server <server>  --reset-offsets  --group >group id> --topic >topic name>:<partition> --to-offset <offset number> --execute"
```

Is there a way to do it with kafka-go?

I did look into the reader but reader does not support set offset when group id is set. 

**Supporting documentation**
Please provides links to relevant Kafka protocol docs and/or KIPs.

**Comment by dominicbarnes** [comment]
We don't currently have support for this, as you pointed out. We would welcome a contribution here, if you are willing to open a Pull Request for this functionality.

**Comment by sunshine69** [comment]
Thanks for reply, but I have moved to another project so having no time for it now.
