### ISSUE TITLE
connPoolState.err is never reset

### ISSUE THREAD

**Issue by vmihailenco** [segmentio/kafka-go#582]
The code in https://github.com/segmentio/kafka-go/blob/master/transport.go#L469-L498

1. `p.grabState()` grabs the current state which has the `err` set to something when Kafka is down
2. `state.err` is never reset to nil even when Kafka broker comes back

Possible fix is to replace

```go
state.metadata, state.layout = metadata, layout
```

with

```go
state = connPoolState{metadata: metadata, layout: layout}
```

**Comment by achille-roussel** [comment]
Closing since you fixed the issue in https://github.com/segmentio/kafka-go/pull/576

Thanks again for your contribution 👍
