### ISSUE TITLE
why (*Reader).SetOffset will return an error when GroupID is set ?

### ISSUE THREAD

**Issue by 924067327** [segmentio/kafka-go#590]
why (*Reader).SetOffset will return an error when GroupID is set?
In Java Kafka Consumer API, threre are commitSync(Map<TopicPartition, OffsetAndMetadata>) or commitAsync(Map<TopicPartition, OffsetAndMetadata>) to set offset whatever I want.

**Comment by achille-roussel** [comment]
Hello @924067327, thanks for opening an issue.

When using a consumer group, the offsets are managed automatically by the consumer group, Kafka doesn't allow overriding the offsets while consumers are connected.

When part of a consumer group, a reader may be assigned multiple partitions, and the partition set may change over time. `SetOffset` would not allow the program to deterministically know what partitions it is configuring the offset for.

**Comment by scarbo87** [comment]
Hello @achille-roussel, I have a similar question. 
I want to run 3 nodes of my application and join them to one consumer group and read one kafka topic with one partition.
I expect that **only one** node will receive kafka messages and if this node is crashed some other node will be elected as a leader of consumer group and start receiving new messages.
And I want to start reading at a certain offset, how can I do it?
Thanks.

**Comment by achille-roussel** [comment]
Managing offsets in consumer group is a common operational task in Kafka, and Kafka ships with a few scripts to do this, like `kafka-consumer-groups.sh`.

I would refer you to the Kafka documentation for further reading, as this is beyond the scope of the Go client implemented by kafka-go: https://kafka.apache.org/documentation/#basic_ops_consumer_lag

I'll close this issue as it seems we answered the original question, feel free to reopen if this deserves further discussion.

**Comment by shcw** [comment]
If I need to discard data from a certain period and start reading from the latest messages, how should I proceed?

@achille-roussel
