### ISSUE TITLE
why dialing 36.86.63.182:9092 when using localhost at docker

### ISSUE THREAD

**Issue by kiyatys** [segmentio/kafka-go#592]
**Describe the bug**
I am using bitnami kafka on docker container macos.

**Kafka Version**
latest bitnami version

**To Reproduce**
I am connecting to my kafka with this parameter

	kbroker := []string{"127.0.0.1:9092","127.0.0.1:9093","127.0.0.1:9094"}
	kProducer := gokafka.Kafkaproducer{
		KafkaBroker:  kbroker,
		KafkaVerbose:  true,
		KafkaClientId: "kafka-client-id",
		KafkaTopic:    "testkiyat",
		KafkaPartition: 2,
		KafkaReplicator: 1,
	}
got panic and log say  dial tcp 36.86.63.182:9092: i/o timeout
I dont get, why that IP come up?

**Comment by achille-roussel** [comment]
Hello @kiyatys, thanks for reporting the issue.

Kafka has a service discovery mechanism built-in. The initial set of addresses that you provide are used by the client to connect to the cluster, but after that it will ask for the list of known brokers, and reconnect to brokers that are leaders of the partitions you are attempting to produce to, or consume from.

Is it possible that your kafka broker is registering to a zookeeper that hosts a cluster which also contains 36.86.63.182?

**Comment by kiyatys** [comment]
Hi @achille-roussel my kaflka cluster running in my mac with docker container.
my network is 127.21.0.x  Iam also using kafdrop, kafdrop running fine.
there no IP 36.86.63.182 in my docker also.

**Comment by achille-roussel** [comment]
Cycling back on this issue. @kiyatys if you are still experiencing the problem, could you submit a full code snippet that reproduces the error? Without the ability to run the complete program it is really hard to advise on where the error may be coming from.

**Comment by achille-roussel** [comment]
I'm going to close this issue due to inactivity, feel free to reopen if it needs further discussion.
