### ISSUE TITLE
Reader: consume from multiple topics

### ISSUE THREAD

**Issue by alebabai** [segmentio/kafka-go#595]
**Describe the solution you'd like**
Please, add opportunity to set multiple topics into reader to fetch from.

**Supporting documentation**
For now it supports single topic and pass it into consumerGroup (if GroupID is specified) as a string slice with one element
https://github.com/segmentio/kafka-go/blob/2b3f6824a9578d01c9f065be97459aa179609bdb/reader.go#L656-L663

**Related**
#564

**Comment by dominicbarnes** [comment]
This improvement was recently released with v0.4.12
