### ISSUE TITLE
0.4.5 waitgroup reuse 

### ISSUE THREAD

**Issue by mingqinz** [segmentio/kafka-go#602]
![image](https://user-images.githubusercontent.com/19308597/107135624-3ea43a00-6937-11eb-8a47-8dfdd3c2325b.png)

**Comment by mingqinz** [comment]
core after running for 48hours

**Comment by dominicbarnes** [comment]
Can you try upgrading to the latest version (v0.4.9) to see if this still occurs?

**Comment by mingqinz** [comment]
okay.

**Comment by mingqinz** [comment]
okay. I will upgrade version next week. thank you.

**Comment by dominicbarnes** [comment]
@mingqinz have you been able to replicate this issue after upgrading? Could you share any more code about your setup and configuration? (are you using `Reader`? or maybe `ConsumerGroup` directly?)

**Comment by dominicbarnes** [comment]
It's been a couple months now, so I'm going to close this issue due to inactivity. I hope that upgrading fixed the problem, if not it would be helpful to get some more context on the scenario so we can try to reproduce.

**Comment by robin-lidekrans** [comment]
In case anyone else stumbles upon this error I ran into this issue with this code:
```
func writeKafka(msg string) {
	w := &kafka.Writer{
		Addr: kafka.TCP(kafkaBrokerAddress),
		Topic: topic,
		Async: true,
	}

	err := w.WriteMessages(context.TODO(),
			kafka.Message{
				Value: []byte(msg),
			},
	)

	if err != nil {
		print("failed to write messages:", err)
	}
	
	if err := w.Close(); err != nil {
		print("failed to close writer:", err)
	}
}
```
Upgrading from v0.4.20 to 0.4.9 appears to have solved the issue.
