### ISSUE TITLE
Question: bound for sending messages

### ISSUE THREAD

**Issue by xiaokgs** [segmentio/kafka-go#606]
Hi, I have a general question about sending messages to kafka.
If we generate events faster than sending events to kafka, the memory will continue going up, isn't it? Can we set a bound to prevent pod going to OOMKilled because of sending events?

**Comment by shomron** [comment]
Adding to this - is there a safe way to use asynchronous delivery? The current implementation of `Writer.batchMessages` seems to allocate a new batch with not regard to how many undelivered batches are still in-flight. What I'd expect is a way to to configure an upper limit and have the API apply back-pressure if its delivery queue has filled.

**Comment by achille-roussel** [comment]
Hello @xiaokgs @shomron, thanks for opening the issue, and apologies for the delayed response.

Generally speaking, the async producer mode is intended to support "fire and forget" operations where the application does not need to receive back pressure from the Kafka client and can tolerate loss of messages. In the current implementation, there are indeed no limits on memory utilization in this case.

I'm going to close this issue and consolidate the discussions in https://github.com/segmentio/kafka-go/issues/819, which seems to cover the same topic.
