### ISSUE TITLE
Empty ReadBatchConfig is treated as valid one

### ISSUE THREAD

**Issue by vadzappa** [segmentio/kafka-go#607]
**Describe the bug**
While validating the ReadBatchConfig:
https://github.com/segmentio/kafka-go/blob/master/conn.go#L755

The following configuration is treated as being valid:
`ReadBatchConfig{}`, while this causes unpredictable results while reading messages from topic (usually only part of the topic got read)

**Kafka Version**
1.1.1

**To Reproduce**
Simple test code:
```go
func TestInvalidReadBatchConfig(t *testing.T) {
	c := &Conn{}
	b := c.ReadBatchWith(ReadBatchConfig{})

	if b.err == nil {
		t.Error("Invalid batch config accepted")
	}
}
```

**Expected behavior**
When empty config provided, error should be returned early, so any further actions will abort early to prevent human mistake

**Comment by dominicbarnes** [comment]
I'm working on addressing this problem with #609 and I've discovered that the failure mode you're describing appears to only impact Kafka 0.10.

The `Reader` sets some sensible defaults for `MinBytes` and `MaxBytes` (1 and 1MB respectively) that you could adopt here, assuming that using `Reader` directly is not an option for you.
