### ISSUE TITLE
"the message contents does not match its CRC" on invalid topic configuration

### ISSUE THREAD

**Issue by dmarkhas** [segmentio/kafka-go#618]
**Describe the bug**
When specifying the Topic on both the `kafka.Writer` and `kafka.Message`, the writer returns an `InvalidMessage` error, whose string representation is "the message contents does not match its CRC".

This happens inside `chooseTopic`:

```
func (w *Writer) chooseTopic(msg Message) (string, error) {
	// w.Topic and msg.Topic are mutually exclusive, meaning only 1 must be set
	// otherwise we will return an error.
	if (w.Topic != "" && msg.Topic != "") || (w.Topic == "" && msg.Topic == "") {
		return "", InvalidMessage
	}

	// now we choose the topic, depending on which one is not empty
	if msg.Topic != "" {
		return msg.Topic, nil
	}

	return w.Topic, nil
}
```

**Kafka Version**
Using kafka-go v0.4.11

**To Reproduce**
Set the Topic field on both the Writer and the Message

**Expected behavior**

The returned error should reflect the misconfiguration correctly, i.e. "Invalid topic specified", etc. The current message is incorrect and may lead the developer on a goose chase.

**Comment by dominicbarnes** [comment]
Thanks for the report, I'll try and take a look at this sometime this week.

**Comment by Neal** [comment]
I just came across this as well but not because the Topic field was set on both the Writer and the Message, but because it was not set on either.

**Comment by dominicbarnes** [comment]
This confusing situation was my fault, I should not be returning `InvalidMessage` as that's an Kafka API error code, which is obviously not what is wrong here. I'll be fixing this with #650
