### ISSUE TITLE
Reader.ReadMessage:  data may be lose when use context with timeout

### ISSUE THREAD

**Issue by marcodapper** [segmentio/kafka-go#622]
**Describe the bug**
I use Reader.ReadMessage to consume Kafka data by setting context with timeout.  I get a piece of data. When Kafka automatically commits, the timeout occurs. The Kafka submission fails, but the Reader.offset is not rollback, resulting in data loss

**Expected behavior**
If kafka commits fail due to the context timeout and get a data , the offset will be rolled back

**Comment by xigang** [comment]
the same problem

**Comment by achille-roussel** [comment]
Hello @marcodapper, thanks for opening this issue!

I left an answer on https://github.com/segmentio/kafka-go/issues/626 which seems related to your question here, let me know if this helps.

**Comment by achille-roussel** [comment]
Closing as we will track this issue in #629
