### ISSUE TITLE
The function used by SASL Support Example were marked as deprecated 

### ISSUE THREAD

**Issue by HuKeping** [segmentio/kafka-go#623]
Both of `kafka.NewWriter` and `kafka.WriterConfig` are marked as **deprecated**,  so how can I instantiate a `Writer`  with SASL when there is not such a field I can use in the struct of `Writer`

**Comment by achille-roussel** [comment]
Thanks for opening the issue @HuKeping!

The SASL configuration being related to connection management, the intention is that it would be configured on the kafka.Transport that the kafka.Writer uses https://pkg.go.dev/github.com/segmentio/kafka-go#Transport

By default, [kafka.DefaultTransport](https://pkg.go.dev/github.com/segmentio/kafka-go#RoundTripper) is used, you could set the SASL configuration there if you want it applied by default.

Let me know if you have other questions!

**Comment by HuKeping** [comment]
Would this work @achille-roussel ?
```
kafka.DefaultTransport = &Transport{
	Dial: (&net.Dialer{
		Timeout:   3 * time.Second,
		DualStack: true,
                SASLMechanism: plain.Mechanism{
                                        Username:  "admin",
                                        Password:  "pwd",
                },
	}).DialContext,
}


// make a writer that produces to topic-A, using the least-bytes distribution
w := &kafka.Writer{
	Addr:     kafka.TCP("localhost:9092"),
	Topic:   "topic-A",
	Balancer: &kafka.LeastBytes{},
}

err := w.WriteMessages(context.Background(),
	kafka.Message{
		Key:   []byte("Key-A"),
		Value: []byte("Hello World!"),
	},
)

```

**Comment by achille-roussel** [comment]
I believe this is how you would construct the transport:

```go
kafka.DefaultTransport = &kafka.Transport{
	Dial: (&net.Dialer{
		Timeout:   3 * time.Second,
		DualStack: true,
	}).DialContext,
        SASL: plain.Mechanism{
                  Username:  "admin",
                 Password:  "pwd",
        },
}
```
(the `SASL` parameter is a field of `kafka.Transport`)

**Comment by HuKeping** [comment]
It works, thanks @achille-roussel 

Do you think it's worth  adding a wrapper to set the SASL rather than setting the raw `DefaultTransport ` ?

**Comment by achille-roussel** [comment]
Glad to hear it worked 👍 

Setting the default transport is not mandatory, you could configure it on the writer as well:
```go
var TransportWithSASL = &kafka.Transport{
  ...
  SASL: plain.Mechanism{
    Username:  "admin",
    Password:  "pwd",
   }
}

...

w := &kafka.Writer{
  Transport: TransportWithSASL, // only writers that need SASL will use this transport, others are unaffected
}
```

**Comment by HuKeping** [comment]
Thanks  @achille-roussel , I think it's OK to close this issue now .
