### ISSUE TITLE
What to poll for creating a topic

### ISSUE THREAD

**Issue by justinrush** [segmentio/kafka-go#624]
**Describe the solution you'd like**
The existing documentation for creating a topic instructs you to create a connection to the leader and call CreateTopics on the Conn object. I routinely see writers starting up right after creating the topic return with an error from the broker that the topic or partition doesn't exist. I get that its an async call, but what's the best way to wait for it to finish? It seems like subsequent calls to the leader to see if the topic exists return true right away... do I need to open a connection to each broker and call ReadPartitions on those too?

Or is doing something like checking the kafka.Partition.Isr() for the desired replication count and waiting for that equal what I asked for?

I think the documentation should reflect this answer as an example.

**Comment by justinrush** [comment]
I wrote a wrapper for create that attempts to publish and consume a "ping" message prior to asserting that the topic is created. It feels heavy handed and a bit dirty, so if there is a better way, please let me know (bonus if its some magical method I can't find that allows me to pass in a channel...)

**Comment by godwhoa** [comment]
Another heavy handed approach might be to watch for path creation on zookeeper([you get a channels api](https://pkg.go.dev/launchpad.net/gozk/zookeeper#Conn.ExistsW)). 
Kafka creates this path `/brokers/topics/<topic_name>` in zookeeper per topic with metadata in it.
You could use this approach for topic deletion as well.

**Comment by achille-roussel** [comment]
If this is helpful, we have code in our test suite to poll for topic creation (which is asynchronous in Kafka). We create a lot of temporary topics to run the tests on and this is working fairly well: https://github.com/segmentio/kafka-go/blob/master/client_test.go#L36-L68

I'm not sure I would recommend messing with Zookeeper directly, as I believe Kafka is in the process of removing their dependency on Zookeeper, which could shorten the lifetime of this approach.

**Comment by justinrush** [comment]
> If this is helpful, we have code in our test suite to poll for topic creation (which is asynchronous in Kafka). We create a lot of temporary topics to run the tests on and this is working fairly well: https://github.com/segmentio/kafka-go/blob/master/client_test.go#L36-L68
> 

this is exactly what i was looking for - tossing that into the faq or readme probably makes sense, unless this is just something I'm hung up on and just needed the example :)

**Comment by achille-roussel** [comment]
Yeah that's a good suggestion 👍 

If you're feeling inspired to add these examples, we always welcome contributions!

**Comment by achille-roussel** [comment]
Closing because we believe the original question has been answered, feel free to reopen if you need to discuss this further.
