### ISSUE TITLE
reader ReadMessage cause data loss

### ISSUE THREAD

**Issue by MacroXJTU** [segmentio/kafka-go#626]
func (r *Reader) ReadMessage(ctx context.Context) (Message, error) {
	m, err := r.FetchMessage(ctx)
	if err != nil {
		return Message{}, err
	}

	if r.useConsumerGroup() {
		if err := r.CommitMessages(ctx, m); err != nil {
		         //here, FetchMessage Succeed but CommitMessages succeed after ctx timeout cause data loss
			return Message{}, err
		}
	}

	return m, nil
}

**Comment by achille-roussel** [comment]
Hello @MacroXJTU 

Even if `CommitMessages` respects the context timeout, it is possible that the application fails to process the message, even tho it was already committed by the reader. Attempting to _fix_ the behavior of `ReadMessage` will not solve the issue.

Applications that require stronger guarantees should use `FetchMessage` and `CommitMessages` explicitly instead, which is what we documented: https://pkg.go.dev/github.com/segmentio/kafka-go#Reader.ReadMessage

> If consumer groups are used, ReadMessage will automatically commit the offset when called. Note that this could result in an offset being committed before the message is fully processed.
> 
> If more fine grained control of when offsets are committed is required, it is recommended to use FetchMessage with CommitMessages instead.

Please let me know if you have suggestions on how to improve the `ReadMessage` API.

**Comment by MacroXJTU** [comment]
get it.

i modify ReadMessage and use two diffrent context with timeout to  control FetchMessage and CommitMessages insted.

the context with timeout for CommitMessages  is large than 500(0+1*1*100 +2*2*100) ms, 550ms for example.

my modification is not elegant ,but guarantees no data loss,  enough for myself.

thanks.

**Comment by Czytx** [comment]
After ctx timeout,  recreated reader can solve this problem?
