### ISSUE TITLE
proposal: allow offsets to be specified by time instead of just -1, -2

### ISSUE THREAD

**Issue by savaki** [segmentio/kafka-go#63]
As of kafka 0.10, specifying offsets by time is now possible. Would be nice to add support for this. 

Here's our use case.  We have a number of services that provide real time analytics.  When the service boots, it reads content from Kafka and generates an in memory view of today stats.  As new events arrive, the stats are updated.  Currently, since there is no time based offset, we read from the old offset and replay, ignore all events that aren't today.  To support that, we've made the time retention of the topic short.  Instead, we'd like a longer time retention and the ability to say start from midnight.

My suggestion would be to add a SetOffsetTime to Reader.

**Comment by achille-roussel** [comment]
That sounds fine 👍 

What do you think about adding a `ReadOffsetAt(t time.Time) (offset int64, err error)` method to the `Conn` type as well?

**Comment by savaki** [comment]
Sounds good.

**Comment by achille-roussel** [comment]
@savaki do you still want to make this happen?

**Comment by achille-roussel** [comment]
This has been implemented a while ago, closing.
