### ISSUE TITLE
Reader read message at specific offset

### ISSUE THREAD

**Issue by ericfengchao** [segmentio/kafka-go#639]
**Describe the solution you'd like**
instead of reading the next message, it would be better to read the current message at specified offset, including FirstOffset(-2) and LatestOffset(-1). 

Currently, i cannot find any way to find out the current exact offset of partition and do binary search on the whole partition.

**Comment by achille-roussel** [comment]
Hello @ericfengchao.

`kafka.Reader` may not be the ideal API for what you attempt to achieve, it is optimized for streaming use cases.

Have you looked at using `kafka.Client` and the `Fetch` method?

**Comment by achille-roussel** [comment]
Closing because we believe the original question has been answered, feel free to reopen if this needs further clarifications.
