### ISSUE TITLE
proposal: refresh consumer groups

### ISSUE THREAD

**Issue by savaki** [segmentio/kafka-go#64]
As I understand it, the max age of an offset stored by Kafka is defined by the broker via offsets.retention.minutes.  If this value is -1, then the consumer is allowed to specify the offset retention time.  If you're working with your own brokers, then this is fine.  

However, if you're working with a hosted kafka provider like confluent, heroku, or aiven, this isn't so good as you don't have control over broker configuration.  The proposed solution is to have the consumer write its offsets, even when they haven't changed.

The question for me is what the frequency should be.  Seems like there are two logical options:

1. Reuse CommitInterval to specify the consumer should commit offsets that frequently regardless of whether new messages have been received. So every CommitInterval, all the known offsets are committed.

2. Specify another parameter, CommitKeepAliveInterval, that specifies the interval for this task.

I lean towards the later, creating a CommitKeepAliveInterval.

Internally, kafka uses a topic to keep track of offsets.  So if we had W consumer groups over X topics with Y partitions publishing at 1s retained for Z days, the broker (when restarted) would have to playback roughly W * X * Y * Z * 86400 offsets before being ready. (yes, the math is wrong, but you get the idea)

**Comment by achille-roussel** [comment]
I feel OK about reusing CommitInterval, the number of offsets being committed is usually small enough that it should have no performance impact. I'd prefer not exposing yet another configuration option that control something that most programs will never have to deal with.

We'd probably need some default value tho because we use a zero CommitInterval to make the commits synchronous.

**Comment by achille-roussel** [comment]
Sounds good to me 👍

**Comment by achille-roussel** [comment]
@savaki do you still want to make this happen?

**Comment by achille-roussel** [comment]
We'll close this due to inactivity, but feel free to reopen if it deserves to be looked at again.
