### ISSUE TITLE
Document developer workflow

### ISSUE THREAD

**Issue by benmathews** [segmentio/kafka-go#642]
The unit tests obviously require a kafka cluster to exercise as they fail without one. I found the docker-compose files in the project root but neither the default `docker-compose.yml` or `docker-compose-241.yml` provide a cluster that results in passing tests. 

I would expect instructions in `README.md` on how to start a reference cluster that gets success when running `go test`.

I'm running go 1.16.2 on Ubuntu 20.4 if that matters

**Comment by godwhoa** [comment]
So the flaky test seems to be `TestConn/nettest` which they [skip in the CI](https://github.com/segmentio/kafka-go/blob/master/.circleci/config.yml#L177-L188).
There are [certain tests](https://github.com/segmentio/kafka-go/blob/9cb6db918c3b84d0f50788c550fa0f7a5706c9b5/describegroups_test.go#L58) which get skipped based on `KAFKA_VERSION`.
So, to test locally:
```bash
docker-compose up -d
export KAFKA_SKIP_NETTEST=1
export KAFKA_VERSION=2.3.1
go test -race -cover ./...
```
A simple Makefile would be nice, want make a PR for that if the maintainers are ok with it.

**Comment by benmathews** [comment]
I'll verify this and make up a PR with the suggested Makefile and a "Developers" note at the bottom of the readme.

**Comment by achille-roussel** [comment]
@benmathews we test kafka-go against multiple kafka versions to ensure it remains backwards-compatible. In our experience, kafka clusters tend to be time consuming to upgrade, we want to maintain compatibility to avoid adding problems to programs that likely already have enough issues to deal with.

The reason we aren't testing against versions later than 2.4.1 is that we just haven't had the need to, nor received a patch to add tests against newer kafka versions (we would welcome one).

**Comment by achille-roussel** [comment]
Closing because we believe the original question has been answered, feel free to reopen if you need to discuss this further.
