### ISSUE TITLE
Check if the Writer is closed

### ISSUE THREAD

**Issue by Veneciaaa** [segmentio/kafka-go#655]
Export the isClosed() function on the Writer: https://github.com/segmentio/kafka-go/blob/master/writer.go#L852
I have an app that seems to be having race conditions related to closing & recreating a Writer. It would be nice to be able to check if the Writer is open before trying to call WriteMessages.

**Comment by dominicbarnes** [comment]
Simply exposing this method won't actually address a race condition like I'm imagining, as it is entirely possible to have the writer be closed after you check on this status and before you write your next batch of messages. (admittedly the window is small, but it's not really the point)

Your best mechanism to respond to this is to check for an error being returned by the `Writer`, which [in this case is `io.ErrClosedPipe`](https://github.com/segmentio/kafka-go/blob/master/writer.go#L565). Other examples of things that have a close function don't ever expose an "is closed" helper as well, presumably for similar reasons.
