### ISSUE TITLE
Q: Inducing failures in the connection against Kafka

### ISSUE THREAD

**Issue by perbu** [segmentio/kafka-go#660]
Hi.

Thanks for writing this. I've enjoyed working with your API.  <3

During testing I've looked for a way to induce errors into the connection against kafka, testing [my application](https://github.com/Celerway/metamorphosis) ability to handle these properly.

I've decided on using [toxiproxy](https://github.com/Shopify/toxiproxy) to achieve this. I forward a TCP connection to localhost so Kafka is available on port 9092 locally. Then I use toxiproxy to assign a random port. On trad. databases this works well, but Kafka is a smart distributed system and I guess the cluster supplies kafka-go with the port it should use to connect. This way it bypassed toxiproxy.

Is there any way I could get kafka-go to ignore the `advertised_kafka_api` that it gets from the broker? So I could force it through toxiproxy?

Other tips on alternative ways of inducing errors are welcome. I'm new to this so I might be missing something obvious.

All the best,
Per.

**Comment by dominicbarnes** [comment]
Sorry about the delayed response here.

Something that comes to mind is using a custom `Dialer` to handle opening the connections, particularly the `Resolver` parameter, as that can override the broker host with something else. This is usually used for custom service-discovery protocols, but it might fit this use-case as well.

Let me know if you want to discuss this further, we can re-open the ticket if desired.

**Comment by perbu** [comment]
For posterity; I ended up doing was to use https://github.com/pingcap/failpoint in order to induce errors. It's not perfect but it made it simple to induce all sort of errors and performance condition and see that I would handle them.

The downside is that I had to add code to induce these errors, but I can live with that.
