### ISSUE TITLE
Would you be open to a pull request which describes how to close connections?

### ISSUE THREAD

**Issue by jrwren** [segmentio/kafka-go#667]
**Describe the solution you'd like**
The high level Reader and Writer types are excellent. As a first time Kafka user I had some surprises. I would like to expand either README or package level godoc to spell out things about groupid and closing connections. I did not know that the kafka server is stateful and the importance of closing the connection.

**Supporting documentation**
unsure about this.

Would such a PR be welcome? Is there preference for README or package level godoc or both?

**Comment by achille-roussel** [comment]
@jrwren thanks for starting the discussion!

Would you be able to describe in more details the documentation you would like to add? Calling `Close` on Reader instances should close the underlying connections for example.

Anyways, feel free to open a PR, we can continue the discussion there then.

**Comment by jrwren** [comment]
I'll try writing something and opening a PR.

The gist of it is: During the dev cycle we were creating readers and terminating our processes without closing the reader. When we would start again, the newly started processes creating readers and trying to read events for a groupid from kafka would not receive anything for a while. Eventually we figured out that kafka was still trying to send to the previously connected processes which hadn't cleanly disconnected.

**Comment by jrwren** [comment]
update: yesterday ran into an issue where k8s kills processes with SIGTERM but we were only handling SIGINT and so we didn't properly close our reader.
