### ISSUE TITLE
Can I pause consuming on the topic partition without causing rebalance？

### ISSUE THREAD

**Issue by GeraltXLi** [segmentio/kafka-go#669]
I want to create a delayed queue, which is based on Kafka, and I do not want to change MaxWait.
For I just want consumer hold this partition instead of giving it to another consumer, which will still pause consuming because of the condition of message

**Comment by achille-roussel** [comment]
Hello @FakerGit, thanks for opening this issue!

Your program should not have to read messages to be part of a consumer group, if it sleeps before calling `ReadMessage` or `FetchMessage` (on a Reader for example), Kafka will not be pushing messages, offsets won't get committed, so it should achieve the "pause" behavior that you are looking for.

Let us know if the answer was helpful.

**Comment by FakerGit** [comment]
Thank you for your reply.
If I use Reader with consumer group, can I `FetchMessage` from each partition?
Because I want to implement a delayed queue, I need to pull the latest data for each partition and make a determination on whether each partition has reached the processable time. But it seems that the documentation does not distinguish between partitions.

**Comment by FakerGit** [comment]
> Hello @FakerGit, thanks for opening this issue!
> 
> Your program should not have to read messages to be part of a consumer group, if it sleeps before calling `ReadMessage` or `FetchMessage` (on a Reader for example), Kafka will not be pushing messages, offsets won't get committed, so it should achieve the "pause" behavior that you are looking for.
> 
> Let us know if the answer was helpful.

Also, if it stops `FetchMessage`, does it have to set a larger MaxWait  so that zookeeper doesn't think the consumer is no longer alive?

**Comment by achille-roussel** [comment]
It seems like using `kafka.Reader` may not be the right approach for your use case.

Have you looked at the `kafka.ConsumerGroup` API that the package exposes? Maybe pairing it with `kafka.Conn` or `kafka.Client` to gain greater control over the timing of fetches and commits?

**Comment by GeraltXLi** [comment]
Thank you very much for your reply. I have set a larger MaxWait.
