### ISSUE TITLE
Got error when use writer to write msg to kafka

### ISSUE THREAD

**Issue by dayeguilaiye** [segmentio/kafka-go#679]
version: 0.4.13
log: `Unknown Topic Or Partition: the request is for a topic or partition that does not exist on this broker`

https://github.com/segmentio/kafka-go/blob/118456fc0b17c08b2c9ae31b1215ffa1acc45078/writer.go#L836-L846
I found that this line says: "this should always hit, unless kafka has a bug."
Is this describing [if t.Name == topic] or [if t.ErrorCode != 0].

In my opinion, it seems like describing  [if t.ErrorCode != 0]. But does that means, this function will always return error?
If it is describing  [if t.Name == topic], does that mean the program should never go to `return 0, UnknownTopicOrPartition?`

**Comment by dayeguilaiye** [comment]
Can writer.WriteMessages() create topic automatically?
I have already set auto create topic to true in kafka service.
And when I use kafka.DialLeader() and conn.WriteMessages(), the topic can be created automatically.
But the writer.WriteMessages() can't, and returns an error: "Unknown Topic Or Partition: the request is for a topic or partition that does not exist on this broker"

**Comment by derekbassett** [comment]
Thanks for the question.  
Please review this section of the documentation.

https://github.com/segmentio/kafka-go#to-create-topics

So you will need to include
```
// to create topics when auto.create.topics.enable='true'
conn, err := kafka.DialLeader(context.Background(), "tcp", "localhost:9092", "my-topic", 0)
if err != nil {
    panic(err.Error())
}
```
if you want your topics created automatically.

**Comment by ngMinhDan** [comment]
My team use this library but not clear, Thanks Sir
