### ISSUE TITLE
how to dial by pem file 

### ISSUE THREAD

**Issue by gozelus** [segmentio/kafka-go#680]
**Describe the solution you'd like**
I want to connect kafka with sasl_ssl, now i have a ca.pem file, pwd and username . how should i do ?

**Comment by xdsxc** [comment]
Hi @gozelus 

You can see examples of our SASL support here: https://github.com/segmentio/kafka-go#sasl-support
That will get you SASL either using PLAIN or SCRAM mechanisms. 

Then you can setup TLS in the dialer by setting the TLS config. See the examples here: https://github.com/segmentio/kafka-go#tls-support

**Comment by xdsxc** [comment]
Closing this issue - feel free to reopen if you have further questions.
