### ISSUE TITLE
v0.4 Writer does not preserve order of messages

### ISSUE THREAD

**Issue by xuyangch** [segmentio/kafka-go#686]
**Describe the bug**
When writing multiple messages using kafka.Writer, multiple batches will be created, and those batches will be processed asynchronously, causing messages to arrive Kafka in random order. e.g. If I write message 1, 2, 3 in one WriteMessages call, then we may create three batches for message 1, 2, 3 and they will reach Kafka in the order of 2, 3, 1.

**Kafka Version**
2.6.0

**To Reproduce**
Start Kafka locally using default configs, create a topic "test-topic", then use this code snippet:
```
package bugreport_test

import (
	"context"
	"math/rand"
	"strconv"
	"testing"
	"time"

	"github.com/golang/glog"
	"github.com/segmentio/kafka-go"
)

type balancer int

func (b balancer) Balance(msg kafka.Message, partitions ...int) (partition int) {
	return 0
}

func NewMessage(size int, key, topic string) kafka.Message {
	return kafka.Message{
		Key:     []byte(key),
		Value:   messageValue(size),
		Headers: []kafka.Header{},
		Time:    time.Now(),
	}
}

func messageValue(size int) []byte {
	val := make([]byte, size)
	for i := 0; i < size; i++ {
		val[i] = byte(random(0, 9))
	}
	return val
}

func random(min int, max int) int {
	return rand.Intn(max-min) + min
}

func TestWriter(t *testing.T) {
	wr := kafka.NewWriter(kafka.WriterConfig{
		Brokers:      []string{"localhost:9092"},
		Topic:        "test-topic",
		Dialer:       kafka.DefaultDialer,
		BatchSize:    1000,
		BatchTimeout: 500 * time.Millisecond,
		Balancer:     balancer(0),
	})
	var msgs = []kafka.Message{
		NewMessage(950000, "1", "test-topic"),
		NewMessage(950000, "2", "test-topic"),
		NewMessage(950000, "3", "test-topic"),
		NewMessage(950000, "4", "test-topic"),
		NewMessage(950000, "5", "test-topic"),
		NewMessage(950000, "6", "test-topic"),
		NewMessage(950000, "7", "test-topic"),
		NewMessage(950000, "8", "test-topic"),
		NewMessage(950000, "9", "test-topic"),
		NewMessage(950000, "10", "test-topic"),
	}
	rdr := kafka.NewReader(kafka.ReaderConfig{
		Brokers:     []string{"localhost:9092"},
		Topic:       "test-topic",
		Dialer:      kafka.DefaultDialer,
		GroupID:     strconv.FormatInt(time.Now().Unix(), 10),
		StartOffset: kafka.LastOffset,
	})
	ctx, _ := context.WithTimeout(context.Background(), 100*time.Second)
	go func() {
		for {
			msg, err := rdr.ReadMessage(ctx)
			if err != nil {
				glog.Errorf("err read msg: %s", err.Error())
			} else {
				glog.Infof("receive msg: key: %s, offset: %d", string(msg.Key), msg.Offset)
			}
		}
	}()
	time.Sleep(3 * time.Second)
	err := wr.WriteMessages(ctx, msgs...)
	if err != nil {
		glog.Errorf("err write msg: %s", err.Error())
	} else {
		glog.Info("write complete")
	}
	time.Sleep(10 * time.Second)
}
```
Run the test using ```go test -v './...' --logtostderr --v=1```, you will see something like:

I0622 14:36:34.674736 kafka-go_test.go:69] receive msg: key: 2, offset: 36
I0622 14:36:34.780102 kafka-go_test.go:69] receive msg: key: 7, offset: 37
I0622 14:36:34.885081 kafka-go_test.go:69] receive msg: key: 3, offset: 38
I0622 14:36:34.990090 kafka-go_test.go:69] receive msg: key: 5, offset: 39
I0622 14:36:35.095683 kafka-go_test.go:69] receive msg: key: 8, offset: 40
I0622 14:36:35.200772 kafka-go_test.go:69] receive msg: key: 6, offset: 41
I0622 14:36:35.303842 kafka-go_test.go:69] receive msg: key: 9, offset: 42
I0622 14:36:35.409054 kafka-go_test.go:69] receive msg: key: 4, offset: 43
I0622 14:36:35.530030 kafka-go_test.go:69] receive msg: key: 1, offset: 44
I0622 14:36:35.634247 kafka-go_test.go:69] receive msg: key: 10, offset: 45

**Expected behavior**
Since we call WriteMessages() in the order of 1 to 10, we expect to see
I0622 14:36:34.674736 kafka-go_test.go:69] receive msg: key: 1, offset: 36
I0622 14:36:34.780102 kafka-go_test.go:69] receive msg: key: 2, offset: 37
I0622 14:36:34.885081 kafka-go_test.go:69] receive msg: key: 3, offset: 38
I0622 14:36:34.990090 kafka-go_test.go:69] receive msg: key: 4, offset: 39
I0622 14:36:35.095683 kafka-go_test.go:69] receive msg: key: 5, offset: 40
I0622 14:36:35.200772 kafka-go_test.go:69] receive msg: key: 6, offset: 41
I0622 14:36:35.303842 kafka-go_test.go:69] receive msg: key: 7, offset: 42
I0622 14:36:35.409054 kafka-go_test.go:69] receive msg: key: 8, offset: 43
I0622 14:36:35.530030 kafka-go_test.go:69] receive msg: key: 9, offset: 44
I0622 14:36:35.634247 kafka-go_test.go:69] receive msg: key: 10, offset: 45

**Additional context**
We are using kafka-go v0.4.16

**Comment by godwhoa** [comment]
Wouldn't each of those messages go into different partitions?

**Comment by chyacinth** [comment]
> Wouldn't each of those messages go into different partitions?

I just updated the writer to use a balancer that always returns partition 0 and got the same issue.

**Comment by vtolstov** [comment]
any news?

**Comment by rhansen2** [comment]
Hello,
Thank you for your patience.

The kafka.Writer type does not make any guarantees of message ordering, especially across batches. If more control of message ordering is needed, the lower level Produce API of the kafka.Client type can be used.

**Comment by robfig** [comment]
@rhansen2 I hope you might reconsider. No longer respecting ordering of messages in a single batch is a big breaking change and it seems like an unnecessary contract to break with clients. We have a lot of usage of your library, and we will need to fork or move to a different library, which is pretty disappointing.

**Comment by rhansen2** [comment]
I appreciate the feedback on this issue. 
We're working on a fix to preserve message ordering across batches.

Thanks!

**Comment by robfig** [comment]
This is great news, thank you 🙏

**Comment by rhansen2** [comment]
We believe we have a fix implemented for this issue at https://github.com/rhansen2/kafka-go/tree/686-writer-message-order . Would anyone be willing to try out that branch and let us know if you encounter any issues?

**Comment by rhansen2** [comment]
Hi @robfig, have you had any issues with the https://github.com/rhansen2/kafka-go/tree/686-writer-message-order  branch?

**Comment by robfig** [comment]
Confirmed working, thank you

**Comment by lishunan246** [comment]
> **Describe the bug** When writing multiple messages using kafka.Writer, multiple batches will be created, and those batches will be processed asynchronously, causing messages to arrive Kafka in random order. e.g. If I write message 1, 2, 3 in one WriteMessages call, then we may create three batches for message 1, 2, 3 and they will reach Kafka in the order of 2, 3, 1.
> 
> **Kafka Version** 2.6.0
> 
> **To Reproduce** Start Kafka locally using default configs, create a topic "test-topic", then use this code snippet:
> 
> ```
> package bugreport_test
> 
> import (
> 	"context"
> 	"math/rand"
> 	"strconv"
> 	"testing"
> 	"time"
> 
> 	"github.com/golang/glog"
> 	"github.com/segmentio/kafka-go"
> )
> 
> type balancer int
> 
> func (b balancer) Balance(msg kafka.Message, partitions ...int) (partition int) {
> 	return 0
> }
> 
> func NewMessage(size int, key, topic string) kafka.Message {
> 	return kafka.Message{
> 		Key:     []byte(key),
> 		Value:   messageValue(size),
> 		Headers: []kafka.Header{},
> 		Time:    time.Now(),
> 	}
> }
> 
> func messageValue(size int) []byte {
> 	val := make([]byte, size)
> 	for i := 0; i < size; i++ {
> 		val[i] = byte(random(0, 9))
> 	}
> 	return val
> }
> 
> func random(min int, max int) int {
> 	return rand.Intn(max-min) + min
> }
> 
> func TestWriter(t *testing.T) {
> 	wr := kafka.NewWriter(kafka.WriterConfig{
> 		Brokers:      []string{"localhost:9092"},
> 		Topic:        "test-topic",
> 		Dialer:       kafka.DefaultDialer,
> 		BatchSize:    1000,
> 		BatchTimeout: 500 * time.Millisecond,
> 		Balancer:     balancer(0),
> 	})
> 	var msgs = []kafka.Message{
> 		NewMessage(950000, "1", "test-topic"),
> 		NewMessage(950000, "2", "test-topic"),
> 		NewMessage(950000, "3", "test-topic"),
> 		NewMessage(950000, "4", "test-topic"),
> 		NewMessage(950000, "5", "test-topic"),
> 		NewMessage(950000, "6", "test-topic"),
> 		NewMessage(950000, "7", "test-topic"),
> 		NewMessage(950000, "8", "test-topic"),
> 		NewMessage(950000, "9", "test-topic"),
> 		NewMessage(950000, "10", "test-topic"),
> 	}
> 	rdr := kafka.NewReader(kafka.ReaderConfig{
> 		Brokers:     []string{"localhost:9092"},
> 		Topic:       "test-topic",
> 		Dialer:      kafka.DefaultDialer,
> 		GroupID:     strconv.FormatInt(time.Now().Unix(), 10),
> 		StartOffset: kafka.LastOffset,
> 	})
> 	ctx, _ := context.WithTimeout(context.Background(), 100*time.Second)
> 	go func() {
> 		for {
> 			msg, err := rdr.ReadMessage(ctx)
> 			if err != nil {
> 				glog.Errorf("err read msg: %s", err.Error())
> 			} else {
> 				glog.Infof("receive msg: key: %s, offset: %d", string(msg.Key), msg.Offset)
> 			}
> 		}
> 	}()
> 	time.Sleep(3 * time.Second)
> 	err := wr.WriteMessages(ctx, msgs...)
> 	if err != nil {
> 		glog.Errorf("err write msg: %s", err.Error())
> 	} else {
> 		glog.Info("write complete")
> 	}
> 	time.Sleep(10 * time.Second)
> }
> ```
> 
> Run the test using `go test -v './...' --logtostderr --v=1`, you will see something like:
> 
> I0622 14:36:34.674736 kafka-go_test.go:69] receive msg: key: 2, offset: 36 I0622 14:36:34.780102 kafka-go_test.go:69] receive msg: key: 7, offset: 37 I0622 14:36:34.885081 kafka-go_test.go:69] receive msg: key: 3, offset: 38 I0622 14:36:34.990090 kafka-go_test.go:69] receive msg: key: 5, offset: 39 I0622 14:36:35.095683 kafka-go_test.go:69] receive msg: key: 8, offset: 40 I0622 14:36:35.200772 kafka-go_test.go:69] receive msg: key: 6, offset: 41 I0622 14:36:35.303842 kafka-go_test.go:69] receive msg: key: 9, offset: 42 I0622 14:36:35.409054 kafka-go_test.go:69] receive msg: key: 4, offset: 43 I0622 14:36:35.530030 kafka-go_test.go:69] receive msg: key: 1, offset: 44 I0622 14:36:35.634247 kafka-go_test.go:69] receive msg: key: 10, offset: 45
> 
> **Expected behavior** Since we call WriteMessages() in the order of 1 to 10, we expect to see I0622 14:36:34.674736 kafka-go_test.go:69] receive msg: key: 1, offset: 36 I0622 14:36:34.780102 kafka-go_test.go:69] receive msg: key: 2, offset: 37 I0622 14:36:34.885081 kafka-go_test.go:69] receive msg: key: 3, offset: 38 I0622 14:36:34.990090 kafka-go_test.go:69] receive msg: key: 4, offset: 39 I0622 14:36:35.095683 kafka-go_test.go:69] receive msg: key: 5, offset: 40 I0622 14:36:35.200772 kafka-go_test.go:69] receive msg: key: 6, offset: 41 I0622 14:36:35.303842 kafka-go_test.go:69] receive msg: key: 7, offset: 42 I0622 14:36:35.409054 kafka-go_test.go:69] receive msg: key: 8, offset: 43 I0622 14:36:35.530030 kafka-go_test.go:69] receive msg: key: 9, offset: 44 I0622 14:36:35.634247 kafka-go_test.go:69] receive msg: key: 10, offset: 45
> 
> **Additional context** We are using kafka-go v0.4.16

Since the patch size is 1000, wouldn't those messages get in the same patch?

**Comment by simonrad** [comment]
Hi, this is a cool feature, but it would be nice to be able to disable this new feature.

In our use case, we care a lot about latency (and don't need order to be preserved). So having multiple batches in flight at once is actually really beneficial to us (as it improves latency dramatically to not have to wait for the previous batch to complete). Do you have any suggestions for how to achieve multiple parallel batches with this new version of the Writer?

Thanks!
