### ISSUE TITLE
proposal: WriterStats

### ISSUE THREAD

**Issue by jonasrmichel** [segmentio/kafka-go#69]
Is there any particular reason there isn't an analog to the `ReaderStats` type for `Writer`s (e.g., `WriterStats`)? Statistics tracking on the writer side would be helpful for applications that both produce and consume messages using this library.

**Comment by achille-roussel** [comment]
There isn't other than the use case never came up, in production we took the approach to have a single service producing to a topic, so the stats that kafka provides give us enough insights. If this is useful to you I'll be happy to review and merge a pull request that adds this feature 👍

**Comment by jonasrmichel** [comment]
Please double check my work. It feels like my eyes are bleeding. :)

I attempted to provide the same amount of connection-level statistics as are captured by `ReaderStats`. I also did my best to capture and expose writer-level metrics of interest to a user. I have my own use cases in mind, but it's possible I missed something basic.

**Comment by achille-roussel** [comment]
It looked good, we can still iterate on it if there are details to adjust.
