### ISSUE TITLE
Consumer Offset no commit!

### ISSUE THREAD

**Issue by freeoa** [segmentio/kafka-go#693]
**Describe the bug**
Consumer Offset no commit。

![image](https://user-images.githubusercontent.com/157936/124273329-73c55900-db72-11eb-8552-ff436b48a058.png)

**Kafka Version**
What version(s) of Kafka are you testing against?
2.2.0

**To Reproduce**
Steps to reproduce the behavior.  Bonus points for a code sample.
```go
cgf := kg.ConsumerGroupConfig{
		Brokers:               c.brokers,
		ID:                    groupId,
		WatchPartitionChanges: true,
		Topics:                []string{topic},
	}
	offsetReader := callback.GetOffset(topic)
	group, err := kg.NewConsumerGroup(cgf)
	if err != nil {
		errors(err)
		return
	}
	//defer group.Close()
	gen, err := group.Next(ctx)
	if err != nil {
		errors(err)
		return
	}
	assignments := gen.Assignments[topic]
	for _, assignment := range assignments {
		partition := assignment.ID
		if _, ok := offsetReader[partition]; !ok {
			offsetReader[partition] = assignment.Offset
		}
	}
	err = gen.CommitOffsets(map[string]map[int]int64{
		topic: offsetReader,
	})
	if err != nil {
		errors(err)
	}
	c.reader = kg.NewReader(kg.ReaderConfig{
		Brokers:               c.brokers,
		GroupID:               groupId,
		Topic:                 topic,
		WatchPartitionChanges: true,
		MinBytes:              2e3, // 10KB
		MaxBytes:              5e6, // 10MB
	})
	go func() {
		for {
			if msg, err := c.reader.FetchMessage(ctx); err == nil {
//do something.
				if err := c.reader.CommitMessages(ctx, msg); err != nil {
						log.Printf("commit messages :%+v\n", err)
				}
			} else {
				log.Printf("read message has error:%+v\n", err)
			}
		}
	}()
	c.started = true
```
**Expected behavior**
this client is java
```xml
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
            <version>1.1.1</version>
        </dependency>
```
![image](https://user-images.githubusercontent.com/157936/124273650-dae30d80-db72-11eb-80db-65f11dc8dc28.png)

**Additional context**

**Comment by vtolstov** [comment]
i think that you need commit current offset + 1 , if you commit current offset you don't move to next message

**Comment by freeocs** [comment]
```go
kafka-go also supports explicit commits. Instead of calling ReadMessage, call FetchMessage followed by CommitMessages.

ctx := context.Background()
for {
    m, err := r.FetchMessage(ctx)
    if err != nil {
        break
    }
    fmt.Printf("message at topic/partition/offset %v/%v/%v: %s = %s\n", m.Topic, m.Partition, m.Offset, string(m.Key), string(m.Value))
    if err := r.CommitMessages(ctx, m); err != nil {
        log.Fatal("failed to commit messages:", err)
    }
}
````
Seeing that the document in the readme does not use offset+1, is this sure to be the case?

**Comment by vtolstov** [comment]
https://github.com/segmentio/kafka-go/blob/master/example_consumergroup_test.go#L49
https://kafka.apache.org/22/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html#:~:text=Note%3A%20The%20committed%20offset%20should,of%20the%20last%20message%20processed

**Comment by vtolstov** [comment]
```
Note: The committed offset should always be the offset of the next message that your application will read. Thus, when calling commitSync(offsets) you should add one to the offset of the last message processed.
```

**Comment by freeocs** [comment]
Why not provide a simpler and smarter processing method? Because it feels that this processing method has more details to be processed than java.

**Comment by achille-roussel** [comment]
@freeoa would be able to share examples of those new APIs you would like to add?

**Comment by achille-roussel** [comment]
I'm going to close this assuming the documentation update in #785 and follow up comments have addressed the original issue. Feel free to reopen if this requires further discussion.
