### ISSUE TITLE
How to get id of the broker I'm connected to?

### ISSUE THREAD

**Issue by bgranvea** [segmentio/kafka-go#697]
I have my own program started with each Kafka node and which is responsible for creating/reconfiguring topics. To avoid concurrency issues, only the program connected to the Kafka controller should do something.

My problem is: how do I get the id of the broker I'm connected to so that I can compare it with conn.Controller()? 

I tried to get the list of all brokers and compare host/port but this is not reliable because of network aliases.

**Comment by achille-roussel** [comment]
Hello @bgranvea, thanks for opening this issue!

We do not currently have APIs to expose the broker ID that a `kafka.Conn` is connected to, but it would be a useful addition.

Would you be able to submit a contribution to add this in?

**Comment by bgranvea** [comment]
hello, I'm not fluent in golang and I don't know Kafka protocol at all but I can try. Can you give me some hints on how to do that? 

I'm not sure how to get the information. I've looked into DescribeConfigs request with ResourceTypeBroker but it seems that you have to provide the brokerId you are requesting. 

Did I miss something?

Thanks.

**Comment by achille-roussel** [comment]
@bgranvea I submitted https://github.com/segmentio/kafka-go/pull/713, let me know if it addresses your issue.

**Comment by bgranvea** [comment]
thanks but I think this doesn't solve my problem. As far as I understand, you set in `Conn.broker` what was given by the caller (`ConnConfig.Broker`).

Here is my use case:
- my go program is embedded in the Kafka container, it waits for Kafka to start and connect with `kafka.Dial("tcp", "localhost:9092")`
- I would like to know if I'm connected to the controller, so my idea was to get my local broker ID and find it in `conn.Controller()`

To get my local broker ID, I tried to compare `conn.RemoteAddr()` with hosts returned by `conn.Brokers()` but obviously it doesn't work because `conn.RemoteAddr()` returns 'localhost' which is not a broker hostname.

I thought it would be easy to obtain this information by API but it seems it isn't.

Maybe my best option is to parse Kafka config file and find `broker.id`. This could work only because I'm running inside Kafka container.

**Comment by achille-roussel** [comment]
🤔 

Can you compare the broker id returned by `Broker` and `Controller` to determine if you're connected to the controller?

Note that this will be racy anyways, the controller may change at any point after the calls, but this is just how Kafka works.

**Comment by bgranvea** [comment]
I finally solved my problem by extracting `broker.id` directly from Kafka config file. Of course this works only because my program runs inside Kafka container, it is not a general solution.

Thanks for your help on this issue.
