### ISSUE TITLE
IPV6 not support

### ISSUE THREAD

**Issue by 751620780** [segmentio/kafka-go#698]
**Describe the bug**
could not connect to kafka when use ipv6 address
Actual measurement：
brokers gives “2020::134” get error:"dial tcp [2020::134:9092]:9092: connect: no route to host"
brokers gives “[2020::134]” get error:"[[2020::134]]:9092: missing port in address"
brokers gives “[2020::134]:9092” get error:"dial tcp [2020::134:9092]:9092: connect: no route to host"

Why always add 9092 to IP address automatically？
```go
rm1 := kafka.NewReader(kafka.ReaderConfig{
		Brokers:          []string{"2020::134"},
		Topic:            topic,
		Partition:        0,
		MinBytes:         1,
		MaxBytes:         10e6,
		JoinGroupBackoff: time.Second * 1,
	})
```

**Comment by 751620780** [comment]
I have debuged kafka, found that file "src/github.com/segmentio/kafka-go/consumergroup.go" with line
```go
address := fmt.Sprintf("%v:%v", out.Coordinator.Host, out.Coordinator.Port)
```
modified to 
```go
address := fmt.Sprintf("[%v]:%v", out.Coordinator.Host, out.Coordinator.Port)
```
could solve this problem.

**Comment by nlsun** [comment]
@751620780 Good catch! Could you try modifying that line to use

https://golang.org/pkg/net/#JoinHostPort
```
address := net.JoinHostPort(out.Coordinator.Host, out.Coordinator.Port)
```


and see if that works for you? You may need to modify a few more places in a similar way but when it works we'll happily take a pull request for the fix

**Comment by vtolstov** [comment]
@nlsun yes, i think net func is better suited for such stuff

**Comment by achille-roussel** [comment]
+1 to replacing the `fmt.Sprintf` call with `net.JoinHostPort` !

**Comment by nlsun** [comment]
Merged https://github.com/segmentio/kafka-go/pull/701, hopefully this is now working

**Comment by 751620780** [comment]
worked successfully
