### ISSUE TITLE
Why is sarama so fast compared to segmentio's kafka-go? 

### ISSUE THREAD

**Issue by alexec** [segmentio/kafka-go#707]
Original issue: https://github.com/Shopify/sarama/issues/1647 and #326

As with everything, I want it to be fast and reliable, but reliably trumps speed every time.

Do you have a feature comparison table?

**Comment by achille-roussel** [comment]
Hello @alexec, thanks for opening this issue.

"fast" is a qualitative metric, could you describe the performance requirements of your application and how you have determined that kafka-go was the bottleneck?

If this is of any use, we employ kafka-go in production and frequently achieve throughput in the 10K msg/s consumed or produced on a single process, sometimes a lot more depending on how much work the program has to do. This is surely "fast enough" for our use cases, but I understand that different systems may need to achieve much higher throughput.

**Comment by alexec** [comment]
Good question. I was getting about 400 TPS with Sarama. With kafka-go (and 200 less LOC) I'm getting 400 TPS reading using kafka-go too (and dumping to a log), but I want to write messages back to another topic. When I add `WriteMessages` into the loop, then TPS drops to 150 TPS. My assuming is that Sarama is committing in batches. I'm going to try different batch sizes and report back.

**Comment by alexec** [comment]
This is not a bug, just need to set configuration correctly.

**Comment by 3AceShowHand** [comment]
> This is not a bug, just need to set configuration correctly.

Hi, can you describe the configuration more in detail, which one is more critical to solve the issue ?
