### ISSUE TITLE
Question: how can I set the starting offset by time

### ISSUE THREAD

**Issue by alexec** [segmentio/kafka-go#710]
Since Kafka 0.10.0 , it maintains a time index for each topic. You can query this to get the correct offset "offsetsForTimes". I'd like to support this is my app, so users can re-run pipelines over the same time period as they tune their model.

How can I do this please?

**Comment by alexec** [comment]
To make this more complex. I'm using a consumer group. So I'm not even sure it is possible to start a consumer group at a specific offset (because of partitions).

**Comment by alexec** [comment]
https://github.com/argoproj-labs/argo-dataflow/issues/110

**Comment by achille-roussel** [comment]
Hello @alexec.

You have two options to lookup the absolute offset associated with a timestamp:
- [`kafka.(*Conn).ReadOffset`](https://pkg.go.dev/github.com/segmentio/kafka-go#Conn.ReadOffset)
- [`kafka.(*Client).ListOffsets`](https://pkg.go.dev/github.com/segmentio/kafka-go#Client.ListOffsets) and specify the timestamp in the [OffsetRequest](https://pkg.go.dev/github.com/segmentio/kafka-go#OffsetRequest) for a topic partition

Once you have resolved the timestamp to an offset, you can use it to fetch messages from the topic partition.

Let me know if this answers your question.

**Comment by achille-roussel** [comment]
Closing as we believe the original question has been answered, feel free to reopen if this needs further discussion.

**Comment by sappusaketh** [comment]
@achille-roussel using any of the above mentioned methods is it possible to get latest offset by timestamp irrespective of partition?
