### ISSUE TITLE
Consume a topic/s but just some partitions

### ISSUE THREAD

**Issue by savsgio** [segmentio/kafka-go#714]
Hi,

I would like to know if i can consume a topic or multiples topics but just some specific partitions with the same Reader (without create a new reader for each partition that i want to consume).

Because in confluent-kafka-go client you could assign the specific topics and partitions that a single consumer connection will consume.

```go
topic1 := "myTopicOne" // Has 8 partitions
topic2 := "myTopicTwo" // Has 5 partitions

assignments := []kafka.TopicPartition{
  {Topic: &topic1, Partition: 0},
  {Topic: &topic1, Partition: 2},
  {Topic: &topic2, Partition: 4},
  {Topic: &topic1, Partition: 7},
}

if err := confluentKafkaGoConsumer.Assign(assignments); err != nil {
  return errors.Wrap(err, "failed to subscribe to the topics")
}
```

**Comment by achille-roussel** [comment]
Hello @savsgio,

Static partition assignment of consumer groups is not a feature that we have implemented in kafka-go, our consumer group APIs currently only support using a coordinator to assign partitions.

You can customize the partition assignment logic by specifying a [`GroupBalancer`](https://pkg.go.dev/github.com/segmentio/kafka-go#GroupBalancer) when [configuring the consumer group](https://pkg.go.dev/github.com/segmentio/kafka-go#ConsumerGroupConfig), tho I am not sure it will solve for what you are trying to do.

Would you be available, we would always welcome a contribution to extend our API footprint to serve new use cases.

**Comment by savsgio** [comment]
Ok, thank you!

I would like to add support for them, but i don't have too much time or knowledges about kafka 😥.
