### ISSUE TITLE
How should I mock consumer and producer written using segmentio?

### ISSUE THREAD

**Issue by vikasorchestral** [segmentio/kafka-go#718]
**Describe the solution you'd like**

**Supporting documentation**
Please provides links to relevant Kafka protocol docs and/or KIPs.

**Comment by kishaningithub** [comment]
@vikasorchestral For unit testing you can use https://github.com/golang/mock
This can generate mocks for literally any interface

**Comment by derekbassett** [comment]
Depending on your use case one of the things you could do is define an interface in your package like so.

```go

import kafka "github.com/segmentio/kafka-go"

// Depending on your use case
type FetchMessager interface {
    FetchMessage(ctx context.Context) (kafka.Message, error)
    CommitMessages(ctx context.Context, msgs ...kafka.Message) error
}

// or
type ReadMessager interface {
    ReadMessage(ctx context.Context) (kafka.Message, error)
}

// or
type WriteMessager interface {
    WriteMessages(ctx context.Context, msgs ...kafka.Message) error
}

```

Create either a `ReadMessager`, `FetchMessager`, `WriteMessager` in your code depending on your use case.  You can create a custom implementation or use a mocking tool to generate the implementation.

**Comment by vikasorchestral** [comment]
> Depending on your use case one of the things you could do is define an interface in your package like so.
> 
> ```go
> import kafka "github.com/segmentio/kafka-go"
> 
> // Depending on your use case
> type FetchMessager interface {
>     FetchMessage(ctx context.Context) (kafka.Message, error)
>     CommitMessages(ctx context.Context, msgs ...kafka.Message) error
> }
> 
> // or
> type ReadMessager interface {
>     ReadMessage(ctx context.Context) (kafka.Message, error)
> }
> 
> // or
> type WriteMessager interface {
>     WriteMessages(ctx context.Context, msgs ...kafka.Message) error
> }
> ```
> 
> Create either a `ReadMessager`, `FetchMessager`, `WriteMessager` in your code depending on your use case. You can create a custom implementation or use a mocking tool to generate the implementation, because of Go's implicit interfaces you should be able to swap in either your implementation or the libraries.

**Comment by vikasorchestral** [comment]
@derekbassett  Thanku.
