### ISSUE TITLE
consume group : Failed to join group

### ISSUE THREAD

**Issue by qingfengshuixu** [segmentio/kafka-go#723]
Kafka cluster version： kafka2.12_2.1.0
Run kafka-go testing,  kafka consume group return wrong
My Code:
```go
config := kafka.ReaderConfig{
		Brokers:           []string{"192.168.64.242:9092"},
		GroupID:           "kafka-go-group-1",
		Topic:             "KLOGInLove3",
		MinBytes:          1,
		MaxBytes:          10e6,
		MaxWait:           100 * time.Millisecond,
		HeartbeatInterval: 100 * time.Millisecond,
	}
	config.Logger = &TmeLog{}
	config.ErrorLogger = &TmeLog{}

	r := kafka.NewReader(config)
	fmt.Println("66666")
	defer r.Close()
	for {
		m, err := r.FetchMessage(context.Background())
		if err != nil {
			t.Fatalf("error fetching message: %s", err)
		}
		fmt.Println(m.Key, m.Value)
		if err := r.CommitMessages(context.Background(), m); err != nil {
			t.Fatal(err)
		}
	}
```
Result:

entering loop for consumer group, kafka-go-group-1

Failed to join group kafka-go-group-1: EOF
EOF
Failed to join group kafka-go-group-1: EOF
EOF
Failed to join group kafka-go-group-1: EOF
EOF
    KGetRcDataSout_test.go:102: error fetching message: EOF

How resolve this problem?  Failed to join group

**Comment by achille-roussel** [comment]
Hello @qingfengshuixu, thanks for opening an issue.

Your code snippet looks similar to a lot of programs that we have used kafka-go in, nothing jumps out as being done wrong on that side.

I would like to ask if you could give more details about how to are starting the Kafka cluster that the code is attempting to connect to (at `192.168.64.242:9092`). Do you also happen to create the topic ahead of starting the consumer?

**Comment by manyasi06** [comment]
I am experience this bug as well should I create a new issue or post in this one?

**Comment by achille-roussel** [comment]
Hello @manyasi06, it will be helpful if you could contribute material to this issue.

Thanks for chiming in!

**Comment by manyasi06** [comment]
I'll see if I post some info running it locally @achille-roussel

**Comment by achille-roussel** [comment]
Hello @manyasi06, do you have any follow ups to share on this issue?

**Comment by abonec** [comment]
I have the same issue. After connect to new group (that do not exist before) it work fine. But if I restart my service and connect to the same group it ended up with the same erorrs.
Where is the successor of this issue?

**Comment by faf-xff** [comment]
I  also have the same issue. After connect to new group (that do not exist before) it work fine. But if I restart my service and connect to the same group it ended up with the same errors.
Where is the successor of this issue?
