### ISSUE TITLE
Is this project a client lib?

### ISSUE THREAD

**Issue by wsyingang** [segmentio/kafka-go#724]
Dear author,I want to know is this project a client lib for kafka api? I do not find the server code，like  a implement of broker。So If I want use this lib，should I start kafka service on my computer or cloud？

**Comment by achille-roussel** [comment]
Hello @wsyingang, I assume you found the answer but for the sake of completeness I will follow up as well.

As of today, kafka-go is indeed a client library. The kafka protocol implementation is exported and can potentially be reused to build server-side components, but the package has no APIs to support these use cases yet.

I hope this answers your question!
