### ISSUE TITLE
ReadMessage from a single consumer takes 15 minutes to consume message from a single partition topic

### ISSUE THREAD

**Issue by prashantwork1** [segmentio/kafka-go#727]
**I have a single partition kafka topic that is being produced into at regular (not periodic though) intervals of time. The producer has batch processing disabled.
I have the consumer that uses "github.com/segmentio/kafka-go". I am using the following ReaderConfig**

```go
r := kafka.NewReader(kafka.ReaderConfig {
		Brokers:  []string{kafkaURL},
		GroupID:  groupID,
		Topic:    topic,
		MaxBytes: 10e6, // 10MB
		Dialer:         dialer,
		MaxWait:        1 * time.Second,
		CommitInterval: time.Second,
})
```

1. On consuming from this topic, I see messages on this topic all in a bunch although the producer published into it at regular intervals.
2. After consuming some of the offsets in the topic, the consumer does not see any messages in the topic, although the producer has produced into it. Basically I see a lag of 9 offsets between producer and consumer and the time gap between the producer producing into the topic and the consumer consuming is 15 minutes

**Kafka version : 2.1.0**

**To Reproduce, Run producer and consumer for a while**
```go
for {
		d, err := r.ReadMessage(ctx)
		if err != nil {
			log.Println("Error reading message from Kafka", err)
		}
		fmt.Printf("message at topic:%v partition:%v offset:%v\n",
			d.Topic, d.Partition, d.Offset)
}
```

**Expected behavior**
Expect to not see a long delay or lag in consumption and expect to not see consumption of offsets in a burst
although production is regular and non-bursty

**Additional context**
Bursty consumption sample
```
{"log":"message at topic:abcd_xyzw partition:0 offset:32\t = \n","stream":"stdout","time":"2021-08-25T01:53:53.8989389"}
{"log":"message at topic:abcd_xyzw partition:0 offset:33\t = \n","stream":"stdout","time":"2021-08-25T01:53:53.53.899025003"}
...
...
{"log":"message at topic:abcd_xyzw partition:0 offset:40\t = \n","stream":"stdout","time":"2021-08-25T01:53:53.900781232"}
```

**Comment by rhansen2** [comment]
Hi @prashantwork1, thanks for submitting this issue!

Is there anything you can share regarding the configuration of the producer that may help reproduce this? Especially related to any batching that's being done on that end.

Thanks!

**Comment by rhansen2** [comment]
Hi @prashantwork1 I've been unable to reproduce any delay between production and consumption of messages. I'm using the following code sample based on what you provided. I'm producing messages via `kafka-console-producer`

```go
	groupID := "test-group-id"
	r := kafka.NewReader(kafka.ReaderConfig{
		Brokers:        []string{"localhost:9092"},
		GroupID:        groupID,
		Topic:          "test-topic",
		MaxBytes:       10e6, // 10MB
		MaxWait:        1 * time.Second,
		CommitInterval: time.Second,
	})

	for {
		d, err := r.ReadMessage(context.Background())
		if err != nil {
			log.Println("Error reading message from Kafka", err)
		}
		fmt.Printf("message at topic:%v partition:%v offset:%v\n",
			d.Topic, d.Partition, d.Offset)
	}
```
Is there any other info you could provide which could help me reproduce this scenario?
