### ISSUE TITLE
Connecting to schema registry/ using custom serialiser

### ISSUE THREAD

**Issue by Macscroge** [segmentio/kafka-go#728]
I have this working in Python but am not sure in GO. I am trying to send a message to a topic which has a schema defined(JSON_SR), so I must connect to the schema registry/ use a custom serialiser.

In GO I have producing to a topic without a schema working. Is there a working example of sending data to a topic with schema? I can't see any documentation on it.

**Comment by achille-roussel** [comment]
Hello @Macscroge, thanks for asking!

We currently do not have an integration with schema registries in kafka-go, message values are manipulated as opaque byte arrays by the library (`[]byte`), so you should be able to then decode them from JSON or any other format within your application.

Let me know if you have any other questions!

**Comment by Macscroge** [comment]
Thanks for the reply.

So I understand that I can convert a message to JSON like this
`b, _ := json.Marshal(msg)`

But for example in Python if you convert the message to JSON and send it, it'll be rejected. It has to be encoded as JSON using the message schema defined for the topic. Does that make sense? Maybe I'm missing something, but at least in Python and kafkacat sending as normal JSON doesn't work. I may well be wrong here.

**Comment by Macscroge** [comment]
Another question if you can spare a minute.

The messages from the topic are fed into a Kafka Connector to redshift. Messages from Python using the Schema registry etc work fine with the connector, but with `kafka-go` it throws an error 'Deserialization exception: Unknown magic byte!' , meaning the message doesn't match the schema. Do you know anything about this?

I wonder is it impossible to use connectors without the schema registry.

**Comment by achille-roussel** [comment]
I'm not finding any occurence of `Deserialization exception: Unknown magic byte!` in the kafka-go code. Would you be able to describe in more details where this error occurs?

**Comment by Macscroge** [comment]
Apologies for not being more clear. The error in this case is given by the Kafka Connect redshift connector within Confluent cloud.  So the error is not in `kafka-go` itself. The message arrives to the topic correctly but the redshift connector gives the error when trying to consume the message from the topic. I'm not sure if this is user error, or if I'm just missing something. I can take a screenshot if that would help.

**Comment by achille-roussel** [comment]
From what I understand, it appears the error may be that the client application which writes to the Kafka topic may not be encoding the message in the format expected by the redshift connector. Do you know which format the message is encoded as, and which format the connector expects?

**Comment by Macscroge** [comment]
Apologies for not getting back to you sooner.

 In the python application it was using `JSON_SR` which is the JSON Scheme Registry format. The connector is expecting `JSON_SR` also. With `kafka-go` it is just sending a stream of bytes as `kafka-go` doesn't support schema registry as you said.  So I am not sure is there a way to use kafka connectors without the Schema Registry, or some sort of work around for `kafka-go`.

**Comment by achille-roussel** [comment]
According to the Confluent docs, it appears JSON_SR is not compatible with JSON https://docs.ksqldb.io/en/latest/reference/serialization/#json

**Comment by Macscroge** [comment]
Damn okay. So is there no way at all to send data from a ` segmentio / kafka-go `producer, to a topic/connector which uses the schema registry?  Can you think of any workarounds?

**Comment by achille-roussel** [comment]
Thanks to everyone who participated!

I'm going to close this as it seems we covered the topic, feel free to reopen if this needs further discussions.

**Comment by chuck-alt-delete** [comment]
Using a schema registry with an encoding format like Avro (or protobufs or json_sr) is bread-and-butter in the Kafka world and well worth supporting, imo. The format is much more compact and allows for schema evolution. It’s basically a requirement for any large scale use case in Kafka these days. I recommend reopening this issue.

I am currently looking at a use case for Segment but the Kafka destination doesn’t support schema registry. This surprised and disappointed me for a product as mature as Segment. I did some googling and found my way here. Is there a better issue / venue to discuss the lack of schema registry support in the segment Kafka destination?
