### ISSUE TITLE
Request for Admin API to create ACLs with SASL

### ISSUE THREAD

**Issue by Mayuresh-Gharat** [segmentio/kafka-go#729]
We are trying to use this client in order to create topics in Kafka, programmatically. Currently, there does not seem to be a way to create the ACLs programmatically. It would be great if we can use this client to do both create ACLs and topics programmatically. Kafka open-source has an admin API for creating ACLs: https://kafka.apache.org/26/javadoc/org/apache/kafka/clients/admin/KafkaAdminClient.html#createAcls-java.util.Collection-org.apache.kafka.clients.admin.CreateAclsOptions-

**Comment by achille-roussel** [comment]
Hello @Mayuresh-Gharat, thanks for starting the conversion!

kafka-go does not currently expose the CreateAcls API, but this could be easily added to the `kafka.Client` type.

We always welcome contributions, would you be able to submit a pull request to add the APIs you need?

**Comment by Mayuresh-Gharat** [comment]
@achille-roussel  I am pretty new to GoLang and might need some guidance on this. I would be happy to take a stab at this. Would you be able to point me to a starting point in the code that I can follow as an example, to achieve this?

**Comment by achille-roussel** [comment]
Sure thing!

I would start by looking at how other APIs are implemented, for example [`kafka.(*Client).CreateTopics`](https://github.com/segmentio/kafka-go/blob/master/createtopics.go), you should be able the follow these models to implement CreateAcls.

The request and response messages sent to and received from Kafka are declared in the `protocol` sub-packet, for example: https://github.com/segmentio/kafka-go/blob/master/protocol/createtopics/createtopics.go

You can find the reference documentation for the Kafka protocol at https://kafka.apache.org/protocol.html#protocol_api_keys

**Comment by achille-roussel** [comment]
Hello @Mayuresh-Gharat, are you still interested in making this contribution?

**Comment by Mayuresh-Gharat** [comment]
Hi, @achille-roussel sorry I completely forgot about this. I would be happy to hand it over to anyone interested in this. I don't have cycles to work on this right now (even though I would like to).

**Comment by achille-roussel** [comment]
Sounds good, we will close the error for now and put this on the backlog, feel free to reopen if you find the need to contribute these new APIs in the future 👍
