### ISSUE TITLE
Why can't the offset be set when the groundID is configured when reading?

### ISSUE THREAD

**Issue by ZQHcode** [segmentio/kafka-go#751]
Why can't the offset be set when the groundID is configured when reading?

**Comment by achille-roussel** [comment]
Hello @ZQHcode, thanks for opening the issue.

By "groundID" I am going to assume you are referring to the "GroupID" of the reader, which configures the reader to take part in a consumer group.

When joining a consumer group, the reader may be assigned multiple partitions. When it is the owner of a partition it is responsible for recording how much progress it has made on the partition by "committing the offset".

In this context, which partition should the reader be setting the offsets for? It may have made different progress on each partition.

Kafka has a tool suite which contains programs to help with consumer group, the `kafka-consumer-groups.sh` script supports setting offsets of individual partitions for example.

Let me know if this was useful.

**Comment by ZQHcode** [comment]
I want to re-consume the previous data and roll it back through time, but I can’t do it now. I think it’s necessary to achieve it.

**Comment by shcw** [comment]
I have a requirement to directly consume the latest data. This is very important to me.
