### ISSUE TITLE
groupMetadata is not version 1? in offical java sdk, it's like version 0 protocol?

### ISSUE THREAD

**Issue by caesarlzh** [segmentio/kafka-go#762]
https://github.com/segmentio/kafka-go/blob/5d063ebe8f792e215847e9b4ad5d5da9097fa65a/consumergroup.go#L945

this protocol type is version 0? if use version 1 kafka client java offical sdk deserialize this metadata will throw BufferUnderflowException because after userData exists TopicPartitionCollection 4byte length data

![image](https://user-images.githubusercontent.com/26215981/138269964-bb0cd1f8-1b64-4f33-9ce4-4831eb65d0e3.png)

**Comment by derekbassett** [comment]
I would be helpful to find the version of Java client and the library you are using.

**Comment by derekbassett** [comment]
Closed due to lack of activity.
