### ISSUE TITLE
Control kafka connetors with kafka-go

### ISSUE THREAD

**Issue by uran246** [segmentio/kafka-go#766]
Hello Everyone, 
I'm new to Go and Kafka and am looking for a way to start or stop a Kafka connector with the kafka-go? 
Is such a function already built in?

Best Regards
Uwe

**Comment by rhansen2** [comment]
kafka-go does not provide a client for Kafka connect.

**Comment by uran246** [comment]
Hello an thanks for your answer.
I will manage that over http. 

Best Regards

Uwe
