### ISSUE TITLE
in `struct reader` member function `run`, the sleep function is called with errcount=1 after batch read EOF, Is it designed like this

### ISSUE THREAD

**Issue by lvhuat** [segmentio/kafka-go#770]
**Describe the bug**
reader fetch message with highlatency
after every batch read message success(batch read end with EOF), there is a sleep line, at the end of readLoop, `errcount++` happend,then sleep(backoffDelayMin) work.

https://github.com/segmentio/kafka-go/blob/v0.4.22/reader.go#L1278
```
	readLoop:
		for {
			if !sleep(ctx, backoff(errcount, r.backoffDelayMin, r.backoffDelayMax)) {
				conn.Close()
				return
			}

			switch offset, err = r.read(ctx, offset, conn); err {
			case nil:
				errcount = 0
			case io.EOF:
				// done with this batch of messages...carry on.  note that this
				// block relies on the batch repackaging real io.EOF errors as
				// io.UnexpectedEOF.  otherwise, we would end up swallowing real
				// errors here.
				errcount = 0  // reset is ok!!!
			
                         //  ignore left code here
			}
			errcount++   // lead errcount = 1 after batch read.
		}
```

**Kafka Version**
v0.4.22

**To Reproduce**
always

**Expected behavior**
no sleep between  batch read if success.

**Comment by rhansen2** [comment]
Hi @lvhuat, thanks for filing this issue!

It should now be fixed via https://github.com/segmentio/kafka-go/pull/774
