### ISSUE TITLE
How to implement throttling on the consumer

### ISSUE THREAD

**Issue by aszecowka** [segmentio/kafka-go#779]
**Describe the solution you'd like**

I am trying to implement a reliable reprocessing mechanism as described here: https://eng.uber.com/reliable-reprocessing/
The idea is the following: in case of processing failure, I send a message to another topic where the frequency of processing events is smaller: for example only one event per 10 seconds. So I would like to implement throttling/delay in reading messages.

The simplest solution will be to use just `time.Sleep`
```
r := kafka.NewReader(kafka.ReaderConfig{
  Brokers:        []string{"localhost:9092"},
  GroupID:        "...",
})


for i := 0; ; i++ {
  m, err := r.ReadMessage(context.Background())
  if err != nil {
	...
  }
  // do processing here
  time.Sleep(time.Second*10)
}
```
I haven't noticed any rebalances inside the consumer group, so my assumption is that heartbeat functionality works correctly. 
Is there any other way to implement reader throttling?

**Comment by achille-roussel** [comment]
Hello @aszecowka, thanks for opening the issue!

Your approach looks OK, you can pause processing for as long as you need in your application, the `kafka.Reader` will continue to manage connections to the Kafka cluster in the backend 👍

**Comment by achille-roussel** [comment]
I will close this issue since it appears the original question was answered, feel free to reopen if it requires further discussion.
