### ISSUE TITLE
ReadBatch honor Seek / newest producers first

### ISSUE THREAD

**Issue by mcr-ksh** [segmentio/kafka-go#787]
Hello,

I'm not able using ReadBatch to get the latest producers messages first. 
`conn.Seek(some_offset, kafka.SeekEnd)` doesn't change anything compared to kafka.SeekStart or kafka.SeekCurrent.

is it even possible to read newest nr of records for a topic using ReadBatch?

From what we observe ReadBatch always reads from the Start to End

**Comment by dominicbarnes** [comment]
I've tried to reproduce this but have not been able to. Can you provide some more details about your setup? A working code sample could help us troubleshoot.

Beyond that, I have some initial thoughts. The `conn.Seek()` method returns the offset that it seeked to. This can help you diagnose the difference between those `kafka.Seek*` parameters (especially in relation to that first parameter) without needing to attempt `ReadBatch`.

**Comment by dominicbarnes** [comment]
I haven't heard back in a while, so I'm going to close this ticket. Please re-open if you are still experiencing issues and we can help troubleshoot.
