### ISSUE TITLE
How to use SASLMechanism with Client?

### ISSUE THREAD

**Issue by jaakkotuosa** [segmentio/kafka-go#792]
Hi!
I am trying to figure out how to use SASL with `kafka.Client`, any pointers? I can set the SASL in `kafka.Dialer` and create `kafka.Connection` from that, but `kafka.Client` takes only plain `net.Addr`.

**Comment by dominicbarnes** [comment]
In #809 I added a section to the README with an example of doing this, which effectively boils down to using a custom `Transport` which has the SASL configuration attached.

https://github.com/segmentio/kafka-go#client
