### ISSUE TITLE
How to test with empty string address?

### ISSUE THREAD

**Issue by mghifariyusuf** [segmentio/kafka-go#793]
Since latest update there is this function:

```
func makeAddr(network, address string) net.Addr {
	host, port, _ := net.SplitHostPort(address)
	if port == "" {
		port = "9092"
	}
	if host == "" {
		host = address
	}
	return &networkAddress{
		network: network,
		address: net.JoinHostPort(host, port),
	}
}
```

My project make a unit test using Kafka and passing an empty string for the address (to prevent connect to server) and it turn back to ":9092" because that function

Can suggest how to make it did not connect to server or maybe can change the function and leave it empty string

**Comment by achille-roussel** [comment]
If you wanted to prevent connecting to a Kafka server, providing a custom dial function would be a better alternative; both the `kafka.Dialer` and `kafka.Transport` types support it.

I agree that the current behavior isn't ideal, maybe we should panic or somehow bubble up the error returned by `net.SplitHostPort`.

**Comment by achille-roussel** [comment]
I'm going to close this issue assuming the last message has provided an answer. Feel free to reopen if this requires further discussion.
