### ISSUE TITLE
Mock broker for user testing.

### ISSUE THREAD

**Issue by 3AceShowHand** [segmentio/kafka-go#794]
**Describe the solution you'd like**

We try to use `kafka-go` in our service, but we found lack of mock method for testing.

At the moment, we use the sarama as Kafka producer, its `Mocks` implementation can meet our basic testing requirement. For example: https://github.com/pingcap/ticdc/blob/master/cdc/sink/producer/kafka/kafka_test.go#L114

Is there any plan to support mock, such as a mocked broker?

**Supporting documentation**
Please provides links to relevant Kafka protocol docs and/or KIPs.

**Comment by rhansen2** [comment]
Hi @3AceShowHand, 
We don't have any current plans to implement mocks as part of this library. I'm not very familiar with Sarama's mock implementation but I imagine the mock broker would be compatible with any kafka client?

**Comment by biancarosa** [comment]
I'd love to be able to mock the Kafka reader itself, too. Right now, the Kafka reader is a struct, but if it were an interface, at least we could use [gomock](https://github.com/golang/mock) and [mockgen](https://github.com/golang/mock/tree/master/mockgen) to generate the mocks on our side. Those are supported mocking libraries from the Go std library.

**Comment by rhansen2** [comment]
That can be accomplished by defining the interface that you use from the reader in your code and then generating a mock from that interface.
