### ISSUE TITLE
Does kafka-go suports idempotence producer.

### ISSUE THREAD

**Issue by imumesh18** [segmentio/kafka-go#797]
**Describe the solution you'd like**
How to enable idempotent producer as there is no config for it in this lib.

**Supporting documentation**
https://docs.confluent.io/platform/current/installation/configuration/producer-configs.html#producerconfigs_enable.idempotence

**Comment by rhansen2** [comment]
Hi @imumesh18 I don't believe we currently support idempotent producers.

**Comment by dezgrant** [comment]
Hi @rhansen2 is there a release that supports the idempotent producer? I noticed it was marked as completed on 1/13. If so, is there documentation on the configuration? Thanks.

**Comment by rhansen2** [comment]
No, kafka-go does not currently support idempotent producers.
