### ISSUE TITLE
Some doubts!

### ISSUE THREAD

**Issue by xusss** [segmentio/kafka-go#8]
Sorry, I have no idea about the passing by pointers will cause large memory alloc. 
Passing values will copy the memory but without increasing the reference count.
Passing pointers will copy the reference but without memory copy of it's data.
Need help!

**Comment by achille-roussel** [comment]
Helllo,

I'm not sure I understand what your problem is, can you tell me what method you're looking at, or maybe show some code or benchmark numbers so I can help with your issue?

**Comment by sposec** [comment]
@xusss memory allocations can happen wherever there is sufficient space in the heap, whilst values are allocated contiguously. As a consequence of that, the CPU may need to "jump" back and forth RAM to read data, invalidating the cache and making applications slower.

**Comment by xusss** [comment]
@sposec Oh，I see! Thanks very much

**Comment by achille-roussel** [comment]
Is there anything we can do here? Otherwise can we close the issue?
