### ISSUE TITLE
Reader config that manages/map to the "max.poll.interval.ms" kafka consumer config

### ISSUE THREAD

**Issue by sayan-mitra** [segmentio/kafka-go#808]
Hi,

Can someone please assist which Reader Config field maps to the **max.poll.interval.ms** kafka consumer config.
My processor that fetch and process message may take more than 5 mins (assuming default value of **max.poll.interval.ms**)

I see the HeartbeatInterval and SessionTimeout in the Reader config but am confused with the Poll interval config.

Please assist.

**Comment by rhansen2** [comment]
Hi @sayan-mitra,

I don't believe we have an equivalent of max.poll.interval.ms. The reader should continue to attempt to read messages from kafka in the background until they are available.

Thanks!

**Comment by sayan-mitra** [comment]
hi @rhansen2 
just to clarify:
does it mean that the application code should do this background fetch OR the library is already doing it and hence this config is not required?

**Comment by ramory-l** [comment]
Hi @rhansen2
How to rebalance consumer group without this setting if one of consumers in the group is deadlocked?
https://kafka.apache.org/documentation/#consumerconfigs_max.poll.interval.ms

**Comment by dalianzhu** [comment]
> Hi @rhansen2 How to rebalance consumer group without `max.poll.interval.ms` setting if one of consumers in the group is deadlocked? https://kafka.apache.org/documentation/#consumerconfigs_max.poll.interval.ms

I faced the same situation, just image this: When one consumer poll 50 messages from patition 1, another consumer starts rebalance trigged, this patition 1 is assigned to it. At this time, these 50 messages have not been commited, the newly stared consumer will continue to receive those 50 messages.
Not sure if it is related to #1259
