### ISSUE TITLE
How to write to a specific apache kafka partition?

### ISSUE THREAD

**Issue by ielyanov** [segmentio/kafka-go#810]
I have a topic with 3 partitions. Now all messages into one partition.
How to write to a specific  kafka partition?

**Comment by dominicbarnes** [comment]
This behavior is determined by the `[Balancer](https://pkg.go.dev/github.com/segmentio/kafka-go#Balancer)`, which determines what partition to send messages to. When using the `Writer`, the default balancer is [RoundRobin](https://pkg.go.dev/github.com/segmentio/kafka-go#RoundRobin) which should spread your messages evenly across the different partitions. We have other implementations included (eg: [LeastBytes](https://pkg.go.dev/github.com/segmentio/kafka-go#LeastBytes) and [Hash](https://pkg.go.dev/github.com/segmentio/kafka-go#Hash)), but you can include your own custom balancer as well, including one that uses `Message.Partition` to route messages.

**Comment by dominicbarnes** [comment]
If this answer isn't helpful, please re-open the ticket and include more details about your setup and the code you are using to write messages to Kafka.

**Comment by ielyanov** [comment]
> This behavior is determined by the [Balancer](https://pkg.go.dev/github.com/segmentio/kafka-go#Balancer), which determines what partition to send messages to. When using the `Writer`, the default balancer is [RoundRobin](https://pkg.go.dev/github.com/segmentio/kafka-go#RoundRobin) which should spread your messages evenly across the different partitions. We have other implementations included (eg: [LeastBytes](https://pkg.go.dev/github.com/segmentio/kafka-go#LeastBytes) and [Hash](https://pkg.go.dev/github.com/segmentio/kafka-go#Hash)), but you can include your own custom balancer as well, including one that uses `Message.Partition` to route messages.

Thank you
