### ISSUE TITLE
Regression after upgrading from v0.4.23: unexpected EOF

### ISSUE THREAD

**Issue by Reasno** [segmentio/kafka-go#814]
**Describe the bug**
If the topic has no messages, the kafka reader starts to report "the kafka reader got an unknown error reading partition x of my-topic at offset y: unexpected EOF"

**Kafka Version**
2.3.0

**To Reproduce**
Run kafka reader in consumer group mode when the partition has no more messages.

**Expected behavior**
No unexpected EOF reported, as pre 0.4.24

**Additional context**
The problem only occurs in v0.4.24 and above (tested with v0.4.23, v0.4.24, v0.4.25). I believe the regression is caused by PR #788 where the highwater mark check is removed just to pass a test. The check seems to be added intentionally in prior PRs.

edit: fix version number

**Comment by Gerifield** [comment]
We had a similar error that disappeared as soon as we reverted the version from 0.4.25 to 0.4.23.

**Comment by lixianmin** [comment]
yes, found the same error, and reverted to 0.4.23 solved this problem

**Comment by rhansen2** [comment]
Hello, thanks for submitting this issue!

Is anyone able to provide a reproduction of this issue? I haven't had any success in replicating it.

**Comment by marselester** [comment]
> Is anyone able to provide a reproduction of this issue? I haven't had any success in replicating it.

@rhansen2 here you go https://gist.github.com/marselester/a7cc16279e990a8d42c41fd9f557b341.

**Comment by rhansen2** [comment]
Thanks for the reproduction @marselester For now I'm going to revert #788

**Comment by rhansen2** [comment]
The revert of #788 is available in https://github.com/segmentio/kafka-go/releases/tag/v0.4.26. Based on the reproduction provided by @marselester I believe that this regression should now be fixed.
