### ISSUE TITLE
How to calculate the total number of messages in the kafka topic?

### ISSUE THREAD

**Issue by ielyanov** [segmentio/kafka-go#815]
```
        ctx := context.Background()
	connDial, errDial := kafka.DialLeader(ctx, "tcp", brokerAddress, topicName, 0)
	if errDial != nil {
	    fmt.Println("failed to open a new kafka connection: ", errDial.Error())
	}
	defer conn.Close()

	lastRO, errDial := connDial.ReadOffset(time.Now())
	fmt.Println("ReadOffsets: ", lastRO, " Error: ", errDial)

```

The following returns -1, rather than e.g. 13. I can see that this is expected behaviour if the group id is set, but I have not knowingly set this.

```
func getKafkaReader(kafkaUrl, topicName string) *kafka.Reader {
	l := log.New(os.Stdout, "consume.kafka reader: ", 0)

	configReader := kafka.ReaderConfig{
		Brokers:  	strings.Split(kafkaUrl, ","),
		Topic:  	topicName,
		MinBytes: 	10e1,
		MaxBytes: 	10e6,
		Logger:  	l,
	}
	return kafka.NewReader(configReader)
}

func main() {
      r := getKafkaReader(brokerAddress, constTopicResponses, "")
      r.SetOffset(-1)
}

```

But it doesn`t work. 

It works like this:  r.SetOffset(13)

**Comment by achille-roussel** [comment]
Hello @ielyanov, thanks for opening the issue.

The number of messages in a topic is the sum of deltas between the last and first messages in each partition. Here's an example of tool that computes and display this information using kafka-go: https://github.com/segmentio/topicctl

https://github.com/segmentio/topicctl/blob/d62a0952941a3cf87b43f47dc521203e5a78e6c6/pkg/cli/cli.go#L400

Let me know if this answer was useful!

**Comment by achille-roussel** [comment]
There hasn't been activity on this issue since the last answer, so I am going to assume that it was useful and close the issue. Feel free to reopen if this needs further discussion!
