### ISSUE TITLE
`partitionWriter` has unlimited batch queue size.

### ISSUE THREAD

**Issue by sko00o** [segmentio/kafka-go#819]
**Describe the bug**
I made a [benchmark](https://github.com/sko00o/benchmark-kafka-go-clients) for 3 kafka go clients.
As a result, I noticed that kafka-go is the fastest producer. But it cost too much memory comparing with other two clients.

**Kafka Version**
kafka:2.12-2.4.0

**To Reproduce**
I set `Writer.Async = true` for better produce performance. Here is my writer [config](https://github.com/sko00o/benchmark-kafka-go-clients/blob/main/client_segmentio.go#L67):

```go
	producer := kafka.Writer{
		Addr:         kafka.TCP(brokers),
		Topic:        topic,
		Balancer:     &kafka.Hash{},
		BatchTimeout: BatchTimeout,
		BatchSize:    BatchSize,
		BatchBytes:   BatchBytes,
		RequiredAcks: kafka.RequireNone,
		Async:        true,
	}
```

Then run following test for producer

```sh
./kafka-benchmark -numMessages 10000000 -msgSize 512 -client kafka-go -mode producer
```

**Expected behavior**
Limit memory usage in async writer.

**Additional context**
I notice that `writer.WriteMessages` will create `partitionWriter` for each topicPartition. 
And `partitionWriter` will hold a `writeBatch` queue for batch process.
Following related code:
* https://github.com/segmentio/kafka-go/blob/37ab7b1b613c78b5edac7f76bb174b6ce2130752/writer.go#L648
* https://github.com/segmentio/kafka-go/blob/37ab7b1b613c78b5edac7f76bb174b6ce2130752/writer.go#L696
* https://github.com/segmentio/kafka-go/blob/37ab7b1b613c78b5edac7f76bb174b6ce2130752/writer.go#L969

`partitionWriter.queue` is a slice with unlimited length. Batch messages in queue will increase
while `queue.Put()` much more than `queue.Get()`.

In my opinion, I would like to have a config option to limit this batch queue length.
So I try to use a buffered channel implement a fixed size queue for this.

**Comment by 3AceShowHand** [comment]
why not used a buffered channel ?
