### ISSUE TITLE
when consumer gourp subsribe a not exist topic，it will be created from broker

### ISSUE THREAD

**Issue by ivenzheng** [segmentio/kafka-go#822]
**Describe the bug**

**Kafka Version**
What version(s) of Kafka are you testing against?

**To Reproduce**
Steps to reproduce the behavior.  Bonus points for a code sample.

**Expected behavior**

**Additional context**

**Comment by nlsun** [comment]
Hi @ivenzheng , can you check your Kafka Broker configurations and check if `auto.create.topics.enable` is set to `false` https://kafka.apache.org/documentation/#brokerconfigs

**Comment by ivenzheng** [comment]
Thanks!

**Comment by ivenzheng** [comment]
> Hi @ivenzheng , can you check your Kafka Broker configurations and check if `auto.create.topics.enable` is set to `false` https://kafka.apache.org/documentation/#brokerconfigs

Thanks!
