### ISSUE TITLE
Question: Why set the partition number when creating a producer? 

### ISSUE THREAD

**Issue by salyakhov-art** [segmentio/kafka-go#835]
When creating a connection, it requires a partition number. But I need to send messages to all partitions.
```go
conn, err := dialer.DialLeader(ctx, "tcp", "127.0.0.1:9092", "topic", 0)
```

I looked in other clients and it's possible there. What am I doing wrong? :)
```go
p, err := kafka.NewProducer(&kafka.ConfigMap{"bootstrap.servers": "localhost"})
p.Produce(&kafka.Message{
    TopicPartition: kafka.TopicPartition{Topic: &topic, Partition: kafka.PartitionAny},
    Value:          []byte(word),
 }, nil)
```

**Comment by rhansen2** [comment]
Hi @salyakhov-art ,

I think the [Writer](https://pkg.go.dev/github.com/segmentio/kafka-go?utm_source=godoc#Writer) is more in-line with what you're looking for.

**Comment by salyakhov-art** [comment]
> Hi @salyakhov-art ,
> 
> I think the [Writer](https://pkg.go.dev/github.com/segmentio/kafka-go?utm_source=godoc#Writer) is more in-line with what you're looking for.

Thanks for the answer! I tried to use it, but it works very slowly.

**Comment by salyakhov-art** [comment]
I set these settings and everything seems to work quickly. Hope this is a good solution :)

```go
Writer: &kafka.Writer{
    Addr: kafka.TCP(bootstrapServers[0]),
    Topic: events.ProductStatusUpdate.String(),
    BatchSize: 1,
    Balancer:  &kafka.LeastBytes{},
}
```

**Comment by rhansen2** [comment]
That looks good to me, glad. you were able to get things working!
