### ISSUE TITLE
Inconsistency issue with range group balancer

### ISSUE THREAD

**Issue by madshov** [segmentio/kafka-go#838]
**Describe the bug**
I'm testing the behaviour of the range group balancer for co-partitioning. My setup consists of a main topic `my-topic` and a hospital topic `my-topic_hospital`, each with 6 partitions. I'm running 2 consumers locally both in the same consumer group. I can see the range group balancer groups the partitions the following way:

`my-topic` consumer 1 gets partitions [0,5,4]
`my-topic` consumer 2 gets partitions [1,2,3]
`my-topic_hospital` consumer 1 gets partitions [0,5,1]
`my-topic_hospital` consumer 2 gets partitions [2,3,4]

For co-partition to work I expect the groups to be the same. For instance if consumer 1 fails reading a message and publishes it to hospital topic I expect it to be picked up by consumer 1 again when consuming from the hospital topic. The message is **always** produced to the same hospital partition as it was consumed from. With the above grouping this only happens if the message was originally consumed from partitions 0 and 5 for consumer 1 (and 2, 3 for consumer 2). Debugging it a bit further, I can see that order of partitions returned from `ReadPartitions()` is different for the too topics:
```
my-topic: [0 5 4 1 2 3]
my-topic_hospital: [0 5 1 4 2 3]
```
I assume Kafka doesn't guarantee any order of the read partitions in `ReadPartitions()`

Example (correct behaviour):
* Consumer 1 consumes message `a` from `my-topic` partition 0.
* Consuming message `a` fails.
* Consumer 1 produces message `a` to `my-topic_hospital` partition 0.
* Consumer 1 consumes message `a` from `my-topic_hospital` partition 0.
* Consuming message `a` succeeds from consumer 1 (correct).

Example (incorrect behaviour):
* Consumer 1 consumes message `a` from `my-topic` partition 4.
* Consuming message `a` fails.
* Consumer 1 produces message `a` to `my-topic_hospital` partition 4.
* Consumer 2 consumes message `a` from `my-topic_hospital` partition 4.
* Consuming message `a` succeeds from consumer 2 (incorrect).

**Kafka Version**
v6.2.0

**To Reproduce**
Setup 2 consumers, consuming from the same topic with a hospital topic. Run them simultaneously and produce to the topic. Make sure a message fails so the consumer will produce it to the hospital topic. Once that happens, the same consumer should consume it again from the hospital topic. Both consumers should be part of the same consumer group.

**Expected behavior**
If a consumer produces a message to the hospital topic, it should also consume that message.

**Additional context**
Producer and hospital producer is using murmur2 balancer.

**Comment by dominicbarnes** [comment]
It's been a while without response, so I'm going to close this ticket, feel free to re-open if there is something further we can assist with.
