### ISSUE TITLE
Attempt to create topic and read from topic results in EOF

### ISSUE THREAD

**Issue by kish0620** [segmentio/kafka-go#840]
**Describe the bug**
I tried to create a topic using the code provided here: https://github.com/segmentio/kafka-go#to-create-topics. But the line `err = controllerConn.CreateTopics(topicConfigs...)` results in an EOF error. I followed the code verbatim (only difference is I replaced "localhost:9092" with my address). This same error occured when I tried to consume from a topic already on my cluster (I used the code provided at https://github.com/segmentio/kafka-go#reader). The list topics command works so I know there isn't an issue with connecting to the cluster
**Kafka Version**
What version(s) of Kafka are you testing against?
The latest version. 
**To Reproduce**
Steps to reproduce the behavior.  Bonus points for a code sample.

**Expected behavior**
I expected the topic to be created and information to be read.
**Additional context**

**Comment by dominicbarnes** [comment]
I attempted to replicate this issue using the sample code you referenced, in the event that our documentation had simply become outdated. Unfortunately, I was not able to reproduce the EOF error you mentioned, but our `docker-compose.yml` setup here is pretty basic and likely doesn't mirror your setup elsewhere.

In our experience, an EOF usually indicates some sort of networking issue, sometimes just a misconfiguration. If you can provide some more details about your setup, we might be able to help troubleshoot further.

In the interim, I think we need to wrap errors with more context so we can help narrow down where sentinel errors like "EOF" and "Unexpected EOF" come from, given their lack of context in general. I'll open a subsequent PR and link back here.

**Comment by dr-dro** [comment]
@kish0620 
I think you are using some custom dialer, but just on first dial
```go
	dialer := &kafka.Dialer{
		DualStack: true,
		SASLMechanism: plain.Mechanism{
			Username: "user",
			Password: "password",
		},
	}

	conn, err := dialer.Dial("tcp", "localhost:9092")
        ...
	//use custom dialer here too
	controllerConn, err = dialer.Dial("tcp", net.JoinHostPort(controller.Host, strconv.Itoa(controller.Port)))
	
```
