### ISSUE TITLE
Option to reuse buffer in Reader.ReadMessage/FetchMessage

### ISSUE THREAD

**Issue by bgranvea** [segmentio/kafka-go#841]
I see that it is possible to reuse a buffer with Batch.Read(b []byte) but this can only be used with the low-level API.

It would be nice to have the same option with the Reader API. It could be a parameter of ReadMessage/FetchMessage or maybe provided with ReaderConfig? 

BTW, it seems that this buffer is only for values in Batch.Read and not for keys.

**Comment by achille-roussel** [comment]
Hello @bgranvea, thanks for opening the issue.

I agree that the `kafka.Reader` API would benefit from exposing an API allowing to reuse the read buffers. At this time, you will need to use `kafka.(*Client).FetchRequest` to achieve this, potentially pairing with `kafka.ConsumerGroup` if you are taking part in a consumer group. Those are lower-level APIs that have lower memory footprint and allow for better resource utilization (or re-utilization where possible).

Modifying the behavior of existing APIs seems like a risky change, but if you have suggestions about what new APIs could be added to enhance `kafka.Reader`, please let us know!
