### ISSUE TITLE
Kafka writer not accept url list for brokers

### ISSUE THREAD

**Issue by rezaalimorady** [segmentio/kafka-go#857]
**Describe the bug**
Cannot add some url for brokers in `kafka.Writer` . just take one in this example -> [here](https://github.com/segmentio/kafka-go/blob/34e8f715bcffb4225deb0f693f48f5035bb3863e/examples/producer-api/main.go#L34) 
it just take one url.
i want to add a broker list like` ['kafka_server1', 'kafka_server2', 'kafka_server3']`

**Kafka Version**
latest

How can use borokers address here?

**Comment by tungdt91** [comment]
I am also facing this problem.
I see kafka-go supports the NewWriter func, but it no longer supports. So what to do now?

**Comment by rhansen2** [comment]
Hello,
@rezaalimorady the  `kafka.TCP` function can accept multiple broker addresses. See: https://pkg.go.dev/github.com/segmentio/kafka-go#TCP

@tungdt91 The Writer can be configured directly, See: https://pkg.go.dev/github.com/segmentio/kafka-go#Writer for some examples.

Let me know if that helps, Thanks!

**Comment by rezaalimorady** [comment]
Hello, 
Thanks

I see the docs that can take string.
![image](https://user-images.githubusercontent.com/60624937/156978026-ab9fbdd1-8c0e-469f-919e-82adf8d2eef4.png)

should i pass string like this => `192.168.99.11:9092,192.168.99.12:9092,192.168.99.13:9092`

in code : 
```
return &kafka.Writer{
  Addr:     kafka.TCP(`192.168.99.11:9092,192.168.99.12:9092,192.168.99.13:9092`),
  Topic:    topic,
  Balancer: &kafka.LeastBytes{},
}

```

is this right?

**Comment by rhansen2** [comment]
It would be 
```go
return &kafka.Writer{
  Addr:     kafka.TCP("192.168.99.11:9092","192.168.99.12:9092","192.168.99.13:9092"),
  Topic:    topic,
  Balancer: &kafka.LeastBytes{},
}
```

**Comment by rezaalimorady** [comment]
Thanks @rhansen2

**Comment by tungdt91** [comment]
Thanks @rhansen2 <3
