### ISSUE TITLE
Modify configuration of an existing topic

### ISSUE THREAD

**Issue by kish0620** [segmentio/kafka-go#880]
**Describe the solution you'd like**
Can a function be added to edit an existing topic. I know CreateTopic is idempotent, so in order to modify the configuration of an existing topic, an additional function would be nice.

**Supporting documentation**
N/A

**Comment by achille-roussel** [comment]
Hello @kish0620, thanks for reaching out!

Have you looked at the following?
* https://pkg.go.dev/github.com/segmentio/kafka-go#Client.AlterConfigs
* https://pkg.go.dev/github.com/segmentio/kafka-go#Client.AlterPartitionReassignments
* https://pkg.go.dev/github.com/segmentio/kafka-go#Client.IncrementalAlterConfigs

**Comment by kish0620** [comment]
Thank you I'll look into these. So If I wanted to change num_partitions for example would I do this?
config := kafka.AlterConfigRequestConfig(
   {
      Name: "num_partitions"
      Value: "5"
   })
resource := kafka.AlterConfigRequestResource(
   {
      ResourceType: 2
      ResourceName: "topic"
      Configs: config
   })

req := kafka.AlterConfigsRequest(
   {
      Addr: "address"
      Resources: resource
      ValidateOnly: false
   })
resp, err := client.AlterConfigs(context, req)

**Comment by kish0620** [comment]
I was able to change retention.ms but I'm having issues changing the number of partitions because I don't know what to put into the name field of kafka.AlterConfigRequestConfig. Do any of you know what to put into this field for num partitions?

**Comment by kish0620** [comment]
Is there a way to alter the number of partitions or replication factor for an existing topic?

**Comment by Luffy110** [comment]
If you want to change the number of partition of one topic, then you can try this method .https://pkg.go.dev/github.com/segmentio/kafka-go#Client.CreatePartitions

**Comment by achille-roussel** [comment]
I'm going to close this ticket, the CreatePartitions API call should support creating new partitions in Kafka topics. Feel free to reopen if you are still experiencing issues with this approach tho!

**Comment by rmrf** [comment]
How to change replication factor for a topic, should I use ReplicaAssignment ?
