### ISSUE TITLE
How to properly communicate with multiple kafka brokers?

### ISSUE THREAD

**Issue by dr-dro** [segmentio/kafka-go#894]
Field `Brokers` allows you to setup multiple hosts, but if one broker is down, the behavior is not as expected.
```go
reader := kafka.NewReader(kafka.ReaderConfig{
    
    // The list of broker addresses used to connect to the kafka cluster
    Brokers: []string{"not_working_host:9092", "working_host:9092"},

    Topic:   "test_topic",
    Dialer: &kafka.Dialer{
        Timeout:   5 * time.Second,
    },
})

for i := 1; i <= 10; i++ {
    reader.ReadLag(context.Background())
}
```
In this case, I get a freeze for 5 seconds on **every** call. Reader does not remember the last successful connection. So how to accommodate the possibility that one of the brokers (first in the list) can die in runtime?

If you use one broker, then you can add one random IP address to the top of the brokers list to reproduce the issue

**Comment by achille-roussel** [comment]
Hello @dr-dro, thanks for opening the issue.

I am curious whether using a shorter dial timeout could be a practical solution to this issue? Maybe a 1s dial timeout could reduce the wait time to something that is more acceptable for you use case?

I would be concerned about trying to be too smart about broker selection. Introducing connection health checks and remembering which broker appeared to be up will add a lot of complexity to the code base, and introduce new failure modes (e.g. a broker goes offline but comes back, now all clients have decided it was unhealthy and won't use it, etc...), simplicity is an essential property of reliable systems.

Let me know if the workaround would solve your issue, if not we can discuss more!

**Comment by dr-dro** [comment]
Hello @achille-roussel, thanks for replying!

I don't think reducing delay makes sense. Let's see in a source `reader.go`
```go
func (r *Reader) ReadLag(ctx context.Context) (lag int64, err error) {
...
  for _, broker := range r.config.Brokers {

    if conn, err = r.config.Dialer.DialLeader(ctx, "tcp", broker, r.config.Topic, r.config.Partition); err != nil {
      continue
    }
```
The user of the package will not get any errors, but will just get a delay multiplied by the number of broken brokers before the working ones. And it will be on every function call

So in my humble opinion there are two options.

- "simplicity": allow exactly one broker in the reader config. And in the case of a network error, user will decide what to do.

- the second option is to add `curent broker` field to reader structure, and use it instead of "range Brokers" loop. In case of network error, `curent broker` is changed on the next in config.Brokers list

I'm sure that current option of set multiple brokers is confusing and can lead to unpredictable freezes

Thank you for this package, it really works)

**Comment by achille-roussel** [comment]
This is good feedback.

I don't think we can allow only one broker since that would be a breaking change in the API, at the very least we would push this kind of change to a major release, likely with a backward-compatibility period to allow users to migrate their code.

I agree it would be a good change, but it may take a little while to land.

In the mean time, maybe we can improve our documentation?

**Comment by lakamsani** [comment]
On a related note, why does the new Writer API not allow supplying multiple brokers? The deprecated WriterCofig allowed this.

**Comment by achille-roussel** [comment]
Hello @lakamsani, thanks for following up!

The `kafka.Writer` API allows you to declare multiple brokers to connect to by constructing a `net.Addr` values which contains the list of broker addresses using the [`kafka.TCP`](https://pkg.go.dev/github.com/segmentio/kafka-go#TCP) function. Here is an example:

```go
w := &kafka.Writer{
    Addr: kafka.TCP("localhost:9092", "localhost:9093", "localhost:9094"),
}
```

As I'm writing this, I realize our documentation does not clearly state this. Would you be able to submit a doc update for future users who run into the same question?

**Comment by lakamsani** [comment]
@achille-roussel thanks for that clarification. Yes, will send a doc PR.
