### ISSUE TITLE
How  to use transactions for consuming and producing messages？

### ISSUE THREAD

**Issue by theoneLee** [segmentio/kafka-go#897]

**Comment by achille-roussel** [comment]
Hello @theoneLee 

We haven't implemented full support for transactions in transactions in kafka-go. Work was initiated in https://github.com/segmentio/kafka-go/pull/755 but has not yet completed.

Would you have cycles available to help finish this work?

**Comment by kumar-explorex** [comment]
@achille-roussel i would like to take this up. Please let me know the steps
