### ISSUE TITLE
Extract the message timestamp from Kafka into Message.Time in Reader

### ISSUE THREAD

**Issue by dgregoire** [segmentio/kafka-go#91]
The type `kafka.Message` has a field for Time. 

```go
type Message struct {
    // Topic is reads only and MUST NOT be set when writing messages
    Topic string

    // Partition is reads only and MUST NOT be set when writing messages
    Partition int
    Offset    int64
    Key       []byte
    Value     []byte

    // If not set at the creation, Time will be automatically set when
    // writing the message.
    Time time.Time
}
```

When using a `Reader` the time in the message itself is not extracted and `Message.Time` is set to zero.

`message timestamp is 1970-01-01 00:00:00 +0000 UTC`

**Comment by achille-roussel** [comment]
Would you mind telling me which version of kafka you are running?

**Comment by dgregoire** [comment]
Running 1.0.1

**Comment by msepp** [comment]
I'm having the same issue.

Seems like the function `writeFetchRequestV1(...)` in `write.go:116` is used to fetch messages and this sets the API version to v1 (=1), when it should in fact be v2 to get timestamped messages in the response. I'm basing my assumption on the documentation about [Kafka improvements proposal about adding timestamps to public interfaces here](https://cwiki.apache.org/confluence/display/KAFKA/KIP-32+-+Add+timestamps+to+Kafka+message#KIP-32-AddtimestampstoKafkamessage-PublicInterfaces).

Also, if I just change line 119 in `write.go` from `		ApiVersion:    int16(v1),` to  use `v2` as API version, I get the timestamps in fetched messages, but I'm not sure what other things this affects or breaks. 

OTOH, I have verified that the messages are timestamped correctly when producing with kafka-go library, using kafkacat.

I'm using Kafka version 2.11-1.1.0.

**Comment by achille-roussel** [comment]
I believe this was fixed by https://github.com/segmentio/kafka-go/pull/266 so I'll close this issue, feel free to reopen if it's not the case!
