### ISSUE TITLE
Can we use consumption limit in kafka-go

### ISSUE THREAD

**Issue by lizhifengones** [segmentio/kafka-go#910]
like `consumer_byte_rate`, I didn't find it. : (

**Comment by rhansen2** [comment]
Hi @lizhifengones,

I'm not familiar with `consumer_byte_rate`. The only reference to it I can find appears to be a broker side quota setting. https://kafka.apache.org/documentation/#quotas If that's the case then I believe this feature should work with kafka-go.

Please let me know if there's something I'm missing.

Thanks!

**Comment by lizhifengones** [comment]
> Is this question related to #919 ?

yes

**Comment by lizhifengones** [comment]
I have no problem for now
