### ISSUE TITLE
Goroutines volatility and doubling

### ISSUE THREAD

**Issue by jiangjinggit** [segmentio/kafka-go#912]
After using segmentio, why does the number of goroutines fluctuate and double occasionally? For example, the number of goroutines from 1:0 to 1:10 is 3000, then the number of goroutines from 1:10 to 1:20 is 6000, and then it drops to 3000 from 1:20 to 1:30

**Comment by dominicbarnes** [comment]
We use goroutines to avoid blocking API calls, performing operations concurrently and even batching messages. Sometimes there are cases where producers & consumers are slowed for any number of reasons, causing things to temporarily stack up.

In general, goroutines are quite inexpensive, so as long as they are all being cleaned up (ie: we have no leaks) this will likely have no bearing on your performance. If you have so many goroutines that your memory usage is a concern, you may need to adjust your reader/writer configuration to reduce concurrency/batching if your cluster isn't able to keep up for whatever reason. (or the cluster itself needs to be scaled up)

I'm going to close this issue for now, as it is rather broad and doesn't provide any specifics for us to address. If you have any concerns, feel free to re-open with more details and we can discuss further.
