### ISSUE TITLE
Can conn only calculate continuous offsets?

### ISSUE THREAD

**Issue by lizhifengones** [segmentio/kafka-go#921]
I see that [conn.Seek](https://github.com/segmentio/kafka-go/blob/294fbdbf43ce5c2bc6aa89d8a35db949e1f95367/conn.go#L663) calculates the relative offset by adding it directly. Is it not suitable for scenarios where the offset is discontinuous? Is there a function to calculate the `nextOffset` through `currentOffset` and `msg_count(messages that have been consumed)`?

like
```sh
offset= 0 1 2 5 6, 
currentOffset=1, msg_count=2, nextOffset=5 not 3
```

**Comment by achille-roussel** [comment]
@lizhifengones thanks for starting this dicussion.

Would you have a suggestion as to how we could better handle discontinued offsets?

**Comment by lizhifengones** [comment]
Personally, after consuming several messages, I hope to get the `current offset` and the `next offset`, which is very helpful for actively restarting from the correct offset after the consumption is interrupted. It should be reusable for seek, but i don't know how to start.

**Comment by lizhifengones** [comment]
> Are you observing a different behavior?

No, I'm just worried about whether there will be discontinuous offsets in kafka, but the behavior of kafka-go is "offset incrementing". In the next consumption, kafka-go specifies an absolute but non-existent offset, which causes the consumption to fail.

This is just my guess, I haven't researched the test yet.
