### ISSUE TITLE
`KafkaWriter` producing to wrong host

### ISSUE THREAD

**Issue by DaniruKun** [segmentio/kafka-go#923]
**Describe the bug**

> A clear and concise description of what the bug is.

When I set the `Addr` of a `Writer`, I expect for the producer to try to produce message to that address.
Instead I get the following error:

```
error writing messages to chats (partition 0): kafka.(*Client).Produce: dial tcp 0.0.0.0:9092: connect: connection refused
```

**Kafka Version**

Redpanda v22.1.3 (rev d1a4e00)

> * What version(s) of Kafka are you testing against?
> * What version of kafka-go are you using? `v0.4.31`

**To Reproduce**

> Resources to reproduce the behavior:

```go
		writer := &kafka.Writer{
			Addr:         kafka.TCP("192.168.64.3:9092"),
			Topic:        "chats",
			Balancer:     &kafka.Hash{},
			WriteTimeout: 10 * time.Second,
			Logger:       kafka.LoggerFunc(logf),
			ErrorLogger:  kafka.LoggerFunc(logf),
		}
```

Full example: https://github.com/holodata/fakebee/blob/master/bee/bee.go

**Expected Behavior**

`Writer` produces messages to correct address set in the writer config.

**Observed Behavior**

Writer tries to produce to the wrong address (`0.0.0.0`).

**Comment by rhansen2** [comment]
Hi @DaniruKun,

The address specified in the writer is used for metadata discovery. The Kakfa cluster responds with the advertised listeners to connect to for message production. Is your advertised listener advertising 0.0.0.0?

If this is not the case please provide a reproduction of the issue and I can look into it.

Thanks!

**Comment by DaniruKun** [comment]
Yep, that was the issue, thanks!
