### ISSUE TITLE
Can a standalone consumer consume multiple topics?

### ISSUE THREAD

**Issue by ppd0705** [segmentio/kafka-go#928]
I want to subscribe multi topics with a standalone consumer. Does it seem like both Reader and Conn don‘t support this situation?

**Comment by kscooo** [comment]
see see this  [example](https://pkg.go.dev/github.com/segmentio/kafka-go#example-Generation.Start-ConsumerGroupParallelReaders 
)

**Comment by ppd0705** [comment]
> see see this [example](https://pkg.go.dev/github.com/segmentio/kafka-go#example-Generation.Start-ConsumerGroupParallelReaders)

this example is for consumer group, not for standalone consumer

**Comment by kscooo** [comment]
> > see see this [example](https://pkg.go.dev/github.com/segmentio/kafka-go#example-Generation.Start-ConsumerGroupParallelReaders)
> 
> this example is for consumer group, not for standalone consumer

try https://github.com/segmentio/kafka-go/blob/v0.4.32/conn.go#L962 ?

**Comment by ppd0705** [comment]
> try https://github.com/segmentio/kafka-go/blob/v0.4.32/conn.go#L962 ?

thank you.
this method gets partition info for the given topics, not subscribes  the given topics.

**Comment by ppd0705** [comment]
> https://github.com/segmentio/kafka-go/blob/v0.4.32/reader.go#L363

// GroupTopics allows specifying multiple topics, but can only be used in
// combination with GroupID, as it is a consumer-group feature.

**Comment by kscooo** [comment]
Can't you set the GroupID?

**Comment by ppd0705** [comment]
haha, I don‘t want use consumer group

**Comment by kscooo** [comment]
I feel that kafka, unlike redis pub/sub, still places more emphasis on the concept of groups

**Comment by ppd0705** [comment]
Hi @achille-roussel 

In my situation,  because messages are time-sensitive, so I only need to consume messages from the latest offset.

**Comment by kscooo** [comment]
> Hi @achille-roussel
> 
> In my situation, because messages are time-sensitive, so I only need to consume messages from the latest offset.

I don't know how your code architecture is, it feels like you can open multiple goroutines to consume multiple topics in parallel, with each reader set to read from the latest offset, after all, goroutines are very lightweight

**Comment by bundleman** [comment]
@kscooo Hi! https://pkg.go.dev/github.com/segmentio/kafka-go#example-Generation.Start-ConsumerGroupParallelReaders   I have long timeout before commit and rebalancing is not correct. What should I do to fix the situation?

**Comment by bundleman** [comment]
I have multiple topics with multiple partitions. What approach can I use so that both topics and their partitions are processed in parallel, given that the delay in processing and messages can be long?

**Comment by kscooo** [comment]
I am not for the maintainer, so I am not very clear about the code details. You might want to take a deeper look at the relevant configuration（like [Balancers](https://pkg.go.dev/github.com/segmentio/kafka-go#ConsumerGroupConfig:~:text=Default%3A%20%5BRange%2C%20RoundRobin%5D-,GroupBalancers%20%5B%5DGroupBalancer,-//%20HeartbeatInterval%20sets%20the) ）, which may help you, on a side note, the comments on this library are written very well

**Comment by kscooo** [comment]
> @kscooo Hi! [pkg.go.dev/github.com/segmentio/kafka-go#example-Generation.Start-ConsumerGroupParallelReaders](https://pkg.go.dev/github.com/segmentio/kafka-go#example-Generation.Start-ConsumerGroupParallelReaders) I have a long timeout(40s) before commit and more than one consumer(1 topic 2 partitions 2 consumers) and i have rebalancing is not correct. What should I do to fix the situation?

I am not for the maintainer, so I am not very clear about the code details. You might want to take a deeper look at the relevant configuration（like [Balancers](https://pkg.go.dev/github.com/segmentio/kafka-go#ConsumerGroupConfig:~:text=Default%3A%20%5BRange%2C%20RoundRobin%5D-,GroupBalancers%20%5B%5DGroupBalancer,-//%20HeartbeatInterval%20sets%20the) ）, which may help you, on a side note, the comments on this library are written very well

**Comment by bundleman** [comment]
> 

Thanks for your reply. I just use this option with the RoundRobin balancer

**Comment by achille-roussel** [comment]
Hello @bundleman 

Was the suggestion to use `kafka.GroupBalancer` on the consumer group useful to address the original issue you reported?

**Comment by achille-roussel** [comment]
I'm going to close this issue due to inactivity, assuming the original question has been answered. Feel free to reopen if it needs further discussion!
