### ISSUE TITLE
support aws-go-sdk-v2 

### ISSUE THREAD

**Issue by kikyomits** [segmentio/kafka-go#934]
**Describe the solution you would like**

I can see `aws-go-sdk-v1` is used to have authentication with MSK. I think it's good to add a support of [aws-go-sdk-v2](https://github.com/aws/aws-sdk-go-v2). I love to contribute to this repository if you are okay with this suggesting.

**Supporting documentation**

- [aws-go-sdk-v2](https://github.com/aws/aws-sdk-go-v2)

**Comment by dominicbarnes** [comment]
We would gladly accept a contribution for this, feel free to open a PR.

**Comment by kikyomits** [comment]
Cool, will raise it shortly. Thanks
