### ISSUE TITLE
metric tag purpose

### ISSUE THREAD

**Issue by haxxorsid** [segmentio/kafka-go#940]
The ReaderStats struct here: https://github.com/segmentio/kafka-go/blob/da91759e946436612f6e31af58971162bf1d058d/reader.go#L568 is using `metric` tag. I am not able to see any code which parses the tag.

Is the tag being used for any purpose?

**Comment by achille-roussel** [comment]
Hello!

The struct tags were intended to be hints that applications can use to interpret the metrics, there is no specific code in kafka-go that depend on them. For example, we are making use of the tags in https://github.com/segmentio/stats and other applications or libraries can follow similar models.

Let me know if the answer was useful.
