### ISSUE TITLE
Settings for max.poll.records

### ISSUE THREAD

**Issue by mammenj** [segmentio/kafka-go#951]
In ReaderConfig, allow settings of Kafka consumer properties like [max.poll.records] and other consumer properties.

(https://kafka.apache.org/28/documentation.html#consumerconfigs_max.poll.records)

**Comment by mammenj** [comment]
Thanks @rhansen2 for the response and the library.
We are migrating our microservices from Java to Go. So we have these services consuming messages using the Kafka listener in Spring boot. Therefore, as I understand these listeners poll the topic for new messages at a specific interval. So the max.poll.records control the number of messages read at one poll. This allows us to tune the consumption based on the number of messages to be processed without timing out.
This may be question as to how to tune consumption of messages on every read using this client library?

**Comment by rhansen2** [comment]
Hi @mammenj 
If you're referring to timing out due to not calling poll often enough, kafka-go does not have that same constraint.

If you're using the reader we provide
```go
        // MinBytes indicates to the broker the minimum batch size that the consumer
	// will accept. Setting a high minimum when consuming from a low-volume topic
	// may result in delayed delivery when the broker does not have enough data to
	// satisfy the defined minimum.
	//
	// Default: 1
	MinBytes [int](https://pkg.go.dev/builtin#int)

	// MaxBytes indicates to the broker the maximum batch size that the consumer
	// will accept. The broker will truncate a message to satisfy this maximum, so
	// choose a value that is high enough for your largest message size.
	//
	// Default: 1MB
	MaxBytes [int](https://pkg.go.dev/builtin#int)
```

to configure how much data is read on each fetch request.

Hope that helps!

Thanks!

**Comment by mammenj** [comment]
Thanks @rhansen2  for the response, it answers my question.

**Comment by nikhil133** [comment]
@rhansen2 how to keep consumer group alive if data request frequency is less.  It may vary one request per day
