### ISSUE TITLE
 kafka write errors (1/1)

### ISSUE THREAD

**Issue by yuezhongtao** [segmentio/kafka-go#952]
**Describe the bug**

> A clear and concise description of what the bug is.

Writer.WriteMessages return error:  kafka write errors (1/1)

but the detail of error is hidden, real error is : no such host?

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/18341274/179176010-0973fd91-1398-4052-8fa1-dc3afa7b812d.png">

**Kafka Version**

> * What version(s) of Kafka are you testing against?
kafka_2.12-3.2.0
> * What version of kafka-go are you using?
github.com/segmentio/kafka-go v0.4.32

**To Reproduce**

> Resources to reproduce the behavior:

1. step 1: create kafka single instance
```shell
docker network create app-tier --driver bridge
docker run -d --name zookeeper-server --network app-tier -e ALLOW_ANONYMOUS_LOGIN=yes bitnami/zookeeper:latest
docker run -d --name kafka-server --network app-tier -p 127.0.0.1:9092:9092 -e ALLOW_PLAINTEXT_LISTENER=yes -e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181 bitnami/kafka:latest
```

2. step 2: golang demo source

```golang
package main

import (
	"context"
	"github.com/segmentio/kafka-go"
	"log"
	"strconv"
)

func main() {
	w := &kafka.Writer{
		Addr:     kafka.TCP("localhost:9092"),
		Topic:    "test",
		Balancer:               &kafka.LeastBytes{},
		AllowAutoTopicCreation: true,
	}

	defer func(w *kafka.Writer) {
		err := w.Close()
		if err != nil {
			log.Printf(err.Error())
		}
	}(w)

	err := w.WriteMessages(context.Background(),
		kafka.Message{
			Key:   []byte("Key-A"),
			Value: []byte("Hello World!"),
		},
	)
	if err != nil {
		// here is error
		// !!! kafka write errors (1/1)
		log.Printf("failed to write messages: %v", err)
	}
}

```

**Expected Behavior**

> A clear and concise description of what you expected to happen.

**Observed Behavior**

> A clear and concise description of the behavior you observed.

```
Often times, pasting the logging output from a kafka.Reader or kafka.Writer will
provide useful details to help maintainers investigate the issue and provide a
fix. If possible, providing stack traces or CPU/memory profiles may also contain
valuable information to understand the conditions that triggered the issue.
```

**Additional Context**

> Add any other context about the problem here.

**Comment by rhansen2** [comment]
Hi @yuezhongtao,

https://pkg.go.dev/github.com/segmentio/kafka-go#WriteErrors shows an example of how to access the details of the individual errors within a single WriteError.

The addresses that kafka-go uses to connect are returned by the cluster itself. It looks like your kafka instance may have the advertised listener set to the hostname of the kafka container. You would need to set that to localhost in order to connect via that address. See https://hub.docker.com/r/bitnami/kafka/ for a full example.

**Comment by yuezhongtao** [comment]
Got it, thanks a lot!

> Hi @yuezhongtao,
> 
> https://pkg.go.dev/github.com/segmentio/kafka-go#WriteErrors shows an example of how to access the details of the individual errors within a single WriteError.
> 
> The addresses that kafka-go uses to connect are returned by the cluster itself. It looks like your kafka instance may have the advertised listener set to the hostname of the kafka container. You would need to set that to localhost in order to connect via that address. See https://hub.docker.com/r/bitnami/kafka/ for a full example.

Got it, thanks a lot!
