### ISSUE TITLE
Support DescribeLogDirs

### ISSUE THREAD

**Issue by lplazas** [segmentio/kafka-go#953]
**Describe the solution you would like**

Implement support on the admin client to allow to call DescribeLogDirs
https://kafka.apache.org/21/javadoc/org/apache/kafka/clients/admin/AdminClient.html#describeLogDirs-java.util.Collection-

**Supporting documentation**

https://docs.cloudera.com/runtime/7.2.10/kafka-managing/topics/kafka-manage-cli-logdir.html
https://kafka.apache.org/25/javadoc/org/apache/kafka/clients/admin/Admin.html

I am not aware of the project structure and any restrictions that may prevent this client from implementing it. In case there aren't any, I'd be willing to give it a go at implementing it.

**Comment by rhansen2** [comment]
Hi @lplazas,

I don't think there's anything restricting us from implementing that functionality. 

Thanks for being willing to contribute! We welcome a PR! Here's an example PR for implementing another API function that might be a helpful example https://github.com/segmentio/kafka-go/pull/741

Let me know if you have any questions!

Thanks!

**Comment by rhansen2** [comment]
Hi @lplazas, 

Just wanted to check in to see if you had any updates on this issue?

**Comment by rhansen2** [comment]
https://github.com/segmentio/kafka-go/pull/1000
