### ISSUE TITLE
kafka-go updates to support Tiered Storage (KIP-405)

### ISSUE THREAD

**Issue by snalvi** [segmentio/kafka-go#954]
There are upcoming changes to Kafka to include Tiered Storage. The [API changes can be found here](https://cwiki.apache.org/confluence/display/KAFKA/KIP-405%3A+Kafka+Tiered+Storage). Would the API changes mentioned in the KIP require modifications on kafka-go?

**Supporting documentation**

* [KIP 405](https://cwiki.apache.org/confluence/display/KAFKA/KIP-405%3A+Kafka+Tiered+Storage)

**Comment by achille-roussel** [comment]
Hello @snalvi, thanks for starting this discussion.

From what I read of [KIP-405](https://cwiki.apache.org/confluence/display/KAFKA/KIP-405%3A+Kafka+Tiered+Storage#KIP405:KafkaTieredStorage-ProtocolChanges) there are no protocol changes required to support tiered storage, it seems to be implemented in the backend only?

There is a mention of being able to support topics by id in [KIP-516](https://cwiki.apache.org/confluence/display/KAFKA/KIP-516%3A+Topic+Identifiers) and an error code which is only used by replication? (`OFFSET_MOVED_TO_TIERED_STORAGE`)
