### ISSUE TITLE
Is Kafka Admin API supported?

### ISSUE THREAD

**Issue by mammenj** [segmentio/kafka-go#960]
Trying to build a administration console for Kafka, so curious if all the admin api are supported?

**Comment by dominicbarnes** [comment]
There are already existing admin consoles for Kafka out there, but if you are looking to build one with kafka-go we likely don't have _every_ admin API available, though we probably have most of what you might need. That being said, if you come across any specific gaps during your development, feel free to submit a PR to add this functionality.
