### ISSUE TITLE
kafka-go got CPU burning at waitResponse 

### ISSUE THREAD

**Issue by fangsherwin** [segmentio/kafka-go#966]
**Describe the bug**

 i've got this issue: read messages from kafka and CPU burning in /github.com/segmentio/kafka-go.(*Conn).waitResponse method.
 i user version is 0.3.3.

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/111065170/184144665-63e95534-0a0b-4dcb-b426-49968dbb0523.png">

we use pprof to  find out what happend. it show like that.
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/111065170/184145268-ccd39dfb-f4ec-4b41-a9f7-17da723f5efe.png">

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/111065170/184145377-f22b6230-5105-4555-9f83-02b63899787c.png">

Do you have any idea about this?

**Comment by dominicbarnes** [comment]
I'm going to close this out as it has been a couple of weeks since the last response. Feel free to re-open this if upgrading has not helped your issue.
