### ISSUE TITLE
Mocks support

### ISSUE THREAD

**Issue by kubakl** [segmentio/kafka-go#968]
It would be really nice to have a mocks package similar to which sarama has, to be able to test the apps without having to start kafka inside of a container and have a real connection.

https://github.com/Shopify/sarama/tree/main/mocks

**Comment by dominicbarnes** [comment]
We've opted to not provide our own mock implementation, as it would inevitably lock our users into some library/ecosystem depending on what we chose.

In addition, each use-case varies a lot in terms of what exactly is suitable to mock/fake for the purposes of testing. For some, spinning up a local kafka with docker is pretty straightforward. For others, maybe the exact queue/storage system is less important and a stub/mock is more appropriate.

For the same reason we don't provide a fake server implementation, we will likely not provide any mock implementations either. See https://github.com/segmentio/kafka-go/issues/656 for additional context.

**Comment by kubakl** [comment]
I'm not completely sure what you mean by locking the user. The easiest way of adding a simpler way to test would be an implementation based on interfaces instead of plain structs. That wouldn't even require you to implement any new stuff. The users would have a much easier way to create mocks by themselves. Now I have to create my own interface that your structs implement. This is not a perfect solution, imagine that there is a new method you add, and the users are no longer are going to be able to call it when they implement their own interfaces. Just saying that interface implementation would be much more flexible.
