### ISSUE TITLE
Reader RetentionTime validation comparing against wrong int type

### ISSUE THREAD

**Issue by msepp** [segmentio/kafka-go#99]
Hey,

I have a use-case where I need set the Reader RetentionTime setting to a non-default value that is bigger than the default. However the setting seems to be capped by max value for int32 when in fact internally the value sent with OffsetCommit request is using int64 for retention time (which is consistent with the spec). 

This is limiting the effective maximum for RetentionTime to something between 24 and 25 days, because when using value `time.Hour * 24 * 24` everything still works, but with `RetentionTime: time.Hour*24*25` I get a panic saying "panic: RetentionTime out of bounds: 2160000000000000"

Can someone tell me if I've understood something wrong here or is this actually an issue with the `NewReader(config ReaderConfig)` validating the retention time option incorrectly.

Ps. Thanks a lot for this library, it's been a big help

**Comment by achille-roussel** [comment]
@msepp this is a bug indeed. Sorry for the delay to get it addressed. Feel free to open a pull request right away next time 👍
