### ISSUE TITLE
Error when producing messages (high throughput)

### ISSUE THREAD

**Issue by vedantkarandikar** [segmentio/kafka-go#997]
I am getting an error when writing messages: `context canceled, logic not executed`

This is only when we are performing writes at a high rate.

Write Config:

```
       kafkaDialer := &kafka.Dialer{
		Timeout:   (time.Duration(10) * time.Second),
		DualStack: true,
		SASLMechanism: &aws_msk_iam.Mechanism{
			Signer: sigv4.NewSigner(awsSession.Config.Credentials),
			Region: config.Config[config.AWS_DEFAULT_REGION],
		},
		TLS: &tls.Config{},
	}

	kafkaWriterConfig := kafka.WriterConfig{
		Brokers:   brokers,
		Topic:     TOPIC_NAME,
		Dialer:    kafkaDialer,
		BatchSize: 1,
	}

	kafkaWriter = kafka.NewWriter(kafkaWriterConfig)
```

This is how I am writing messages:
```
err := kafkaWriter.WriteMessages(ctx, kafka.Message{
    Value: message,
})
```

`fmt.Println(err) // context canceled, logic not executed`

**Comment by rhansen2** [comment]
HI @vedantkarandikar,

Is the only error you're seeing `context canceled`? Looking at WriteMessages I believe that error would only be returned if the context passed into that call is canceled externally. Is it possible that's what's happening?

If not are you able to provide a runnable reproduction of the issue?

Thanks!

**Comment by vedantkarandikar** [comment]
I trace backed the error message and it seems, the context was getting cancelled earlier in the chain. 
Not a segmentio/kafka-go issue. My bad.

Thanks!
