### ISSUE TITLE
I use the following configuration, why are messages generated in one partition?

### ISSUE THREAD

**Issue by w182757427** [segmentio/kafka-go#999]
### **code:**
func KafkaProducer(value []byte)  {

	w := &kafka.Writer{
		Addr:         kafka.TCP(broker1,broker2,broker3),
		Topic:        topic,
		Balancer:     &kafka.LeastBytes{},
		Async:        true,
		RequiredAcks: 1,
	}

	err := w.WriteMessages(context.Background(),
		kafka.Message{
			Value: []byte(value),
		},
	)
	if err != nil {
		log.Fatal("failed to write messages:", err)
	}

	if err := w.Close(); err != nil {
		log.Fatal("failed to close writer:", err)
	}
}

**It looks pretty common, right? It's an example from the official document. Each time, a message is passed to KafkaProducer.**
**However, querying the Kafka topic using Linux commands shows the following results.**

kafka-run-class.sh kafka.tools.GetOffsetShell --broker-list 10.0.16.190:9092 --topic kube-logs.fluentbit.json.test  --time -1

kube-logs.fluentbit.json.test:0:6169
kube-logs.fluentbit.json.test:1:0
kube-logs.fluentbit.json.test:2:0
kube-logs.fluentbit.json.test:3:0
kube-logs.fluentbit.json.test:4:0
kube-logs.fluentbit.json.test:5:0
kube-logs.fluentbit.json.test:6:0

**They are all sent to partition 0.What should I do?**

**Comment by w182757427** [comment]
Oh, my God, the message gets sent to partition 0 every time, because I put it in a function. Can I specify partitions in Writer or WriteMessages? I have to put them in the function

**Comment by DenisKnezBeforeNine** [comment]
@w182757427 I'm facing the same issue where all the messages are going to partition 0. And I see you commented that the issue was "it was in a function". I'm not sure what do you mean by that. Could you explain a little bit more why it was going in the partition 0 for you and what did you do to fix it?  I don't need to specify which partition it needs to go I just want the load balancer to distribute the messages across the partitions that I have on the topic

**Comment by w182757427** [comment]
The reason is that I put the Kafka Producer code in another function. Actually, it's my code. The default configuration of the Kafka-go producer is random. Every time my program calls this function, the kafka-go producer treats it as the first call and writes the message to partition 0. Then I wrote Kafka-go Producer into the main function.
